### ISSUE TITLE
Facebook-login not displaying the button

### ISSUE THREAD

**Issue by tnguyen42** [facebook/react-native-fbsdk#1]
Hi,

I know the plugin is very new, but I already got a problem (it's most likely on me).
Everything compiles, but I got this:

![image](https://cloud.githubusercontent.com/assets/12211685/9135061/2717eef4-3d0a-11e5-898f-4346d02cff33.png)

I got this when just trying to set the Login button on the page, with that example code from the npm:

```es6
		return (
			<View style={styles.container}>
				<FBSDKLoginButton
					onLoginFinished={(error, result) => {
						if (error) {
							alert('Error logging in.');
						} else {
							if (result.isCanceled) {
								alert('Login cancelled.');
							} else {
								alert('Logged in.');
							}
						}
					}}
					onLogoutFinished={() => alert('Logged out.')}
					readPermissions={[]}
					publishPermissions={['publish_actions']}
				/>
			</View>
		);
```

I'd like to detail that I got the plist right since I got another facebook-login to work, and I'm just using the frameworks from Documents/FacebookSDK instead. So this should be right.

I believe the mistake could come from my AppDelegate since I modified it several times to install different plugins and I don't understand (at all) what's in it:

```

#import "AppDelegate.h"

#import "RCTRootView.h"

#import <FBSDKCoreKit/FBSDKCoreKit.h>
#import <FBSDKLoginKit/FBSDKLoginKit.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle"];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"JibberJabber"
                                                   launchOptions:launchOptions];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [[UIViewController alloc] init];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}



// ----------------------------- Facebook login -------------------------------

// Facebook SDK
- (void)applicationDidBecomeActive:(UIApplication *)application {
  [FBSDKAppEvents activateApp];
}

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
  return [[FBSDKApplicationDelegate sharedInstance] application:application
                                                        openURL:url
                                              sourceApplication:sourceApplication
                                                     annotation:annotation];
}

// -------------------------------------------------------------------------------------------------
// Code part required for the orientation control (react-native-orientation)
- (NSUInteger)application:(UIApplication *)application supportedInterfaceOrientationsForWindow:(UIWindow *)window {
  NSUInteger orientations;
  
  orientations = UIInterfaceOrientationMaskPortrait;
  
  if (self.shouldRotate == YES) {
    orientations = UIInterfaceOrientationMaskAllButUpsideDown;
  }
  
  return orientations;
}

@end
```

Can anyone help me out?

**Comment by cphackm** [comment]
It appears I made a mistake in the installation instructions -- this looks like what happens when the native module isn't found.  If you look at this step: 

"From Finder, drag the 'react-native-fbsdkcore' folder from node_modules into the XCode project navigator."

It should say react-native-fbsdklogin.  If you haven't already, try adding that folder to your project in Xcode.

**Comment by justinmakaila** [comment]
I'm having a similar issue, only the button isn't appearing on the screen at all...

**Comment by tnguyen42** [comment]
@justinmakaila : glad I'm not alone ^^

@cphackm : ok I did what you told me, but now I got a new error:

![image](https://cloud.githubusercontent.com/assets/12211685/9137701/c1f8c4ba-3d1f-11e5-958e-35315ae667d7.png)

Which is weird because I also have that when I type npm list:
"npm ERR! extraneous: react-native-fbsdklogin@0.0.2 /Users/tnguyen/JibberJabber/JibberJabber/node_modules/react-native-fbsdklogin"

**Comment by cphackm** [comment]
@justinmakaila - Paste the render method where you added the login button and I'll take a look.

@tnguyen42 - Try deleting the react-native-fbsdklogin folder(don't forget to remove it from your Xcode project as well) from node_modules and try reinstalling the package with this command:

npm install --save react-native-fbsdklogin

The save option will add react-native-fbsdklogin to your project's dependencies and prevent the error when running npm list.  You won't have to relink the Facebook SDK.

**Comment by justinmakaila** [comment]
The following `renderFacebookButton()` is invoked from my `render()` method.

```javascript
	renderFacebookButton() {
		const {
			signInWithExternalService,
		} = this.props

		return (
			<FBSDKLoginButton
				style={styles.facebookButton}
				onLoginFinished={(error, result) => {
					if (error) {
						console.log('Error logging in with Facebook:', error)
					} else {
						if (result.isCancelled) {
							console.log('User cancelled Facebook login')
						} else {
							console.log('Successfully logged in with Facebook!')
							return signInWithExternalService('Facebook', result)
						}
					}
				}}
				onLogoutFinished={() => console.log('Successfully logged out of Facebook')}
				readPermissions={['email', 'public_profile']}
				publishPermissions={[]}/>
		)
	}
```

**Comment by cphackm** [comment]
@justinmakaila - It may be a style issue. Try displaying it with the default style(just don't pass a style prop), and also let me see the style you're using.

**Comment by tnguyen42** [comment]
@cphackm : I tried what you told me, but now, even when trying to get back to the red rectangle I used to have, I can't. And I still have the same error.

Also, from the AppDelegate.m, I'm having some trouble merging what is in the file by default:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle"];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"JibberJabber"
                                                   launchOptions:launchOptions];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [[UIViewController alloc] init];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}
```

Which get in conflict with what I'm supposed to add:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  return [[FBSDKApplicationDelegate sharedInstance] application:application
                                  didFinishLaunchingWithOptions:launchOptions];
}
```

So I simply ignored that last part, and it used to display a red rectangle instead of the button. Can it explain the error? (which is still the same, ie "Requiring unknown module")

**Comment by tnguyen42** [comment]
Ok @cphackm, I found something: when installing core, login gets to work. There must be a dependency somewhere someone missed so login requires the core library.

Thanks for your time!

**Comment by cphackm** [comment]
@tnguyen42 - The login npm -- like all three of them -- relies on FBSDKCoreKit.framework from the SDK, but there shouldn't be any dependencies between the npm packages themselves, but I'm glad you got it working.

Concerning the delegate, just change the return value from YES to what you see in the getting started guide.

``` objective-c
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  jsCodeLocation = [NSURL URLWithString:@"http://localhost:8081/index.ios.bundle"];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"JibberJabber"
                                                   launchOptions:launchOptions];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [[UIViewController alloc] init];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return [[FBSDKApplicationDelegate sharedInstance] application:application
                                  didFinishLaunchingWithOptions:launchOptions];;
}
```

**Comment by justinmakaila** [comment]
@cphackm If I don't pass a style prop, I'm still getting the same thing. No button on the screen.

**Comment by tnguyen42** [comment]
@justinmakaila : did you try to replace your return FBSDKLoginButton with anything else? Like some text?

**Comment by justinmakaila** [comment]
@tnguyen42 yeah, works fine

**Comment by justinmakaila** [comment]
No kidding, as soon as i removed the text and uncommented the button, it appeared on screen...

**Comment by cphackm** [comment]
@justinmakaila Good to know it's working now. If there are any further problems, feel free to open a new issue.

**Comment by john-griffin** [comment]
I see this red box after logging in. Get redirected back from Facebook login screen into the app and it just shows the red box. App is frozen, react native refresh broken. onLoginFinished not fired.
