### ISSUE TITLE
Login Button Not working...

### ISSUE THREAD

**Issue by yelled3** [facebook/react-native-fbsdk#10]
I followed the login button example from the readme and the I got:
```
Warning: Native component for "RCTFBSDKLoginButton" does not exist'
```
and the button actions and style is not working...

I installed facebook ios sdk from cocoapods:

```rb
PODS:
  - Bolts (1.2.0):
    - Bolts/AppLinks (= 1.2.0)
    - Bolts/Tasks (= 1.2.0)
  - Bolts/AppLinks (1.2.0):
    - Bolts/Tasks
  - Bolts/Tasks (1.2.0)
  - FBSDKCoreKit (4.5.1):
    - Bolts (~> 1.1)
    - FBSDKCoreKit/arc (= 4.5.1)
    - FBSDKCoreKit/no-arc (= 4.5.1)
  - FBSDKCoreKit/arc (4.5.1):
    - Bolts (~> 1.1)
  - FBSDKCoreKit/no-arc (4.5.1):
    - Bolts (~> 1.1)
    - FBSDKCoreKit/arc
  - FBSDKLoginKit (4.5.1):
    - FBSDKCoreKit

DEPENDENCIES:
  - FBSDKCoreKit
  - FBSDKLoginKit

SPEC CHECKSUMS:
  Bolts: d176cb1e0012175589e389a9db49b85e27787576
  FBSDKCoreKit: f335eaf6865e1e1597dee1debfb533045500da47
  FBSDKLoginKit: 225cc9a388a92916ee3f3bb14422017b6e44b65b

COCOAPODS: 0.37.2

``` 

maybe the cocoapods is the issue?

**Comment by yelled3** [comment]
**UPDATE**
just install the without a cocoapods - same thing

**Comment by yelled3** [comment]
just realised this is a duplicate of https://github.com/facebook/react-native-fbsdk/issues/8
closing

**Comment by codepreneur** [comment]
I am getting exactly the same issue with `react-native-cli` @0.1.4

```
Warning: Native component for "RCTFBSDKLoginButton" does not exist'
```

**Comment by kent10ou** [comment]
Hello! I am also getting the same message "RCTFBSDKLoginButton" does not exist. I'm following the examples in here 'https://developers.facebook.com/docs/facebook-login/ios' and have tried to create and edit viewcontroller.h & m files with no luck
