### ISSUE TITLE
Missing steps of  Configure native projects of 0.1.0-alpha in Android

### ISSUE THREAD

**Issue by vshy108** [facebook/react-native-fbsdk#100]
- Need to do import in MainActivity.java

```
import android.content.Intent;
import android.os.Bundle;

import com.facebook.CallbackManager;
import com.facebook.FacebookSdk;
import com.facebook.reactnative.androidsdk.FBSDKPackage;
```

-  Refer to [Android Setup: react-native-facebook-login](https://github.com/magus/react-native-facebook-login/blob/master/android/README.md) , need to follow the step 4 and step 5 to add Facebook App ID to String resources, add FacebookActivity and reference facebook app id.

Thanks for the efforts to make react-native-fbsdk supports Android.

**Comment by dzhuowen** [comment]
Good point. I'll specify this with a mention to [Android Stuido tips]( http://developer.android.com/sdk/installing/studio-tips.html).
