### ISSUE TITLE
[Android] How to get FB user object

### ISSUE THREAD

**Issue by apastel** [facebook/react-native-fbsdk#101]
I'm using the new 0.1.0-alpha release for Android and using this Login example:
```
<LoginButton
          publishPermissions={["publish_actions"]}
          onLoginFinished={
            (error, result) => {
              if (error) {
                alert("login has error: " + result.error);
              } else if (result.isCancelled) {
                alert("login is cancelled.");
              } else {
                alert("login has finished with permissions: " + result.grantedPermissions)
              }
            }
          }
          onLogoutFinished={() => show("logout.")}/>
```
How would I retrieve the logged-in user's data (id, name, DoB, token, etc.)? What object contains that data, since it seems that `result` only contains the list of permissions, and the `isCancelled` flag.

I tried setting `publishPermissions={["email", "user_friends"]}` to see if that would change what's in the `result` but that causes my application to crash upon login.

**Comment by ajoshdee** [comment]
+1

**Comment by dzhuowen** [comment]
You can use AccessToken module to get back info about the access token. For the user's data, you can make Graph APIs (with sdk, use GraphRequest module) to fetch them. https://developers.facebook.com/docs/graph-api.
