### ISSUE TITLE
Login Behavior

### ISSUE THREAD

**Issue by ajoshdee** [facebook/react-native-fbsdk#103]
Hi, I can't make the setLoginBehavior to work. How does this open the native Facebook App? Since the default is 'native'.

**Comment by dzhuowen** [comment]
Because the native sdk start using safariViewController. https://developers.facebook.com/blog/post/2015/10/29/Facebook-Login-iOS9/
Thanks for pointing this out. I'll specify this in the comment.

**Comment by ajoshdee** [comment]
Any workaround to open the native facebook app?
