### ISSUE TITLE
Graph issue

### ISSUE THREAD

**Issue by ajoshdee** [facebook/react-native-fbsdk#104]
Hi,how can i get rid of this warning 
FBSDKLog: starting with Graph API v2.4, GET requests for //me should contain an explicit "fields" parameter

**Comment by dzhuowen** [comment]
'fields' is required by Graph API for //me so you need to specify the parameters you want to fetch in the API call, e.g id,name.
You can use Graph API Explorer to test out the API call as well.

**Comment by ajoshdee** [comment]
thanks, but how do i implement the parameter? I keep getting an exception when i enter this in the parameter field: {"key" : "id, email"}

**Comment by ajoshdee** [comment]
![image](https://cloud.githubusercontent.com/assets/7309782/14162208/49d42f58-f71c-11e5-8597-12dffc1988b3.png)

**Comment by ajoshdee** [comment]
Also , i'm not getting any results using the sample callback

**Comment by mattfca** [comment]
change '/me' to '/me?fields=id,name,email'

**Comment by SrihariThalla** [comment]
@ajoshdee Here is the format for the `config` object:
```javascript
{
    parameters: {
        fields: {
            string: 'id'
        }
    }
}
```

**Comment by donedgardo** [comment]
This should be documented #267
