### ISSUE TITLE
Installations for Android missing step in readme

### ISSUE THREAD

**Issue by xelent** [facebook/react-native-fbsdk#106]
These imports need to be imported for android aswell.
MainActivity.java
// FBSDK
import com.facebook.CallbackManager;
import com.facebook.FacebookSdk;
import com.facebook.reactnative.androidsdk.FBSDKPackage;
import android.content.Intent;
import android.os.Bundle;

**Comment by dzhuowen** [comment]
Fixed in 0.1.0-alpha.1 release.
