### ISSUE TITLE
Android GraphRequest response is a string, not an object

### ISSUE THREAD

**Issue by udfalkso** [facebook/react-native-fbsdk#110]
On iOS the same code yields an object.  On Android, a string.

**Comment by dzhuowen** [comment]
Thanks for pointing this out! Will fix in the next release.

**Comment by ketsugi** [comment]
When will this next release be? Alternatively, what was the fix for this issue?

**Comment by dzhuowen** [comment]
React Native FBSDK follows the monthly release cycle of Facebook SDK.

**Comment by dzhuowen** [comment]
https://github.com/facebook/react-native-fbsdk/issues/141#issuecomment-216599528
