### ISSUE TITLE
Can't get it the installation/setup working

### ISSUE THREAD

**Issue by joshbedo** [facebook/react-native-fbsdk#114]
So i just went step by step through the Facebook SDK setup and also went through the manual setup provided here since i kept having issues with the Pod setup and i keep getting the following error. Here are from my setup and the error i keep getting when the app starts. If someone could help I would greatly appreciate it, this is stopping me from working on this project right now.

![](http://i.imgur.com/77r4Ja9.png)
![](http://i.imgur.com/mseZgF8.png)
![](http://i.imgur.com/6dxubdS.jpg)
![](http://i.imgur.com/lRibK6x.jpg)

**Comment by joshbedo** [comment]
Does everything look okay am i linking everything correctly?

**Comment by udfalkso** [comment]
You may want to make sure the header paths are correct as well.  This PR seems like it's trying to address that issue:
https://github.com/facebook/react-native-fbsdk/pull/102

We had to change from "../../" to "../../../" in this new android friendly version.. (recursive)

![screen shot 2016-04-13 at 3 35 53 pm](https://cloud.githubusercontent.com/assets/2029383/14506765/76d2fb30-018d-11e6-94c7-9bbe744102c3.png)

**Comment by joshbedo** [comment]
@udfalkso Hmm this is what i have for my header paths. Does this look correct? I'm targeting only iOS for now.
![](http://i.imgur.com/i44BMiV.jpg)

**Comment by dzhuowen** [comment]
Judging from the red box(FBSDKAccessToken.ios.js) you're using version smaller than 0.1.0-alpha. Can you try v0.1.0 instead?

**Comment by ericraio** [comment]
I was having issues using the master branch and had to switch back to 0.1.0-alpha

**Comment by dzhuowen** [comment]
Hi @ericraio , can you give me some detail of the issue? I assume the problem you see is different from @joshbedo. Free feel to open a new issue with your problem. Thanks!

**Comment by dzhuowen** [comment]
No response for a while.
