### ISSUE TITLE
Include contentUrl in FBSharePhotoContent cause error

### ISSUE THREAD

**Issue by vshy108** [facebook/react-native-fbsdk#115]
When I defined 

```javascript
    const sharePhotoContent = {
      contentType: 'photo',
      photos: photoArray,
    };
```
it can be successfully shared with ShareDialog.

but after I added the content Url to it,

```javascript
    const sharePhotoContent = {
      contentType: 'photo',
      photos: photoArray,
      contentUrl: 'http://www.taessina.com/'
    };
```

```javascript
ShareDialog.canShow(sharePhotoContent).then(
      (canShow) => {
        if (canShow) {
          console.log('canShow', canShow);
          return ShareDialog.show(sharePhotoContent);
        }
        return null;
      }
    ).then(
      (result) => {
        if (result.isCancelled) {
          console.log('Share cancelled');
        } else {
          console.log('Share success');
        }
      },
      (error) => {
        //trigger this
        console.log('Share fail with error: ' + error);
      }
    );
```

Console Output

> canShow true
> Share fail with error: **Error: Only one of link, photos, and video should be specified.**
> 

What I understand is we only can share either link or photos but cannot have ContentUrl and photos at the same time. Then, I cannot understand why we need contentUrl field in FBSharePhotoContent?Thanks

**Comment by dzhuowen** [comment]
Yeah you're right ContentUrl and photos can not be set at the same time. I'm not sure why native sdks behavior in this way but feel free to sent a PR for the issue. Thanks!
