### ISSUE TITLE
Description of the project is outdated

### ISSUE THREAD

**Issue by ptomasroos** [facebook/react-native-fbsdk#116]
"A wrapper around the iOS Facebook SDK for React Native apps. Provides access to login, sharing, graph requests, etc." 

should be changed to 

"A wrapper around the iOS and Android Facebook SDK for React Native apps. Provides access to login, sharing, graph requests, etc." 

Could not submit pull request on it :-)

**Comment by dzhuowen** [comment]
Updated. Thanks :-) !
