### ISSUE TITLE
LikeView on Dark Theme

### ISSUE THREAD

**Issue by ericraio** [facebook/react-native-fbsdk#118]
Unable to change the text color when displaying the LikeView on a dark themed application

**Comment by mingflifb** [comment]
We do not support changing the text color for the LikeView for branding reasons.

**Comment by ericraio** [comment]
@mingflifb with the web like plugin you can pass in a property called colorscheme that is defaulted to "light"

`The color scheme used by the plugin for any text outside of the button itself. Can be light or dark.`

Why would this be any different?

https://developers.facebook.com/docs/plugins/like-button#settings

**Comment by mingflifb** [comment]
Oh you mean for the social sentence? The LikeView follows the convention set by the like buttons on the native SDKs, so checkout the foregroundColor property on the component.
