### ISSUE TITLE
Anyway to incorporate this package to work with rnpm?

### ISSUE THREAD

**Issue by kennetpostigo** [facebook/react-native-fbsdk#119]
Is there anyway to incorporate react-native-fbsdk with `rnpm`? 

`rnpm` is a package manager for __Native__ modules in react-native. Making linking them into your react-native application as easy as `rnpm link`. `rnpm` works with most native modules but does not work with this sdk because:
> RNPM currently does not support multiple projects located in a single repository (that's the case I guess). Support to be considered.

Would be great to make this package easier to setup if it was compatible with rnpm. Maybe something to look forward to?

**Comment by ms88privat** [comment]
Thats a big issue! Also because if you are using `rnpm link` to link, it will also try to link fbsdk, which will then break the code.

**Comment by knowbody** [comment]
Here is the issue open on rnpm https://github.com/rnpm/rnpm/issues/144 should be fixed shortly.

**Comment by grabbou** [comment]
Yes - the main issue are the 3 packages - if they could've been deployed separately as a top-level npm packages, that would fix the problem (since they are independent).

However we are trying to fix that as @knowbody this weekend - I'll post an update here how it goes :)

PS. Thanks @knowbody for referencing that issue - didn't know about this one!

**Comment by tomprogers** [comment]
This package is prohibitively difficult to use alongside other third-party react-native modules. It's simply not an option to "Remove all the subprojects under Libraries/ in Xcode," and I doubt that the primary dev audience of react-native is skilled enough with Objective-C and CocoaPods to resolve this module's monolithic demands with those of their host projects.

I ended up using magus's [wrapper](https://github.com/magus/react-native-facebook-login) module. It seems much less flexible and much more limited, and setup is more involved than with any of the other react-native modules I've used, but it still doesn't present the integration difficulties this project does.

I'd be very interested in revisiting this project if there were substantial changes around setup.

**Comment by dzhuowen** [comment]
https://github.com/rnpm/rnpm/issues/144#issuecomment-217226740

**Comment by chrisp-fb** [comment]
We're working on improving this process for the next release such as consolidating the multiple RCTFBSDK* projects into one. Stay tuned.

**Comment by grabbou** [comment]
Just cross posting here the solution we've came up so far in rnpm to at least work around the multi-project stuff: https://github.com/rnpm/rnpm/issues/144#issuecomment-217247883

**Comment by dzhuowen** [comment]
Start support rnpm with 0.2.0 release.
