### ISSUE TITLE
Readme installation instructions unclear

### ISSUE THREAD

**Issue by pickhardt** [facebook/react-native-fbsdk#12]
The instructions say "Drag the XCode projects from node_modules/react-native-sdk... into your XCode project navigator"

I believe the directory you mean is node_modules/react-native-fbsdkcore? If so, there are no XCode projects in that file. With other libraries, I've added something of the form *.xcodeproj, but there isn't anything like that in node_modules/react-native-fbsdkcore

This is what I see:
![contents](https://cloud.githubusercontent.com/assets/610082/9399368/294b9ff0-4768-11e5-8436-0dc21355f11a.png)

**Comment by pickhardt** [comment]
So I tried dragging the folders into the project, like this:

![1-dragged-folders](https://cloud.githubusercontent.com/assets/610082/9400051/51a487e2-4771-11e5-8d1a-cf37a80e41e7.png)

Then I added a login screen, like this:

![2-added-screen](https://cloud.githubusercontent.com/assets/610082/9400052/57b9efb4-4771-11e5-9e95-b6e61545e307.png)

But an empty button shows up, like this, and it doesn't do anything when clicked:

![3-button](https://cloud.githubusercontent.com/assets/610082/9400055/64fdd794-4771-11e5-9502-a8053abba0c3.png)

I'm clearly missing something from the installation instructions. Can you help me, and also probably update the readme, because it's not clear what I did wrong.

**Comment by philikon** [comment]
> The instructions say "Drag the XCode projects from node_modules/react-native-sdk... into your XCode project navigator"

I'm assuming you read that in the README file on the GitHub repository after I had committed the Xcode projects to master. In other words, the text was correct for the code that was in GitHub at the time, but not for the released versions. I have just released version 0.0.4 of all three packages that contain the Xcode projects.

**Comment by philikon** [comment]
As for your problem with the login button, note that the Sample app sets some explicit styles on the button: https://github.com/facebook/react-native-fbsdk/blob/master/Sample/styles.js#L47-L54. In particular, width and height are important given React Native's flexbox layout (where it's difficult for native views to have a variable intrinsic size).

**Comment by philikon** [comment]
I'm going to close this issue. Please reopen if continue to have problems (ideally separate issues for each individual problem you encounter.) Thanks!

**Comment by pickhardt** [comment]
Alright, thanks. That was the problem. Now I'll just use the new versions with xcodeproj files.
