### ISSUE TITLE
README's Graph Requests example mismatches callback name

### ISSUE THREAD

**Issue by ScandyMark** [facebook/react-native-fbsdk#121]
_response[Info]Callback

//Create response callback.
_responseCallback

const infoRequest = new GraphRequest(
  '/me',
  null,
  this._responseInfoCallback

**Comment by KBLNY** [comment]
Well done, please submit a PR

**Comment by SrihariThalla** [comment]
I've been worrying why the Graph Request isn't working! Thanks and I've submitted a PR :smile:

**Comment by dzhuowen** [comment]
Thanks! PR #127  merged.
