### ISSUE TITLE
AppEventsLogger.activateApp is not a function. (In 'AppEventsLogger.activateApp()', 'AppEventsLogger.activateApp()' is undefined)

### ISSUE THREAD

**Issue by prabak** [facebook/react-native-fbsdk#122]
I am trying to setup a simple event tracking on my mobile app for iOS. More specifically, I am trying to track when the app is activated. i.e. activateApp(). I followed the instruction on the setup guide. My fbsdk for react native is working since I can get the facebook login button to work, however when I try to log an event, i.e. activateApp, I am getting the error "AppEventsLogger.activateApp is not a function".

Here is my code.

```
import FBSDK, {
   AppEventsLogger
} from 'react-native-fbsdk';

```
....

```
componentWillMount() {
    AppEventsLogger.activateApp();
}

```
Am I missing something?

**Comment by dzhuowen** [comment]
If you follow the instruction on the setup guide(make sure you do the step for using AppEventsLogger in Android), you should be able to call logEvent method directly.

**Comment by prabak** [comment]
I updated my initial comment. To track activateApp() event for android, the documentation specifies to update the onResume(), onPause(), and onStop() methods. However, it does not mention anything about iOS. According to the FacebookSDK documentation we must do the following for iOS:

```
// Add to your AppDelegate.m file
- (void)applicationDidBecomeActive:(UIApplication *)application {    
    // Call the 'activateApp' method to log an app event for use
    // in analytics and advertising reporting.
    [FBSDKAppEvents activateApp];
}
```

Can someone confirm this?

**Comment by dzhuowen** [comment]
@prabak Yes you should call  `[FBSDKAppEvents activateApp];` in native project. We tried to hide the platform specific implementation from developers but this time it's unavoidable. The `activateApp` method can only be called from JS for the Android platform like [this](https://github.com/facebook/react-native-fbsdk/blob/efb7470ba16d7828951ba48753d8be68c13b69cb/Android/src/main/java/com/facebook/reactnative/androidsdk/FBAppEventsLoggerModule.java#L126-130).
Thanks for pointing this out! I'll specify this in readme and comment 😄 .

**Comment by booboothefool** [comment]
@dzhuowen so `AppEventsLogger` does not work at all for iOS?
