### ISSUE TITLE
LoginManager.logInWithReadPermissions doesn't work from componentDidMount

### ISSUE THREAD

**Issue by mikelambert** [facebook/react-native-fbsdk#123]
I'm trying to use: https://github.com/facebook/react-native-fbsdk#user-content-requesting-additional-permissions-with-login-manager

If I call LoginManager.logInWithReadPermissions in componentDidMount, the login modal apparently tries to present against a ViewController that contains a UIView (no interesting/noteworthy info about them in the debugger). I never see the presented login Safari screen, and the await hangs indefinitely.

But if I then try to Login again from my Touchable's onPress, it works. This time it is presenting against a ViewController that contains a RCTRootView, and I see the login screen.

I'm trying to auto-login (for cases of reloading an expired token, or requesting one-additional-permission on an app update), but it seems the LoginManager doesn't support this from componentDidMount (of the enclosing launch screen view.) Is this by design and I am using it wrong? Or should it be working from anywhere?

I saw https://github.com/facebook/react-native-fbsdk/issues/55 , which might be related (he saw the same thing), though that got sidetracked into unrelated "native vs safari" issues.

**Comment by dzhuowen** [comment]
Hi @mikelambert , auto-login is not workable by design. To do this you will need to dispatch the login call to main queue in native code and handle the threading yourself.
Besides you can use `FBAccessToken: refreshCurrentAccessTokenAsync` to refresh token. 
Thanks!

**Comment by mikelambert** [comment]
In the case of an expired token from a user who has not visited in 60+ days, while refreshCurrentAccessTokenAsync give me a new valid token for them? Or will that user's cached token not be refreshable, necessitating a full re-login? (This is something that is extremely difficult to test myself given the limitations of the test-users framework/features available to me.)

**Comment by dzhuowen** [comment]
Sorry for getting back late, an expired token [cannot be refreshed](https://developers.facebook.com/docs/reference/ios/current/class/FBSDKAccessToken/).
Also you can use the iOS and Android SDK docs for the future reference [here](https://developers.facebook.com/docs/)
