### ISSUE TITLE
 Native component for "RCTFBLoginButton" does not exist

### ISSUE THREAD

**Issue by jerson** [facebook/react-native-fbsdk#126]
1) create project and install fbsdk
```
react-native init fbprueba
npm install --save react-native-fbsdk
```
2) create pod file and add deps and install pods
```
	# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'fbprueba' do
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'React', :subspecs => ['Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket'], :path => '../node_modules/react-native'
  pod 'react-native-fbsdkcore', :path => '../node_modules/react-native-fbsdk/iOS/core'
  pod 'react-native-fbsdklogin', :path => '../node_modules/react-native-fbsdk/iOS/login'
#NO FB SDK SHARE
end

target 'fbpruebaTests' do

end


```
```
pod install
```

3) config facebook params and add login button

```js
/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 * @flow
 */

import React, {
  AppRegistry,
  Component,
  StyleSheet,
  Text,
  View
} from 'react-native';

const FBSDK = require('react-native-fbsdk');
const {
  LoginButton,
} = FBSDK;

class fbprueba extends Component {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>
          Welcome to React Native!
        </Text>
        <Text style={styles.instructions}>
          To get started, edit index.ios.js
        </Text>
        <Text style={styles.instructions}>
          Press Cmd+R to reload,{'\n'}
          Cmd+D or shake for dev menu
        </Text>
         <LoginButton
          publishPermissions={["publish_actions"]}
          onLoginFinished={
            (error, result) => {
              if (error) {
                alert("login has error: " + result.error);
              } else if (result.isCancelled) {
                alert("login is cancelled.");
              } else {
                alert("login has finished with permissions: " + result.grantedPermissions)
              }
            }
          }
          onLogoutFinished={() => alert("logout.")}/>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});

AppRegistry.registerComponent('fbprueba', () => fbprueba);

```

4) run ios
```
react-native run-ios
```

5) no render Views and show errors
```
Warning: Native component for "RCTFBLikeView" does not exist
Warning: Native component for "RCTFBLoginButton" does not exist
Warning: Native component for "RCTFBSendButton" does not exist
Warning: Native component for "RCTFBShareButton" does not exist
```

**Comment by rakesh0r** [comment]
am also stuck with same issue.
any luck?

**Comment by Froelund** [comment]
I have the same issue.

**Comment by barroslee** [comment]
same issue here.

**Comment by dzhuowen** [comment]
Please open the xcworkspace in xcode and make sure the library are linked correctly (other linker flag setting).

**Comment by pietropizzi** [comment]
Same issue here

**Comment by pietropizzi** [comment]
I think to get rid of this issue you need to also add the share pod in the podfile

`pod 'react-native-fbsdkshare', :path => '../node_modules/react-native-fbsdk/iOS/share'`

That got rid of the warnings for me. I am not using share though. So it is a little weird.

**Comment by dzhuowen** [comment]
Thanks @pietropizzi for pointing this out. In 0.1.0 you need to install all three kits to make things work. This is because we're using the unified set of JS API for both platform and native Android SDK doesn't divide features into kits.

**Comment by knowbody** [comment]
I get the same issue, I followed the instructions and I get all of those warnings:

```
Warning: Native component for "RCTFBLikeView" does not exist
Warning: Native component for "RCTFBLoginButton" does not exist
Warning: Native component for "RCTFBSendButton" does not exist
Warning: Native component for "RCTFBShareButton" does not exist
```

all of the pods are included in the `Podfile`, any idea what is not correct?

**Comment by jamesone** [comment]
@knowbody  I'm also having the same issue, even after following the instructions. Did you ever find what was going on?

**Comment by jamesone** [comment]
I fixed this, it turns out I forgot to follow step 6 https://developers.facebook.com/docs/ios/getting-started/ 

You must remember to connect your appdelegate.m file with the FB sdk and add the data into your info.plist as well as add the keys into the `LSApplicationQueriesSchemes`. http://stackoverflow.com/questions/32006033/ios-9-fbauth2-missing-from-info-plist

**Comment by JatinKinra** [comment]
Hi , I am also facing the same issue. Did anyone solved this issue.
I creates pod, but when I run the command "pod install", I get this error "No podspec found for `react-native-fbsdkcore` in `../node_modules/react-native-fbsdk/iOS/RCTFBSDK/core`".
Can anybody please tell what I am doing wrong ?

**Comment by kamek-pf** [comment]
Same here on the Android side with RN 0.29. The app builds and runs, but then :
 
```
Warning: Native component for "RCTFBLikeView" does not exist
Warning: Native component for "RCTFBLoginButton" does not exist
Warning: Native component for "RCTFBSendButton" does not exist
Warning: Native component for "RCTFBShareButton" does not exist
```

**Comment by Fandekasp** [comment]
I'm also getting this error for android. This thread explains the resolution for ios by updating the PodFile. Do you know what should I add in which file to get the android build to work properly?

**Comment by depombo** [comment]
Same as @Fandekasp running the example out of the box.

react 15.3.1
react-native 0.33.0
react-native-fbsdk 0.3.0

**Comment by jasmo2** [comment]
Hello on Android what Step should we follow. There is no example
