### ISSUE TITLE
Graph API: Can't get friends list

### ISSUE THREAD

**Issue by SrihariThalla** [facebook/react-native-fbsdk#129]
I can't get the edge `/me/friends` work! I have `user_friends` permission.

I get this output all the time 
```javascript
{
    "data": [],
    "summary": {
        "total_count": 353
    }
}
```

But when I try using the Graph Explorer, everything works fine! All friends of mine are listed with pagination!

**Comment by dzhuowen** [comment]
I guess you did not switch the `Application` on top right corner of Graph API Explorer to your app. If you did you should see the warning `Only friends who installed this app are returned in API v2.0 and higher. total_count in summary represents the total number of friends, including those who haven't installed the app.`

**Comment by SrihariThalla** [comment]
Oh yeah, I forgot that. Either way, I've installed the app on my friend's phone and logged in. Which should mean the edge should return him in the `data` array, but it isn't :confused:
