### ISSUE TITLE
Crash when suspending app

### ISSUE THREAD

**Issue by pietropizzi** [facebook/react-native-fbsdk#130]
Version used: `0.1.0`

In my app if you follow the these steps you can always reproduce a crash:

1. Sign in with Facebook
2. Put app into background
3. The app crashes

The reason is this code here:

![screen shot 2016-04-21 at 14 47 02](https://cloud.githubusercontent.com/assets/410305/14709446/f310d444-07d0-11e6-9c62-3fbf451b5844.png)

When the app is being suspended the TimeSpentData is trying to send something but the `_sessionID` is `nil` which does not go well with the `NSDictionary` and the app crashes.

I do not know why those app events of time spent are even triggering. I did not active that and I did not find any way to deactivate it.

In another place where something similar is done in the code there is an empty string fallback (see `_sessionID ?: @""`)

![screen shot 2016-04-21 at 14 55 59](https://cloud.githubusercontent.com/assets/410305/14709532/6096323e-07d1-11e6-90f5-213b1934e330.png)

Maybe this would be a solution(?)

Any help is appreciated. This is keeping us from an important app release.

**Comment by dzhuowen** [comment]
Hi @pietropizzi I believe this may be a bug in native sdk. It would be greate if you can provide a sample project with the repo.
For workaround, please try manually setting the `_sessionID` when it's nil like this:
Line 154:  _sessionID -> _sessionID ? : [[NSUUID UUID] UUIDString]

**Comment by dzhuowen** [comment]
We will fix this bug in next release of Facebook iOS SDK. Thanks!

**Comment by pietropizzi** [comment]
Cool thanks!

There's one other thing I would like to bring up related to this. The reason we got into a situation where it was hard to get out of quickly was that even when we had version `0.0.7` installed still, the underlying Facebook iOS SDK Pod would still update to the newest version. That is really not good. The way we worked around it was to fork this repo and change it so that the `FBSDKCoreKit` is pinned to a specific version. So we replaced

`s.dependency 'FBSDKCoreKit'`

with

`s.dependency 'FBSDKCoreKit', '4.10.1'`

here

https://github.com/facebook/react-native-fbsdk/blob/master/iOS/core/react-native-fbsdkcore.podspec#L12

Is that something you want to adopt?

**Comment by dzhuowen** [comment]
Thanks for the advice! This is something we can consider doing in the future. 
Besides another workaround for this bug is to call `activateApp` in AppDelegate.m described in [Getting Started guide](https://developers.facebook.com/docs/ios/getting-started#app-events).
