### ISSUE TITLE
Graph API error: Unexpected number of results

### ISSUE THREAD

**Issue by SrihariThalla** [facebook/react-native-fbsdk#131]
I have created a Graph Request in two separate components as said in the README and I'm stuck with this error:
```javascript
Object {exception: "Unexpected number of results", errorMessage: "Unexpected number of results", errorCode: -1, subErrorCode: -1, requestStatusCode: -1}
```

If I disable one of them, everything works fine. What am I doing wrong?

**Comment by SrihariThalla** [comment]
Anyone?

**Comment by dzhuowen** [comment]
Can you provide some more detail of how you use the GraphRequest and error logs?

**Comment by chrisp-fb** [comment]
Closing - feel free to reopen if you're still seeing a problem and can provide more details (e.g., code snippets) to help us understand and reproduce the issue.

**Comment by bollogo** [comment]
I am having the same issue on Android 6.0.1, the same code was working fine on lower Android Versions.
```json
{ exception: 'Unexpected number of results',
errorMessage: 'Unexpected number of results',
errorCode: -1,
subErrorCode: -1,
requestStatusCode: -1 }
```

this is my API-Call, it seems to happen when I send parameters, and also when sending null as parameters.

```javascript
_responseInfoCallback(error, result) {
	if (error) {
		console.log(JSON.stringify(error));
	} else {
		// Handle data
	}
}

const infoRequest = new GraphRequest(
	'/me',
	{
		parameters: {
			fields: {
				string: 'email,name,first_name,last_name,picture.type(large)'
			}
		}
	},
	this._responseInfoCallback
);
```
