### ISSUE TITLE
Cocoapods and Realm

### ISSUE THREAD

**Issue by giacomorebonato** [facebook/react-native-fbsdk#134]
When I remove all of the subprojects in the Libraries group, I remove also the Realm React Native one... And this breaks the application.
How should I add Realm React Native dependency in this scenario?

**Comment by chrisp-fb** [comment]
Sorry, you don't need to remove all the subprojects in the Libraries group - just the core React ones that are are duplicated via Cocoapods. We're working on greatly improving this flow in the next release.
