### ISSUE TITLE
Edit readme.md to make it clearer

### ISSUE THREAD

**Issue by tnguyen42** [facebook/react-native-fbsdk#139]
Hi,

Just a thought since I believe I'm not alone to struggle during the installation: I think it would be clearer to add the [Facebook SDK Getting Started](https://developers.facebook.com/docs/ios/getting-started) steps  left to install in the iOS version into the ReadMe.md.
Maybe a few screenshots would also help to make the installation instructions clearer.

Finally, maybe the troubleshooting section should be completed with how to solve the problems...

I'll be glad to help once I get it to work ^^

**Comment by dzhuowen** [comment]
Hi @tnguyen42 ,
The reason to separate the native iOS installation here is to avoid providing outdated instructions when native sdk installation changes.
You can use our developer site to get a more convenient setup flow. https://developers.facebook.com/docs/react-native/getting-started-ios.
Thanks!
