### ISSUE TITLE
Shouldn't it prompt me to log in? Error "Not logged in: You are not logged in"

### ISSUE THREAD

**Issue by pickhardt** [facebook/react-native-fbsdk#14]
When using the FB Login, the app shows me an error "Not logged in: You are not logged in". Shouldn't it prompt me to first log in, then authenticate the app, instead of showing me an error?

I'm seeing this:

![notloggedin](https://cloud.githubusercontent.com/assets/610082/9419145/125eec4c-480e-11e5-97cf-9dce25662a52.png)

**Comment by cphackm** [comment]
This may be related to your app settings on the Facebook developer portal. Someone on StackOverflow was having a [similar issue](http://stackoverflow.com/questions/31977310/fbsdkloginmanager-with-fbsdkloginbehaviorweb-failing-with-not-logged-in-error) with the iOS SDK(off of which this SDK works), so you might see if the solution offered there helps.

**Comment by philikon** [comment]
Tentatively closing this for now. Please re-open if the solution linked to above doesn't work out.
