### ISSUE TITLE
Error on some Android devices

### ISSUE THREAD

**Issue by ghamaide** [facebook/react-native-fbsdk#140]
When running on some Android devices, Samsung S5 mini for example, I get this error : 
```
Class not found when unmarshalling: com.facebook.login.LoginClient$Request
E/Parcel  ( 9585): java.lang.ClassNotFoundException: com.facebook.login.LoginClient$Request
```

On other devices like Nexus 5 or Samsung Galaxy S4, it works fine... Any ideas why ?

I'm using the package this way : 

```
LoginManager.logInWithReadPermissions(['email', 'user_friends']).then(
      function(data) {
        AccessToken.getCurrentAccessToken().then((accessToken) => {
          // sending the token to back-end here
        });
      },
      function(error) {
        return callback(error);
      }
    );
  }
```

**Comment by dzhuowen** [comment]
Hi @ghamaide, can you paste the complete error stack trace and repro steps here?

**Comment by ghamaide** [comment]
Here's the full error log. 
Repro steps are clicking on a TouchableHiglight that launches the function I wrote in my previous post, nothing more. It launches a blank view (as if it were a normal WebView) but this view disappears and nothing happens...
[log.txt](https://github.com/facebook/react-native-fbsdk/files/251889/log.txt)

**Comment by dzhuowen** [comment]
Thanks! We've seen the similar cases in Facebook Android SDK [here](https://developers.facebook.com/bugs/1621984714705591/). It's likely that some Samsung models cause the issue. We'll look into this and in the meantime, you can also report this bug to Samsung.
I'm closing the thread here. Please keep track of the issue via the external bug tool.
