### ISSUE TITLE
was there any fix for the issue 110

### ISSUE THREAD

**Issue by sasikg** [facebook/react-native-fbsdk#141]
was there any fix for the issue 110 which was closed, I am getting string response for Android Graph Request. I am using react-native-fbsdk 0.1.0.

**Comment by dzhuowen** [comment]
Hmm, the problem should be fixed by 0.1.0 release [here](https://github.com/facebook/react-native-fbsdk/blob/master/js/FBGraphRequestManager.js#L54-64).

**Comment by sasikg** [comment]
Thank you.
