### ISSUE TITLE
FBSDKCore can't find RCTBridgeModule.h

### ISSUE THREAD

**Issue by NKLINDKE** [facebook/react-native-fbsdk#142]
Hi,

Similair as in https://github.com/facebook/react-native-fbsdk/issues/21 my RCTFBSDKCoreinitializer.m cannot find RCTBridgeModule.h, and I have tried to go into build settings under Header Search Paths and changed it to this: 

![skarmavbild 2016-05-04 kl 13 54 01](https://cloud.githubusercontent.com/assets/13731052/15013484/30738d2a-1200-11e6-9f54-a8fc3e543fdc.png)

As I know the BridgeModule is in the /Base folder. But the build still fails throwing the error that it cannot be found. What have I done wrong?

**Comment by xcarpentier** [comment]
+1

**Comment by NKLINDKE** [comment]
I have kind of solved this in a sense (at least relative to my initial issue). My initial goal was to generate the fbAccessToken within JS, but I had many issues with that. But generating it within the app delegate, saving it in a text file in the app domain directory, and then reading it and sending it as a string as described by this method: http://facebook.github.io/react-native/docs/native-modules-ios.html#ios-calendar-module-example

**Comment by chrisp-fb** [comment]
Sorry for the error, we're fixing the header search paths in the next release. It should be 
`$(SRCROOT)/../../../react-native/React/` (recursive = YES) and you'll need to do this for all three `RCTFBSDKCore.xcodepro`, `RCTFBSDKLogin.xcodeproj` and `RCTFBSDKShare.xcodeproj`

Also make sure your app's build setting's Linker Flags include `$(inherited)`.

We'll leave this issue open until the next release.

**Comment by xcarpentier** [comment]
Thx !

**Comment by dzhuowen** [comment]
Closing the issue b/c 0.2.0 is up.
