### ISSUE TITLE
Add missing packages into podfile example

### ISSUE THREAD

**Issue by kohver** [facebook/react-native-fbsdk#144]
Today I had this error:
<img src="https://cloud.githubusercontent.com/assets/795466/15028070/91c67818-124f-11e6-9354-968ecb9d8d32.png" width="260px" />
It was very confusing to me, considering that [React Native docs](https://facebook.github.io/react-native/docs/vibration.html#content) don't tell something about this.
After a long time I figured out, that I don't have a native module in my xcode project. When I added `RCTVibration` at my Podfile and rerun `pod install`, problem was resolved.

```ruby
target 'YourApp' do
  source 'https://github.com/CocoaPods/Specs.git'
  pod 'React', :subspecs => ['Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket', 'RCTVibration'], :path => '../node_modules/react-native'
  pod 'react-native-fbsdkcore', :path => '../node_modules/react-native-fbsdk/iOS/core'
  pod 'react-native-fbsdklogin', :path => '../node_modules/react-native-fbsdk/iOS/login'
  pod 'react-native-fbsdkshare', :path => '../node_modules/react-native-fbsdk/iOS/share'
end
```

I think there are some other packages, that needed to be included. [Random link](https://github.com/facebook/react-native/issues/2025)
```ruby
pod 'React/RCTActionSheet'
pod 'React/RCTGeolocation'
pod 'React/RCTImage'
pod 'React/RCTLinkingIOS'
pod 'React/RCTNetwork'
pod 'React/RCTSettings'
pod 'React/RCTText'
pod 'React/RCTVibration'
pod 'React/RCTWebSocket'
```

**Comment by dzhuowen** [comment]
@kohver , thanks for pointing this out!
The README Podfile only points out some basic subspecs in the react-native package. And as you mentioned you can add any other subspecs you want to use in the project.
Will specify this in the README.
