### ISSUE TITLE
Could not connect to development server

### ISSUE THREAD

**Issue by kuhnhu** [facebook/react-native-fbsdk#146]
I followed the README and fackbook Quick Starts.

1. npm install --save react-native-fbsdk
2. pod init
3. modify Podfile
4. Remove all the subprojects under Libraries/ in Xcode.
5. pod install
6. go to Xcode's target Build Setting section, find Other linker flags and add $(inherited) in it.
7. modify plist 
![2016-05-05_19-01-12](https://cloud.githubusercontent.com/assets/1326897/15042132/0086bb74-12f4-11e6-88cb-c9cce8cfc641.png)
8. run "react-native run-ios"

Got error below. seems the server not started. 
Before install this SDK. when I run  "react-native run-ios". a new terminal open for server. now no terminal open.

![simulator screen shot 5 may 2016 6 57 28 pm](https://cloud.githubusercontent.com/assets/1326897/15042133/00e2114a-12f4-11e6-9b70-53e4f6b20ac9.png)

**Comment by holyxiaoxin** [comment]
run `react-native start` in your project root

**Comment by kuhnhu** [comment]
@holyxiaoxin
It works. Thanks for your suggestion

Do you how to start the server automatically? instead of manually. Thanks a lot~~~

**Comment by kuhnhu** [comment]
I resolved this issue follow comments from (https://github.com/facebook/react-native/issues/3135). Should we add this step into README?

Add run script in build phase.

```bash
if nc -w 5 -z localhost 8081 ; then
if ! curl -s "http://localhost:8081/status" | grep -q "packager-status:running"; then
echo "Port 8081 already in use, packager is either not running or not running correctly"
exit 2
fi
else
open "$SRCROOT/../node_modules/react-native/packager/launchPackager.command" || echo "Can't start packager automatically"
fi
```
![2016-05-06_12-58-33](https://cloud.githubusercontent.com/assets/1326897/15064743/732e85c6-138a-11e6-8c22-8cfcf74e32d4.png)

**Comment by CoericK** [comment]
@kuhnhu I had the same problem, @holyxiaoxin any idea how to fix that besides kuhnhu answer?

**Comment by chrisp-fb** [comment]
This doesn't seem related to the react-native-fbsdk and as noted should have been taken care of react-native start or the project set up from react-native init. Feel free to reopen if I misunderstood or if there's something we should do on the fbsdk side
