### ISSUE TITLE
LoginButton with permissions for email and user_friends not working

### ISSUE THREAD

**Issue by prabak** [facebook/react-native-fbsdk#147]
The following code only gives you the public_profile permission. 

```
  <LoginButton
          publishPermissions={["publish_actions"]}
          readPermissions={["email", "user_friends", "public_profile"]}
          onLoginFinished={this._onFacebookLoginFinished.bind(this)}
          onLogoutFinished={this._onFacebookLogoutFinished.bind(this)}
        />

```
When user logins in, they are only shown the public profile access permission. No mention of friend list or email during the authentication process. However as mentioned on the documentation, if I do the following using the LoginManager, it does work.

```
LoginManager.logInWithReadPermissions(['email', 'user_friends', 'public_profile']).then(
      function(result) {
        __DEV__ && console.log("Signup [_onLoginWithFacebook] result", result);
        if (result.isCancelled) {
          __DEV__ && console.log("Signup [_onLoginWithFacebook] result cancelled");
        } else {
          __DEV__ && console.log("Signup [_onLoginWithFacebook] result signed in with permissions:", result.grantedPermissions.toString());
        }
      },
      function(error) {
        __DEV__ && console.log("Signup [_onLoginWithFacebook] error", error);
      }
    );

```

Is this bug with LoginButton? Or is LoginButton support only for publishPermissions and public_profile for readPermissions?

**Comment by dzhuowen** [comment]
You cannot require read permissions and publish permissions at the same time. 
See https://developers.facebook.com/docs/facebook-login/permissions/requesting-and-revoking#optimizing

**Comment by bpred754** [comment]
If anyone is still running into this like I was, `readPermissions` has now been replaced with `permissions`

```
 <LoginButton
          permissions={["email", "user_friends", "public_profile"]}
          onLoginFinished={this._onFacebookLoginFinished.bind(this)}
          onLogoutFinished={this._onFacebookLogoutFinished.bind(this)}
        />
```

**Comment by douglasjosenieves** [comment]
> LoginButton

Bro me estaba volviendo loco con esto jajajaj gracias

**Comment by anonewb** [comment]
> If anyone is still running into this like I was, `readPermissions` has now been replaced with `permissions`
> 
> ```
>  <LoginButton
>           permissions={["email", "user_friends", "public_profile"]}
>           onLoginFinished={this._onFacebookLoginFinished.bind(this)}
>           onLogoutFinished={this._onFacebookLogoutFinished.bind(this)}
>         />
> ```

Thanks a lot, mate! You saved me.
