### ISSUE TITLE
Sample App: FBSDKShareKit.h file not found.

### ISSUE THREAD

**Issue by chirag04** [facebook/react-native-fbsdk#15]
I just cloned the repo. Did npm install. I get below error when i try to run the sample app.

```
Sample/node_modules/react-native-fbsdkshare/iOS/RCTFBSDKShareDialog.h:21:9: 'FBSDKShareKit/FBSDKShareKit.h' file not found
```

I can see shareKit framework being linked in the Sample app. Not sure what else i can do to debug this.

**Comment by chirag04** [comment]
Ohk. I think it's because i downloaded the framework at a wrong location. Let me test with Documents/FacebookSDK

**Comment by Fluzing** [comment]
Could you be more specific how you solved this? I have the same isue.

**Comment by chirag04** [comment]
I download the fbsdk at some random location while xcode was looking for it in ``Documents/FacebookSDK`` directory

**Comment by lrettig** [comment]
Happened to me too. I had to update the "Framework Search Paths" setting under Build Settings for RCTFBSDKShare (not for my base project).
