### ISSUE TITLE
FBLogin button not returning onLoginFinished in v0.1.0

### ISSUE THREAD

**Issue by tooba** [facebook/react-native-fbsdk#152]
With the example code below I end up at a blank Facebook web page. Clicking the button leads to the standard Facebook login page showing the correct permissions request. Clicking Continue then leads to a blank web page. onLoginFinished never fires. The app does show as logged within the users app privacy settings on the Facebook site.

The only option is to then click Done which does fire onLoginFinished but cancels the login. How can I get the button to complete the login?

```
<LoginButton
          publishPermissions={["publish_actions"]}
          onLoginFinished={
            (error, result) => {
              if (error) {
                alert("login has error: " + result.error);
              } else if (result.isCancelled) {
                alert("login is cancelled.");
              } else {
                alert("login has finished with permissions: " + result.grantedPermissions)
              }
            }
          }
          onLogoutFinished={() => alert("logout.")}/>
```

**Comment by futhrevo** [comment]
Can you confirm behaviour on android/iOS or both?

**Comment by tooba** [comment]
Currently only tested and seen the issue on iOS

**Comment by tooba** [comment]
I'd missed out step six on the iOS SDK setup guide here - [https://developers.facebook.com/docs/ios/getting-started](https://developers.facebook.com/docs/ios/getting-started). This meant the login actions weren't returning. Adding the correct lines to appdelegate.m means the login button is working as expected.
