### ISSUE TITLE
Can't share Image with ShareDialog or ShareApi 

### ISSUE THREAD

**Issue by nicholasstephan** [facebook/react-native-fbsdk#154]
This may just be me doing something wrong, but I can't get the ShareDialog or ShareApi to share images. The docs have this snippet:

    const shareLinkContent = {
      contentType: 'link',
      contentUrl: "https://facebook.com",
      contentDescription: 'Wow, check out this great site!',
    };

    // ...

    // Share using the share API.
    ShareApi.canShare(this.state.shareLinkContent).then(
      var tmp = this;
      function(canShare) {
        if (canShare) {
          return ShareApi.share(tmp.state.shareLinkContent, '/me', 'Some message.');
        }
      }
    ).then(
      function(result) {
        alert('Share with ShareApi success.');
      },
      function(error) {
        alert('Share with ShareApi failed with error: ' + error);
      }
    );

which doesn't even seem to be valid javascript with the `var tmp = this;` just hanging outside the function like that. Even once that's corrected, I get the error

    ShareApi.canShare is not a function

Using `ShareDialog` with the following:

    const sharePhotoContent = {
      contentType: 'photo',
      photos: [
        {
          imageUrl: "./path/to/my/image.png",
          userGenerated: false,
          caption: "Hello World"
        }
      ]
    };

    ShareDialog.canShow(sharePhotoContent).then(
      function(canShow) {
        if (canShow) {
          return ShareDialog.show(sharePhotoContent);
        }
      }
    ).then(
      function(result) {
        if (result.isCancelled) {
          AlertIOS.alert('Share cancelled');
        } else {
          AlertIOS.alert('Share success with postId: ' + result.postId);
        }
      },
      function(error) {
        AlertIOS.alert('Share fail with error: ' + error);
      }
    );

`RCTFBSDKShareDialog.m` throws the error

    Exception '-[NSError _fastCStringContents:]: unrecognized selector sent to instance ... while invoking canShow on target FBShareDialog with params ...

Is there an example somewhere of this working?

**Comment by dzhuowen** [comment]
Based on the error message you're working on the iOS side. The canShare method of ShareAPI is only available to [Android](https://github.com/facebook/react-native-fbsdk/blob/master/js/FBShareApi.js#L29-L33)
For ShareDialog can you provides more detail of your code(especially the imageUrl part) and the error stack trace? 
Sorry for the confusion on the code sample. Feel free to send a PR for that :).

**Comment by nicholasstephan** [comment]
Yes, ideally I'd like to release both iOS and Android, but for now I'm only looking at iOS. 

I'm using FBSDKCoreKit, FBSDKLoginKit and FBSDKShareKit v4.12.0, the latest version of react-native-fbsdk; v0.2.1. 

I'm able to log a user in successfully with 

`LoginManager.logInWithPublishPermissions(['publish_actions'])`

I'm able to share a link successfully with; 

    ShareDialog.canShow(shareLinkContent).then(
      function(canShow) {
        if (canShow) {
          return ShareDialog.show(shareLinkContent);
        }
      }
    ).then(
      function(result) {
        if (result.isCancelled) {
          alert('Share cancelled');
        } else {
          alert('Share success with postId: '
            + result.postId);
        }
      },
      function(error) {
        alert('Share fail with error: ' + error);
      }
    );

So I believe everything is set up correctly. 

Trying to use `ShareApi` with the same link content as the `ShareDialog` like so

`ShareApi.share(shareLinkContent, '/me', 'Some message.');`

gives me this is the JS debugger:

    ShareAPI encounters error
    Error: ShareAPI encounters error
        at createErrorFromErrorData (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:3485:11)
        at http://localhost:8081/index.ios.bundle?platform=ios&dev=true:3440:11
        at MessageQueue.__invokeCallback (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:3317:10)
        at http://localhost:8081/index.ios.bundle?platform=ios&dev=true:3200:8
        at guard (http://localhost:8081/index.ios.bundle?platform=ios&dev=true:3145:1)
        at MessageQueue.invokeCallbackAndReturnFlushedQueue (http://localhost:8081/    index.ios.bundle?platform=ios&dev=true:3199:1)
        at DedicatedWorkerGlobalScope.onmessage (http://localhost:8081/debuggerWorker.js:39:56)    


and no errors in XCode. 


I know, still not a lot to go on... that's the trouble.

Can you maybe just put a working example of a) the ShareApi sharing a link, and b) Sharing an image in the samples?

Thanks

**Comment by dzhuowen** [comment]
@nicholasstephan Sorry for getting back such late. Did you log in to facebook before sharing with ShareApi? 
For sharing image, you can use the [react-native-image-picker](https://github.com/marcshilling/react-native-image-picker) to get the uri of the image and use it create a SharePhotoContent. Note that you need to have the facebook app installed in order to share an image.

**Comment by dzhuowen** [comment]
Closing b/c of inactivity.

**Comment by agenthunt** [comment]
The way I got this to work is as follows (Tested on android device and ios simulator)
Make sure you have publish actions permissions

```
        const sharePhoto = {
          imageUrl: 'file:///sdcard/test.png',
          userGenerated: false,
          caption: 'hello'
        };
        const sharePhotoContent = {
          contentType: 'photo',
          photos: [sharePhoto]
        };
       ShareApi.share(sharePhotoContent, '/me', 'Hello')
        .then((result)=> {
          alert(JSON.stringify(result));
         })
         .catch((error) => {
           alert(JSON.stringify(error));
        });
```
