### ISSUE TITLE
Can't login through native facebook app on Android

### ISSUE THREAD

**Issue by allmaxgit** [facebook/react-native-fbsdk#158]
Kind of a strange issue: login works fine when web version is used, but fails when using a native app. 

`FBLoginManager.logInWithReadPermissions(['email', 'public_profile']).then(
      result => this._fbLoginResponseHandler(result),
      error => this._errorHandler(error)
    );`

Once I enter correct credentials it loads for a little while and then I get this strange error:
![screenshot_2016-05-13-10-30-44](http://i.imgur.com/lEyw4dd.png)

react-native 0.23&0.25(haven't tried 0.24)
Android 4.4.2.
react-native-fbsdk 0.1.0

**Comment by dzhuowen** [comment]
Can you provide more detail on how you use the sdk in the code and error stack trace?

**Comment by allmaxgit** [comment]
So there's a touchable opacity that triggers function I posted in original post, then I handle results and error, and that's it. 
So I tried to debug this in Chrome and I got different error message, though I still don't really get it. What's with those key hashes and why do they match fine in web version and don't match in native app?
![screen shot 2016-05-16 at 1 49 05 pm](https://cloud.githubusercontent.com/assets/16587631/15283577/62a3f304-1b6d-11e6-8e9a-7f3f0bb18db7.png)

**Comment by dzhuowen** [comment]
The web version is using jssdk, which is not related to react-native-fbsdk. react-native-fbsdk is a wrapper around the native Facebook SDK. 
To use Facebook login in Android, you need to [set the development key hash](https://developers.facebook.com/docs/android/getting-started#create_hash) in the 'quick start' dash board.
Sorry for the confusion, I'll work on surfacing the errors.

**Comment by dzhuowen** [comment]
Feel free to reopen this if you're still seeing error after setting up the key hash :)
