### ISSUE TITLE
While `pod install` recieve an error on missed specification 

### ISSUE THREAD

**Issue by A1ex5andr** [facebook/react-native-fbsdk#159]
After `pod init` trying to install and getting a message: 
[!] Unable to find a specification for `FBSDKCoreKit` depended upon by `react-native-fbsdklogin`

**Comment by chrisp-fb** [comment]
Are you using Cocoapods 1.0? Can you try specifying `source 'https://github.com/CocoaPods/Specs.git'` in your Podfile to make sure you're accessing the main Cocoapods trunk?

**Comment by A1ex5andr** [comment]
My pod version is 1.0.0.
source is exactly as described in readme:
`target 'IWONADO' do
  source 'https://github.com/CocoaPods/Specs.git'...`

**Comment by chrisp-fb** [comment]
Odd. If you create a brand new iOS project in Xcode and set up a Podfile there to declare `pod 'FBSDKCoreKit'`, does it work? That error message seems to imply Cocoapods is unable to find the podspec and seems unrelated to the react-native-fbsdk in particular, so doing a test with a new Xcode project independent of react native might confirm that. If so, then maybe you can uninstall and reinstall Cocoapods.

Also our next release (hopefully this coming week) will remove the next for Cocoapods so worst case we'll resolve it that way.

**Comment by A1ex5andr** [comment]
Problem was with Cocoapods master branch. reinstalling solved the problem. 
Best regards.

**Comment by dzhuowen** [comment]
Closing the resolved issue.
