### ISSUE TITLE
undefined is not an object

### ISSUE THREAD

**Issue by tnguyen42** [facebook/react-native-fbsdk#16]
Hi,

I reset my entire project and I got it to compile. Only this time, I'm having "undefined is not an object" errors that I didn't have using the same code on 0.0.3:

![image](https://cloud.githubusercontent.com/assets/12211685/9455028/60ba657c-4ac7-11e5-8f3f-83cf76bf9692.png)

(for the search record, this is about getCurrentAcessToken)

When commenting that part, I get the same thing with FBSDKNativeGraphRequestManager.addConnection.

I think I followed the installation steps correctly, but just in case, here's my project navigator:
![image](https://cloud.githubusercontent.com/assets/12211685/9455102/0f97daa2-4ac8-11e5-912a-1e302329d90c.png)

Of course I'm available is further details are required to find a solution...
Thanks in advance!

**Comment by tnguyen42** [comment]
Closing this issue which has been solved with issue #17.

**Comment by yelled3** [comment]
@t2munika 
aside from the issue,
the way to do this:
```js
const FBSDKCore = require('react-native-fbsdkcore');
const {
  FBSDKAccessToken
  } = FBSDKCore;

FBSDKAccessToken.getCurrentAccessToken((token)=> {
      console.log('token');
      console.log(token);
    });
```

**Comment by tnguyen42** [comment]
If you meant to tag me, it was just an installation issue. Nothing was defined since I didn't "Link Binary with Libraries" as you said in #17 ;)
