### ISSUE TITLE
LoginButton not closing the browser

### ISSUE THREAD

**Issue by grbinho** [facebook/react-native-fbsdk#160]
Hi all,

I'm trying out LogginButton from the sdk and I noticed that when using default behavior, after going through the login process in the browser, control is never returned (no callback is fired). Only way to get back is to click on done, which gives canceled result in `onLoginFinished`.

When `loginBehaviorIOS='web'` is set, it behaves as expected.

**Comment by gopidon** [comment]
+1

**Comment by chrisp-fb** [comment]
Did you complete the steps in https://developers.facebook.com/docs/ios/getting-started specifically the section about updating your application delegate; e.g., 
```
//  AppDelegate.m
#import <FBSDKCoreKit/FBSDKCoreKit.h>

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  [[FBSDKApplicationDelegate sharedInstance] application:application
    didFinishLaunchingWithOptions:launchOptions];
  // Add any custom logic here.
  return YES;
}

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
  BOOL handled = [[FBSDKApplicationDelegate sharedInstance] application:application
    openURL:url
    sourceApplication:sourceApplication
    annotation:annotation
  ];
  // Add any custom logic here.
  return handled;
}
```

**Comment by jpohhh** [comment]
FWIW, I was having an identical issue, and implementing `- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
` fixed everything. Thank you for the reminder Chris 👍

**Comment by grbinho** [comment]
@chrisp-fb That was it. Tnx for the help!

I'm just a noob in the iOS world, so this kind of thing was not obvious to me.
It did follow most of those steps, but not that one :) I kind of figured that it comes with the library. 

Maby it's an idea to put this link into readme?

**Comment by chrisp-fb** [comment]
Yep, the readme has the link in [3.3 Configure native sdk](https://github.com/facebook/react-native-fbsdk#33-configure-native-sdk) but we will be updating the whole flow in the next release to hopefully make it simpler and more clear.
