### ISSUE TITLE
iOS Still require fill username/pass for fb login

### ISSUE THREAD

**Issue by nvcken** [facebook/react-native-fbsdk#163]
I have already login fb account. Why open f8 app still prompt text box require fill username/pass.
I see f8app include fbsdk module, so I thought it should be allow login with fb device account.
I am confuse
p/s: I see login scene look likes web view. Is that the reason ?
Related : https://github.com/fbsamples/f8app/issues/44

**Comment by chrisp-fb** [comment]
This is intentional on iOS 9. You can learn more about our reasoning at https://developers.facebook.com/blog/post/2015/10/29/Facebook-Login-iOS9/

**Comment by nvcken** [comment]
Thanks, I read it.
But I got login scene likes this, not what I expect
![img_0146](https://cloud.githubusercontent.com/assets/3489866/15309785/185ba3c6-1c14-11e6-9da7-a9ce9351902f.PNG)

**Comment by mingflifb** [comment]
If you got to this screen from the F8 app then something is wrong. If you got to this screen from the Pinterest app, then it's as expected.

**Comment by nvcken** [comment]
sorry I posted wrong screenshot, I also got this on f8app
![img_0052](https://cloud.githubusercontent.com/assets/3489866/15346205/b1f01cf8-1cdf-11e6-8474-0889e7b88d9f.PNG)

**Comment by nvcken** [comment]
Two app login in with Facebook still take me to same page require fill up user/pass, what I expect is that a prompt to allow use my already login fb account on iOS device.
