### ISSUE TITLE
Missing step in your guide: Add FacebookActivity to manifets

### ISSUE THREAD

**Issue by yaronlevi** [facebook/react-native-fbsdk#170]
It is not clear enough from your guide that you should add FacebookActivity to the manifest. It can easily be overlooked because you say "already taken care of by the steps above". It would be kind of you to add this step and save a developer some precious time (-:

**Comment by dzhuowen** [comment]
Thanks for the suggestion, we'll address the problem this problem in the next release. 
Keeping the thread open till the updated readme is on.

**Comment by dzhuowen** [comment]
Closing the issue b/c readme is updated with 0.2.0.
