### ISSUE TITLE
Please clarify how to manually install this. Cocoapods don't plays well with rnpm link

### ISSUE THREAD

**Issue by rturk** [facebook/react-native-fbsdk#174]
Please clarify how I can use this lib manually linking to existing Xcode Project. I can't make cocooapods work with other libraries.

**Comment by dzhuowen** [comment]
Please use rnpm with v0.2.0. Feel free to open a new issue if you have problem with rnpm install process.

**Comment by rturk** [comment]
@dzhuowen this was quite fast. thank you!

**Comment by ajoshdee** [comment]
I need help on this, I installed fbsdk via cocoapods, but RNfbsdk can't find it
