### ISSUE TITLE
Better upgrade guide 0.1.0 -> 0.2.0

### ISSUE THREAD

**Issue by knowbody** [facebook/react-native-fbsdk#178]
I think there should be better upgrade guide, there are quite a few breaking changes.

In my case I used CocoaPods only because of fbsdk 0.1.0, now that 0.2.0 is released I could get rid off CocoaPods:

Here is how to do it quickly:

```sh
$ sudo gem install cocoapods-deintegrate cocoapods-clean
$ pod deintegrate
$ pod clean
$ rm Podfile
```

I would also take the steps from [Getting Started](https://developers.facebook.com/docs/ios/getting-started/) (for both Android and iOS) and include them here in the README, as it requires to jump back and forth between the pages at the moment, specially that Android requires you to do some of the steps not all of them. And for example if someone used previous 0.1.0 half of the steps are already done. Would be good to underline what should be done for the upgrade and for starting the new project with 0.2.0.

Thanks again for the release as it solves a lot of issues!

**Comment by jamesone** [comment]
This should definitely be put in the README!

**Comment by chrisp-fb** [comment]
Great suggestion, I'll update the changelog to call this out and link from the README

**Comment by digitalcatnip** [comment]
I personally find it annoying I have to put the Facebook library in ~Documents, where it pollutes the directory where I store actual documents.  It's kind of an odd place for it - can't we install it in ~/.FB or ~Library or something?  It's not like the general public is going to be implementing the Facebook SDK.

**Comment by jamesone** [comment]
You can place it anywhere you like, as long as it's referenced in the new location and not the  documents folder.

Sent from Outlook




On Mon, May 23, 2016 at 3:22 PM -0700, "James McCarthy" <notifications@github.com> wrote:












I personally find it annoying I have to put the Facebook library in ~Documents, where it pollutes the directory where I store actual documents.  It's kind of an odd place for it - can't we install it in ~/.FB or ~Library or something?  It's not like the general public is going to be implementing the Facebook SDK.

**Comment by dzhuowen** [comment]
@knowbody The upgrade guide is up. I'm not sure if there're other easy way to re-add the static libraries back to the project besides `react-native upgrade`. Feel feel to comment / reopen the issue if there's a better way.

**Comment by abefetterman** [comment]
Could you post a link to the upgrade guide? I'm having trouble finding it

**Comment by dzhuowen** [comment]
It's in the release note

**Comment by digitalcatnip** [comment]
@jamesone That doesn't work because the path is hard coded in the node_modules XCode project, which many people do not commit to VCS.  So, if you work on a multi-developer project you either get the entire team to manually edit the XCode project in node_modules or you just suck it up and stick it in Documents, which I have now done.

**Comment by knowbody** [comment]
@dzhuowen thank you for writing it down, sorry I didn't find the time to do it.
