### ISSUE TITLE
FBSDKShareKit/FBSDKShareKit.h file not found

### ISSUE THREAD

**Issue by dyf102** [facebook/react-native-fbsdk#180]
react-native-cli: 0.1.10
react-native: 0.26.1

After I run rnpm install react-native-fbsdk in a brand new project.

**Comment by dzhuowen** [comment]
Probably the same issue [here](https://github.com/facebook/react-native-fbsdk/issues/175)?

**Comment by chrisp-fb** [comment]
@dyf102 Make sure you've added all three FBSDKCoreKit, FBSDKLoginKit, FBSDKShareKit, and that they were installed to the `~/Documents/FacebookSDK` directory. Feel free to add more info/reopen if that doesn't work.
