### ISSUE TITLE
Support SDKs installed outside of ~/Documents/FacebookSDK (a.k.a. Change build target RCTFBSDK)

### ISSUE THREAD

**Issue by knowbody** [facebook/react-native-fbsdk#181]
As per discussion in #177 I think we should change the default location of where the build target RCTFBSDK is looking for the SDK.

> If you put the iOS SDK in a fixed location like ~/Documents/FacebookSDK, you can use this sdk for all you react-native projects without keeping multiple copies of the SDK in your local, right?

I don't think that @dzhuowen reasoning is wrong, is just another solution, which might be useful in some cases.

On the other hand I think that the SDK should be tightly coupled with the project:

> If you work in a team do you ask everyone to install FBSDK in their Documents directory, also what if I need different versions of the SDK for different projects? I would just expect to git clone the project and start working with it.

I do agree that `rnpm` is a great solution as it makes it easy to add the library to the project, but I think we should support Cocoapods users too.

**Comment by Maxyss** [comment]
I think will be nice to add cocoapods support as well. Because now it's hard to use with CI services.

**Comment by chrisp-fb** [comment]
Hey everyone, thanks for the thoughts. We went with ~/Documents to be consistent with non-react-native developers who manually install our SDK or follow the typical instructions from our developer portal.

That said, this is great feedback and I'm looking at ways to make this better still. Cocoapods hasn't worked out well for us given all the extra steps and is actually more likely to cause esoteric errors for people who haven't worked with it before.  You all raise really good points about CI and build determinism, so I'm pretty sure we can still install the SDKs into a local folder under your project (and thus under local source control) as long as you update the search path for the build target - you'd have to do this yourself for now.

**Comment by dzhuowen** [comment]
Here're the steps to include iOS SDK in the project.
* Create a `FacebookSDK` directory under `node_modules/react-native-fbsdk/iOS/`. We'll put the SDK here.
* Download and unzip FacebookSDK archive, copy `FBSDKCoreKit.framework`, `FBSDKLoginKit.framework` and `FBSDKShareKit.framework` and paste it into `node_modules/react-native-fbsdk/iOS/FacebookSDK`.
* Create a new group `Frameworks` in the Project navigator and drag the `FBSDKCoreKit.framework`, `FBSDKLoginKit.framework` and `FBSDKShareKit.framework` into the `Frameworks` group.
* Tell the `RCTFBSDK` target where to search for the SDK by adding `$(SRCROOT)/FacebookSDK` in the **Frameworks Search Path** section under the target RCTFBSDK's **Build Settings**.
* Tell your project where to search for the SDK by adding `$(SRCROOT)/../node_modules/react-native-fbsdk/iOS/FacebookSDK` in the **Frameworks Search Path** section under the app target **Build Settings**.
* Follow the [Getting Started Guide](https://developers.facebook.com/docs/ios/getting-started) to Create a Facebook App, Configure Facebook App Settings for iOS,  Configure Xcode Project, Connect Application Delegate. Now you can start using the SDK.

**Comment by dzhuowen** [comment]
The steps are added to the release note as well. Feel free to comments/reopen if that doesn't work.

**Comment by mtven** [comment]
@chrisp-fb but pods is well known tool, maybe sometimes it gives strange errors but it's quite easy to figure out what's wrong. 

@dzhuowen could you explain how to do that on CI server? :) Every time it spin up new vagrant machine.

@chrisp-fb @dzhuowen how hard is to add cocoapods as well? Can I help you?

**Comment by knowbody** [comment]
maybe we can have a rnpm plugin which does all the steps above, then it would be easy to run it in the CI. /cc: @grabbou

**Comment by grabbou** [comment]
BTW

> We went with ~/Documents to be consistent with non-react-native developers who manually install our SDK or follow the typical instructions from our developer portal

That is a no-go for me as I have FacebookSDK installed through CocoaPods e.g. by Appodeal and other 3rd party vendors using it for advertising and logging.

@knowbody There's work on our side to support installing native modules. Extra hands would be appreciated though :)

**Comment by knowbody** [comment]
@grabbou I'm ready 🙌

**Comment by chrisp-fb** [comment]
We'll tweak the FRAMEWORK_SEARCH_PATHS in the RTCFBSDK wrapper so that it can also look locally for the FBSDK frameworks: https://github.com/facebook/react-native-fbsdk/pull/191

That'll make it easier to install the FBSDK* into local directories for build servers and decoupling different projects. I also took a stab at writing a [node script](https://github.com/facebook/react-native-fbsdk/pull/191) to do the linking, amd I'll still work on improving that (i.e., I'm thinking it would be really nice to have an official FB npm that downloads the sdk and modifies the app's plist, etc per our Getting Started guide). In the meantime, that means you can do something like the following with a brand new project

```
rnpm install react-native-fbsdk;
mkdir ios/Frameworks; #make a local folder for the FBSDK frameworks
curl -#L https://origincache.facebook.com/developers/resources/?id=facebook-ios-sdk-current.zip | bsdtar -xf- -C ./ios/Frameworks; #download them
npm install xcode; #for my node script
curl https://gist.githubusercontent.com/chrisp-fb/ade0baca1391982f97e2fbc0ad73b934/raw/d3d81a38d2465f8e820285a4a5f5656ef5f9c5a9/fbsdk-setup.js | node; 
# now open your xcodeproj file and finish the rest of the plist configuration
```

Our FBSDK frameworks will continue to support Cocoapods also so you can still use that if that's your preference - you just might need to tweak the FRAMEWORK_SEARCH_PATHS in RTCFBSDK.xcodeproj to be able to find them correctly.

**Comment by knowbody** [comment]
Thanks for your work @chrisp-fb. Shout if you need some help.

**Comment by digitalcatnip** [comment]
@chrisp-fb I think your proposal is solid.  Let me know if you need help / testing.

**Comment by grabbou** [comment]
@chrisp-fb Would you be up to writing `rnpm` plugin for that? I'd be happy to offer some help re: the general structure.

**Comment by Maxyss** [comment]
Can we have option in rnpm which asks for where to search sdk: in cocoapods or default location like ~/FacebookSDK?

**Comment by knowbody** [comment]
@Maxyss I don't think this is a solution to the problem, you can always change it via XCode and this option wouldn't change anything IMO. I look for more out of the box solution, where I don't need to care about the whole config.

**Comment by ajoshdee** [comment]
Hi, Is there a way to get rid of the auto linker warning, I don't want to import fbsdk in my project.

**Comment by vkartaviy** [comment]
👍 for Cocoapods. For now we are patching `HEADER_SEARCH_PATHS` in xcode project.

**Comment by vkartaviy** [comment]
@chrisp-fb Why not to add `"$(PROJECT_DIR)/../../../ios/**"` into `HEADER_SEARCH_PATHS` too?

**Comment by chrisp-fb** [comment]
@vkartaviy good point - do you want to submit a pull request?

**Comment by Maxyss** [comment]
I would like to reference this project https://github.com/auth0/react-native-lock as an example of co-existing rnpm and cocoapods.

**Comment by grabbou** [comment]
Thanks @Maxyss, there are actually quite a few examples of that (and people tend to support both cases for the sake of better developer experience). I believe we should try to do it in a way that FBSDK can be either pulled separately through CocoaPods, put in `vendor` folder (or any other in-project folder) manually by the user or present in the Documents (suggested Facebook guide). I think that two first should be easy to achieve with correct search paths w/o any extra steps required.

**Comment by marcshilling** [comment]
Maybe I'm missing something here but isn't `../../../ios` _way_ too many levels up?

My app structure is `MyApp/ios/MyApp.xcodeproj`. The search paths that were added in response to this issue take me all the way back to `~/`

**Comment by alexanderjarvis** [comment]
I just got bitten by this where my project was previously using Cocoapods to include the FacebookSDK.. and now I need to manually download and configure it. I think I'll wait until the rnpm script can do this for me (that would be the best solution I think). Then perhaps I can ditch pods altogether.

Also I should point out that this new way of doing things wasn't clear in the README.

**Comment by ipsy-eric** [comment]
Another great reason to not reference ~/Documents is for build automation tools and continuous integration, such as that offered by Bitrise
