### ISSUE TITLE
Why was cocoapods support removed in 0.2.0?

### ISSUE THREAD

**Issue by aforty** [facebook/react-native-fbsdk#184]
I really prefer to manage native components via cocoapods because I also include some non-RN components in my project as well. 

Why was this removed in 0.2.0? Oversight or by design?

**Comment by chrisp-fb** [comment]
By design - Cocoapods introduced more complexity in the set up especially for developers that are not familiar with it. That said, you're still welcome to use it but we didn't want to prescribe it as the typical installation method.

**Comment by SudoPlz** [comment]
Thats too bad, all my dependencies are pods, (fbsdk v1 was a pod too) now we have to mix pods with /Libraries using rnpm....
