### ISSUE TITLE
Undefined symbols for architecture x86_64:   "_OBJC_CLASS_$_FBSDKHashtag"

### ISSUE THREAD

**Issue by ghamaide** [facebook/react-native-fbsdk#188]
I'm having trouble understanding why I get this error when compiling ? I have added the framework as explained in the Readme (it is in my project navigator on the left of the screenshot..). Any thoughts on what I'm doing the wrong way ?

<img width="1280" alt="screen shot 2016-05-24 at 15 15 59" src="https://cloud.githubusercontent.com/assets/6986811/15505143/720f4126-21c2-11e6-8bd9-8924689360f5.png">

**Comment by sgwilym** [comment]
Having the same problem, even though the Facebook SDK is installed.

**Comment by dzhuowen** [comment]
@ghamaide please use using the iOS SDK 4.11+. Feel free to reopen the issue if it still doesn't work.

**Comment by ghamaide** [comment]
I downloaded the latest SDK from here : https://developers.facebook.com/docs/ios/downloads

I still have the same error : 
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FBSDKHashtag", referenced from:
      objc-class-ref in libRCTFBSDK.a(RCTConvert+FBSDKSharingContent.o)
```

The FBSDKHashtag.h file is in the Framework (as in the picture in the initial question)...

**Comment by sgwilym** [comment]
@ghamaide I found a solution to this.

In your product’s build phases, expand 'Link binary with Libraries'. Add libraries with the + button in the lower left of the expanded pane, and this sheet should appear:

<img width="393" alt="screen shot 2016-05-25 at 11 17 10" src="https://cloud.githubusercontent.com/assets/579491/15534664/3f688158-226a-11e6-9669-9b18ceea1a68.png">

Select 'Add Other' in the lower left, and navigate to the FacebookSDK folder in Documents, and select the frameworks you need (e.g. FBSDKCoreKit, FBSDKLoginKit, etc.)

Hope this helps!

**Comment by ghamaide** [comment]
@sgwilym I've done this already, and they appear in the left pane of my Xcode project 

![screenshot](https://cloud.githubusercontent.com/assets/6986811/15535457/c3e34d66-226d-11e6-84e5-5d92068272a1.png)

**Comment by chrisp-fb** [comment]
Did you make sure that the FRAMEWORK_SEARCH_PATHS for your project is set to find the correct SDK libraries? The items in the left navigation pane unfortunately may not match what the linker actually finds.

**Comment by chrisp-fb** [comment]
To clarify, FBSDKHashTag was added in v4.11 of the SDK, so it looks like the linker is finding an older version of FBSDKShareKit.

**Comment by ghamaide** [comment]
Yes, I'm pretty sure the path is set correctly. Check the following two screenshots that show the frameworks paths and my finder.
<img width="1280" alt="screen shot 2016-05-26 at 08 32 55" src="https://cloud.githubusercontent.com/assets/6986811/15565691/9c5eaf74-231c-11e6-9cda-ee766ccdbb7f.png">
<img width="1280" alt="screen shot 2016-05-26 at 08 33 04" src="https://cloud.githubusercontent.com/assets/6986811/15565692/9c7a8618-231c-11e6-8e43-d05d21d2609d.png">

**Comment by dzhuowen** [comment]
Did you make sure the `Framework Search Path` for build target NeedIIOS is also set correctly? The screenshot is only showing the search path for build target RCTFBSDK.
As @chrisp-fb mentioned the NeedIIOS build target might be using an old SDK.

**Comment by ghamaide** [comment]
Indeed, the Framework Search Path for build target NeedlIOS was wrong. Thanks for your help !

**Comment by florentdestremau** [comment]
I put the link towards `~/Documents/FacebookSDK` on top of all the rest and this did the trick.
