### ISSUE TITLE
Better location for Facebook SDK for iOS

### ISSUE THREAD

**Issue by digitalcatnip** [facebook/react-native-fbsdk#192]
Following on back of issue #178 , I had a think about my complaint regarding placing the Facebook SDK for iOS in your Documents folder and whether there's a more proper place for it.

A suggestion was made that I could change the XCode project for FBSDK and place the SDK wherever I want, but it resides in node_modules which many teams including the default React Native `init` command choose to ignore from version control.

The current solution works okay for individuals working on multiple React Native projects, but I see three major flaws with the location.

- Multiple developers on the same project may not have the same version of the Facebook SDK installed, causing strange behavior
- Developers store their source directories all over, so it's difficult to get the XCode framework linking for the project correct when it relies on the location of the react native project relative to the Documents directory.
- There's no audit tracking on when the library should be upgraded by team members, so it's hard to track where issues arise related to different FBSDK versions.

My recommendation is to place the SDK in the root directory of the React Native project.  This requires multiple copies of the SDK if you work on multiple apps (as I do) but it relieves the amount of work on the developer to get the project up and running.  Just having a folder called FacebookIOSSDK or something is sufficient in my opinion.

**Comment by chrisp-fb** [comment]
Yep, what do you think about https://github.com/facebook/react-native-fbsdk/issues/181#issuecomment-221413381 (going to close this in favor of that thread; but we can reopen if there's a distinct issue).
