### ISSUE TITLE
[Question] Any plan for AccountKit?

### ISSUE THREAD

**Issue by kkgelu** [facebook/react-native-fbsdk#198]
It would be cool to have it in this component too!

**Comment by chrisp-fb** [comment]
Thanks for the feedback. Not yet, but there have been some community efforts you can try (I haven't tried them myself):

https://www.npmjs.com/package/react-native-account-kit
https://www.npmjs.com/package/react-native-facebook-account-kit

**Comment by karimmorta** [comment]
These libraries are good but they don't allow for much customization of the UI. You can't really integrate the workflow in a completely custom design. No plans to integrate this in the official SDK yet :) ?
