### ISSUE TITLE
JS SDK?

### ISSUE THREAD

**Issue by tnguyen42** [facebook/react-native-fbsdk#2]
Hi,

Just a few questions by curiosity:
- Are we supposed to use the JS SDK to access the user's data? Or is there something planned using only react-native-fbsdk?
- Are there some states provided to detect if someone is already logged in? Or some tricks to create those?

Thanks!

**Comment by cphackm** [comment]
You shouldn't need to use the JS SDK for anything.  If you look at the react-native-fbsdkcore package, there's support for graph requests -- which you can use to request user data, among other things -- and access tokens.  The getCurrentAccessToken method in FBSDKAccessToken can be used to determine if the user is logged in by checking if an access token was returned.  Example:
``` js
var FBSDKCore = require('react-native-fbsdkcore');
var {
  FBSDKAccessToken,
} = FBSDKCore;

...

FBSDKAccessToken.getCurrentAccessToken((token) => {
  if (token) {
    // A non-null token indicates that the user is currently logged in.
  }
});

...
```

**Comment by tnguyen42** [comment]
Ok thanks!
I assumed it was in the login library ^^
