### ISSUE TITLE
(iOS) rnpm doesn't install all libraries and configure the right header search paths

### ISSUE THREAD

**Issue by freemanon** [facebook/react-native-fbsdk#200]
rnpm only added `RCTFBSDKCore.xcodeproject` but not `RCTFBSDKLogin.xcodeproject` and `RCTFBSDKShare.xcodeproject`

I also had to add `$(SRCROOT)/../../../react-native/React` (recursive) as a Header Search Path in both projects.

**Comment by dzhuowen** [comment]
The sdk starts supporting rnpm from 0.2.0. The further explanation is that rnpm doesn't support multiple native projects, so we merge the individual RCTFBSDK[Core, Login, Share].xcodeproj into a single RCTFBSDK.xcodeproj in 0.2.0. Check out [issue 119](https://github.com/facebook/react-native-fbsdk/issues/119) for details.
