### ISSUE TITLE
(Android) Build Error after RNPM

### ISSUE THREAD

**Issue by rammuk** [facebook/react-native-fbsdk#201]
Hi 

After doing the rnpm install react-native-fbsdk i am getting an error in android studio 

Project with path ':react-native-fbsdk' could not be found in project ':app'.

Failing on build.gradle 

dependencies {
    compile project(':react-native-fbsdk')
   ...
}

Any suggestions?

Thanks

**Comment by dzhuowen** [comment]
Did you run 'rnpm install react-native-fbsdk' at the root directory of the react-native project?
If the command runs successfully, 
in `setting.gradle`
```java
'include ':react-native-fbsdk'
project(':react-native-fbsdk').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fbsdk/android')`
```
in `app/build.gradle`
```java
dependencies {
    compile project(':react-native-fbsdk')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
}
```

**Comment by rammuk** [comment]
@dzhuowen Thanks i did the rnpm but it didnt add the line :
project(':react-native-fbsdk').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-fbsdk/android')`

I added that and its working now
