### ISSUE TITLE
[iOS] Bolts is not a dylib

### ISSUE THREAD

**Issue by crysfel** [facebook/react-native-fbsdk#203]
Hi Guys, I've installed this package successfully, it works perfect on development, on the simulator and on my real devise.

However, when I try to create the archive to submit my app the Apple Store I'm getting the following error.

```
ld: warning: Auto-Linking supplied '/Users/Crysfel/Documents/FacebookSDK/Bolts.framework/Bolts', framework linker option at /Users/Crysfel/Documents/FacebookSDK/Bolts.framework/Bolts is not a dylib
clang: error: unable to execute command: Segmentation fault: 11
clang: error: linker command failed due to signal (use -v to see invocation)
```

This error is only happening when I try to archive my project, it works perfect on my devise. Here are my configurations

![Frameworks](https://s3.amazonaws.com/quizzpot/images/260-Screen_Shot_2016-05-30_at_12.56.44_PM.png?2016)

![Frameworks](https://s3.amazonaws.com/quizzpot/images/261-Screen_Shot_2016-05-30_at_12.57.07_PM.png?2016)

![Paths](https://s3.amazonaws.com/quizzpot/images/262-Screen_Shot_2016-05-30_at_12.57.48_PM.png?1464627555)

Am i missing any other configuration? Any help would be appreciate.

**Comment by crysfel** [comment]
I've included the Bolts framework into the project and now I'm not getting the warning anymore, only the errors:

```
clang: error: unable to execute command: Segmentation fault: 11
clang: error: linker command failed due to signal (use -v to see invocation)
```

**Comment by dzhuowen** [comment]
Can you try archiving with Xcode 7.3? The iOS SDK is built with Xcode 7.3 and archiving could fail with setting `bitcode enabled` if you're not using Xcode 7.3+.

Feel free to comment/re-open the issue if this doesn't work.
