### ISSUE TITLE
Feature request -  FBAudienceNetwork

### ISSUE THREAD

**Issue by philipheinser** [facebook/react-native-fbsdk#204]
Are there any plans to include the FBAudienceNetwork. We would love to show Native Ads in our react native app. Or are there any guides how to accomplish this with the current sdks?

**Comment by dzhuowen** [comment]
Thanks for the feedback! We don't have plan for that yet. But you refer to this [iOS PR](https://github.com/facebook/react-native-fbsdk/pull/27/)  to port the native modules into react-native:
https://facebook.github.io/react-native/docs/native-modules-ios.html#content
https://facebook.github.io/react-native/docs/native-modules-android.html#content
