### ISSUE TITLE
rnpm fails to link Android project with Case-sensitive Journaled HFS+ File System

### ISSUE THREAD

**Issue by syaau** [facebook/react-native-fbsdk#205]
Since the project uses a non-standard name for the android folder with a capital 'A', rnpm doesn't link the Android project in OSX with Case-sensitive Journaled HFS+ File System.

**Comment by dzhuowen** [comment]
In this case you can manually set up the Android project.
In settings.gradle, include the sdk subproject and specify the subproject path.
```java
include ':react-native-fbsdk'
project(':react-native-fbsdk').projectDir = new File(settingsDir, '../node_modules/react-native-fbsdk/Android')
```
In app/build.gradle,  add sdk to dependencies.
```java
//...
dependencies {
    //...
    compile project(":react-native-fbsdk")
}
```
Then you can follow the readme to finish the setup.

I'm closing the issue here. Please file the issue to [rnpm](https://github.com/rnpm/rnpm).

**Comment by syaau** [comment]
I was first planning to file the issue to rnpm, then I realized that react-native init had somewhat standardized the use of 'android' and 'ios' folder names (all small). 

I am pretty much sure this problem will be faced by lot of linux users. It would be a lot of time wasted for a lot of developers.

Also, the manual setup is needed for iOS as well. The rnpm doesn't link the iOS project either. 
In XCode, right click **Libraries**, click **Add Files to [Your Project]**.  Add the file  **node_modules/react-native-fbsdk/iOS/RCTFBSDK.xcodeproj**.

In the **Project Navigator**, select your project, select **Build Phases** in your build target. Expand **Link Binary with Libraries**. Click the plus button and add **libRCTFBSDK.a** under Workspace.

**Comment by maikokuppe** [comment]
Thanks @dzhuowen, it works now.

In case somebody gets this error on Ubuntu 14.04
```
* What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':react-native-fbsdk'.
   > failed to find Build Tools revision 23.0.2
```
take a look at [this post](http://stackoverflow.com/a/33157378/5328224) from stackoverflow. Installing `Build Tools revision 23.0.2` via the android tools GUI didn't work for me.

**Comment by MayeuldP** [comment]
@maikokuppe Hey it helped me : 

> take a look at this post from stackoverflow. Installing Build Tools revision 23.0.2

 but now I have another error : `error cannot find symbol : new FBSDKPackages(mCallbackManager) `.

However, I added in my project <br>`include ':react-native-fbsdk'
project(':react-native-fbsdk').projectDir = new File(settingsDir, '../node_modules/react-native-fbsdk/Android')` and 
`    compile project(":react-native-fbsdk")`, and of course rnpm link as @dzhuowen said ... But still have the error :/

**Comment by syaau** [comment]
@MayeuldP looks like you have a typo, its FBSDKPackage without 's'.

**Comment by MayeuldP** [comment]
@syaau Oup's no it's a mistake, my bad ! This is the copy-paste packages function that I have.... : 
```@Override
   protected List<ReactPackage> getPackages() {
        mCallbackManager = new CallbackManager.Factory().create();
        ReactPackage packages[] = new ReactPackage[]{
            new MainReactPackage(),
            new VectorIconsPackage(),
            new RNSharePackage(),
            new FacebookLoginPackage(),
            new RNGoogleSigninPackage(this),
            new FBSDKPackage(mCallbackManager)
         };
       return Arrays.<ReactPackage>asList(packages);
    }```

**Comment by MayeuldP** [comment]
Ok `Build Successfull` . I think I have trouble with rnpm...  I haven't this import `import com.facebook.reactnative.androidsdk.FBSDKPackage;
` in my project. Now, it seems working.

**Comment by maikokuppe** [comment]
@MayeuldP: try `android/gradlew --stop && react-native run-android`. Rerun `npm start` afterwards.

Maybe there is something old in the cache or on the device or in the packager or whatever.

**Comment by MayeuldP** [comment]
@maikokuppe I tried.. But doesn't work, but really wtf ! I deleted all the files which concerned react-native-fbsdk in gradle, manifest, MainActivity.java, but my app still crashing... Is there any way to find where and why my app crash ? 
I just get this : 
```
Starting the app on ......
Starting : Intent { cmp=com.movieproject/.MainActivity }
```
and crash... The output is not very clear... :/

**Comment by maikokuppe** [comment]
@MayeuldP Sorry, I don't know anything about Java or native Android developing. Can't help you with that.

**Comment by MayeuldP** [comment]
@maikokuppe I did some changements, and now I have this error when I build the project, 
`Unexpected top-level exception ....multiple dex files define....C:\ProgrammFiles\java\jdk1.7.0_79\bin\java.exe` did you already had this error ?

**Comment by maikokuppe** [comment]
@MayeuldP Nope, never seen that. Also I'm using Ubuntu, so there might be some differences.

**Comment by MayeuldP** [comment]
@maikokuppe Ok, I did some changement, and doesn't have this error anymore ! thank's anyway for your help.

**Comment by JatinKinra** [comment]
@MayeuldP I am facing the same issue. Followed all the steps. Solved the issue of build version 23.0.1.Build Successfull.
But, app crashes on launnch.
Can u tell me what changes you made ?

**Comment by MayeuldP** [comment]
Try `cd android/ && ./gradlew clean` and restart build... If it doesn't work, I really don't know...

**Comment by JatinKinra** [comment]
@MayeuldP , Still the same issue man.
debug.apk is running fine. But, release.apk is crashing
Any idea about that ?

**Comment by MayeuldP** [comment]
@JatinKinra You cannot generate the realease.apk ? Or yes you can, and when you launch it, it crashes ? Because me, I didn't generate a realease.apk... :/  Are you sure that you correctly followed all the steps for generate a signed apk ?

**Comment by JatinKinra** [comment]
@MayeuldP I am able to generate the signed apk, but it crashes. Now, the case is worse, debug apk is also crashing after running the above mentioned command i.e. gradlew clean.
This has become a mess now. There is no way to find why app is crashing.

**Comment by JatinKinra** [comment]
Hi
I debugged the app step by step. This is what I got-
Before adding the fbsdk manually(rnpm is unable to do it), app runs fine.
But, once I include fbsdk in build.gradle and seetings.gradle, App crashes.
Can anyone tell what is the issue here ?

**Comment by dzhuowen** [comment]
@syaau, we'll fix the directory name in the next release. Feel free to submit a pull request if you would like to.
