### ISSUE TITLE
fbsdk didnot installed on my project

### ISSUE THREAD

**Issue by susylPearl** [facebook/react-native-fbsdk#207]
i have done all of method mentioned, fbsdk also get installed through command prompt on specific project path but in project node module folder react-native-fbsdk is not shown and in package.json also there is no fbsdk. what i have done wrong please suggest me.

**Comment by susylPearl** [comment]
all thing have set up correctly and facebook login button also displayed but it doesnot work when i press it. what had happened?

**Comment by dzhuowen** [comment]
Hi @susylPearl , can you provide more detail on this, e.g error log in Xode/Android Studio, JS debug log, Manifest file, etc?

**Comment by susylPearl** [comment]
Facebook login button doesnot  do any task. when i clicked it nothing happens, after certain time when i again clicked it , application get crashed. i have provided permission as public_profile and email.

**Comment by crysfel** [comment]
@susylPearl have you included correctly the configurations on `info.plist` file and included the `FBSDKCoreKit` module on `AppDelegate.m`?

**Comment by susylPearl** [comment]
No i am implementing it in android not ios.

**Comment by dzhuowen** [comment]
Hi @susylPearl, did you finish the `Using Login or Share` part in https://developers.facebook.com/docs/android/getting-started?
You need to add the FacebookActivity to the Manifest.xml before you can use the login button.

**Comment by susylPearl** [comment]
yes i have configured as same like mentioned by facebook for react-native. since i am implementing this feature in react-native. All the things get success , facebook login button also appears in my application but when i clicked in login button nothing gets happened. Why does my facebook login button doesnot perform any click events? i have done all described here: https://developers.facebook.com/docs/react-native/getting-started-android/

**Comment by dzhuowen** [comment]
@susylPearl Can you try running the HelloFacebook Sample app https://github.com/facebook/react-native-fbsdk/tree/master/Sample and see if that works for you? If so, please refer to that, otherwise, feel free to upload your project (with only the LoginButton implementation) to a github repo so I can help with the debugging.

**Comment by susylPearl** [comment]
Ok

**Comment by ajnudnyy** [comment]
I got this error when I launched this project, I was wandering which reasons could be caused 
this issue?

>  FBSDKCoreKit/FBSDKCoreKit.h file not found

**Comment by ajnudnyy** [comment]
I got this error when I launched this project, I was wandering which reasons could be caused 
this issue?

FBSDKCoreKit/FBSDKCoreKit.h file not found
<img width="1030" alt="2016-06-09 9 22 25 pm" src="https://cloud.githubusercontent.com/assets/18208441/15954451/d104eee8-2f09-11e6-98fd-d3de0a28a406.png">

**Comment by ajnudnyy** [comment]
Where could I get the file which is called FBDKCoreKit.h?

**Comment by gopidon** [comment]
@susylPearl Ensure u added the following element directly under <application> like below

<application
      android:name="com.gst.MyApplication"
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme">
      <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
      <activity
        android:name="com.gst.MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    </application>

**Comment by cmmartin** [comment]
@ajnudnyy See this question...
http://stackoverflow.com/questions/12849209/how-to-make-xcode-find-file-facebooksdk-h

Also, make sure your path to the Facebook SDK is in Target > Build Settings > Framework Search Paths
