### ISSUE TITLE
"An unknown error has occurred" when trying to get paging.next url

### ISSUE THREAD

**Issue by mnjongerius** [facebook/react-native-fbsdk#208]
I run the following request:
```
var url = "/me/events?access_token=<token>&limit=25&after=<hash>";
var infoRequest = new GraphRequest(
  url,
  null,
  function(error: ?Object, result: ?Object) {
    //do things here
  }
);
new GraphRequestManager().addRequest(infoRequest).start();
```

This results in an error with the message "An unknown error has occurred". 

I've checked the token, it's a correct accessToken.

Also, the information about both the `<token>` and the `<hash>` both come directly the `paging.next` from a request to url `'/me/event'`. If I open the url in my browser, it works.

What am I doing wrong?

**Comment by dzhuowen** [comment]
Please reference to [issue 105](https://github.com/facebook/react-native-fbsdk/issues/105) for creating Graph Request. Beside you can use the [Graph API resolver]( https://developers.facebook.com/tools/explorer/) to check the result. 
Feel free to comment/re-open if you have any problems.
