### ISSUE TITLE
fbgraphrequest.addToConnection got 3 arguments expected 2

### ISSUE THREAD

**Issue by gannetson** [facebook/react-native-fbsdk#209]
I get an error while doing a GraphRequest on android in 0.2.1
Seems like the batchId in https://github.com/facebook/react-native-fbsdk/commit/83b702a385e638b212f1951d746be33aef92155b#diff-0dc8501a02eaed78e476e52dd1d5f049 is causing problems

**Comment by dzhuowen** [comment]
Hi @gannetson 
Can you try updating the sdk project in your app to the master?  Looks to me that the js file got updated but the android project didn't.

**Comment by dzhuowen** [comment]
Closing b/c of inactivity
