### ISSUE TITLE
Can't Archive App - "RCTBridgeModule.h' not found

### ISSUE THREAD

**Issue by MossP** [facebook/react-native-fbsdk#21]
Hi, firstly thank you for these libraries. They are a great help :) .

Sorry to flag issues but I have installed them and got them all running fine. But for some reason, when I try to archive my app for testflight I get an error

Line 19 of RCTFBSDKShareDialog.h
```
Lexical or Preprocessor Issue
'RCTBridgeModule.h' file not found
```

Do you know what could be causing this?

version Info:
react-native v0.9
xcode v6.3.2
OSX 10.10.4

**Comment by MossP** [comment]
Sorry, I forgot to add, I have added the location of the FacebookSDK to my header search paths

**Comment by MossP** [comment]
Closing for now as I've seen a few things that I might have done wrong.

**Comment by MossP** [comment]
Re-opening it. I thought I'd got a few things wrong but They seem ok. Sorry.

**Comment by MossP** [comment]
I've tried this on a virgin project with only this component added yet it still fails to archive.. Any advice appreciated, thanks.

**Comment by yelled3** [comment]
continued from https://github.com/facebook/react-native-fbsdk/issues/17#issuecomment-138890320

I'm also getting the same issue
```
.../node_modules/react-native-fbsdkcore/iOS/RCTFBSDKGraphRequestManager.h:19:9: 'RCTBridgeModule.h' file not found
```

@philikon @cphackm 
this seems like an important issue...

**Comment by robteix** [comment]
This problem seems to only occur when compiling for Release. Even adding $(SRCROOT) recursively to the header search path doesn't help.

**Comment by MossP** [comment]
You're a god in disguise @robteix. Thanks for the heads up. I assumed it was something to do with what I was doing rather than an error in the repo itself.

Cheers! :)

@yelled3, the fix @robteix has supplied appears to work. I can archive now, at least.

**Comment by yelled3** [comment]
@mingflifb @philikon @cphackm
I see https://github.com/facebook/react-native-fbsdk/issues/30 was merged, but the release tag is still on `0.0.5`.
when's the next release & npm update?

**Comment by jrichardlai** [comment]
+1 I ran into this too

**Comment by ms88privat** [comment]
+1 please update the package

**Comment by Sherlock92** [comment]
+1 for package update

**Comment by mingflifb** [comment]
We just release 0.0.6.

**Comment by jrichardlai** [comment]
Thanks @mingflifb !

**Comment by yelled3** [comment]
@mingflifb thanks!
