### ISSUE TITLE
Gradle issues on Linux

### ISSUE THREAD

**Issue by rlancer** [facebook/react-native-fbsdk#213]
Running Ubuntu 16.04 LTS
Gradle 2.13
Node v6.2.1

Got everything working on my Mac, but when I take that project and run it on my Linux box I get:

>  \> Cannot evaluate module react-native-fbsdk : Configuration with name 'default' not found.

This also happens with the HelloFacebook sample.

**Comment by dzhuowen** [comment]
Could be related to this. https://github.com/facebook/react-native-fbsdk/issues/205

**Comment by rlancer** [comment]
Yes, that was it!
