### ISSUE TITLE
While using login button, how to customise the landing page after login?

### ISSUE THREAD

**Issue by sahilaug** [facebook/react-native-fbsdk#215]
I don't want the logout button. Instead want to show homepage for my app.

**Comment by Tehnix** [comment]
Your question is probably more suited for stackoverflow, but I'll try to give a brief example anyways.

In this example the login state is saved in my `redux` store, you could just save it in the component state if you wanted, and access it with `this.state.loginState`.

```javascript
class MainLayout extends Component {

  render() {
    const { store } = this.context
    let initialScreen
    if (this.props.loginState == "logged_in") {
      initialScreen = (
        <View>
          // ... Main view code
        </View>
      )
    } else {
      initialScreen = <FBLogin/>
    }
    return (
      <View}>
        {initialScreen}
      </View>
    )
  }
}
```

It will show either the FB login button or whatever you have as the alternative (e.g. your homepage).
