### ISSUE TITLE
Update Android sample for 0.2.x.

### ISSUE THREAD

**Issue by herby** [facebook/react-native-fbsdk#216]
I am puzzled with the "make your own `Application` subclass" thing in 0.2.x which moved initializing Fb SDK from RN onCreate to this new thing onCreate.

**Comment by mingflifb** [comment]
Can you be more specific? In this case, you'd create a class that extends the Application class in Android. The Application class also has a lifecycle (similar to Activity), but is only done once for the application rather than when Activities come in and out of view. There are a lot of searchable articles on how to create an Application class.

**Comment by herby** [comment]
Yes, it's exactly about this Application class thing.

Not a clue. Not developing Java. No other RN module needs such a thing, every other just needs some patches in MainActivity.java and config files.

So I would like to see a sample configured so that I see exactly what everything is needed to be there to have that Application class thing.

Ming Li wrote:
> Can you be more specific? In this case, you'd create a class that 
> extends the Application class in Android. The Application class also 
> has a lifecycle (similar to Activity), but is only done once for the 
> application rather than when Activities come in and out of view. There 
> are a lot of searchable articles on how to create an Application class.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/facebook/react-native-fbsdk/issues/216#issuecomment-225664583>, 
> or mute the thread 
> <https://github.com/notifications/unsubsc
ribe/AANjsVTL_gdUyLaEy92I-JQ9m45beK6wks5qLZ7vgaJpZM4I0l8R>.
>

**Comment by mingflifb** [comment]
See the sample app. There's a MyApplication.java class here:

https://github.com/facebook/react-native-fbsdk/tree/master/Sample/HelloFacebook/android/app/src/main/java/com/hellofacebook

and you also need to add it to your AndroidManifest.xml

https://github.com/facebook/react-native-fbsdk/blob/master/Sample/HelloFacebook/android/app/src/main/AndroidManifest.xml

specifically:

    <application
      android:name=".MyApplication"
      ...

**Comment by herby** [comment]
Thanks.
