### ISSUE TITLE
[0.2.1][iOS] Recursive framework search path may cause compile error

### ISSUE THREAD

**Issue by ultragtx** [facebook/react-native-fbsdk#217]
Commit https://github.com/facebook/react-native-fbsdk/commit/01f15be4dc35f74c6426b5cb9f40ec0da8a4d42b added a recursive framework search path `$(PROJECT_DIR)/../../../ios`. And in my case, this recursive search path leads to build error `Argument list too long: recursive header expansion failed at ...`

**Comment by dzhuowen** [comment]
Sorry for getting back late. Please modify the framework search path to `$(PROJECT_DIR)/../../../ios/Frameworks` and switch the entry to non-recursive for now.
