### ISSUE TITLE
Malformed access token

### ISSUE THREAD

**Issue by stephenweaver** [facebook/react-native-fbsdk#220]
I can't query any data other then the default /me. If I add any fields and the access token, i get this message?

"{FacebookServiceException: httpResponseCode: 400, facebookErrorCode: 190, facebookErrorType: OAuthException, message: Malformed access token [the token]}"

using the following code to create the request
      const infoRequest = new GraphRequest(
        '/me?fields=email&access_token=' + fb_access_token,
        null,
        callback,
      );

Is this something wrong with the package or my code? I seem to be following all the documentation.

**Comment by dzhuowen** [comment]
Please see #105
