### ISSUE TITLE
[0.2.2] Build Fails

### ISSUE THREAD

**Issue by pietropizzi** [facebook/react-native-fbsdk#225]
Error in `react-native-fbsdk/iOS/RCTFBSDK/core/RCTFBSDKGraphRequestManager.m:62:1`:

"ARC forbids synthesizing a property of an Objective-C object with unspecified ownership or storage attribute"

<img width="1438" alt="screen shot 2016-06-30 at 12 39 00" src="https://cloud.githubusercontent.com/assets/410305/16485542/abf6fec8-3ebf-11e6-9b93-457ebecedd21.png">

**Comment by dzhuowen** [comment]
Can you try clean (Product -> Clean) and rebuild? It looks suspicious b/c this error should point to a property definition.

**Comment by pietropizzi** [comment]
Thanks for the suggestion, but unfortunately still the same thing. I tried it with React Native 0.27.2 and 0.28.0.

**Comment by melvinxie** [comment]
Same error here. Using react native 0.28 and react-native-fbsdk 0.2.2.
react-native-fbsdk 0.2.1 also shows the same error.

**Comment by heyuan2816** [comment]
Similar issue for me. For the same package, my friend is XCode 7.3.1 and he built it successfully, while I am using Xcode Version 7.2.1 (7C1002) and seeing this similar ARC issue. Is that related?

**Comment by heyuan2816** [comment]
I disabled the Objective-C Automatic Reference Counting (ARC) at the build setting and it worked. Not sure if it will have other negative impact on the project though

**Comment by 6thfdwp** [comment]
Same as @heyuan2816,  I tried to upgrade to XCode 7.3.1 which supports latest iOS 9.3 SDK, and this issue is gone.

Hope this also works for you.

**Comment by frangeris** [comment]
Same issue here, `XCode Version 7.2 (7C68)`, @6thfdwp so the fix is update to ` XCode 7.3+`?

@dzhuowen What you think of this?
