### ISSUE TITLE
Migration to RN 0.29

### ISSUE THREAD

**Issue by avishayil** [facebook/react-native-fbsdk#226]
https://github.com/facebook/react-native/commit/49f20f41546e3ba8e7fe43c84c4c701684d0434d

**Comment by ericraio** [comment]
@avishayil looks like the main activity needs to be implemented into this package.

> Those packages need to be updated so that they don't need the activity to be passed in the constructor. The correct way is to extend ReactContextBaseJavaModule and use the getCurrentActivity() method.

**Comment by ericraio** [comment]
@dzhuowen  what do you think?

**Comment by dzhuowen** [comment]
Currently the sdk package is tied to the main activity so the workaround for RN0.29 would be passing  the activity into the package class and init the callback manager there. Haven't try it myself but will look into it.

**Comment by satya164** [comment]
Something like this might work - https://gist.github.com/satya164/bc9e6f16f2d86a622e82ea795cc8292b

**Comment by donedgardo** [comment]
Im sorry but how would we implement that gist? 
Sorry not a Java developer.

**Comment by satya164** [comment]
@donedgardo Modify your `MainActivity.java` and `MainApplication.java` according to the gist.

**Comment by brien-crean** [comment]
This is very unclear from an android new comers perspective. The howtwo docs need a serious update. I cannot integrate this SDK with 0.29 at present

**Comment by satya164** [comment]
@brien-crean Probably you didn't import the `FBSDKPackage`? Use Android SDK to edit Java files. It auto-imports packages.

**Comment by dzhuowen** [comment]
Readme updated with instruction for rn 0.29+ 
Feel free to comment if you see further issues.
