### ISSUE TITLE
size of access tokens?

### ISSUE THREAD

**Issue by wzup** [facebook/react-native-fbsdk#227]
What is access tokens size? Repair your broken link.

https://developers.facebook.com/docs/facebook-login/access-tokens/#sizes
From this page https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow?locale=en_US

**Comment by dzhuowen** [comment]
Check out [this answer](http://stackoverflow.com/questions/4408945/what-is-the-length-of-the-access-token-in-facebook-oauth2).
Thanks for pointing out the link. We'll fix it on dev site.
