### ISSUE TITLE
Getting error"The sdk has not being initialised,make sure to call FacebookSdk.sdkInitialize() first"

### ISSUE THREAD

**Issue by charlie-rc** [facebook/react-native-fbsdk#228]
Hello,

I have followed each and every instruction provided on https://github.com/facebook/react-native-fbsdk for integrating the facebook login, still getting error"The sdk has not being initialised,make sure to call FacebookSdk.sdkInitialize() first".
I am using react native 0.27.2

Please can anyone help?

**Comment by dzhuowen** [comment]
Please make sure you complete Step 6 in the [Getting Started Guide](https://developers.facebook.com/docs/android/getting-started#androidstudio) to call `FacebookSdk.sdkInitialize` in your **Application** class. Feel free to comment/reopen the issue.
