### ISSUE TITLE
RCTAlertManager.alertWithArgs must not be null

### ISSUE THREAD

**Issue by maxs15** [facebook/react-native-fbsdk#23]
Hi,

Having this error trying to use the login button on react native 0.10.
```[error][tid:main][RCTModuleMethod.m:59] Argument 1 (RCTResponseSenderBlock) of RCTAlertManager.alertWithArgs must not be null.```
Any idea how this could be fixed ?

Thanks for the help

**Comment by MossP** [comment]
I can't answer directly for you but it looks like someone else has come across a similar issue and found a solution: https://github.com/facebook/react-native-fbsdk/issues/20

**Comment by rodrigopivi** [comment]
Having the same issue, i had to overwrite the native implementation of start method:

```
var FBSDKCore = require('react-native-fbsdkcore');
var {
  FBSDKGraphRequest,
  FBSDKGraphRequestManager,
} = FBSDKCore;

FBSDKGraphRequest.prototype.start = function (timeout: ?number) {
  FBSDKGraphRequestManager.batchRequests([this], function () {}, timeout);
};

// and then use something like:
fetchMe.start(120000);
```

**Comment by dzhuowen** [comment]
This issue has been handled by #44
