### ISSUE TITLE
ShareDialog : share link - only the contentUrl is used

### ISSUE THREAD

**Issue by pavb74** [facebook/react-native-fbsdk#231]
Hi

I am trying to share a link using the sample provided in the documentation.
The attributes contentTitle and contentDescription are correctly used on the IOS simulator (IOS 9.3) to pre fill the message but not in a real device. On my device only contentUrl is used.
I am using the release 0.2.1 with the Facebook sdk 4.13.1 on IOS 9.3.2.

Thanks

Pierre-André

**Comment by omrihq** [comment]
+1

**Comment by dzhuowen** [comment]
Closing the issue b/c it's duplicate with #257
