### ISSUE TITLE
iOS: blank web view when calling LoginManager.logInWithReadPermissions

### ISSUE THREAD

**Issue by shahen94** [facebook/react-native-fbsdk#236]
When i'm clicking on my button, there is opening your WebView.
There i'm writing my credentials.
Then after clicking login button its opening a white page.
And nothing happening.

![screen shot 2016-07-13 at 8 26 08 pm](https://cloud.githubusercontent.com/assets/13334788/16811207/5163d3ae-4938-11e6-9200-42b7d4f32af7.png)

**Comment by dzhuowen** [comment]
See https://github.com/facebook/react-native-fbsdk/issues/72
Feel free to comment if this doesn't work.

**Comment by shahen94** [comment]
Thats it ! thank you so much

**Comment by mwmcgill** [comment]
@dzhuowen I have looked at issue #72, and have tried completing those steps. I have triple checked my AppDelegate.swift file to verify that I've typed everything in correctly (I have), but I am still running into the same issue. Any other suggestions?

**Comment by tnbao91** [comment]
This happened to me too. I tried #72 but it doesn't work

**Comment by gryffindors** [comment]
@tnbao91 Any luck?
