### ISSUE TITLE
Logging in with both read and publish permissions

### ISSUE THREAD

**Issue by sampurcell93** [facebook/react-native-fbsdk#239]
Hi, I noticed that in the login manager there are two types of login methods, and I need the permissions of both. Is there a way to combine them without the user having to go through the flow twice?

**Comment by mingflifb** [comment]
No, the separation of read and publish permissions is by design, and you should only ask for those permissions as you require them, rather than all up front. This should increase your conversion and also provide a better experience for people using your app.
