### ISSUE TITLE
Duplicate protocol, duplicate interface and redefinition errors

### ISSUE THREAD

**Issue by roberttod** [facebook/react-native-fbsdk#24]
I followed the installation setup using CocoaPods but I am getting duplicate protocol, duplicate interface and redefinition errors. Not sure if I have included something twice but I have tried to make sense of this with no luck.

<img width="376" alt="screen shot 2015-09-02 at 01 28 23" src="https://cloud.githubusercontent.com/assets/823104/9620439/fd2a5d54-5111-11e5-8768-1b49a680c4e1.png">

**Comment by dzhuowen** [comment]
fix README file in release0.0.6
