### ISSUE TITLE
[Android] Facebook activity seems to have a PUSH transition instead of being a modal

### ISSUE THREAD

**Issue by SudoPlz** [facebook/react-native-fbsdk#244]
Hi,

some users have noticed a weird behaviour of facebook login manager when they log in on their android devices using fbsdk.

In this video you can see the whole process: 
https://vid.me/SSw6

What the correct behaviour would be, is a MODAL activity should show instead of an activity push, because then we have this back and forth animation which does not look good.

The thing is, I get the expected behaviour in some devices, but in others I get this error, and I have no way of reproducing it.

This is the part of my manifest:
```java
        <provider android:authorities="com.facebook.app.FacebookContentProvider949301848442473"
            android:name="com.facebook.FacebookContentProvider"
            android:exported="true" />

        <activity android:name="com.facebook.FacebookActivity"
            android:configChanges="keyboard|keyboardHidden|screenLayout|screenSize|orientation"
            android:theme="@android:style/Theme.Translucent.NoTitleBar"
            android:label="@string/app_name">
        </activity>
```

Any ideas?

Thank you.

**Comment by dzhuowen** [comment]
The push transition is the expected behavior when the device has Facebook app installed. 
When the Facebook app is not installed, the login dialog is displayed in a webview, which is the modal.
