### ISSUE TITLE
Programatically logout

### ISSUE THREAD

**Issue by andfs** [facebook/react-native-fbsdk#245]
Hi guys,

How can I do a programatically logout? When I'm logged in, I don't have the LoginButton, so I want to logout by my self. How can I accomplish that?

**Comment by chrisp-fb** [comment]
Have you tried `LoginManager.logOut()`?

**Comment by andfs** [comment]
I was trying LoginManager.logout()

Thanks :D

**Comment by Quadriphobs1** [comment]
`LoginManager.logOut()` returns undefined is not a function

**Comment by Madhur2207** [comment]
Use this code on any component to log out - 
 <LoginButton
          onLoginFinished={
            () => console.log("log in.")
          }
          onLogoutFinished={() => console.log("logout.")}/>

**Comment by thecodecafe** [comment]
Calling LoginManager.logOut() does not work, both after and before facebook login.
