### ISSUE TITLE
Allow LoginButton localization

### ISSUE THREAD

**Issue by tioback** [facebook/react-native-fbsdk#248]
I'm trying to set a different language for LoginButton, however there doesn't seem to be a way.
It always displays: "Log in with Facebook".

**Comment by dzhuowen** [comment]
rnsdk is a wrapper around the native Facebook SDKs. You should change the localization in Facebook Android SDK and iOS SDK.  e.g http://stackoverflow.com/questions/22476820/ios-facebook-sdk-localization

**Comment by tioback** [comment]
@dzhuowen have you actually seen this work with React Native projects?
I've followed the instructions mentioned in your reference, but nothing happened.
