### ISSUE TITLE
How could you know the version of the Graph API used?

### ISSUE THREAD

**Issue by dejakob** [facebook/react-native-fbsdk#253]
Since Facebook is deprecating an older API soon, I want to check which version of the Graph API I am currently using. What is the best way to get that information?

Thanks in advance...

**Comment by mingflifb** [comment]
The default Graph API version is tied to the underlying Facebook SDK versions, and whenever we change the default version, we update our changelog.

For example, here's the SDK changelog for Android: https://developers.facebook.com/docs/android/change-log-4.x

As you can see, we updated to using Graph API v2.6 in the 4.11.0 release, and v2.7 in 4.14.0. You can similarly follow the chain back to previous releases.

**Comment by dejakob** [comment]
Ok, thank you :)
