### ISSUE TITLE
Raise compilation errors (version 0.2.2) 

### ISSUE THREAD

**Issue by xareelee** [facebook/react-native-fbsdk#254]
I try to build the [f8 app](https://github.com/fbsamples/f8app) which uses **react-native-fbsdk 0.2.2**.

It raises compilation errors:

```
 Property 'hashtag' not found on object of type '__strong RCTFBSDKSharingContent' (aka '__strong id<FBSDKSharingContent>')
```

```
 Use of undeclared identifier 'FBSDKHashtag'
```

```
 Property 'quote' not found on object of type 'FBSDKShareLinkContent *'
```

The `Podfile.lock` shows:

```
...
  - FBSDKCoreKit (4.10.1):
    - Bolts (~> 1.5)
  - FBSDKLoginKit (4.10.1):
    - FBSDKCoreKit
  - FBSDKShareKit (4.10.1):
    - FBSDKCoreKit
  - React (0.28.0):
    - React/Core (= 0.28.0)
  - react-native-fbsdk/Core (0.2.2):
    - FBSDKCoreKit
    - React
  - react-native-fbsdk/Login (0.2.2):
    - FBSDKLoginKit
    - React
  - react-native-fbsdk/Share (0.2.2):
    - FBSDKShareKit
    - React
...
```

I find the related code is missing in `FBSDKShareKit 4.10.1`.

**Comment by xareelee** [comment]
OK, I found the source repos of `cocoapods` was out-of-date. As of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

After running `pod repo update` and `pod install` again, the `FBSDKShareKit` is upgraded to the latest version, `4.14`.

Problem solved.

BTW, maybe adding the version dependencies to the `.podspec` is a good idea.

**Comment by dzhuowen** [comment]
We no long officially support cocoapods. But feel free to submit a PR for this.
