### ISSUE TITLE
Was description and image removed and how to use setmode? 

### ISSUE THREAD

**Issue by omrihq** [facebook/react-native-fbsdk#257]
When adding contentDescription, imageURL, or contentTitle, I'm only getting the scraped ones from the URL, and not the ones that I added, even when following the exact example on the README. Was this functionality taken away?

Also: Is there documentation for the RN setmode? Can't find it anywhere and I'm not sure what to infer from the Objective-C SDK documentation.

EDIT: Narrowed it down to content populates when the Facebook app isn't downloaded on the phone. Any way to do it when the facebook app is on the phone?

**Comment by vassix** [comment]
Same problem here, i have it only on ios9, android and ios8 works perfectly.
@omrihq for the setMode you can look at the react-native-fbsdk js source, for example, the ShareDialog uses the setMode(ShareDialogMode), you can view all the modes and more on the react-native-fbsdk/js/FBShareDialog.js file.

**Comment by omrihq** [comment]
Thanks, I figured it out eventually. However, even in a forced browser mode it strips all the content when the Facebook app is installed on my phone. When the app isn't installed all the content is there. I'm forced to use https://github.com/doefler/react-native-social-share until this problem is fixed. It's very limited but it at least allows pictures.

**Comment by dzhuowen** [comment]
Hi @omrihq , we're looking into this and you can file a bug on https://developers.facebook.com/bugs/ for better tracking.

**Comment by apurv** [comment]
Any updates on this? I've tried `ShareDialog.setMode('browser')` with no luck. In addition, I've tried using the ShareApi and although I'm able to post an image to Facebook via iOS simulator / Android device, I'm having no luck posting with an actual iOS device.

Here's the code using ShareApi method:

```
const sharePhoto = {
    imageUrl: this.state.imageUrl, // local file URI
    userGenerated: false,
    caption: 'test caption'
}

const sharePhotoContent = {
    contentType: 'photo',
    photos: [ sharePhoto ]
}

ShareApi.share(sharePhotoContent, '/me', 'Hello').then(result => {
    console.log(result)
}).catch(error => {
    console.error(error)
})
```
Getting the stacktrace when I use ShareApi method on iOS device:
```
Error: ShareAPI encounters error(…)
reactConsoleError @ ExceptionsManager.js:76
console.error @ YellowBox.js:59
(anonymous function) @ index.js:155
tryCallOne @ core.js:37
(anonymous function) @ core.js:123
JSTimersExecution.callbacks.(anonymous function) @ JSTimers.js:79
callTimer @ JSTimersExecution.js:69
callImmediatesPass @ JSTimersExecution.js:127
callImmediates @ JSTimersExecution.js:142
(anonymous function) @ MessageQueue.js:137
guard @ MessageQueue.js:41
__callImmediates @ MessageQueue.js:137
(anonymous function) @ MessageQueue.js:104
guard @ MessageQueue.js:41
invokeCallbackAndReturnFlushedQueue @ MessageQueue.js:102
onmessage @ debuggerWorker.js:39
```

**Comment by dzhuowen** [comment]
The supporting parameters varies in share dialog of different modes. This is the expected behavior for now.
@apurv Please file a bug at https://developers.facebook.com/bugs if you still see error in the Share API.
