### ISSUE TITLE
ShareDialog doesn't work with SharePhotoObject type

### ISSUE THREAD

**Issue by rosiakr** [facebook/react-native-fbsdk#258]
I'm on RN v0.30
I have this in my code:

    const sharePhotoContent = {
      contentType: 'photo',
      photos: [{imageUrl: '<some_url_to_image>'}]
    };

and then in onSharePhotoClicked function I have:

    ShareDialog.canShow(sharePhotoContent).then(
      function(canShow) {
        if (canShow) {
          return ShareDialog.show(sharePhotoContent);
        }
        else {
          alert('Cannot show dialog for photo share');
        }
      }
    );

but `canShow` evaluates to false and the share dialog doesn't show.

**Comment by dzhuowen** [comment]
See https://github.com/facebook/react-native-fbsdk/issues/154
Feel free to comment/reopen the issue.

**Comment by rosiakr** [comment]
@dzhuowen Thank you for replying. I tried the solution that @agenthunt provided in #154 and it's working, but it's not for ShareDialog. Am I to assume that it can't be done?
So far the only dialog scenario that works (for me) is to use ShareLinkContent, but the photo's url has to be of a photo on the web, not on the device.

**Comment by mingflifb** [comment]
Are you testing in the simulator? If you don't have the Facebook app installed, you can't share photos because the web based share dialog doesn't support sharing photos from the gallery.

**Comment by rosiakr** [comment]
@mingflifb I am testing on Android device connected to laptop via USB.
Just to confirm - are you saying that if I install FB app on my device then I will be able to use ShareDialog with SharePhotoContent object? Can you clarify? thank you

**Comment by mingflifb** [comment]
Yes, that's correct. This is why we have the canShow methods because some dialogs (the web dialog) don't support native images, but if you have the FB app installed, then we hand over sharing to the app, which will have access to images.

**Comment by rosiakr** [comment]
@mingflifb Thank you. Yes, I think it's bypassing the problem I've previously observed after I installed FB app on my Android, but I notice these new issues:

1. Login takes like 2 minutes. Also - now it doesn't show the login screen anymore, even after I logged out of the FB app. How does it remember the username/password? BTW - my login screen is set up the same was as in the README of this repo + I'm getting user's AccessToken in the process
2. For photo sharing - after my code executes `return ShareDialog.show(sharePhotoContent);` an error pops up on screen that says: "A ContentProvider for this app was not set up in the AndroidManifest.xml, please add `com.facebook.app.FacebookContentProvider{APP_ID}`."
But the thing is - I already have it set up. Here is my AndroidManifest.xml:
    
    
        <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.{appName}">

            <uses-permission android:name="android.permission.INTERNET" />
            
            <application
                android:name=".MainApplication"
                android:allowBackup="true"
                android:label="@string/app_name"
                android:icon="@mipmap/ic_launcher"
                android:theme="@style/AppTheme">
                <activity
                    android:name=".MainActivity"
                    android:label="@string/app_name"
                    android:configChanges="keyboard|keyboardHidden|orientation|screenSize">
                    <intent-filter>
                        <action android:name="android.intent.action.MAIN" />
                        <category android:name="android.intent.category.LAUNCHER" />
                    </intent-filter>
                </activity>
                <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
                <meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
            </application>
            <activity android:name="com.facebook.FacebookActivity"
                android:configChanges=
                    "keyboard|keyboardHidden|screenLayout|screenSize|orientation"
                android:theme="@android:style/Theme.Translucent.NoTitleBar"
                android:label="@string/app_name" />
            <provider android:authorities="com.facebook.app.FacebookContentProvider{myAppID}"
                android:name="com.facebook.FacebookContentProvider"
                android:exported="true" />
        </manifest>

What am I missing?

**Comment by mingflifb** [comment]
It's very difficult to debug these where we don't have a sample of your app. I'm going to point you to developers.facebook.com/bugs where you can file a bug and upload a sample app if something isn't working for you.
