### ISSUE TITLE
contentDescription doesn't work when Facebook App installed

### ISSUE THREAD

**Issue by omrihq** [facebook/react-native-fbsdk#259]
I'm running the sample app with the sharing modal opening, but all I see is the Facebook link with the following shareLinkContent:

```
const shareLinkContent = {
  contentType: 'link',
  contentUrl: "https://facebook.com",
  contentDescription: 'Wow, check out this great site!',
};
```
I've tried other sites with the same issue. When I delete the Facebook app on my phone the contentDescription, and any images suddenly work. 

It also doesn't work when I do `Sharedialog.setmode("browser");`

**Comment by dzhuowen** [comment]
See https://github.com/facebook/react-native-fbsdk/issues/257#issuecomment-238676170

**Comment by dzhuowen** [comment]
Closing the issue b/c it's duplicate with #257
