### ISSUE TITLE
Android:  duplicate entry: com/facebook/csslayout/CachedCSSLayout.class

### ISSUE THREAD

**Issue by marcejohnson** [facebook/react-native-fbsdk#264]
Everything builds and runs fine for IOS.
But for Android at the end of compilation (during aapt / packaging) it fails with:

```
:app:transformClassesWithJarMergingForDebug FAILED

FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/facebook/csslayout/CachedCSSLayout.class
```

In app/build.gradle I have already added ```multiDexEnabled true``` but does not help.

Spent hours investigating but getting nowhere.
Any ideas on this?
Thanks!

**Comment by dzhuowen** [comment]
You shouldn't need to enable multiDexed. 
Check out this http://stackoverflow.com/questions/33209631/errorexecution-failed-for-task-apptransformclasseswithjarmergingfordebug
