### ISSUE TITLE
Unable to check login status. 

### ISSUE THREAD

**Issue by berkayk** [facebook/react-native-fbsdk#265]
Hi,

I want to detect a user's login status before touching the login button. How can I detect whether a user is logged in from the app or not? 

If I use LoginButton, it changes it's label to Log Out but I do not want to display that button if user is logged in.

LoginManager doesn't have a method to check login status either. When using LoginManager, it shows "You are already authorized", which is the expected behavior. 

Thanks.

**Comment by chrisp-fb** [comment]
You can check `AccessToken.getCurrentAccessToken()`.
