### ISSUE TITLE
loginBehaviorAndroid and loginBehaviorIOS doesn't effect?

### ISSUE THREAD

**Issue by zslucky** [facebook/react-native-fbsdk#268]
Seems there are no doc to introduce the properties for LoginButton, I did a quick look in code, looks like loginBehaviorAndroid and loginBehaviorIOS are valid properties, but when I tried to set
```javascript
loginBehaviorAndroid="native_with_fallback" // in android component
loginBehaviorIOS="native" // in ios component
```
It still use the web to start login flow not the native client. do I miss anything important?

**Comment by dzhuowen** [comment]
Do you have facebook installed?

**Comment by zslucky** [comment]
@dzhuowen 
yes installed, I found an article said due to IOS 9.0+ switch app to login will get a bad user experience, so disabled?  I'm not sure is it solved now?

**Comment by dzhuowen** [comment]
The underlying Facebook SDK for iOS chooses the best login method available. By specifying login behavior native you are simply telling the sdk that it can login through the native app.
https://github.com/facebook/facebook-ios-sdk/blob/master/FBSDKLoginKit/FBSDKLoginKit/FBSDKLoginManager.h#L78

for more details on why this the behavior 
http://stackoverflow.com/questions/32375916/safari-web-view-opening-when-logging-to-fb-through-ios-9
