### ISSUE TITLE
Failure to finish logging in

### ISSUE THREAD

**Issue by bshlgrs** [facebook/react-native-fbsdk#270]
I've just started a new React Native project and tried to use this library. My project is [here](https://github.com/bshlgrs/map-advisor-react-native). The only changes I've made since I ran `react-native create-project` are the ones proposed in the README of this repo--installing this module and installing the Facebook SDK and so on.

So I start my app up and it looks like this:

![image](https://cloud.githubusercontent.com/assets/2689010/18037925/a05adc4e-6d43-11e6-8ad2-02c15bb32c0b.png)

Then I click "Log in with Facebook" and it shows me this:

![image](https://cloud.githubusercontent.com/assets/2689010/18037928/b075acd0-6d43-11e6-833e-a50517107514.png)

Alright, that makes sense, I guess I have already authorized my app. So I click "OK" and then it takes me to the next screen:

![image](https://cloud.githubusercontent.com/assets/2689010/18037935/d000a8fc-6d43-11e6-8214-511623ab1d74.png)

which is Safari trying to open `https://m.facebook.com/v2.7/dialog/oauth/confirm`.

And then nothing happens. If I click "Done", I get the alert saying "Login was cancelled."

-----

I have a few questions:

- Is there a way to set it up so that the login request ends successfully?
- How do I get the SDK to tell me the authentication details of the currently logged in user?

**Comment by dzhuowen** [comment]
See #72
Feel free to comment if this doesn't work.
For auth info, you can take a look at https://github.com/facebook/react-native-fbsdk/blob/master/js/FBAccessToken.js
