### ISSUE TITLE
rnpm deprecated ?

### ISSUE THREAD

**Issue by Fandekasp** [facebook/react-native-fbsdk#271]
It looks like rnpm was merged into react-native ([reference](https://github.com/rnpm/rnpm/commit/1db2a06850f8f727b5c68ab0f3450f140c24ac91)), but the react-native-fbsdk installation procedure still asks to install this package. Is that really needed? Can you maybe update the documentation?

Thank you

**Comment by Fandekasp** [comment]
Finally figured out that `react-native link` is the new way to go

**Comment by dzhuowen** [comment]
Thanks for the heads up! Readme is updated.
