### ISSUE TITLE
Use of non-public APIs Issue

### ISSUE THREAD

**Issue by toddmetheny** [facebook/react-native-fbsdk#273]
This may be something on my end...maybe I need to install something different. But after using this library without issue for a few months, I recently got a rejection from Apple for using a non-public API. 

<img width="729" alt="screen shot 2016-09-04 at 12 29 17 pm" src="https://cloud.githubusercontent.com/assets/1427752/18232355/246a6a4c-729c-11e6-8a11-dd249e2e4219.png">

When I attempt to look to see where ```setResult``` is being used, I get this: 

<img width="460" alt="screen shot 2016-09-04 at 12 31 33 pm" src="https://cloud.githubusercontent.com/assets/1427752/18232363/388e65a0-729c-11e6-9602-3a5328f7e64e.png">

Any thoughts? Is this an issue of something that hasn't been properly updated on behalf of this library or is it something that I'm doing wrong? Thanks in advance.

**Comment by nakaruna** [comment]
Related with this issue: https://github.com/magus/react-native-facebook-login/issues/155

Stupid solution: appealing to apple
Smart solution: change namespace (http://stackoverflow.com/questions/33775536/ios-app-non-public-api-usage-app-references-non-public-selectors-cancelbutto)
