### ISSUE TITLE
Application crash when clicking on Facebook button

### ISSUE THREAD

**Issue by Fandekasp** [facebook/react-native-fbsdk#274]
After following the installation steps from the documentation, I'm now able to see the facebook button in my application.
But when clicking on it, the app crashes. Looking at the logs from android studio, I found the following error
```
09-05 11:29:47.930 3442-3844/com.myApp A/chromium: [FATAL:gl_surface_android.cc(58)] Check failed: kGLImplementationNone != GetGLImplementation() (0 vs. 0)
09-05 11:29:47.930 3442-3844/com.myApp A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 3844 (GpuThread)
```

Any idea how to debug and fix this issue? Thank you for your support

React native v0.32.0
Gradle 2.14.1
Android 6.0
react-native-fbsdk 0.3.0

**Comment by dzhuowen** [comment]
The error log you provide isn't helpful.
Can you find the error log from Activity Monitor and pasted it here?
Besides please make sure you're using latest Facebook-Android-SDK.

**Comment by Fandekasp** [comment]
I finally realized that the root of the problem wasn't related to react native or the fbsdk plugin, but to the simulator. The android 6 simulator was running the Browser application instead of Chrome, and it was crashing when trying to open it. the fb button was just simply trying to open the Browser, which caused the error.
Moving to android 7 simulator and the Chrome browser solved the issue.

**Comment by rajatgupta1993** [comment]
Hi , I am trying to integrate Fb SDK , and i tried implementing Fb login Button , it is visible on my page but when I click on it, I am getting this error :  

![screen shot 2016-09-17 at 9 04 22 pm](https://cloud.githubusercontent.com/assets/20831611/18609360/f77bb9be-7d1d-11e6-9fa7-2cb9dc0e2398.png)



My log


`    2016-09-17 21:32:00.408 DobbleApp[2169:157396] *** Terminating app due to uncaught exception 'InvalidOperationException', reason: 'App ID not found. Add a string value with your app ID for the key FacebookAppID to the Info.plist or call [FBSDKSettings setAppID:].'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010ae14d85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000109f3bdeb objc_exception_throw + 48
	2   DobbleApp                           0x00000001096a4d25 +[FBSDKInternalUtility validateURLSchemes] + 0
	3   DobbleApp                           0x00000001096a4d48 +[FBSDKInternalUtility validateURLSchemes] + 35
	4   DobbleApp                           0x000000010966a840 -[FBSDKLoginManager logInParametersWithPermissions:] + 82
	5   DobbleApp                           0x000000010966ad2d -[FBSDKLoginManager logInWithBehavior:] + 50
	6   DobbleApp                           0x000000010966ace5 -[FBSDKLoginManager logInWithPermissions:handler:] + 238
	7   DobbleApp                           0x0000000109669a03 -[FBSDKLoginManager logInWithReadPermissions:fromViewController:handler:] + 257
	8   DobbleApp                           0x00000001096664d2 -[FBSDKLoginButton _buttonPressed:] + 1082
	9   UIKit                               0x000000010cd4da8d -[UIApplication sendAction:to:from:forEvent:] + 92
	10  UIKit                               0x000000010cec0e67 -[UIControl sendAction:to:forEvent:] + 67
	11  UIKit                               0x000000010cec1143 -[UIControl _sendActionsForEvents:withEvent:] + 327
	12  UIKit                               0x000000010cec0263 -[UIControl touchesEnded:withEvent:] + 601
	13  UIKit                               0x000000010cdc099f -[UIWindow _sendTouchesForEvent:] + 835
	14  UIKit                               0x000000010cdc16d4 -[UIWindow sendEvent:] + 865
	15  UIKit                               0x000000010cd6cdc6 -[UIApplication sendEvent:] + 263
	16  UIKit                               0x000000010cd46553 _UIApplicationHandleEventQueue + 6660
	17  CoreFoundation                      0x000000010ad3a301 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	18  CoreFoundation                      0x000000010ad3022c __CFRunLoopDoSources0 + 556
	19  CoreFoundation                      0x000000010ad2f6e3 __CFRunLoopRun + 867
	20  CoreFoundation                      0x000000010ad2f0f8 CFRunLoopRunSpecific + 488
	21  GraphicsServices                    0x00000001100f3ad2 GSEventRunModal + 161
	22  UIKit                               0x000000010cd4bf09 UIApplicationMain + 171
	23  DobbleApp                           0x000000010957e87f main + 111
	24  libdyld.dylib                       0x000000010e41f92d start + 1
	25  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)     `

**Comment by Fandekasp** [comment]
@rajatgupta1993 I don't recommend posting on closed issues, especially if your problem isn't related.

Your log clearly explains the problem:

> reason: 'App ID not found. Add a string value with your app ID for the key FacebookAppID to the Info.plist or call [FBSDKSettings setAppID:].'

**Comment by rajatgupta1993** [comment]
@Fandekasp  yeah it explains the problem , but i have had already done it. 
here is my info.plist : 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>$(EXECUTABLE_NAME)</string>
	<key>CFBundleIdentifier</key>
	<string>org.reactjs.native.example.$(PRODUCT_NAME:rfc1034identifier)</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>$(PRODUCT_NAME)</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.0</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>1</string>
	<key>LSApplicationCategoryType</key>
	<string></string>

	<key>LSRequiresIPhoneOS</key>
	<true/>
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>CFBundleURLTypes</key>
		<array>
			<dict>
				<key>CFBundleURLSchemes</key>
				<array>
					<string>fb179549879147261</string>
				</array>
			</dict>
		</array>
		<key>FacebookAppID</key>
		<string>179549879147261</string>
		<key>FacebookDisplayName</key>
		<string>DobbleRealEstate</string>
		<key>LSApplicationQueriesSchemes</key>
		<array>
			<string>fbapi</string>
			<string>fb-messenger-api</string>
			<string>fbauth2</string>
			<string>fbshareextension</string>
		</array>
		<key>NSExceptionDomains</key>
		<dict>
			<key>localhost</key>
			<dict>
				<key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
				<true/>
			</dict>
		</dict>
	</dict>
	<key>NSLocationWhenInUseUsageDescription</key>
	<string></string>
	<key>UIAppFonts</key>
	<array>
		<string>Lato-Bold.ttf</string>
		<string>Lato-Medium.ttf</string>
		<string>Lato-Thin.ttf</string>
		<string>Lato-Semibold.ttf</string>
		<string>Lato-Light.ttf</string>
		<string>Lato-Regular.ttf</string>
		<string>Lato-Heavy.ttf</string>
		<string>Andale Mono.ttf</string>
		<string>Arial Black.ttf</string>
		<string>Arial.ttf</string>
		<string>Comic Sans MS.ttf</string>
		<string>Courier New.ttf</string>
		<string>Georgia.ttf</string>
		<string>Microsoft Sans Serif.ttf</string>
		<string>Roboto_medium.ttf</string>
		<string>Roboto.ttf</string>
		<string>SF-UI-Text-Regular.otf</string>
		<string>Skia.ttf</string>
		<string>Times New Roman.ttf</string>
		<string>Entypo.ttf</string>
		<string>EvilIcons.ttf</string>
		<string>FontAwesome.ttf</string>
		<string>Foundation.ttf</string>
		<string>Ionicons.ttf</string>
		<string>MaterialIcons.ttf</string>
		<string>Octicons.ttf</string>
		<string>Zocial.ttf</string>
	</array>
	<key>UILaunchStoryboardName</key>
	<string>LaunchScreen</string>
	<key>UIRequiredDeviceCapabilities</key>
	<array>
		<string>armv7</string>
	</array>
	<key>UISupportedInterfaceOrientations</key>
	<array>
		<string>UIInterfaceOrientationPortrait</string>
	</array>
	<key>UIViewControllerBasedStatusBarAppearance</key>
	<false/>
</dict>
</plist>

**Comment by heron2014** [comment]
@Fandekasp I have exact the same issue as you had. I’m on Nexus 5, Android 6.0 (API 23) on Intel Atom (x86_64). Could you tell me what are the details of your simulator? Thank you

**Comment by heron2014** [comment]
@Fandekasp Also one more question. Do you need to set up the browser to be Chrome or it comes as default with the android 7?
