### ISSUE TITLE
Works on iOS emulator but not device

### ISSUE THREAD

**Issue by carleryd** [facebook/react-native-fbsdk#275]
I can successfully compile FacebookSDKs-iOS-4.15.0 and run it on iOS simulator 9.3, but it won't run on either an iPad running 9.3 or an iPhone running 8.0.

Here is gist of the error I'm getting and my info.plist file
https://gist.github.com/carleryd/cb17628bfb6b68e44a5a4a9c22106065

I'm running react-native@0.30

**Comment by dzhuowen** [comment]
The error log indicates this is a javascript type error. Please check your js code.
Here's the reference of this method https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Read-only
