### ISSUE TITLE
remove loader when logging in

### ISSUE THREAD

**Issue by atlanteh** [facebook/react-native-fbsdk#276]
When using fbsdk on android, there's this loader spinning.
I want to have my custom loader, and it's in the way.
Is there any way to hide it?

**Comment by dzhuowen** [comment]
Check out this http://stackoverflow.com/questions/29357310/android-how-to-hide-progress-circle-in-facebook-login

**Comment by atlanteh** [comment]
Just had a chance to check this. This solution is no good as it changes the app theme to hide progress bar so it hides the progress bar in the entire application. We need a solution to hide only fbsdk progressbar.

**Comment by mingflifb** [comment]
Try using the latest FB SDK for Android (v4.16), there was a fix to the progress bar.

**Comment by atlanteh** [comment]
The fix was "Better handling of themes for webdialog spinners".
We need it removed entirely.. But I guess this might be a bug for facebook sdk, not the react implementation?
