### ISSUE TITLE
Open this page in "FBSDKBasic" ?

### ISSUE THREAD

**Issue by andyfenelon** [facebook/react-native-fbsdk#278]
this was working then i logged out and went to log back in after the "authorise this app" i'm getting this ?! it breaks if i click "open" or "cancel" and my app isn't called "FBSDKBasic".

<img width="358" alt="screen shot 2016-09-07 at 14 07 55" src="https://cloud.githubusercontent.com/assets/5710962/18328717/ef1aa242-7504-11e6-8739-ef89bfc5c331.png">

**Comment by chrisp-fb** [comment]
Do you have another app installed on your device called FBSDKBasic? This looks like you have an app with that name that has mistakenly registered the same URL scheme (fbauth:// of fbauth2://) as the Facebook app.

If not, are you able to reproduce on a different device or simulator?

**Comment by andyfenelon** [comment]
i reset the content and settings on the simulator and it's fixed it. yeah it must have been an old app i had on the simulator. thanks.

**Comment by juddey** [comment]
Note for future readers: You'll also get the same message if you haven't added the code under the heading "Track App Installs and App Opens" in the "Quick Start for iOS" setup guide for the Facebook iOS SDK.

(as you can probably guess, I've just been through this).

**Comment by andyfenelon** [comment]
obviously this is pretty random, but could this happen in production ? say two apps have the SDK installed ?
