### ISSUE TITLE
iOS 10.0 xcode 8 - Error - createErrorFromErrorData

### ISSUE THREAD

**Issue by sibelius** [facebook/react-native-fbsdk#279]
I have the following error when I try to login on ios 10 built with xcode 8

```js
Error: Login Failed
    at createErrorFromErrorData (MessageQueue.js:454)
    at MessageQueue.js:405
    at MessageQueue.__invokeCallback (MessageQueue.js:268)
    at MessageQueue.js:130
    at guard (MessageQueue.js:42)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:129)
    at onmessage (debuggerWorker.js:39)
```

has something changed for ios 10 on facebook login?

**Comment by sibelius** [comment]
adding entitlements fixed the issue

http://stackoverflow.com/questions/38456471/secitemadd-always-returns-error-34018-in-xcode-8-beta-4-in-ios-10-simulator/38543243#38543243

**Comment by owencm** [comment]
Wow. I ran into this issue today and was 100% stumped by the error and callstack.

I followed that SO post and it solved the problem for me too. Thanks for rescuing my evening! 

I've gotta know though, how did you know that was the problem?!

**Comment by sibelius** [comment]
@owencm, I've just googled and tried different possible solutions

**Comment by sbaar** [comment]
If anyone else is still getting this error when switching accounts, make sure to call LoginManager.logOut() before logging in again. App functionality will remain identical, but this handles the edge case of swapping users.
