### ISSUE TITLE
Object Returned Contains No public_profile User Data

### ISSUE THREAD

**Issue by quadsurf** [facebook/react-native-fbsdk#280]
The only response I get back is a list of grantedPermissions but no values like an email address or age range, etc. Furthermore, there are no next steps for what to do next in order to obtain those values. There may be an assumption that next steps are obvious, but they're not. I am very respectfully frustrated with Facebook. I had hoped that Facebook Login would seamlessly work with Facebook React Native. Please help!

Also, there doesn't seem to be an API reference listing out all the methods/options for the LoginButton Component.

**Comment by chrisp-fb** [comment]
Once you've completed a login and have an access token, you need to use the Graph API https://github.com/facebook/react-native-fbsdk#graph-api to retrieve data. Sorry about the confusion, we'll see how we can better update our docs. One thing to keep in mind is that the react-native-fbsdk wraps around our native SDKs so the docs at developers.facebook.com have more information. For example, you can learn more about the Graph API at https://developers.facebook.com/docs/graph-api
