### ISSUE TITLE
FB Login Result Returning a 'ECOM.FACEBOOK.SDK.LOGIN308' Error for iOS 10

### ISSUE THREAD

**Issue by jakehasler** [facebook/react-native-fbsdk#281]
Running react-native-fbsdk `^0.3.0`, and Xcode 8 beta with iOS 10, I kept getting the Login Error in the Title, `ECOM.FACEBOOK.SDK.LOGIN308` when the following code was executed:
```javascript
LoginManager.logInWithReadPermissions([
      'public_profile'
    ]).then((result) => {
      if (result.isCancelled) {
        alert('Login cancelled');
      } else {
        alert('Login success with permissions: '
            + result.grantedPermissions.toString());
      }
    }, function (error) {
      console.log(error);
      alert('Login fail with error: ' + error);
    });
```

### Solution
Under the _capabilities_ section of the app, you need to enable _Keychain Sharing_ for you application. Upon enabling this.
![screen shot 2016-09-10 at 2 01 39 pm](https://cloud.githubusercontent.com/assets/10869870/18413238/51ea7d0a-775f-11e6-8740-7a25a592027d.png)

**Comment by dzhuowen** [comment]
iOS SDK released 4.15.1 to support iOS 10. Make sure you use it. https://developers.facebook.com/docs/ios/change-log-4.x
