### ISSUE TITLE
LoginWithRead/PublishPremissions

### ISSUE THREAD

**Issue by gviligvili** [facebook/react-native-fbsdk#282]
Using RN 0.32

I saw at FBLoginManager module  the following: 
```
  logInWithReadPermissions(permissions: Array<string>): Promise<LoginResult> {
    return LoginManager.logInWithReadPermissions(permissions);
  },

  /**
   * Logs the user in with the requested publish permissions.
   */
  logInWithPublishPermissions(permissions: Array<string>): Promise<LoginResult> {
    return LoginManager.logInWithPublishPermissions(permissions);
  },
```

It give me errors because logInWithReadPermissions & logInWithPublishPermissions Doesn't exist
in the NativeModules.FBLoginManager.

there is only "loginWithPermissions" for me.

Maybe I'm missing something? Anyway I thought I should update here.

(The Login button works great BTW).

**Comment by gviligvili** [comment]
I would really appreciate if someone which this module works great for him will reply with his ios & android SDK version and RN and RN-cli Version.
If i will find anything new I will update :)

**Comment by dzhuowen** [comment]
Hi @gviligvili  given the limited info I can't see where the problem is, but it looks to me that you didn't set up the native sdk correctly (I'm assuming you're working on iOS).

**Comment by owencm** [comment]
I had a similar issue, I think @dzhuowen is right that you haven't got it set up quite right.

Be sure you've added the Frameworks and added them to your build settings correctly (see https://developers.facebook.com/docs/ios/getting-started/)

**Comment by gviligvili** [comment]
Okay,  you can close the issue. 
Yesterday,  for the god knows how many times,  I cleaned the project,  but the difference was that when I saw 'updated xcode is needed'  I checked Xcode updates again,  I updated the xcode (I thought it was updated) and after some settings changes it worked flawlessly :) ! 
Thanks so much.
