### ISSUE TITLE
Error code 308 after xcode update

### ISSUE THREAD

**Issue by justin808** [facebook/react-native-fbsdk#283]
After the recent xcode update, we can no longer use the simulator to login:

```
error	NSError *	domain: @"com.facebook.sdk.login" - code: 308	0x000060800024f330
```

Direct device installs seem OK.

I'm using 0.3.0.

We tried:

1. simulator reset
2. remove FB permissions on user
3. debugging in xcode (is there some way to get symbols or source code? we quickly end up in assembly code)

**Comment by bighitbiker3** [comment]
@justin808 http://stackoverflow.com/a/38877600/5526221 - That answer worked for me.  I needed to enable keychain access.

**Comment by jhack32** [comment]
Another link with explanation below:
http://stackoverflow.com/questions/38689631/how-to-use-facebook-ios-sdk-on-ios-10/38799196#38799196
