### ISSUE TITLE
reasking for declined permissions

### ISSUE THREAD

**Issue by carlespuyol** [facebook/react-native-fbsdk#285]
Hi !
I would like to reask (if declined) for 'user_photos' permission when someone is trying to import photos from facebook.

I searched about this issue but I couldn't find a solution using react-native.

**Comment by dzhuowen** [comment]
You can make [graph request](https://github.com/facebook/react-native-fbsdk/blob/efb7470ba16d7828951ba48753d8be68c13b69cb/js/FBGraphRequest.js) to query user photo. Check out the graph api https://developers.facebook.com/docs/graph-api/reference/user/picture/.
