### ISSUE TITLE
Unable to resolve module react-native-fbsdk from /Users/username/Desktop/MyApp/MyApp/index.ios.js

### ISSUE THREAD

**Issue by mihirroy87** [facebook/react-native-fbsdk#288]
The moment I add this to index.ios.js I receive the above error:
const FBSDK = require('react-native-fbsdk');
const {
  LoginButton,
  AccessToken
} = FBSDK;

![screen shot 2016-09-20 at 12 30 34 am](https://cloud.githubusercontent.com/assets/8078228/18661222/7c63fb9e-7ec9-11e6-83d0-d120ec23e6ef.png)

I have tried everythign from this post https://github.com/facebook/react-native/issues/4968 but still don't understand the reason for this error. 

My package.json dependencies:
"dependencies": {
    "react": "15.3.1",
    "react-native": "0.33.0",
    "react-native-fbsdkcore": "0.0.8",
    "react-native-fbsdklogin": "0.0.8",
    "react-native-fbsdkshare": "0.0.8"
  }

**Comment by yazgazan** [comment]
Looks like you are missing the `react-native-fbsdk` dependency.

**Comment by dzhuowen** [comment]
Please update the version react native fbsdk for better experience.
