### ISSUE TITLE
Compile error when compiling via 'react-native run-ios' (cannot find Frameworks)

### ISSUE THREAD

**Issue by aforty** [facebook/react-native-fbsdk#290]
Everything works great when I build and run from within Xcode but when I run `react-native run-ios` it will fail compiling the package.

```
(...)/node_modules/react-native-fbsdk/iOS/RCTFBSDK/login/RCTFBSDKLoginButtonManager.h:19:9: fatal error: 'FBSDKLoginKit/FBSDKLoginKit.h' file not found
#import <FBSDKLoginKit/FBSDKLoginKit.h>
        ^
1 error generated.
```

I installed with `react-native install react-native-fbsdk` and otherwise I haven't changed anything.

I am still pretty new to Xcode and Obj-C but it appears it cannot find the `FBSDKLoginKit` framework. I have all the necessary frameworks in `ios/Frameworks`. My application target has `Framework Search Paths` configured with `$(PROJECT_DIR)/Frameworks` and I checked `FBSDK.xcodeproj` has it configured with `$(PROJECT_DIR)/../../../ios/Frameworks`. Both those paths should correctly resolve to where the frameworks are located.

What am I doing wrong? What other settings could be interfering with this?

**Comment by nicolabortignon** [comment]
+1

**Comment by benoitvallon** [comment]
Same here, I am running react-native 0.32

**Comment by dzhuowen** [comment]
Hi @benoitvallon please file a bug at https://developers.facebook.com/bugs/ for quicker response

**Comment by jtremback** [comment]
Me too

**Comment by dzhuowen** [comment]
Hi everyone, please subscribe to this bug at https://developers.facebook.com/bugs/198744800546672/.
For future issues please file a bug at  https://developers.facebook.com/bugs/. It allows you to securely upload sample repros project for debugging.
