### ISSUE TITLE
Error: Login Failed

### ISSUE THREAD

**Issue by Panda313** [facebook/react-native-fbsdk#291]
Hi

First : thanks for such an amazing project. It was working on iOS in the simulator lately... But since I updated to xcode 8, I needed to update RN 0.33. And since then, I was unable to login using my app.

I can open the facebook login webview, login, but the call bacl say : "Error: Login Failed". And I'm getting back to my screen.

Any idea ?

Thanks

**Comment by ywongweb** [comment]
Same problem here, also just upgraded to Xcode 8

**Comment by srsholmes** [comment]
Have you tried enabling keychain sharing? https://developer.apple.com/library/content/documentation/IDEs/Conceptual/AppDistributionGuide/AddingCapabilities/AddingCapabilities.html

I think with the iOS 10 update we require additional permissions, and i think this may solve it.

**Comment by Panda313** [comment]
Hum, don't seems to solve it for me ; @ywongweb better luck ?

**Comment by axeldelafosse** [comment]
Hi !

What's the FBSDK Login Error Code ?

I had the same problem and fixed it by adding Keychain Access Groups to the Entitlements file.

<img width="735" alt="capture d ecran 2016-09-23 a 11 45 00" src="https://cloud.githubusercontent.com/assets/10477267/18781703/3afac900-8183-11e6-8df9-d1e7eedfa458.png">

**Comment by iambanh2** [comment]
I solved my problem with enabling keychain sharing.

**Comment by ywongweb** [comment]
@Panda313 I went back to v7.3.1 :)

**Comment by Panda313** [comment]
My bad, needed to clean up everything. works like a charm

thanks all

**Comment by balibou** [comment]
1 day to figure it out ... Thank you very much it works perfectly !

**Comment by schumannd** [comment]
shouldn't this be in the setup docs?

**Comment by cassianomon** [comment]
I am still having this in a clean install, already activated Keychain Sharing, did `LoginManager.logOut()`

**Comment by cassianomon** [comment]
Still having the same issue, tried everything above.

```
"react-native": "0.56.0",
"react-native-fbsdk": "0.8.0"
```
