### ISSUE TITLE
logInWithReadPermissions erroring out

### ISSUE THREAD

**Issue by a-koka** [facebook/react-native-fbsdk#292]
Hi,

I recently upgraded to `React 0.33` and `FBSDK 0.3` from `React 0.28` and `FBSDK 0.22`. None of my JS code changed and I am no longer able to login via Facebook. I did update my Facebook SDK as the new version of this plugin did not work with the old SDK.

Just wondering if anyone is experiencing similar issues and if there is some help I could get on how to debug this further.

Thank you!

**Comment by mjsisley** [comment]
I am not sure what your issue is. But if you happened to also switch to iOS 10, this may help you:
https://stackoverflow.com/questions/38689631/how-to-use-facebook-ios-sdk-on-ios-10

**Comment by a-koka** [comment]
Thanks a lot for your prompt response @mjsisley. I wasn't sure if there was a known issue with the latest libraries. If not, I will go ahead and create a new project to track down the issue. If it happens to be unrelated to my project, I'll update this issue.

Thanks again!

**Comment by a-koka** [comment]
It was the Keychain sharing. I didn't realize that updating Xcode also updated my iOS version. Thanks a lot @mjsisley!
