### ISSUE TITLE
libRCTFBSDK.a can not be find

### ISSUE THREAD

**Issue by Talkwondo** [facebook/react-native-fbsdk#295]
Hi,
does anyone know why it can not be find? 
the build is Ok but when i add this file to  Link Binary with Libraries the build failed.
<img width="252" alt="screen shot 2016-10-10 at 19 10 35" src="https://cloud.githubusercontent.com/assets/20122139/19242834/92367de8-8f1d-11e6-9b32-c2ef5436f2fb.png">

Please help.

Thanks

**Comment by Talkwondo** [comment]
OK that is because i have not link by rnpm.

**Comment by saaddigitaldividend** [comment]
@Talkwondo  can you please tell me how you solved this. I am having the same issue.
I have run yarn add , also linked as well. 
In XCode I have also gave the path from Doucments/FacebookSDK

Please help!

**Comment by Talkwondo** [comment]
@saaddigitaldividend You need to link the library. You can do that with rnpm or link manually by drag to Xcode link with library.

**Comment by bamaarintoko** [comment]
this not work, i try it then build ios failed

**Comment by Talkwondo** [comment]
Try clean and rebuild, this is a linking problem for sure. maybe try pod install if you are using cocoa pods
