### ISSUE TITLE
set mode to webview for app invite dialog

### ISSUE THREAD

**Issue by stantoncbradley** [facebook/react-native-fbsdk#296]
Is it possible to open the app invite dialog in the native facebook app or webview, similar to `ShareDialog.setMode("webview");`?

If so, how?  If not, are there plans to implement this, or is it similar enough to the share dialog that I can make a PR?

Thanks!

**Comment by dzhuowen** [comment]
Please post questions on sdk set up to stackoverflow for quicker response. Besides it's easier for others searching for similar questions. 
Report bugs or issues to https://developers.facebook.com/bugs/
