### ISSUE TITLE
Could not build module FBSDKCoreKit - "react-native-fbsdk": "^0.3.0"

### ISSUE THREAD

**Issue by nhatchimai111** [facebook/react-native-fbsdk#298]
![screen shot 2016-10-17 at 3 16 21 pm](https://cloud.githubusercontent.com/assets/13510054/19435950/ad77498c-9497-11e6-971c-3003c0b1e260.png)

I have configurated the project same link https://github.com/facebook/react-native-fbsdk#33-troubleshooting but xcode show error "_Could not build module FBSDKCoreKit._ "
![screen shot 2016-10-17 at 6 33 50 pm](https://cloud.githubusercontent.com/assets/13510054/19436131/a3a53fd0-9498-11e6-9938-6b18b857063c.png)

**Comment by dzhuowen** [comment]
The "red" frameworks indicates it's not found at the path set in the project. Please try using the ios_set.js script.

**Comment by dzhuowen** [comment]
Please post questions on sdk set up to stackoverflow for quicker response. Besides it's easier for others searching for similar questions. Report bugs or issues to https://developers.facebook.com/bugs/
