### ISSUE TITLE
login button is red box and doesn't work. no compile errors or warning

### ISSUE THREAD

**Issue by noahdesu** [facebook/react-native-fbsdk#299]
I followed the README for iOS and am not getting nay compile errors or warning. However the login button code from the README results in a blank clear red button, and clicking it doesn't initiate the login flow or produce any alerts or console messages.

Not sure what to do. Any more information I can provide or next steps to help diagnose?

**Comment by chrene** [comment]
I also have this issue kinda. 
The app starts and the facebook button is there. When pressing it the app closes (maybe it crashes I don't know) 
now I open the app again and the box is a red outline.

**Comment by dzhuowen** [comment]
Please post questions on sdk set up to stackoverflow for quicker response. Besides it's easier for others searching for similar questions. Report bugs or issues to https://developers.facebook.com/bugs/

**Comment by ssomnoremac** [comment]
@chrene , @noahdesu any progress on this? I'm getting the same
