### ISSUE TITLE
fb login isCancelled is always true

### ISSUE THREAD

**Issue by rt2zz** [facebook/react-native-fbsdk#3]
Not sure if my issue is with react-native-fbsdk, but I am getting `isCancelled: true` on my login requests (even when pressing "ok")

**Comment by cphackm** [comment]
Make sure you've correctly followed the iOS Facebook SDK [getting started guide](https://developers.facebook.com/docs/ios/getting-started).  You may have made a mistake setting up info.plist, or -- more likely -- the app delegate.  You can refer to [AppDelegate.m](https://github.com/facebook/react-native-fbsdk/blob/master/Sample/iOS/AppDelegate.m) to see how to correctly set that up.

**Comment by rt2zz** [comment]
Ah, yes I skipped over the AppDelegate business. Thanks!
