### ISSUE TITLE
FBSDK initialize

### ISSUE THREAD

**Issue by skyride99** [facebook/react-native-fbsdk#300]
Using RN 25.1 and the latest FBSDK 0.3.0

For Android I get this error:
the sdk has not been initialized, make sure to call FacebookSdk.sdkinitialize() first.

Where is this initialized  for RN < 29. 

Thanks

**Comment by skyride99** [comment]
I have followed the instructions for https://developers.facebook.com/quickstarts/978764902233014/?platform=android

The instructions work for RN17. Does FBSDK support RN 25?
but in RN 25 the main class inherits from 

public class MainActivity extends ReactActivity {}

You can not override onCreate()

**Comment by skyride99** [comment]
I have used this as a guide
http://stackoverflow.com/questions/37719258/adding-facebook-sdk-to-react-native-project
I had upgraded from RN 17 to RN 25.1 , its not working.

**Comment by skyride99** [comment]
I found the issue with this the documentation is missing a line. In the android manifest.xml

<application
      android:allowBackup="true"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:theme="@style/AppTheme"
      android:name="com.muo.MyApplication"
      >

The android:name needs to be there. Facing another issue now.

**Comment by dzhuowen** [comment]
For elder RN version, if there's no MainApplication.java auto-generated for you in project init, you need to create the class yourself. See https://developers.facebook.com/docs/android/getting-started/ step 6 for the file content.
