### ISSUE TITLE
getting very low resolution of the profile picture

### ISSUE THREAD

**Issue by Talkwondo** [facebook/react-native-fbsdk#301]
this is the code i am using.
   LoginManager.logInWithReadPermissions(['public_profile', 'email', 'user_hometown','user_birthday','user_friends']).then(function(result) {
       console.log(result)
       if (result.isCancelled) {
         // Login was cancelled
       } else {
         AccessToken.getCurrentAccessToken().then(
         (data) => {
           let accessToken = data.accessToken
           const responseInfoCallback = (error, result) => {
             if (error) {
               console.log(error)
               console.log('Error fetching data: ' + error.toString());
             } else {
               console.log(result);
               console.log('Success fetching data: ' + result.toString());
}
const infoRequest = new GraphRequest(
             '/me',
             {
               accessToken: accessToken,
               parameters: {
                 fields: {
                   string: 'email,first_name,last_name,picture,gender,birthday,hometown'
                 }
               }
             },
             responseInfoCallback
           );
           new GraphRequestManager().addRequest(infoRequest).start()
         }
       )
       }
     },
     function(error) {
       console.log(error);
     },
   );
  }
}
I am getting the profile picture but very low resolution.

i know that there is an issue with that..

Thanks

**Comment by kelset** [comment]
Hey, it's not strictly an issue, it is related to the graph query you are sending up: by modifying the string setting `picture.type(large)` instead of `picture` you should be fine.

In any case, refer to the [Graph API documentation](https://developers.facebook.com/docs/graph-api/reference/user/picture/)

**Comment by Talkwondo** [comment]
Thanks! Fixed
