### ISSUE TITLE
Can't use AppEventsLogger on android

### ISSUE THREAD

**Issue by mylake** [facebook/react-native-fbsdk#303]
using "react": "15.3.2", "react-native": "0.35.0", "react-native-fbsdk": "^0.3.0"
the android virtual Devices I use is => Android 7.0, API Level: 24

I have followed README.md setting
I want to use Analytics for Apps. 

On iOS it works well both on App Launches and AppEventsLogger

On Android it works well on App Launches, and I could got the data on facebook analytics website
but about the AppEventsLogger.logPurchase or AppEventsLogger.logEvent, I will got failed msg

```
const FBSDK = require('react-native-fbsdk');
const {
  AppEventsLogger,
} = FBSDK;
AppEventsLogger.logPurchase(15, 'USD', {'param': 'value'})
```

but I got the error like this

```
Attempt to invoke virtual method 'void com.facebook.appevents.AppEventsLogger.logPurchase(java.math.BigDecimal, java.util.Currency, android.os.Bundle)' on a null object reference
logPurchase
    FBAppEventsLoggerModule.java:175
invoke
    Method.java:-2
```

could you help me figure out why, thank you

**Comment by dzhuowen** [comment]
Let's continue the discuss in stackoverflow http://stackoverflow.com/questions/40230785/react-native-fbsdk-cant-use-appeventslogger-on-android/40232257#40232257
