### ISSUE TITLE
Problem when Facebook App is installed on Android device

### ISSUE THREAD

**Issue by luisfuertes** [facebook/react-native-fbsdk#304]
I have a production App in Play Store. I have a issue when Android Device has Fb app installed.

If fb app isnt installed, component open WebView and all ok, but if has Fb, first say: 
![captura de pantalla 2016-10-21 a las 13 11 41](https://cloud.githubusercontent.com/assets/18212615/19596687/11ead80c-9790-11e6-9021-f28f1d35e2b8.png)

I upp my release keystore hash, and the new error:
```
FacebookLogin error:  Error: Invalid key hash. The key hash [HASH=] does not match any stored key hashes. Configure your app key hashes at http://developers.facebook.com/apps/XXXXX
```

My android facebook project configuration:
![captura de pantalla 2016-10-21 a las 13 13 54](https://cloud.githubusercontent.com/assets/18212615/19596750/6465e374-9790-11e6-8005-dcd501f386bb.png)

How can i fix it?

**Comment by luisfuertes** [comment]
Ok i solved it. I wrote bad my STORE_PASSWORD and console give me bad app key hash.

**Comment by dzhuowen** [comment]
Please make sure you follow all the steps in https://developers.facebook.com/docs/android/getting-started/#release-key-hash
The error indicates that you're not adding the correct the key hash to app dashboard.

**Comment by theobouwman** [comment]
I am facing the same issue. @dzhuowen I can't fix the issue. I find the documentation pretty hazy. Could you help?

**Comment by sergiulucaci** [comment]
Check this: https://github.com/facebook/react-native-fbsdk/issues/424#issuecomment-441578068

**Comment by harshals25** [comment]
Place this code into the main activity (or wherever you are making call to connect to Facebook) and you'll have a key returned in the log. put that into the android key hashes on your project console on facebook developer 

public static void createKeyHash(Activity activity, String yourPackage) {
        try {
            PackageInfo info = activity.getPackageManager().getPackageInfo(yourPackage, PackageManager.GET_SIGNATURES);
            for (Signature signature : info.signatures) {
                MessageDigest md = MessageDigest.getInstance("SHA");
                md.update(signature.toByteArray());
                Log.d("KeyHash:", Base64.encodeToString(md.digest(), Base64.DEFAULT));
            }
        } catch (PackageManager.NameNotFoundException e) {
            e.printStackTrace();
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        }
    }
