### ISSUE TITLE
Android Build Error When Following Install Instructions

### ISSUE THREAD

**Issue by keeleycarrigan** [facebook/react-native-fbsdk#306]
I recently installed the FBSDK in my React Native project (version 0.35.0) and get a build error when building for Android. When I follow step 'F' on this [page](https://developers.facebook.com/docs/facebook-login/android) I get this error in the build.

```
Error:
	Attribute activity#com.facebook.FacebookActivity@theme value=(@android:style/Theme.Translucent.NoTitleBar) from AndroidManifest.xml:32:4-63
	is also present at [com.facebook.android:facebook-android-sdk:4.16.1] AndroidManifest.xml:32:13-63 value=(@style/com_facebook_activity_theme)
	Suggestion: add 'tools:replace="android:theme"' to <activity> element at AndroidManifest.xml:29:3-33:39 to override
```

So if I remove `android:theme="@android:style/Theme.Translucent.NoTitleBar"` from `AndroidManifest.xml` the build is fine. I also get the warning below but it still builds and works on my test phone.

```
Warning:
	Element activity#com.facebook.react.devsupport.DevSettingsActivity at AndroidManifest.xml:34:3-80 duplicated with element declared at AndroidManifest.xml:28:3-80
```

**Comment by dzhuowen** [comment]
The instruction on developer site is outdated. You don't need to add the FacebookActivity in the app manifest file b/c Facebook Android SDK already has it. Please follow this https://developers.facebook.com/docs/android/getting-started  Thanks for the heads up.
