### ISSUE TITLE
Facebook SDK version 4.17.0 causes Android crash

### ISSUE THREAD

**Issue by hieudole** [facebook/react-native-fbsdk#310]
Crashed on Android 4.4.4.
Pinning Facebook SDK version to 4.16.1 (node_modules/react-native-fbsdk/Android/build.gradle line 26) solves the issue.

**Comment by dzhuowen** [comment]
Please update to the latest Android SDK. http://stackoverflow.com/questions/40321265/android-studio-suddenly-started-to-display-unable-to-resolve-com-android-support

**Comment by hieudole** [comment]
The link you posted that is related to the errors when compiling project. I already have API 25 and Android Support Repository 25, and Android Support Library 25 installed on my local environment. My project was built successfully with the setting compile('com.facebook.android:facebook-android-sdk:4.+'), but the app crashes every time I run on my device. **It works well after I updated Google Play Services to the latest version and rebuilt the project.**
