### ISSUE TITLE
Any reason Param is limited to string|number

### ISSUE THREAD

**Issue by dozoisch** [facebook/react-native-fbsdk#312]
Hello!

Is there any reason that https://github.com/facebook/react-native-fbsdk/blob/master/js/FBAppEventsLogger.js#L38 is limited to `string | number` and does not accept boolean values? Is it a limitation on the SDK side?

I'll be happy to send a pr to add booleans if it's accepted!

**Comment by dzhuowen** [comment]
Yeah Facebook SDK requires the parameter value to be either string or number. This is explicitly specified by Facebook iOS SDK as [below](https://developers.facebook.com/docs/reference/ios/current/class/FBSDKAppEvents/)
"Arbitrary parameter dictionary of characteristics. The keys to this dictionary must be NSString's, and the values are expected to be NSString or NSNumber. Limitations on the number of parameters and name construction are given in the FBSDKAppEvents documentation. "

**Comment by dozoisch** [comment]
Alright thanks! Time to cast all the bools!
