### ISSUE TITLE
ShareDialog not displaying with contentType photo and hashtag

### ISSUE THREAD

**Issue by ropilz** [facebook/react-native-fbsdk#313]
When displaying `ShareDialog` with `contentType: 'photo'` and `commonParameters.hashtag : '#anyhash'` Share dialog is returning empty object and not displaying. For example:

```javascript
ShareDialog.show({
  contentType: 'photo',
  photos: [{
    imageUrl: 'valid photo uri',
    userGenerated: true
  }],
  commonParameters: {
    hashtag: '#facebook'
  }
}).then(result => { 
    // result is {}, dialog was not displayed
});
```

Removing `commonParameters` makes the dialog behave properly.

react-native: 0.35.0
react-native-sdk: 0.3.0
OS: iOS 10.0

**Comment by dzhuowen** [comment]
Please report bugs or issues to https://developers.facebook.com/bugs/ for quicker response.
