### ISSUE TITLE
LoginButton custom height

### ISSUE THREAD

**Issue by NikolaBorislavovHristov** [facebook/react-native-fbsdk#317]
How to center label vertically if i change the default height of the FacebookLoginButton to 60?
I am using same code on both platforms. The problem appears only on Android.
[Android](http://i.imgur.com/CqXr2dC.png)
[iOS](http://i.imgur.com/odrQdcr.png)

**Comment by dzhuowen** [comment]
Please report bugs or issues to https://developers.facebook.com/bugs/ for quicker response.

**Comment by mnmistake** [comment]
why is this closed? any reference to https://developers.facebook.com/bugs/
