### ISSUE TITLE
React-Native - Customise facebook login button

### ISSUE THREAD

**Issue by kmanishprdxn** [facebook/react-native-fbsdk#318]
Hi,

I'm using **react-native** for build a mobile app. In my app I've used **react-native-fdbsk@0.3.0** for social login(facebook). One difficulty I'm facing i.e I don't know how I suppose to customise this login button. I don't want login button with text on it, I just want simple facebook icon and when I click on this icon this should give me an user info if user is already logged in with facebook else app should ask for facebook login. (currently this button also provides a logout functionality which I don't required)

Currently I don't have much insights about android, all I know is react-native. So could you please help me here re: How I suppose to customise/configure my facebook login button?

**Comment by drop-dan** [comment]
Hey there,

I would suggest just making your own button component and then calling the necessary methods in the onPress callback.  I think this is what most people do.  Allowing customization of the button just opens up a whole can of worms.

**Comment by drop-dan** [comment]
```javascript
export default class FacebookLogin extends React.Component {
  render() {
    return (
      <TouchableOpacity onPress={this._login}>
        <Text>
          Log in with Facebook
        </Text>
      </TouchableOpacity>
    )
  }

  _login = () => {
    LoginManager.logInWithReadPermissions(permissionsList).then((result) => {
      if (!result.isCancelled) {
        AccessToken.getCurrentAccessToken().then((data) => {
          // Do success stuff
        })
      }
    }, (error) => {
      alert('There was an error connecting to Facebook. Please try again later.')
    })
  }
}
```

**Comment by kmanishprdxn** [comment]
Yes, This is what I was actually looking for. @drop-dan Thanks for your reply, it solved my problem. :+1:
