### ISSUE TITLE
There is no Documentation

### ISSUE THREAD

**Issue by RyanMitchellWilson** [facebook/react-native-fbsdk#319]
I've been searching for a few hours now with zero luck as to the fields I can use with ShareDialog. Has anybody found a something that could help me out? You'd think there would be some sort of documentation here [https://developers.facebook.com/docs/react-native/getting-started-ios](url) about how to use this library.

**Comment by dzhuowen** [comment]
Please report bugs or issues to https://developers.facebook.com/bugs/ for quicker response.
