### ISSUE TITLE
ShareDialog only works correctly in simulator

### ISSUE THREAD

**Issue by RyanMitchellWilson** [facebook/react-native-fbsdk#320]
I'm using the Share Dialog to share something to facebook. When I use `ShareDialog.show` in the simulator it opens a safari webView with all the correct information ready to share. But when I load it onto a device, it just opens a modal with none of the info I gave it to display. Why is this happening?

Here is what my code looks like:
```
const shareContent = {
  contentDescription: 'Stuff here',
  contentTitle: 'Share Title',
  contentUrl: 'google.com',
  imageUrl: 'someUrlHere'
}

ShareDialog.canShow(shareContent).then((canShow) => {
  canShow && ShareDialog.show(shareContent);
})
```

When the facebook modal pops up it only displays what the meta tags have for the site and not what was given to the `show` function.

<img width="300" alt="screen shot 2016-11-14 at 11 45 23 am" src="https://cloud.githubusercontent.com/assets/11371200/20277925/edc981f2-aa5f-11e6-9f6f-f39b63113365.png">

<img width="300" alt="img_0032" src="https://cloud.githubusercontent.com/assets/11371200/20278200/fc058698-aa60-11e6-913b-be79699fd3c9.png">

iOS 10
react-native-fbsdk - 0.4.0
react-native - 0.30.0

**Comment by dzhuowen** [comment]
Please report bugs or issues to https://developers.facebook.com/bugs/ for quicker response.
