### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by rt2zz** [facebook/react-native-fbsdk#33]
It would be great to have android support

**Comment by drager** [comment]
I agree on this, hoping to see this soon.

**Comment by santhosbaala** [comment]
:+1:

**Comment by lalith26** [comment]
:+1:

**Comment by danghatam** [comment]
:+1:

**Comment by diemvtt** [comment]
:+1:

**Comment by nlhkh** [comment]
:+1:

**Comment by Sh3rawi** [comment]
+1.

**Comment by ms88privat** [comment]
:+1:

**Comment by PoshHsu** [comment]
+1

**Comment by yeso126** [comment]
+1

**Comment by pickhardt** [comment]
Since everyone else has already +1'ed this, I'll ask a question. Should we be expecting this soon, in a few months, never? The last commit was 3 weeks ago and we're not sure what the status is.

**Comment by mingflifb** [comment]
This is something we would like to have and support, but there's no timeline or schedule to announce at this time.

**Comment by nlhkh** [comment]
I think this lack of support, whatever the reason is, is hindering React
Native to really shine. Most people who are struggling here are not
familiar with using native module or native UI components in React Native
JavaScript.
I think that it is worth while if you invest in tutorials (videos, best
practices and stuff) for using  fbsdk with React Native, both in iOS and
Android, so that you no longer have to maintain this for the community, and
we can customize the behavior to our heart content. The fbsdk is complex
and featureful enough that the experience can be applied to other native
libraries.

**Comment by ktoh** [comment]
+1

**Comment by kevinzzz007** [comment]
@nlhkh @mingflifb @pickhardt First this is an amazing repo, thank you guys so much for creating this, but I also agree that there haven't been many updates...as a developer, I would love to get more help on this SDK. I also think maintaining this repo is a good business decision since it gets more developers to adopt the Facebook platform :-)

**Comment by anusharamachandra** [comment]
:+1:

**Comment by pickhardt** [comment]
In FB's defense, the people working on RN have a lot to do and I suspect are spread thin. This particular repo feels unmaintained, and could use some more focus, but RN on the whole is a great gift from Facebook that we should be grateful for.

**Comment by kevinzzz007** [comment]
I cannot agree with you more, RN is absolutely amazing, and I definitely
understand that they are spread thin and I am really grateful for their
hard work

On Wednesday, October 14, 2015, Jeff Pickhardt <notifications@github.com>
wrote:

> In FB's defense, the people working on RN have a lot to do and I suspect
> are spread thin. This particular repo feels unmaintained, and could use
> some more focus, but RN on the whole is a great gift from Facebook that we
> should be grateful for.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/react-native-fbsdk/issues/33#issuecomment-147934041>
> .
>


-- 
Kevin Zhao | LinkedIn <http://www.linkedin.com/in/kevinzhaouva> | Personal
Blog <https://medium.com/@kevinzhao> | Github
<https://github.com/kevinzzz007>
(434) 282-5369
Computer Science and Information Technology | University of Virginia 2016
Alpha Kappa Psi Professional Business Fraternity
<http://www.akpsiatuva.org/>

**Comment by lalith26** [comment]
I would definitely agree about the awesomeness of React-Native. But Since React-Native has just been released for android, There are not a lot of modules which people can really refer to. So, It would be awesome if Facebook itself provides this and People can use this as a reference while creating other modules or exposing UI Components.

**Comment by PhilippKrone** [comment]
Are there any news here? It would be highly appreciated to have android support :)

**Comment by jforaker** [comment]
+1,000,000

**Comment by akiran** [comment]
+1

**Comment by ms88privat** [comment]
Please! :+1:

**Comment by PhilippKrone** [comment]
@dzhuowen Do you know whether someone is working on it at the moment?

**Comment by braco** [comment]
*Crickets*

**Comment by magus** [comment]
There is a PR up in my repository which people have verified is working but it's important to note my library is focused on login. Any additional features such as sharing and graph requests may not be as simple as through this library. Maybe we can merge the result into this library as well, somehow.

https://github.com/magus/react-native-facebook-login/pull/33

**Comment by MrSaints** [comment]
:+1:

**Comment by MossP** [comment]
this would be great +1 :+1:

**Comment by mattds** [comment]
:+1: @dzhuowen any plans to support android?

**Comment by magus** [comment]
Android support merged into my repo
https://github.com/magus/react-native-facebook-login

**Comment by shohey1226** [comment]
:+1:

**Comment by treeder** [comment]
+1

**Comment by jittuu** [comment]
:+1:

**Comment by niftylettuce** [comment]
:+1:

**Comment by aneesv** [comment]
:+1:

**Comment by minibikini** [comment]
:+1:

**Comment by surfeurX** [comment]
:+1:

**Comment by minibikini** [comment]
:+1:

**Comment by jaggs6** [comment]
:+1:

**Comment by pickhardt** [comment]
The thumbs ups are pretty redundant at this point.

**Comment by jaggs6** [comment]
Maybe mention the React Native Engineering Manager might help. @obishop

**Comment by Dr-Horv** [comment]
:+1:

**Comment by rt2zz** [comment]
Please consider using https://github.com/magus/react-native-facebook-login - it wraps the SDK and should not be hard to extend with other functionality

**Comment by niftylettuce** [comment]
I agree with @rt2zz -- Android support is in the /android examples folder here <https://github.com/magus/react-native-facebook-login/tree/master/android> works great for me. :boom:

**Comment by pickhardt** [comment]
My understanding is that https://github.com/magus/react-native-facebook-login is just for the login functionality, whereas this repo aims to be the RN way to interact with the FB APIs. For example, this repo should be able to do sharing messages, app invites, etc. I actually tried the other repo out a few months ago, before it had Android support, and it's alright for what it does (login), but it's not really the same. Login is probably the most important feature, but the other features are also important.

**Comment by niftylettuce** [comment]
You could have server side handle API events and send responses, but that
might be overkill

**Comment by obishop** [comment]
cc @frantic who might be working on this

**Comment by frantic** [comment]
We're on it folks, have some internal prototypes and will be pushing them to OSS soon

**Comment by MossP** [comment]
Thanks @obishop, @frantic. We all look forward to it :+1:

**Comment by ericraio** [comment]
+1

**Comment by kanerogers** [comment]
Great to hear, @frantic. :heart:

**Comment by 9mm** [comment]
That's awesome! Do you have a super rough ETA? I'm trying to determine if I should hold off implementing it or go with a short term solution

**Comment by dzhuowen** [comment]
We plan to release it before F8 this year :-).

**Comment by shukerullah** [comment]
+1

**Comment by derese** [comment]
+1

**Comment by pickhardt** [comment]
For those wondering when F8 is, I looked it up and F8 is April 12. My guess is it's a quarterly goal to release it by the end of Q1 (March), so that it's released in time for April 12.

**Comment by caltrain** [comment]
+1

**Comment by iamuros** [comment]
+1

**Comment by crysfel** [comment]
+1

**Comment by Ricky-Nz** [comment]
+1

**Comment by timsmiths** [comment]
+1

**Comment by SlowShip** [comment]
:+1:

**Comment by mingflifb** [comment]
Hi all, we know that everyone wants Android support, and please know that we're working on it, but I don't think keeping this issue open is adding any more value, so I'm going to close it for now.

**Comment by dzhuowen** [comment]
Hey everyone, thanks for your attention to the repro. The Android support is up for grab in release-0.1.0-alpha branch now. Advices and comments are welcome :-D !
