### ISSUE TITLE
Podfile instructions outdated

### ISSUE THREAD

**Issue by davodesign84** [facebook/react-native-fbsdk#35]
When creating a new project, the node_modules directory is not on the folder as the podfile.

This should work:

pod 'React', :subspecs => ['Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket'], :path => '../node_modules/react-native'
	pod 'react-native-fbsdkcore', :path => '../node_modules/react-native-fbsdkcore'
	pod 'react-native-fbsdklogin', :path => '../node_modules/react-native-fbsdklogin'
	pod 'react-native-fbsdkshare', :path => '../node_modules/react-native-fbsdkshare'

**Comment by tnguyen42** [comment]
Another way to make it work is to actually work from the main directory and add a last line (what I did):
```
source 'https://github.com/CocoaPods/Specs.git'
pod 'React', :subspecs => ['Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket'], :path => 'node_modules/react-native'
pod 'react-native-fbsdkcore', :path => 'node_modules/react-native-fbsdkcore'
pod 'react-native-fbsdklogin', :path => 'node_modules/react-native-fbsdklogin'
pod 'react-native-fbsdkshare', :path => 'node_modules/react-native-fbsdkshare'
xcodeproj 'ios/YourAppName.xcodeproj'
```

**Comment by dzhuowen** [comment]
fix in release0.0.6
