### ISSUE TITLE
CocoaPods issues

### ISSUE THREAD

**Issue by tnguyen42** [facebook/react-native-fbsdk#36]
Hi,

I'm new at CocoaPods, and I've just tried setting my project using it. I encountered 2 issues, but I'm not sure they are fbsdk-related:

First one is: Foundation.framework and JavaScriptCore.framework seem to miss...
![image](https://cloud.githubusercontent.com/assets/12211685/9996156/1321d1a4-6086-11e5-8fca-5cb373956507.png)

Second one is: I can't open the file anymore since the original xcodeproj "is already opened from another project or workspace":

![image](https://cloud.githubusercontent.com/assets/12211685/9996217/4a9d1a8a-6086-11e5-8335-f4bc90a65c13.png)

Thank you for your help!

**Comment by kevinzzz007** [comment]
I also see the first image, but my project is working fine, so that's probably not the problem...I haven't encountered the second issue, maybe close all Xcode and restart?

**Comment by dzhuowen** [comment]
Framework in red usually means the actual frameworks are not at the path that the project has for them. But if your project is working fine, no worries.
One project can only be opened by one Xcode at a time. As @kevinzzz007 suggested, just close all Xcode and reopen the project.
