### ISSUE TITLE
Build failed when copying .xcodeproj over

### ISSUE THREAD

**Issue by nlhkh** [facebook/react-native-fbsdk#40]
Per the instruction, for example this one:
> Option: Using the provided Xcode projects

> Download and install the Facebook SDK for iOS into the standard location at ~/Documents/FacebookSDK. Follow the Getting Started guide to link your app's project with the Facebook SDK frameworks and set up the app delegate.

> Add any of the following Xcode projects to your app's Xcode project:

> node_modules/react-native-fbsdkcore/RCTFBSDKCore.xcodeproj
node_modules/react-native-fbsdklogin/RCTFBSDKLogin.xcodeproj
node_modules/react-native-fbsdkshare/RCTFBSDKShare.xcodeproj Follow the Linking Libraries (iOS) guide for each of them to make sure they're added correctly to your project's build targets.

I have installed the Facebook SDK, and configure the `Info.plist` file correctly, and setup the AppDelegate.m like this ![screen shot 2015-10-01 at 12 58 19 pm](https://cloud.githubusercontent.com/assets/3459416/10213825/2db74f7c-683c-11e5-85cd-cf4c0166d7f0.png)

My Build Phase looks like this ![screen shot 2015-10-01 at 12 59 49 pm](https://cloud.githubusercontent.com/assets/3459416/10213841/61f65512-683c-11e5-8410-601a2cf96b7d.png).

And everything works fine, so I know that I setup Facebook SDK correctly.

I then continue with the instruction to copy the `.xcodeproj` folders over, and add their products to the Build Phase of the main project, and Xcode just say `Build Failed` without showing any error.

I removed the products from Build Phase, and everything works again (works as in no error, and I can see my app in simulation).

However, my button looks like this, and it does nothing (no alerts). ![screen shot 2015-10-01 at 1 03 31 pm](https://cloud.githubusercontent.com/assets/3459416/10213898/d7015172-683c-11e5-8ed0-17315f76a483.png)

Do you know what could be wrong?

**Comment by grin** [comment]
I also run into that "Build failed" error at exactly the same stage as @nlhkh. In my case the issue was incorrect __Framework Search Paths__ value in both `RCTFBSDKCore.xcodeproj` and `RCTFBSDKLogin.xcodeproj`. By default it was set to `~/Documents/FacebookSDK` while I downloaded it to a different location. Changing the path solved the issue for me. See the picture below:

![image](https://cloud.githubusercontent.com/assets/12468/10270010/b8154d4e-6ae5-11e5-9a28-145057013b03.png)

**Comment by nlhkh** [comment]
I did update the framework path, but it does not help for me.

I install the FBSDK via cocoapod though.

I also have this extra directory which also has the framework.
![screen shot 2015-10-07 at 9 47 05 pm](https://cloud.githubusercontent.com/assets/3459416/10341008/08b2adec-6d3d-11e5-8d38-addfec53e35f.png)

**Comment by dzhuowen** [comment]
Update README file in release0.0.7
