### ISSUE TITLE
FBSDKShareKit/FBSDKShareKit.h file not found 

### ISSUE THREAD

**Issue by rumbaa01** [facebook/react-native-fbsdk#401]
I have tried all ways:
1.  Download fresh version of Facebook SDK and save a Documents folder
<img width="451" alt="screenshot at nov 01 15-55-14" src="https://user-images.githubusercontent.com/15148689/47856035-db89db80-ddee-11e8-8754-52502edcdbcc.png">
<img width="628" alt="screenshot at nov 01 15-56-23" src="https://user-images.githubusercontent.com/15148689/47856036-db89db80-ddee-11e8-813e-b7aa4db329d6.png">
2. Add FBSDK[Core, Login, Share]Kit.framework from  Documents/Facebook
<img width="841" alt="screenshot at nov 01 15-59-51" src="https://user-images.githubusercontent.com/15148689/47856196-45a28080-ddef-11e8-9e17-5dffc8927e8e.png">
SDK  folder
3. Add path to Framework Search Path
<img width="877" alt="screenshot at nov 01 16-02-09" src="https://user-images.githubusercontent.com/15148689/47856465-fc9efc00-ddef-11e8-9d86-452978aac8f2.png">
4. Also I have tried install via cocopods, and same issue

**Comment by Helga108** [comment]
@rumbaa01 Try doing this in XCode (i have 10): go to RCTFBSDK.xcodeproj then build settings->framework search paths. And change ~/Documents/FacebookSDK to $(HOME)/Documents/FacebookSDK
It saved me a lot of time. Now it finally gets built.

**Comment by ChengHsuanLiu** [comment]
@Helga108 Thank you very much! You save me~

**Comment by fexx** [comment]
It worked for me: 
/Users/{user}/Documents/FacebookSDK

**Comment by mjstelly** [comment]
I've installed the `react-native-fbsdk`. I don't have the folder `FacebookSDK` in my Docs directory. Should some process installed it?

**Comment by fexx** [comment]
@mjstelly, Download the sdk in this link: https://developers.facebook.com/docs/ios/downloads
Then rename to FacebookSDK and move to the Documents folder. worked for me.

**Comment by mjstelly** [comment]
I went the pods route. Hoping that it resolves this issue. Thanks!

Sincerely,
Michael Stelly | M: +1.918.978.2000 Blog | LinkedIn | Github

**Comment by vinhphamh** [comment]
> @rumbaa01 Try doing this in XCode (i have 10): go to RCTFBSDK.xcodeproj then build settings->framework search paths. And change ~/Documents/FacebookSDK to $(HOME)/Documents/FacebookSDK
> It saved me a lot of time. Now it finally gets built.

Thank you.  This worked for me.  I didn't remove the old path.  I just added the new path $(HOME)/Documents/FacebookSDK

**Comment by adilvectorcoder** [comment]
> @rumbaa01 Try doing this in XCode (i have 10): go to RCTFBSDK.xcodeproj then build settings->framework search paths. And change ~/Documents/FacebookSDK to $(HOME)/Documents/FacebookSDK
> It saved me a lot of time. Now it finally gets built.

still not working

**Comment by reyalpsirc** [comment]
@adilvectorcoder did you clean the build folder after you made the change? In my case it was a required step since it tried to use the old build data even after I changed the path

**Comment by vuvantoan95** [comment]
still not working through already clean the build folder @reyalpsirc

**Comment by reyalpsirc** [comment]
@vuvantoan95 Well, to be honest, I changed to `$(HOME)/Documents/FacebookSDK` on both the RCTFBSDK.xcodeproj and my main project. Perhaps you only changed in one place and you have more occurrences of **~/Documents/FacebookSDK** that you need to change?

**Comment by kg-currenxie** [comment]
Using `$(HOME)` works, BUT the setting resets anytime I do a `react-native link`, so it breaks on the next build in XCode. Super annoying! 

Also, how does a relative `~` path differ from an absolute one? And why did it change recently? 
`~` worked perfectly in RN 57 or older, but not in 58 or newer..

**Comment by adilvectorcoder** [comment]
> @adilvectorcoder did you clean the build folder after you made the change? In my case it was a required step since it tried to use the old build data even after I changed the path

Thank you sir now its working :)

**Comment by donghungx** [comment]
@Helga108 how stupid facebook is, thank you so much, i spent a month for this kind of shitty config

**Comment by AdamZaczek** [comment]
This literally breaks every day for us.

**Comment by sbcatania** [comment]
I'm having this issue too. I've tried everything listed here–– I've changed it on the RCTFBSDK.xcodeproj and my main project, I've cleaned the build folder after making the change, I've added the new path alone as well as on top of the old one and nothing works. Please advise!

**Comment by nemanjas1** [comment]
Remember that the order of Framework Search Paths (RTCFBSDK.xcodeproj -> /TARGET and PROJECT/ -> Build Settings is important. I have added my FacebookSDK to new folder (APP)/ios/Frameworks, and am using paths $(PROJECT_DIR)/../../../ios/Frameworks/FacebookSDK to reach it from RTCFBSDK, that is referenced in node_modules.

**Comment by kg-currenxie** [comment]
My workaround! 🛠 

- Open XCode
- Product > Scheme > Edit Schema
- Build > Pre-actions
- Click the little `+` > New Run Script Action

Shell `/bin/sh`
Script: `sed -i '' 's|~/Documents|$(HOME)/Documents|g' ${SRCROOT}/../node_modules/react-native-fbsdk/ios/RCTFBSDK.xcodeproj/project.pbxproj`

![Screenshot 2019-04-14 at 00 52 06](https://user-images.githubusercontent.com/48229166/56082811-e6da3c00-5e4f-11e9-8957-ca98b8b6db23.png)

**Comment by cristianPerez** [comment]
Thanks, everyone, in the end, I solved the issue just dragging and dropping FacebookSDK into the Libraries>RCTFBSDK.xcodeproj  --> on the Build settings searched for Framework Search path

TO AVOID type error is better to drag and drop the complete folder.

RCTFBSDK.xcodeproj
<img width="283" alt="Screen Shot 2019-05-03 at 4 01 39 PM" src="https://user-images.githubusercontent.com/1987909/57165534-03b5bf80-6dbd-11e9-88d0-0ab8af596a92.png">

Global project 
<img width="228" alt="Screen Shot 2019-05-03 at 4 04 22 PM" src="https://user-images.githubusercontent.com/1987909/57165593-3069d700-6dbd-11e9-97cc-7dadb7b49d49.png">

**Comment by optimatex** [comment]
Hi
when this issue will be finally fixed? I have to implement this solution with `$(HOME)/Documents/FacebookSDK` after each `react-native link`

**Comment by reyalpsirc** [comment]
@optimatex You can always fork the repository, change the file on your forked version and import it with npm/yarn

**Comment by optimatex** [comment]
@reyalpsirc great idea, but wait, I need to do this with each library updates, so probably no thanks

**Comment by daniellamarr** [comment]
> @rumbaa01 Try doing this in XCode (i have 10): go to RCTFBSDK.xcodeproj then build settings->framework search paths. And change ~/Documents/FacebookSDK to $(HOME)/Documents/FacebookSDK
> It saved me a lot of time. Now it finally gets built.

@Helga108 Believe me, you are a lifesaver. I have spent hours debugging this.

**Comment by kg-currenxie** [comment]
> > @rumbaa01 Try doing this in XCode (i have 10): go to RCTFBSDK.xcodeproj then build settings->framework search paths. And change ~/Documents/FacebookSDK to $(HOME)/Documents/FacebookSDK
> > It saved me a lot of time. Now it finally gets built.
> 
> @Helga108 Believe me, you are a lifesaver. I have spent hours debugging this.

and

> @reyalpsirc great idea, but wait, I need to do this with each library updates, so probably no thanks


The problem with fixing it manually, is that it will "reset" your change every time you run `yarn` or `react-native link`

Please check my fix above to do it automatically for you :)

**Comment by daniellamarr** [comment]
Thanks @kg-currenxie I’m lucky to have stumbled on this link. I’ve been on this for HOURS. I can at least close one eye when I sleep😅

**Comment by luisaverza** [comment]
> My workaround! 🛠
> 
> _The problem with fixing it manually, is that it will "reset" your change every time you run `yarn` or `react-native link`_
> 
> Using https://www.npmjs.com/package/patch-package will do this automatically for you!
> 
> * Open the file `node_modules/react-native-fbsdk/ios/RCTFBSDK.xcodeproj/project.pbxproj` in your editor
> * Replace `~/Document` with `$(HOME)/Documents`. There should be 2 places in this file.
> * `yarn add patch-package postinstall-postinstall -d`
> * `npx patch-package react-native-fbsdk`
> * Add this to `package.json`
> 
> ```
>  "scripts": {
> +  "postinstall": "patch-package"
>  }
> ```
> 
> Done :) Never fix it manually from now on!

It worked for me, I just had to change the order because `yarn add patch-package postinstall-postinstall -d` overwritten the changes inside `node_modules/react-native-fbsdk...`

**Comment by ssuchanowski** [comment]
I have a different workaround as I don't like the idea that those frameworks would not end up in repo and new person would have to redownload them - stupid.

This is `Framework Search Paths` of the `RCTFBSDK` Project
![Screenshot 2019-05-29 at 14 53 03](https://user-images.githubusercontent.com/1038270/58558571-7a5da580-8221-11e9-8794-d8e96fcb5375.png)

So you can utilise one of last two directories and put there framework files and viola.

**Comment by madandrija** [comment]
> I have a different workaround as I don't like the idea that those frameworks would not end up in repo and new person would have to redownload them - stupid.
> 
> This is `Framework Search Paths` of the `RCTFBSDK` Project
> ![Screenshot 2019-05-29 at 14 53 03](https://user-images.githubusercontent.com/1038270/58558571-7a5da580-8221-11e9-8794-d8e96fcb5375.png)
> 
> So you can utilise one of last two directories and put there framework files and viola.

Agreed, I had the same problem, and while Importing the Framework files, I thought they were being imported to `$(PROJECT_DIR)/../../../ios/Frameworks`; they are instead imported to `$(PROJECT_DIR)/../../../ios`, so the simplest way is what you propose, import the files to the `Frameworks` subfolder

**Comment by umar0107** [comment]
> @rumbaa01 Try doing this in XCode (i have 10): go to RCTFBSDK.xcodeproj then build settings->framework search paths. And change ~/Documents/FacebookSDK to $(HOME)/Documents/FacebookSDK
> It saved me a lot of time. Now it finally gets built.

thank you so much you save my time.
