### ISSUE TITLE
LoginButton text is truncated or missing on Android

### ISSUE THREAD

**Issue by ntwigs** [facebook/react-native-fbsdk#402]
## Expected:
![screen shot 2018-11-02 at 09 56 37](https://user-images.githubusercontent.com/14088342/47904643-ac727900-de85-11e8-9041-c791180259fb.png)

## Actual:
![screen shot 2018-11-02 at 09 58 15](https://user-images.githubusercontent.com/14088342/47904785-daf05400-de85-11e8-931f-0b8710e8f525.png)

## Details:
It works fine on iOS - but does not show any text at all on Android. If I open it on my physical android phone, it shows the first letter `C` shoved halfway into the Facebook logo. If I push the android back button (which closes the app), and then go back into the app it says `Continue with Facebook` and the button now works.

## Versions:
`"react-native-fbsdk": "^0.8.0"`
`"react": "16.5.0"`
`"react-native": "0.57.0"`

**Comment by gmertk** [comment]
Closing this as it is working fine now in the latest version.
