### ISSUE TITLE
[Question]Can install FacebookSDK from CocoaPod ?

### ISSUE THREAD

**Issue by Winglonelion** [facebook/react-native-fbsdk#405]
i try to install FacebookSDK from pod but it can not build success. Any one sucess with this  ?

I will update this issues more clarify late. thanks

**Comment by hramos** [comment]
Hey, it looks like this issue is more of a general question on use. We'd like to keep this issue tracker focused on specific issues that can be addressed with a pull request. I'm going to close this for now, but feel free to open a new issue once you have more details.

**Comment by Winglonelion** [comment]
Hi there, sorry for late feedback.

For every ones who have same question: 

The answer is: `react-native-fbsdk` compatable and work fine with dbsdk install from cocoapod without any modify in modules.

I have a small conversation with @kortirso about this here: https://github.com/facebook/react-native-fbsdk/pull/418

And in my case, just simple to add header path for this 
```
${SRCROOT}/Pods/FBSDKCoreKit/FBSDKCoreKit
${SRCROOT}/Pods/FBSDKLoginKit/FBSDKLoginKit
${SRCROOT}/Pods/FBSDKShareKit/FBSDKShareKit
```

hope it will useful for all of you.
