### ISSUE TITLE
Cannot build with Facebook 4.38.0 and Marketing Kit

### ISSUE THREAD

**Issue by grahamyesfit** [facebook/react-native-fbsdk#406]
I'd like to take advantage of the new Marketing Kit features (e.g. codeless App events). I changed the pod entries described in the SDK section to the following:
```
    pod 'FacebookSDK/LoginKit'
    pod 'FacebookSDK/ShareKit'
```
This works great and everything builds and links as expected, and Facebook SDK 4.38.0 is correctly linked. However, when I add this:
```
   pod 'FacebookSDK/MarketingKit'
```
I receive the following error when I run the project in xCode:
```
  Framework not found FBSDKCoreKit for architecture x86_64_
```
I've deleted my node_modules folder and done a full npm install, I've cleared my watchman cache, I've tried everything, it just won't link.

Here is some more information:
```
  react-native: 0.57.4
  react-native-fbsdk: 0.8.0
```
In addition, sharing an image using the "file://" protocol has broken in the last couple of Facebook SDK versions. It used to work (I'm unsure of the exact version number where it stopped working). It still works for Android, but with iOS, after upgrading to SDK 4.38.0 and FBSDK 0.8.0, I receive an error when calling ShareDialog with a file reference for the photo. Here is the data I am sending in:
```
 var content = {
	contentType: 'photo',
	photos: [{
		imageUrl: 'file:///[path to temporary image]',
		userGenerated: false,
		caption: 'Caption text'
	}]
}
```
And I pass that data as follows:
```
ShareDialog.show(content)
```
Note that ShareDialog.canShow(content) returns true, but the share call throws an exception. The same code works on Android.

**Comment by Winglonelion** [comment]
i met same issues with you when build Project

my `Podfile`:

```
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
```

but not use `use_frameworks!`

I think it had some problems with framework search path

**Comment by grahamyesfit** [comment]
I found [this page](https://developers.facebook.com/docs/app-events/codeless-app-events) which states that if you're using SDK v4.38.0, the Marketing Kit is automatically included. So it looks like I'm good there.

As far as my second issue is concerned, I changed my iOS code to use the base64 of the image instead of a file reference, and it works perfectly.
