### ISSUE TITLE
node_modules/react-native-fbsdk/ios/RCTFBSDK/share/RCTFBSDKShareDialog.h:19:9: 'React/RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by lightninglu10** [facebook/react-native-fbsdk#414]
Hey guys, trying to build my app from a detached expo app with ExpoKit but getting this error on Facebook's SDK:

```node_modules/react-native-fbsdk/ios/RCTFBSDK/share/RCTFBSDKShareDialog.h:19:9: 'React/RCTBridgeModule.h' file not found```

Anyone know what's going on here?

Followed the instructions to get fbsdk through cocoapods:

pod 'FacebookSDK' then pod install as well as putting all the right info in Info.plist and AppDelegate.m.

Not even sure what this error is.

**Comment by L-Yeiser** [comment]
Are you using xCode ten? If so, in xCode select `RCTFBSDK.xcodeproj` from your projects `Libraries` folder. In `Builds Settings` search from `FrameworkSearchPaths` and add `$(HOME)/Documents/FacebookSDK`. Changes introduced with xCode ten break the suggested search path.

![screen shot 2018-11-13 at 11 36 06 am](https://user-images.githubusercontent.com/6750498/48438351-abb8cd00-e738-11e8-995a-47f67c6cd734.png)

**Comment by L-Yeiser** [comment]
https://github.com/facebook/react-native-fbsdk/pull/417
