### ISSUE TITLE
Android ShareDialog - postId is always null

### ISSUE THREAD

**Issue by cuilongzhe** [facebook/react-native-fbsdk#415]
## Environment
React Native: 0.47.0
Facebook SDK: 4.38.1
Platform: Android
react-native-fbsdk: 0.8.0

## Description
Android ShareDialog always returns postId = null

## Reproducible Demo
https://github.com/facebook/react-native-fbsdk/blob/master/sample/HelloFacebook is a good one to reproduce this issue.
Importantly, it seems that the author of this app is already aware of that Android SDK doesn't return postId, coz he didn't include postId when alerting the success result. (@dzhuowen @lepouya)
https://github.com/facebook/react-native-fbsdk/blob/master/sample/HelloFacebook/index.android.js#L62
Note that the only difference between iOS and Android sample code is this postId part.
https://github.com/facebook/react-native-fbsdk/blob/master/sample/HelloFacebook/index.ios.js#L62
However, I can't find any discussions about postId being null in this repo.

According to this discussion, I even tried to set ShareDialog's mode to 'feed', but no luck.
https://stackoverflow.com/questions/32470850/post-id-facebook-share-dialog-always-return-null-in-android?rq=1
https://stackoverflow.com/questions/31881861/facebook-share-dialog-postid-is-null

So, can you provide more info about what's the latest update about postId being null?

**Comment by cuilongzhe** [comment]
@dzhuowen @lepouya any update?

**Comment by mateyFromTheBlock** [comment]
I'm also facing the same issue. any solution?

**Comment by mrtaiw** [comment]
Same issue, any solution?

**Comment by gmertk** [comment]
Closing this as postId isn't supposed to be returned. This is by-design.

**Comment by thienlq** [comment]
Hello, sorry I have a question about this. 
If share dialog can't get result.postId, so how about share via ShareApi with publish_actions permission? can I get postId? actually I need postId but no way now?
