### ISSUE TITLE
Incorrect installation

### ISSUE THREAD

**Issue by kortirso** [facebook/react-native-fbsdk#416]
## Environment

react: 16.6.1 => 16.6.1 
react-native: 0.57.4 => 0.57.4 

## Description

I checked documentation here https://developers.facebook.com/docs/ios/getting-started/ and they said install sdk by cocoapods, so no more copy anything.

But in your documentation said:
Along with FBSDKCoreKit.framework, don't forget to import FBSDKShareKit.framework and FBSDKLoginKit.framework into your Xcode project.

What is the correct way of installation?

**Comment by kortirso** [comment]
It works awasome! Thank you

**Comment by dedan** [comment]
Thanks a lot for your extensive write-up.

> I then tweaked later Libraries->RCTFBSDK.xcodeproj settings, namely Framework Search Path which points to ~/Documents/FacebookSDK (not really sure why?).

How exactly did you tweak these settings? It's still not working for me

**Comment by zavadpe** [comment]
@dedan I just added correct paths to downloaded FacebookSDK library. I can look up how exactly if you still need it.

**Comment by dengue8830** [comment]
the official docs worked for me

https://developers.facebook.com/docs/facebook-login/ios

**Comment by kevinobruno** [comment]
I'm still getting the error `'FBSDKCoreKit/FBSDKAppEvents.h' file not found` even after adding everything to `Podfile`, `Libraries` and `Link Binary With Libraries`. Anyone has any idea how to resolve?

**Comment by ital0** [comment]
> I'm still getting the error `'FBSDKCoreKit/FBSDKAppEvents.h' file not found` even after adding everything to `Podfile`, `Libraries` and `Link Binary With Libraries`. Anyone has any idea how to resolve?

same problem here.

**Comment by ital0** [comment]
Just to let you guys know, downgrading FBSDKCoreKit, FBSDKLoginKit and FBSDKShareKit to version 4.40.0 (instead of 4.42.0) works.

**Comment by anwargul0x** [comment]
@ital0  can you please write the steps you perform to downgrade .... as i did specify the version in podfile explicitly and then run pod install ...but still the issue persist

**Comment by ital0** [comment]
@anwargul0x just pointed the version in the Podfile:

```
pod 'FBSDKCoreKit', '~> 4.40.0'
pod 'FBSDKLoginKit', '~> 4.40.0'
pod 'FBSDKShareKit', '~> 4.40.0'
```

**Comment by anwargul0x** [comment]
@ital0 thanks... I exactly did this early ...but it didn't work for me I guess I will have reinstall all pod dependencies

**Comment by anwargul0x** [comment]
@ital0 .... i solved this issue by deleting node_modules and podfiles and pod folder.
then ran 
`npm install`
`cd ios`
`pod init`

specified  fbsdk in podfile as
`pod 'FBSDKCoreKit', '~> 4.40.0'`
`pod 'FBSDKLoginKit', '~> 4.40.0'`
`pod 'FBSDKShareKit', '~> 4.40.0'`

then finally
 
`pod install'

**Comment by biomancer** [comment]
By the way instead of manually linking xcodeproj and adding libRCTFBSDK.a, you can rename or delete `node_modules/react-native-fbsdk/react-native-fbsdk.podspec`and then run 
`react-native link react-native-fbsdk`, the same way it's suggested here https://github.com/react-native-community/react-native-google-signin/blob/master/docs/ios-guide.md

**Comment by eraycetiner** [comment]
I'm trying to upgrade to the latest version of the library (0.10.1). Unfortunately, I am getting `'FBSDKCoreKit/FBSDKAppEvents.h' file not found` error when I try to manually link the library as @zavadpe suggests. I removed react-native-fbsdk line from Podfile and manually dragged xcodeproj file from node_modules/react-native-fbsdk. I also added libRCTFBSDK.a to Link Binary With Libraries. My Podfile is as:

```
  pod 'FBSDKCoreKit', '5.1.1'
  pod 'FBSDKLoginKit', '5.1.1'
  pod 'FBSDKShareKit', '5.1.1'
```

I am using React Native v0.59.8 and I tried all 5.0.0, 5.0.1, 5.0.2, 5.1.0 and 5.1.1 versions of FBSDK libraries.
 
As an alternative, I tried to link the library via CocoaPods as below. This time it builds fine, but I am getting `null is not an object (evaluating 'AppEventsLogger.setUserID')` JavaScript error.

```
  rn_path = '../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
```

**Comment by scaralfred** [comment]
@eraycetiner I'm getting the same issue... 'FBSDKCoreKit/FBSDKAppEvents.h' file not found.
Did you find any solution?here is my snippet of podfile

pod 'FacebookSDK'
pod 'FBSDKShareKit', '~> 5.0'
pod 'FBSDKCoreKit', '~> 5.0'
pod 'FBSDKLoginKit', '~> 5.0'

**Comment by ErayCetinerGelato** [comment]
@scaralfred Removing `use_frameworks!` from Podfile helped me.

**Comment by leotm** [comment]
> @scaralfred Removing `use_frameworks!` from Podfile helped me.

Exactly you'll want `use_native_modules!` instead because _react-native-fbsdk_'s implemented in Objective-C (not Swift).
