### ISSUE TITLE
Can not change fb account after login

### ISSUE THREAD

**Issue by denis-shostik** [facebook/react-native-fbsdk#422]
Environment
React Native: 0.55.4
Facebook SDK: 4.38.1
Platform: IOS
react-native-fbsdk: 0.8.0

Description
Can't change fb account after login

Reproducible Demo
- login to facebook
- logout
- login again and you will see your previous account which you can't change

![default](https://user-images.githubusercontent.com/36534894/48934598-5e451880-ef0d-11e8-9e89-b576a429ed09.png)

**Comment by denis-shostik** [comment]
LoginManager.setLoginBehavior('web');

**Comment by danielmartinprieto** [comment]
This solution no longer works. Is there any alternative?
