### ISSUE TITLE
The Key Hash Does not match any store key hashes.

### ISSUE THREAD

**Issue by i-suraj007** [facebook/react-native-fbsdk#424]
![screenshot_20181124-144834](https://user-images.githubusercontent.com/24787428/48966566-28ca2900-effa-11e8-840e-961e38e355a5.png)
I tried to generate hash by using 
`>keytool -exportcert -alias payoja -keystore "C:\Users\Epsum Labs\Desktop\PAYOJA\android\app\payoja.keystore" | "C:\Users\Epsum Labs\Desktop\openssl\bin\openssl" sha1 -binary | "C:\Users\Epsum Labs\Desktop\openssl\bin\openssl" base64`

I am unable to login neither in debug nor in release mode.

**Comment by mushinz** [comment]
I have the same problem, without the app installed, it works, when the facebook app is installed, I get the invalid key hash, however, the hash that gives on the error, is on facebook app.

Help plz

**Comment by sergiulucaci** [comment]
Make sure you get the hash of the signed key used for generated APK. 

MacOS: 

```
keytool -exportcert -alias <RELEASE_KEY_ALIAS> -keystore <RELEASE_KEY_PATH> | openssl sha1 -binary | openssl base64
```

Real example, assuming that keystore is placed under android/app:

```
keytool -exportcert -alias my-key-alias -keystore android/app/my-release-key.keystore | openssl sha1 -binary | openssl base64
```

This will generate a hash key that must be placed into app's profile:

1. Go to https://developers.facebook.com/apps/YOUR_APP_ID/settings/basic/
2. Scroll down to Android Key Hashes
3. Place the key there

[Source](https://developers.facebook.com/docs/android/getting-started/#release-key-hash)

**Comment by suraj-epsumlabs** [comment]
any solution for this???

**Comment by duarte-evocorp** [comment]
I have the same problem

**Comment by CapitanRedBeard** [comment]
For me it was redirecting to the FB app and it was displaying a hash that I never generated. I copied that hash into the FB console and it seemed to work after that. Not quite sure why.

**Comment by Ovi** [comment]
This worked for me.

Copy the APK to your PC in Program Files\java\jdkX.X.X_XXX\bin folder

In my case it's C:\Program Files\Java\jdk1.8.0_191\bin

Open CMD in this directory and type the following

`keytool -list -printcert -jarfile YOUR_APK_NAME.apk`

Copy the SHA1 value to your clipboard It will be something like this: `79:D0:E6:80:4E:28:1E:D1:88:28:CB:D7:E6:BE:2E:0C:FB:24:98:52`

Then go to http://tomeko.net/online_tools/hex_to_base64.php to convert your SHA1 value to base64.

This is what Facebook requires get the generated hash " ********************= " and copy the key hash to your Facebook developers app settings.

**Comment by nuclearWinters** [comment]
I used the openssl version "e" in windows, the others generate false hashes

**Comment by masierraf** [comment]
Anyone has any solution?

**Comment by ramanaputra1** [comment]
- I've been **solved** this issue using java/kotlin code here

```
fun createKeyHash(activity: Activity, yourPackage: String) {
        try {
            val info = activity.packageManager.getPackageInfo(yourPackage, PackageManager.GET_SIGNATURES)
            for (signature in info.signatures) {
                val md = MessageDigest.getInstance("SHA")
                md.update(signature.toByteArray())
                Log.d("KeyHash:", Base64.encodeToString(md.digest(), Base64.DEFAULT))
            }
        } catch (e: PackageManager.NameNotFoundException) {
            e.printStackTrace()
        } catch (e: NoSuchAlgorithmException) {
            e.printStackTrace()
        }

    }
```

and call your function like this

`createKeyHash(this, "com.ramana.myapp")`

> **_Note: "com.ramana.myapp" it is my package and to see your keyhash please type search the debug message 'KeyHash'._**

**Comment by UzairAhmedSiddiqui** [comment]
Solved this for myself, I carefully added the correct hash of my release key but my app keep complaining about key hash does not match any store key hashes and showed a hash which was different from my release key hash. 
After going nuts over where this new hash comes from I finally figured out that google play probably also signs the apk when you upload it. so after publishing if you go to google play console you will see find versions of the apk, one signed by your release key and another derived apk probably signed by google.

You have to download the derived apk and get the SHA1 hash using
`keytool -list -printcert -jarfile YOUR_APK.apk`
the output will be in Hex so you'll have to convert it into base64, and it will be the same hash that the app complains about after being published to store. 

I don't know why this isn't mentioned in facebook dev console and their docs.

**Comment by tuononh** [comment]
Check if your "App Signing by Google Play" is enabled. Then copy SHA1 from there and go to http://tomeko.net/online_tools/hex_to_base64.php to get the key hash.

**Comment by jagmel** [comment]
Recently found this <a href="https://play.google.com/store/apps/details?id=com.hasher">Hasher App</a> which helps in extracting keyhash from sha1 (from google play store console) and vice-versa

**Comment by Seerat-Ahmed** [comment]
> Solved this for myself, I carefully added the correct hash of my release key but my app keep complaining about key hash does not match any store key hashes and showed a hash which was different from my release key hash.
> After going nuts over where this new hash comes from I finally figured out that google play probably also signs the apk when you upload it. so after publishing if you go to google play console you will see find versions of the apk, one signed by your release key and another derived apk probably signed by google.
> 
> You have to download the derived apk and get the SHA1 hash using
> `keytool -list -printcert -jarfile YOUR_APK.apk`
> the output will be in Hex so you'll have to convert it into base64, and it will be the same hash that the app complains about after being published to store.
> 
> I don't know why this isn't mentioned in facebook dev console and their docs.

This solved my problem :)

**Comment by MayarAhmed** [comment]
@UzairAhmedSiddiqui unfortunately i followed these steps but didn't work with me 

Did you figure any other solution??

**Comment by UzairAhmedSiddiqui** [comment]
> @UzairAhmedSiddiqui unfortunately i followed these steps but didn't work with me
> 
> Did you figure any other solution??

@MayarAhmed I'm afraid not, but if the error is the same then it should work, the problem simply is that the hash of the signed apk and the one set on facebook dev console do not match.
If you're also signing the apk yourself then you can try [disabling app signing by google play](https://stackoverflow.com/questions/44180930/how-to-disable-app-signing-from-google-play-console) and use the hash of your own certificate.

**Comment by MayarAhmed** [comment]
this two steps solved it for me 

 Copy the File debug.keystore from .android folder in my case (C:\Users\SYSTEM.android) and paste into JDK bin Folder in my case (C:\Program Files\Java\jdk1.6.0_05\bin)

and then excute cmd

keytool -exportcert -alias androiddebugkey -keystore %HOMEPATH%\.android\debug.keystore | openssl sha1 -binary | openssl base64

which gives me the same hash code in the error and then it solved

**Comment by BDominik** [comment]
> 
> 
> This worked for me.
> 
> Copy the APK to your PC in Program Files\java\jdkX.X.X_XXX\bin folder
> 
> In my case it's C:\Program Files\Java\jdk1.8.0_191\bin
> 
> Open CMD in this directory and type the following
> 
> `keytool -list -printcert -jarfile YOUR_APK_NAME.apk`
> 
> Copy the SHA1 value to your clipboard It will be something like this: `79:D0:E6:80:4E:28:1E:D1:88:28:CB:D7:E6:BE:2E:0C:FB:24:98:52`
> 
> Then go to http://tomeko.net/online_tools/hex_to_base64.php to convert your SHA1 value to base64.
> 
> This is what Facebook requires get the generated hash " ********************= " and copy the key hash to your Facebook developers app settings.

Thank you this is helped me.

**Comment by milkmanjr** [comment]
This fixed it for me

https://github.com/expo/expo/issues/2079

**Comment by nguyen95** [comment]
We can get hash from Android studio:

**Comment by ChinGyi2019** [comment]
https://github.com/facebook/react-native-fbsdk/issues/424#issuecomment-469047955
here is the answer above Explain!! thanks

**Comment by amitbravo** [comment]
> This worked for me.
> 
> Copy the APK to your PC in Program Files\java\jdkX.X.X_XXX\bin folder
> 
> In my case it's C:\Program Files\Java\jdk1.8.0_191\bin
> 
> Open CMD in this directory and type the following
> 
> `keytool -list -printcert -jarfile YOUR_APK_NAME.apk`
> 
> Copy the SHA1 value to your clipboard It will be something like this: `79:D0:E6:80:4E:28:1E:D1:88:28:CB:D7:E6:BE:2E:0C:FB:24:98:52`
> 
> Then go to http://tomeko.net/online_tools/hex_to_base64.php to convert your SHA1 value to base64.
> 
> This is what Facebook requires get the generated hash " ********************= " and copy the key hash to your Facebook developers app settings.

what possible location can be for OSX ?

**Comment by MarwinNortington** [comment]
> This worked for me.
> 
> Copy the APK to your PC in Program Files\java\jdkX.X.X_XXX\bin folder
> 
> In my case it's C:\Program Files\Java\jdk1.8.0_191\bin
> 
> Open CMD in this directory and type the following
> 
> `keytool -list -printcert -jarfile YOUR_APK_NAME.apk`
> 
> Copy the SHA1 value to your clipboard It will be something like this: `79:D0:E6:80:4E:28:1E:D1:88:28:CB:D7:E6:BE:2E:0C:FB:24:98:52`
> 
> Then go to http://tomeko.net/online_tools/hex_to_base64.php to convert your SHA1 value to base64.
> 
> This is what Facebook requires get the generated hash " ********************= " and copy the key hash to your Facebook developers app settings.

I met the same issue while I did generate a SHA1 key before. I solved it now thanks to the link you provide. Thank you very much !

**Comment by trOnk12** [comment]
Somehow when I am running it in windows powershell the generated code has wrong format but when I run it in cmd the format is valid.

**Comment by ghasemikasra39** [comment]
any solution ?

**Comment by Hansel03** [comment]
> We can get hash from Android studio: CLick Gradle --> double clicks signingReport --> get SHA1 --> convert to hash
> ![image](https://user-images.githubusercontent.com/36287542/70768136-7d238080-1d96-11ea-97cb-9a4c6b4ecc8e.png)



> This worked for me.
> 
> Copy the SHA1 value to your clipboard It will be something like this: `79:D0:E6:80:4E:28:1E:D1:88:28:CB:D7:E6:BE:2E:0C:FB:24:98:52`
> 
> Then go to http://tomeko.net/online_tools/hex_to_base64.php to convert your SHA1 value to base64.
> 
> This is what Facebook requires get the generated hash " ********************= " and copy the key hash to your Facebook developers app settings.

**Comment by PirunSeng** [comment]
Hi there, same issue here. But first, I wonder why the complaint invalid key hash is different from the one I have. And second, where I can get the apk file? During development, is it required that we need to register the app with Google Play?

**Comment by SaravananRath** [comment]
> This worked for me.
> 
> Copy the APK to your PC in Program Files\java\jdkX.X.X_XXX\bin folder
> 
> In my case it's C:\Program Files\Java\jdk1.8.0_191\bin
> 
> Open CMD in this directory and type the following
> 
> `keytool -list -printcert -jarfile YOUR_APK_NAME.apk`
> 
> Copy the SHA1 value to your clipboard It will be something like this: `79:D0:E6:80:4E:28:1E:D1:88:28:CB:D7:E6:BE:2E:0C:FB:24:98:52`
> 
> Then go to http://tomeko.net/online_tools/hex_to_base64.php to convert your SHA1 value to base64.
> 
> This is what Facebook requires get the generated hash " ********************= " and copy the key hash to your Facebook developers app settings.

Use the above method to generate the key.
After spending couple of hours on this. I found out.
No point of adding keyhash here(as per documentation) - https://developers.facebook.com/settings/developer/sample-app/

Add the Key Hash Here - https://developers.facebook.com/docs/facebook-login/android/v2.2
1) Select your app name
6) Add keyhash in step 6.

**Comment by PirunSeng** [comment]
> 
> 
> Hi there, same issue here. But first, I wonder why the complaint invalid key hash is different from the one I have. And second, where I can get the apk file? During development, is it required that we need to register the app with Google Play?
> PS: I am using Windows OS.

Just solved my issue by pointing to debug keystore in the project itself "PATH_TO_YOUR_PROJECT/android/app/debug.keystore"

**Comment by brianasu-notdoppler** [comment]
If you use Google's new android upload key method then your apk gets re-signed after it uploads. The keystore you use to upload is not the actual keystore google signs it with.

You have to go into your Google play release page and download the resigned apk before doing the above steps by OVI. They called it derived APK.

**Comment by parnekov** [comment]
> > We can get hash from Android studio: CLick Gradle --> double clicks signingReport --> get SHA1 --> convert to hash
> > ![image](https://user-images.githubusercontent.com/36287542/70768136-7d238080-1d96-11ea-97cb-9a4c6b4ecc8e.png)
> 
> > This worked for me.
> > Copy the SHA1 value to your clipboard It will be something like this: `79:D0:E6:80:4E:28:1E:D1:88:28:CB:D7:E6:BE:2E:0C:FB:24:98:52`
> > Then go to http://tomeko.net/online_tools/hex_to_base64.php to convert your SHA1 value to base64.
> > This is what Facebook requires get the generated hash " ********************= " and copy the key hash to your Facebook developers app settings.

**This works on Mac**. Thank you!!!

**Comment by Blossom-Solutions** [comment]
> > Hi there, same issue here. But first, I wonder why the complaint invalid key hash is different from the one I have. And second, where I can get the apk file? During development, is it required that we need to register the app with Google Play?
> > PS: I am using Windows OS.
> 
> Just solved my issue by pointing to debug keystore in the project itself "PATH_TO_YOUR_PROJECT/android/app/debug.keystore"

You are a saviour mate, this worked for me. Kudos!

**Comment by douglassilvaa** [comment]
> > Olá, mesmo problema aqui. Mas primeiro, eu me pergunto por que o hash da chave inválida da reclamação é diferente do que eu tenho. E em segundo lugar, onde posso obter o arquivo apk? Durante o desenvolvimento, é necessário registrar o aplicativo no Google Play? 
> > PS: Estou usando o sistema operacional Windows.
> 
> Acabei de resolver meu problema apontando para debug keystore no próprio projeto "PATH_TO_YOUR_PROJECT / android / app / debug.keystore"

eu quero te agradecer mil milhões <3
