### ISSUE TITLE
undefined is not an object(evluting 'LoginManager.loginWithReadPermissions')

### ISSUE THREAD

**Issue by xeastcrast** [facebook/react-native-fbsdk#426]
## Environment

Run `react-native info` in your terminal and paste its contents here.
```React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
      Memory: 32.22 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.11.0 - /usr/local/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 24.0.1, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
        API Levels: 23, 24, 25, 26, 27
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5014246
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.5.1 => 16.5.1
      react-native: 0.57.1 => 0.57.1
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
```
## Description

Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.
<img width="309" alt="screen shot 2561-11-27 at 01 43 14" src="https://user-images.githubusercontent.com/12433101/49034916-d64d6000-f1e5-11e8-8cac-ba5c77bd5d01.png">

I install by cocoapod

## Reproducible Demo
1. rm -rf nodd_modules
2.react-native unlink react-native-fbsdk
3.check every installation step
4.make them again
5.don't work every solution that I can found on the internet and other place

I stuck this issue about 1 month

Let us know how to reproduce the issue. Include a code sample, share a project, or share an app that reproduces the issue using https://snack.expo.io/.
Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by imadarif** [comment]
same issue is there any solution ?

**Comment by bogdanustyak** [comment]
Getting same error.

**Comment by xeastcrast** [comment]
@imadarif @bogdanustyak I can solved it now
add this line in Podfile
```
 pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
```

**Comment by chromonav** [comment]
@hasgarAOT where do you find libRCTFBLogin.a ?

**Comment by hasgarAOT** [comment]
@chromonav  sorry its libRCTFBSDK.a
