### ISSUE TITLE
Document "Framwork Search Paths" setting

### ISSUE THREAD

**Issue by alfonsodev** [facebook/react-native-fbsdk#43]
By default "Build Settings -> Search Paths -> Framework Search Paths" setting is set to $(inherited)$(PROJECT_DIR)
The [ Getting started page ](https://developers.facebook.com/docs/ios/getting-started), guides you on how to add the framework, in step 4 but the AppDelegate.m gives an error in the line 
`#import <FBSDKCoreKit/FBSDKCoreKit.h>`
It can be fixed by setting Framework Search Paths correctly , I thinnk it should be mentioned in Step 4 of Getting Started guide, but also in the Readme, maybe for people with a background in XCode is obvious, but for beginners makes instructions imposible to follow.

I didn't pull request myself , because I'm not sure if the Framework Search Path should point to $(PROJECT_DIR)/Frameworks or to ~/Documents/FacebookSDK
the instructions.  

Tested with react-native (0.11.4).

**Comment by alfonsodev** [comment]
\ok , I read it's in Troubleshooting section of the main Readme, I was following react-native-fbsdkcore/Readme.md  
Maybe should be included in that readme too or general getting started guide.

**Comment by jadsonlourenco** [comment]
I agree, this is necessary, I lost a few hours trying to figure out where I was missing until I discovered this detail. Almost of developers that are begin with RN are inexperienced with Xcode (iOS development), and Some details, like this, helps.

I hope that some developer add this in the installation instructions without Cocoapods, I think.

**Comment by antigirl** [comment]
:+1:

**Comment by dzhuowen** [comment]
Thanks for the advice! The getting started doc has been updated with the framework search path instruction.
