### ISSUE TITLE
Could not resolve project :react-native-fbsdk.

### ISSUE THREAD

**Issue by flolege** [facebook/react-native-fbsdk#436]
Following the guide exactly, but when I do a gradly Sync in Android Studio, I get 
Could not resolve project :react-native-fbsdk.

**Comment by Prashant-Mutnale** [comment]
> Following the guide exactly, but when I do a gradly Sync in Android Studio, I get
> Could not resolve project :react-native-fbsdk.

Try building using react-native run-android command

**Comment by VeirryAu** [comment]
How to solve it ?

**Comment by apjinfosolution** [comment]
> How to solve it ?

Did you get solution for this?
