### ISSUE TITLE
HttpMethod DELETE not work

### ISSUE THREAD

**Issue by jeongsd** [facebook/react-native-fbsdk#448]
## Environment
```
 React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (4) x64 Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz
      Memory: 76.47 MB / 16.00 GB
      Shell: 5.3 - /bin/zsh
    Binaries:
      Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.1/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: ^16.6.1 => 16.6.1
      react-native: ^0.57.5 => 0.57.5
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      react-native-app-id-fixed: 0.2.1
      react-native-app-id: 0.0.5
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-rename: 2.4.0
      svg-to-react-native-cli: 0.0.3
```

## Description
Revoking Login on react-native-fbsdk `GraphRequest` not work 
I expect response with `success: true` but  it response with data

#### Expect response
```json
{
  "success": true
}
```
#### Actual response
```json
{
  "data": [
    {
      "status": "granted",
      "permission": "email"
    },
    {
      "status": "granted",
      "permission": "public_profile"
    }
  ]
}
```

- https://developers.facebook.com/docs/facebook-login/permissions/requesting-and-revoking/

## Reproducible Demo
```js
import {
  GraphRequest,
  GraphRequestManager,
} from 'react-native-fbsdk'

const infoRequest = new GraphRequest(
  '/me/permissions',
  {
    HttpMethod: 'DELETE',
  },
  (error, graphqlRes) => {
    console.log(graphqlRes) // 
  },
)
new GraphRequestManager()
  .addRequest(infoRequest)
  .start()
```

**Comment by jeongsd** [comment]
Use fetch it work for me
```js
import queryString from 'query-string'
import { AccessToken } from 'react-native-fbsdk'
const data = await AccessToken.getCurrentAccessToken()
const query = queryString.stringify({
  access_token: data.accessToken.toString(),
})

fetch(`https://graph.facebook.com/v3.2/me/permissions?${query}`, {
  method: 'post',
  headers: {
    Accept: 'application/json',
    'Content-Type': 'application/json',
  },
  body: JSON.stringify({
    method: 'delete',
    format: 'json',
  }),
})
  .then(response => console.log(response)) \\ { "success": true }
  .catch(err => console.log(err))
```

**Comment by srvkataria** [comment]
You need to **revoke the app permission** on Logout (Before LoginManager.logOut()..)

To revoke the APP permission, you need to send a **GraphRequest** with **accessToken**. Here's how to do it:

```
customFacebookLogout = () => {
    var current_access_token = '';
    AccessToken.getCurrentAccessToken().then((data) => {
      current_access_token = data.accessToken.toString();
    }).then(() => {
      let logout =
      new GraphRequest(
        "me/permissions/",
        {
            accessToken: current_access_token,
            httpMethod: 'DELETE'
        },
        (error, result) => {
            if (error) {
                console.log('Error fetching data: ' + error.toString());
            } else {
                LoginManager.logOut();
            }
        });
      new GraphRequestManager().addRequest(logout).start();
    })
    .catch(error => {
      console.log(error)
    });      
  }
```

**Comment by jeongsd** [comment]
@srvkataria Thank you for reply and it helpful

**Comment by Gustavomagalhaes** [comment]
> You need to **revoke the app permission** on Logout (Before LoginManager.logOut()..)
> 
> To revoke the APP permission, you need to send a **GraphRequest** with **accessToken**. Here's how to do it:
> 
> ```
> customFacebookLogout = () => {
>     var current_access_token = '';
>     AccessToken.getCurrentAccessToken().then((data) => {
>       current_access_token = data.accessToken.toString();
>     }).then(() => {
>       let logout =
>       new GraphRequest(
>         "me/permissions/",
>         {
>             accessToken: current_access_token,
>             httpMethod: 'DELETE'
>         },
>         (error, result) => {
>             if (error) {
>                 console.log('Error fetching data: ' + error.toString());
>             } else {
>                 LoginManager.logOut();
>             }
>         });
>       new GraphRequestManager().addRequest(logout).start();
>     })
>     .catch(error => {
>       console.log(error)
>     });      
>   }
> ```

For the iOS this works great, but for some reason on Android after I have logged once, this logout method does not work and goes straight to the error log. I've changed the version from 4.40.0 to 4.37.0 and in some SDKs it is working but not the right way, it opens browser and after I return to the app it prompts the login inputs again. 

I could not figure out this issue that happens on Android devices only. Any idea, guys?
