### ISSUE TITLE
LoginButton style width not working: the button disappears if I change width

### ISSUE THREAD

**Issue by GiacomoK** [facebook/react-native-fbsdk#449]
## Environment

  OS: Windows 7
  Node: 11.3.0
  Yarn: 1.10.1
  npm: 6.4.1
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.6.0 => 16.6.0
  react-native: 0.55.2 => 0.55.2

## Description

I am trying to change LoginButton width, but if I do useing style the button is not shown at all.

## Reproducible Demo

This is the code I use, and the Button is not shown:

      <LoginButton
        readPermissions={["user_friends", "email"]}
        style={{ width: 230 }}
        onLoginFinished={
            (error, result) => {
                if (error) {
                    alert("login has error: " + result.error);
                } else if (result.isCancelled) {
                    alert("login is cancelled.");
                } else {
                    AccessToken.getCurrentAccessToken().then(
                        (data) => {
                            updateFbToken(data.userID, data.accessToken).then(response => {
                                console.log('TOKEN UPDATED');
                                console.log(response);
                            }).catch(err => {
                                console.log('Oh shoot. Something went wrong with the promise code:');
                                console.log(err.message);
                            });
                        }
                    ).catch(function(e) {
                        console.log(e); // "oh, no!"
                    });
                }
            }
        }
        onLogoutFinished={() => {
            props.onLogout();
        }} />;`

If I remove style line, the button is shown.

**Comment by Michaelvons** [comment]
Instead, use the **LoginManager** object.
**Highly recommended !!**

// Imports
`import {LoginButton, AccessToken, LoginManager} from 'react-native-fbsdk';`

// Your custom button
```
<Button
    icon={<Icon name="facebook-box" size={32} color="white" />}
    buttonStyle={styles.LandingButtonFacebook}
    title="continue with Facebook"
    titleStyle={styles.LandingBtnText}
    type="solid"
    onPress={() => loginWithFacebook()}
/>
```

// Function that uses LoginManager to invoke Facebook's login flow
```
  const loginWithFacebook = () => {
    LoginManager.logInWithPermissions(['email']).then(
      function(result) {
        if (result.isCancelled) {
          console.log('Login cancelled');
        } else {
          console.log(
            'Login success with permissions: ' +
              result.grantedPermissions.toString(),
          );
          AccessToken.getCurrentAccessToken().then(data => {
            console.log(data.accessToken.toString());
            console.log('result-->', result);
          });
        }
      },
      function(error) {
        console.log('Login fail with error: ' + error);
      },
    );
  };
```
