### ISSUE TITLE
LoginButton results in `com.facebook.sdk.core error 3` or crashing app

### ISSUE THREAD

**Issue by coryb08** [facebook/react-native-fbsdk#450]
## Environment

React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.1
      CPU: (4) x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
      Memory: 46.86 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.11.3 - /usr/local/bin/node
      Yarn: 1.9.2 - /usr/local/bin/yarn
      npm: 6.3.0 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
      Android SDK:
        API Levels: 26, 27, 28
        Build Tools: 26.0.3, 27.0.3, 28.0.2
        System Images: android-27 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: 0.57.8 => 0.57.8 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native: 0.56.0

## Description

After following all instructions under "Getting Started" and "Login" at  https://developers.facebook.com/docs/react-native `LoginButton` with default attributes does not work. With prop `publishPermissions` the app crashes. Changing that to `readPermissions` results in error `com.facebook.sdk.core error 3`

Other than `com.facebook.sdk.core error 3` I have no errors in console or in xcode.

I've tried default facebook-sdk v4.39 and also tried manually downgrading to v.438 and v.437

## Reproducible Demo

`react-native init [yourproject]`

then following all official instructions here: https://developers.facebook.com/docs/react-native/getting-started

**Comment by danvasem** [comment]
Same problem here. Any solution?

**Comment by preko96** [comment]
I got the same the same thing happening, I just followed the 
https://developers.facebook.com/docs/ios/getting-started/
Tried using multiple SDK (4.35, 4.36, 4.37, 4.38, 4.39), but none of them seemed to work...
I did not use pods either, just the javascript script file...

**Comment by coryb08** [comment]
Just noting that this is still an issue. Im working on an app for the city of New York and am literally making excuses as to why the facebook login isn't implemented. Please look into this someone.

**Comment by coryb08** [comment]
this problem was resolved by one or all of the following:
1) using latest version of fbsdk 4.39.1
2) updated xcode to latest version
3) ONLY adding the following to `appdelegate.m` for tracking app installs. right below `@implementation AppDelegate`
 ```- (BOOL)application:(UIApplication *)application
             openURL:(NSURL *)url
   sourceApplication:(NSString *)sourceApplication
          annotation:(id)annotation {
   return [[FBSDKApplicationDelegate sharedInstance] application:application
                                                         openURL:url
                                               sourceApplication:sourceApplication
                                                      annotation:annotation];
}```
