### ISSUE TITLE
FBSDKLoginButton not refresh itself

### ISSUE THREAD

**Issue by nlhkh** [facebook/react-native-fbsdk#47]
I have a `FBSDKLoginButton` in my login view, and I use `FBSDKLoginManager` in another view. When I logout with FBSDKLoginManager, I have the Navigator transition back to the login view. However, the FBSDKLoginButton still shows as if I am still login (it says "Log Out"). When I click on the button, however, the click trigger a login action. Reloading the app reset the button to display correctly.

**Comment by dzhuowen** [comment]
Fixed in release0.0.6
