### ISSUE TITLE
Support for androidx project

### ISSUE THREAD

**Issue by iagorm** [facebook/react-native-fbsdk#473]
My question is very simple, will be a version that supports androidx projects?

Some of the libraries in React Native started to migrate to androidx and is necessary that others do so.

**Comment by hery** [comment]
+1

Currently updating every import such that `import android.support.annotation.Nullable;` becomes `import androidx.annotation.Nullable;`, but it's not maintainable.

**Comment by Saad-Bashar** [comment]
+111111111

**Comment by Saad-Bashar** [comment]
When can we expect an upadate with the support for androidx?

**Comment by Lucas-Geitner** [comment]
@Saad-Bashar @harokevin, @iagorm, thanks to @janicduplessis it's now possible using master branche, put that on your package.json
`'react-native-fbsdk": "facebook/react-native-fbsdk#master"`

**Comment by janicduplessis** [comment]
You can also use 1.0.0-rc.3
