### ISSUE TITLE
'FBSDKShareKit/FBSDKShareKit.h' file not found

### ISSUE THREAD

**Issue by peymancyb** [facebook/react-native-fbsdk#475]
<img width="258" alt="screen shot 2019-02-08 at 4 10 46 pm" src="https://user-images.githubusercontent.com/18486930/52477765-882ce380-2bbc-11e9-9cd3-747849a3805f.png">
Trying to use facebook login, and getting 'FBSDKShareKit/FBSDKShareKit.h' file not found error for days, any suggestion on how to fix this issue? 
i have looked all the issue but i did not find any solution

**Comment by ckOfor** [comment]
@peymancyb check this solution out https://github.com/facebook/react-native-fbsdk/issues/401#issuecomment-435312536

Which is 
`Try doing this in XCode (i have 10): go to RCTFBSDK.xcodeproj then build settings->framework search paths. And change ~/Documents/FacebookSDK to $(HOME)/Documents/FacebookSDK
It saved me a lot of time. Now it finally gets built.`

**Comment by peymancyb** [comment]
@ckOfor Thank you so much, I have tried all the solutions but I found the solution, I should change the path in Libraries>RCTFBSDK.xcodeproj and then on the Build settings searched for Framework Search path, and then change ~/Documents/FacebookSDK to $(HOME)/Documents/FacebookSDK

thank you so much again for the help

**Comment by cristianPerez** [comment]
Thanks, everyone, in the end, I solved the issue just dragging and dropping FacebookSDK into the Libraries>RCTFBSDK.xcodeproj  --> on the Build settings searched for Framework Search path

TO AVOID type error is better to drag and drop the complete folder.

RCTFBSDK.xcodeproj
<img width="283" alt="Screen Shot 2019-05-03 at 4 01 39 PM" src="https://user-images.githubusercontent.com/1987909/57165534-03b5bf80-6dbd-11e9-88d0-0ab8af596a92.png">

Global project 
<img width="228" alt="Screen Shot 2019-05-03 at 4 04 22 PM" src="https://user-images.githubusercontent.com/1987909/57165593-3069d700-6dbd-11e9-97cc-7dadb7b49d49.png">

**Comment by theredfoxfire** [comment]
Can we have this in the doc, under troubleshooting section?

**Comment by rogerkerse** [comment]
This is not something someone should manually do because every time u download project dependencies again it is broken again?

**Comment by GastonInfante** [comment]
Open the terminal.

Check that git is installed by running this command : git --version  (otherwise follow this article to install it https://confluence.atlassian.com/crucible045/installing-and-upgrading-git-947848144.html).

Go the root folder of your Xcode generated project by running: cd + " Xcode project path".
Run this command : sudo gem install cocoapods.
Run this command : pod update.
Open again your Xcode project(from .workspace file) and build.
