### ISSUE TITLE
Invalid access_token

### ISSUE THREAD

**Issue by yogevlahyani** [facebook/react-native-fbsdk#480]
## Environment
Local
Run `react-native info` in your terminal and paste its contents here.
```
React Native Environment Info:
    System:
      OS: Windows 10
      CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
      Memory: 3.40 GB / 15.87 GB
    Binaries:
      npm: 6.4.0 - C:\Program Files\nodejs\npm.CMD
      Watchman: 4.9.4 - C:\Windows\system32\watchman.EXE
    IDEs:
      Android Studio: Version  3.2.0.0 AI-181.5540.7.32.5056338

```

## Description
access_token that I'm getting from `LoginManager.logInWithReadPermissions` is invalid, I went to the [access_token debugger](https://developers.facebook.com/tools/debug/accesstoken) and got this message:
`Error validating access token: The session has been invalidated because the user changed their password or Facebook has changed the session for security reasons.`

I did changed my password during the development, and couldn't find a way to create a new token or refresh it. also it says that my token would never be expired.

Although, I have a web app which uses ngx-facebook-sdk or something (didn't developed the web FE app) and the token there is just fine, I used it before and after I changed my facebook password.

Describe your issue in detail. Include screenshots if needed. If this is a regression, let us know.

## Reproducible Demo

Let us know how to reproduce the issue. Include a code sample, share a project, or share an app that reproduces the issue using https://snack.expo.io/.
Please follow the guidelines for providing a MCVE: https://stackoverflow.com/help/mcve

**Comment by dorthwein** [comment]
If anyone else runs into this issue on android set add `await LoginManager.setLoginBehavior("web_only")` to force browser login avoiding the problem.
