### ISSUE TITLE
facebooksdkstrings.bundle is missing after upload app to Testflight

### ISSUE THREAD

**Issue by ptdede** [facebook/react-native-fbsdk#483]
Hi! I want to upload my app to Testflight and got this message from apple to my email:

```
Dear Developer,

We identified one or more issues with a recent delivery for your app, "*** App". Please correct the following issues, then upload again.

This bundle is invalid - The Info.plist file for /Payload/***.app/FacebookSDKStrings.bundle is missing or could not be read.

Invalid Bundle - The bundle at '/Payload/***.app/FacebookSDKStrings.bundle' does not contain a bundle executable.

Best regards,

The App Store Team
```

Anybody else got this issue? I found this SO also found this issue:
https://stackoverflow.com/questions/54798216/react-native-expo-apple-upload-fail

Open issue Facebook developer:
https://developers.facebook.com/bugs/2077613562276009/

**Comment by JonghunYu** [comment]
I have same problem but couldn't figure out why.

**Comment by JonghunYu** [comment]
Please check the link below. I think it's beyond control and we should wait until it resolved
https://stackoverflow.com/questions/54798216/react-native-expo-apple-upload-fail

**Comment by ptdede** [comment]
It's solve!
