### ISSUE TITLE
Login with native dialog

### ISSUE THREAD

**Issue by nlhkh** [facebook/react-native-fbsdk#49]
I notice that apps like Tinder have native login dialog, i.e. they don't open a web view for logging in. I am trying to achieve the same thing with React Native FBSDKLoginButton, and try to set the `loginBehavior` prop to `native`, but it seems no matter what the value is, a web view pops up. Is this a missing feature of `react-native-fbsdklogin` or a misconfig from my part?

**Comment by nlhkh** [comment]
It seems that all the dialogs (including share dialogs) are web view.

**Comment by mingflifb** [comment]
It depends on the underlying version of the Facebook SDK that you're using. We changed some behaviors for iOS9, Tinder might still be on the old versions of the SDK.

**Comment by nlhkh** [comment]
Could you explain further why you made such change? Is there any
circumstance that the native dialog will be available?

**Comment by mingflifb** [comment]
With iOS 9, there are two OS-level changes that affected this decision.
1. There's now an interstitial that pops up the first time a native app switch happens. We believe this could be disruptive to the user.
2. There's now a SFSafariViewController which shares cookies with Safari, which does not require an app switch, and provides a relatively low friction way to log in (or accept permissions if the user has already logged into FB on Safari).

We're still evaluating this change in behavior, and will update the behavior if one experience is clearly better for the user.

**Comment by alfonsodev** [comment]
@mingflifb Thanks for the information
but is there a way to force native dialog ? Which version of the SDK supports it ?

**Comment by DVassilev** [comment]
@mingflifb As asked above, is there a way to force native?

**Comment by mattwkelly** [comment]
Bump

**Comment by GeoffreyPlitt** [comment]
+1 - no answers since Oct 2015?
