### ISSUE TITLE
Your Facebook SDK is out of date. We recommend upgrading to the latest Version 4.37.0, to ensure your app's performance is not affected and to take advantage of our newest features

### ISSUE THREAD

**Issue by vinoa-team** [facebook/react-native-fbsdk#495]
Hi,

We are using the below versions:
    "react-native": "0.57.5",
    "react-native-fbsdk": "^0.8.0",

And when the app is launched, we get the below message in the log: 
Your Facebook SDK is out of date. We recommend upgrading to the latest Version 4.37.0, to ensure your app's performance is not affected and to take advantage of our newest features

Is there a plan to release a new version of react-bative-fbsdk with the latest version of the Facebook SDK (Facebook SDK for Android v.4.39.0 or Facebook SDK for iOS v.4.39.0)

Alternatively, is there a way to do the upgrade "manually" ?

Many thanks !

**Comment by narendardiscover** [comment]
I am using 4.44.0 but still getting same warning in Xcode console _"Your Facebook SDK is out of date. We recommend upgrading to the latest Version 4.37.0, to ensure your app's performance is not affected and to take advantage of our newest features!_"

https://developers.facebook.com/docs/ios/downloads/

One more question in SDK 5.x.x there is not .framework file like ShareKit.framework, Bolts.framework. How to switch 5.x.x? I am not using any pod.

**Comment by michalzelinka** [comment]
Facebook SDK for iOS started to send an improper `User-Agent` header using a wrong format `FBiOSSDK.5.x.x` instead of a traditional one `FBiOSSDK/5.x.x` with a slash; I've discovered this by capturing the log message and following the stack trace up to the request data.

This needs to be fixed by the Facebook iOS SDK team.

**Comment by BaderSerhan** [comment]
They are now at 0.5.0 and we still haven't figured out how to update react-native-fbsdk without breaking everything :/

> Your Facebook SDK is out-of-date. Please upgrade to v5.0 for access to new privacy features.

**Comment by dbelchev** [comment]
Yes, there's issues with the compatibility of react-native-fbsdk and FacebookSDK v5.0.x

This configuration, produces build errors:
react-native-fbsdk@0.9.0
pod 'FBSDKCoreKit', '~> 5.0.1'
pod 'FBSDKLoginKit', '~> 5.0.1'
pod 'FBSDKShareKit', '~> 5.0.1'

![Screenshot 2019-06-05 at 10 17 36](https://user-images.githubusercontent.com/9073252/58937466-2bf95b00-877b-11e9-926f-3f88d4e72074.png)

Though, the following configuration works just fine:
react-native-fbsdk@0.9.0
pod 'FBSDKCoreKit', '~> 4.39.1'
pod 'FBSDKLoginKit', '~> 4.39.1'
pod 'FBSDKShareKit', '~> 4.39.1'

**Comment by ovy9086** [comment]
is this in anybody's plan ? to make this compatible with FBSDK 5.0+ ?

**Comment by ovy9086** [comment]
still no updates ? 👀

**Comment by BaderSerhan** [comment]
I managed to upgrade to the latest facebook version like this. I didn't find any compatibility issues.

#### FBSDK Installation / Update Steps

- Run `yarn install git+https://github.com/facebook/react-native-fbsdk.git`.

- Add the latest version of `FBSDKCoreKit.framework`, `FBSDKLoginKit.framework`, and `FBSDKShareKit.framework` to `Documents/FacebookSDK` folder.

- Add `/Users/{name_of_user}/Documents/FacebookSDK` to `Framework Search Paths` in project's `Build Settings`.

- Manually link `RCTFBSDK` in XCode (see manual linking steps).

- Under `RCTFBSDK` target, make sure the frameworks are found in:
    - `RCTFBSDK.xcodeproj/Frameworks` folder
    - `Build Phases/Link Binary with Libraries`

- [Temporary Fix] To solve `'React/RCTComponentEvent.h` or `React/RCTBridgeModule.h` file not found errors, add `RCTComponentEvent.h` to `Build Phases/Copy Headers` under `React` target.

**Comment by janicduplessis** [comment]
You should be able to use v0.10.0 with FBSDK 5 and RN 0.59

**Comment by AmitPandya007** [comment]
> I managed to upgrade to the latest facebook version like this. I didn't find any compatibility issues.
> 
> #### FBSDK Installation / Update Steps
> * Run `yarn install git+https://github.com/facebook/react-native-fbsdk.git`.
> * Add the latest version of `FBSDKCoreKit.framework`, `FBSDKLoginKit.framework`, and `FBSDKShareKit.framework` to `Documents/FacebookSDK` folder.
> * Add `/Users/{name_of_user}/Documents/FacebookSDK` to `Framework Search Paths` in project's `Build Settings`.
> * Manually link `RCTFBSDK` in XCode (see manual linking steps).
> * Under `RCTFBSDK` target, make sure the frameworks are found in:
>   
>   * `RCTFBSDK.xcodeproj/Frameworks` folder
>   * `Build Phases/Link Binary with Libraries`
> * [Temporary Fix] To solve `'React/RCTComponentEvent.h` or `React/RCTBridgeModule.h` file not found errors, add `RCTComponentEvent.h` to `Build Phases/Copy Headers` under `React` target.

@BaderSerhan 
This is only when you are using RN .60 or .60+ version.
I am using 0.59.9 RN and getting error, Any help would be really appreciated. Thank you.

**Comment by witalobenicio** [comment]
@janicduplessis I've upgraded, but message still there on developers.facebook. :/
