### ISSUE TITLE
Requiring unknown module

### ISSUE THREAD

**Issue by tnguyen42** [facebook/react-native-fbsdk#5]
Hi,

After updating the package to 0.0.3, I got the same error than the one I got before with Login:

![image](https://cloud.githubusercontent.com/assets/12211685/9154487/f96199be-3e90-11e5-9ea2-cb7b08911072.png)

This also happens with AccessToken from Core.
I tried removing the packages (from npm and XCode), reinstalling them with npm install --save... But the errors are still here.

I don't understand since I got it to work last time and I only updated the packages :-(

**Comment by cphackm** [comment]
0.0.3 didn't change either of those components, so there may be something else going on here.  Make sure the version on the react-native-fbsdklogin and react-native-fbsdkcore dependencies in your app's package.json file are at 0.0.3.

Failing that, uninstall the packages, then run:

**npm install --save react-native-fbsdklogin@0.0.2**
**npm install --save react-native-fbsdkcore@0.0.2**

To uninstall the previous versions and ensure that they're still working.

**Comment by tnguyen42** [comment]
Actually I've been able to make everything work with the same method than before... By adding fbsdkshare. But I can't explain anything.
Maybe we should leave this issue open to see if anyone has the same problem or if it's just me...

**Comment by tnguyen42** [comment]
Any news? I know the plugin is pretty now, but am I still the only one who has a problem running the libs independently?
(by the way, share still isn't working :/ )

**Comment by chirag04** [comment]
i can't even get to compile it.

**Comment by yelled3** [comment]
i'm using 
```js
"react-native-fbsdkcore": "0.0.4",
"react-native-fbsdklogin": "0.0.4",
```

and I still get:

```
'Warning: Native component for "RCTFBSDKLoginButton" does not exist'
```

and of course the login button doesn't work

**Comment by philikon** [comment]
Thanks for your comments, everyone. It's best to start out filing a new issue rather than piling onto an existing one. It's always easier to merge tickets after the fact when we realize they're the same issue. It's harder to keep track of different problems within the same thread. When you do file a ticket, please include detailed steps to reproduce. Also please check out the Sample app and ensure you can build and run that.

**Comment by chirag04** [comment]
@philikon Sorry i was not descriptive enough. I will create a separate issue with more details.

**Comment by philikon** [comment]
@tnguyen42, do you still have any problems here? I'm closing this for now, please reopen with detailed error messages if you're still seeing problems.
