### ISSUE TITLE
React Native 0.12 breaks react-native-fbsdkcore and fbsdklogin

### ISSUE THREAD

**Issue by kevinzzz007** [facebook/react-native-fbsdk#50]
When I upgrade to RN 0.12 and do the pod install, I get the follow error:

<img width="260" alt="screen shot 2015-10-09 at 9 27 39 pm" src="https://cloud.githubusercontent.com/assets/5249746/10408477/9c8ebc5a-6ecc-11e5-9416-360263e56598.png">

Has anyone else encountered the same thing?

**Comment by devlesedi** [comment]
You could follow this [video](https://www.youtube.com/watch?v=yQi6F4Dh6gY). It helped me to get started. I'm on react native v0.12 and I get successful builds however, I get this warning on the console 'Warning: Native component for "RCTFBSDKLoginButton" does not exist'

**Comment by devlesedi** [comment]
Nevermind what I said about the warning. I didnt reference the libraries right and now everything is working.

**Comment by hzyIO** [comment]
I'm getting this error specifically with a Pod spec install using react-native-fbsdkcore. How did you guys resolve this issue?

**Comment by kevinzzz007** [comment]
Haven't found a solution yet

On Monday, October 12, 2015, Logan Hendershot <notifications@github.com>
wrote:

> I'm getting this error specifically with a Pod spec install using
> react-native-fbsdkcore. How did you guys resolve this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/react-native-fbsdk/issues/50#issuecomment-147473248>
> .
>


-- 
Kevin Zhao | LinkedIn <http://www.linkedin.com/in/kevinzhaouva> | Personal
Blog <https://medium.com/@kevinzhao> | Github
<https://github.com/kevinzzz007>
(434) 282-5369
Computer Science and Information Technology | University of Virginia 2016
Alpha Kappa Psi Professional Business Fraternity
<http://www.akpsiatuva.org/>

**Comment by kevinzzz007** [comment]
@devlesedi so if we use Cocoapod, there is issue...

**Comment by seokgyo** [comment]
It look like there's some conflict between FBSDKxxxKit and react-native.
The following is what if found.
If you use FBSDKxxxKit version 4.7, you should use react-native@0.13.0-rc.
If you use FBSDKxxxKit version 4.6, you should use react-native@0.11.x or 0.12.0.

**Comment by seokgyo** [comment]
BTW, you would not able to install react-native@0.13.0-rc because of peerDependencies in react-natve-fbsdk.

**Comment by MossP** [comment]
Anyone managed to get this working on 0.13.0-rc yet either? The loginManager seems to be giving me issues using FDSBK v4.7.

**Comment by dzhuowen** [comment]
@MossP Can you provide more detail on the issue? Because I can setup the React Native project(0.13.0-rc) with the SDK(v4.7) using cocoaPod.  The README file is outdated and some detail on Xcode side are not pointed out. That might be the problem.

**Comment by MossP** [comment]
I hadn't noticed that 0.13.0 was out when I posted this. Maybe that has something to do with it. I'll get my RN updated first then come back with any errors, thanks.

**Comment by MossP** [comment]
oh, you got it working on 13.0-rc?

**Comment by MossP** [comment]
OK, I've updated and tried to do it again @dzhuowen . I'm getting a few errors..

First one is. 
```
Can't find variable: GlobalStore
```
Removing this line then causes LoginManager to fall over at the next line
```
undefined is not an object (evaluating 'FBSDKLoginManagerInterface.loginWithReadPermissions')

logInWithReadPermissions
FBSDKLoginManager.ios.js @ 83:0
```

Any idea what I'm doing wrong?

**Comment by MossP** [comment]
Ok @dzhuowen. Got it working. It appears that linking via the XCode Projects fails but dragging the iOS folder in (like in the video link above) makes it work.

I've just got to get it to login via the native app now rather than safari which it's trying to do by default.

**Comment by MossP** [comment]
ps. I wasn;t using CocoaPods. Sorry for any confusion. I got lost in the thread.

**Comment by dzhuowen** [comment]
React Native SDK can be used with React Native 0.12 and 0.13 using CocoaPods.
When upgrade React Native, it's strongly recommended to remove the original .xcworkspace file and then do 'pod install'. 
Also during 'pod install', if you see warnings like: 
The `Test [Debug]` target overrides the `OTHER_LDFLAGS` build setting defined in `Pods/Target Support Files/Pods/Pods.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.

Go to xcode's target `build setting` section and search 'Other Linker Flags' and add '$(inherited)' to it.

**Comment by kevinzzz007** [comment]
@dzhuowen by chance you could help update the README for the CocoaPod part?  I think that would really help newcomers :-)
