### ISSUE TITLE
'FBSDKShareKit/FBSDKShareKit.h' file not found can not find any solution while applying all possible path 

### ISSUE THREAD

**Issue by adilvectorcoder** [facebook/react-native-fbsdk#501]

**Comment by huuthinh245** [comment]
i think you missed install with pod and Link Binary to Libraries
 // add to podfile  
  pod 'FBSDKShareKit', '4.38.0'
hope it helpful

**Comment by vuvantoan95** [comment]
I have the same problem with rn 0.43.2 and react-native-fbsdk: 0.5.0 😭

**Comment by huuthinh245** [comment]
@vuvantoan95  should upgrade version react-native-fbsdk. I work well with "react-native-fbsdk": "^0.8.0",

**Comment by vuvantoan95** [comment]
thank @huuthinh245. I fixed.
remove `~/Documents/FacebookSDK` or `${HOME}/Documents/FacebookSDK` in  `build settings->framework search paths`
// add to podfile
pod 'FBSDKShareKit'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
and run pod install
It works!

**Comment by NgoVanTien** [comment]
Download the SDK and extract the archive file to ~/Documents/FacebookSDK
Or change ```$(HOME)/Documents/FacebookSDKs-iOS-4.40.0``` with version name when download it into 
https://github.com/facebook/react-native-fbsdk/blob/master/ios/RCTFBSDK.xcodeproj/project.pbxproj#L393

**Comment by tunm1228** [comment]
ld: library not found for -lBolts
