### ISSUE TITLE
App crashes when clicking on the top left corner "Back to <App>" in AppInviteDialog

### ISSUE THREAD

**Issue by PhilippKrone** [facebook/react-native-fbsdk#51]
Hello,

I'm using the FBSDKAppInviteContent as follows:

````javascript
  var inviteContent = new FBSDKAppInviteContent('https://fb.me/XXXXXXXXXXXX', 'my.png');
  FBSDKAppInviteDialog.show(inviteContent, (error, result) => {
    console.log(error);
    console.log(result);
  });
`````

That works quite fine except the case that the user clicks on "Back to app" at the top left corner of the device screen in the facebook app:

1) Click on button to trigger the AppInviteDialog
2) Don't click "Cancel" but click on "Back to <APP>"

Any idea what this might cause?

Regards
Philipp

**Update 1**:
It seems like the following code in RCTFBSDKAppInviteDialog.m throws an exception:
````javascript
  if ([results[@"completionGesture"] isEqualToString:@"cancel"]) {
    _showCallback(@[[NSNull null], @{@"isCancelled": @YES}]);
  } else {
    _showCallback(@[[NSNull null], results]);
  }
  _showCallback = nil;
`````
as "results" in the else {} block is NULL, the following exception is thrown:
````javascript
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[1]'
*** First throw call stack:
````

**Update 2**
Changing the lines to the following seems to work:
````javascript
  if ([results[@"completionGesture"] isEqualToString:@"cancel"]) {
    _showCallback(@[[NSNull null], @{@"isCancelled": @YES}]);
  } else {
    if (results == NULL) {
        _showCallback(@[[NSNull null], [NSNull null]]);
    } else {
        _showCallback(@[[NSNull null], results]);
    }
 ````
If this is the correct way to fix it, I'll gladly submit a PR.

**Comment by mingflifb** [comment]
I think that's a reasonable solution. Please submit a PR.

**Comment by PhilippKrone** [comment]
See https://github.com/facebook/react-native-fbsdk/pull/53
