### ISSUE TITLE
null is not an object (evaluating LoginManager.logInWithReadPermissions)

### ISSUE THREAD

**Issue by hey-mx** [facebook/react-native-fbsdk#510]
## 🐛 Bug Report
Followed the steps in this URL https://developers.facebook.com/docs/ios/getting-started/ I have the error 
![Screen Shot 2019-04-09 at 2 37 44 AM](https://user-images.githubusercontent.com/212843/55781994-00a30a00-5a71-11e9-8daf-2db9852ff7c3.png)

## To Reproduce
Only I have followed the steps in https://developers.facebook.com/docs/ios/getting-started/

## Code Example
On my react component I wrote this:
<img width="725" alt="Screen Shot 2019-04-09 at 2 37 55 AM" src="https://user-images.githubusercontent.com/212843/55782118-419b1e80-5a71-11e9-821b-717f26f04780.png">

I have reviewed the framework configuration into the xcode project and looks like this

![Screen Shot 2019-04-09 at 2 38 13 AM](https://user-images.githubusercontent.com/212843/55782215-6a231880-5a71-11e9-90b2-65d0d702d7a1.png)

And

![Screen Shot 2019-04-09 at 2 38 31 AM](https://user-images.githubusercontent.com/212843/55782238-73ac8080-5a71-11e9-92d7-e582b9c05d31.png)

Finally

![Screen Shot 2019-04-09 at 2 38 53 AM](https://user-images.githubusercontent.com/212843/55782258-7dce7f00-5a71-11e9-9b04-d3474452be77.png)

Did I forget to include some else into the xcode configuration? 

Thanks

**Comment by santilorenzo** [comment]
Same issue here, without awaiting the promise, the app crashes with error:
`undefined is not an object (evaluating LoginManager.logInWithReadPermissions)`

**Comment by bosung90** [comment]
Post your Podfile I may be able to help

**Comment by hey-mx** [comment]
@bosung90 thank you. That was the problem I have added the FBSDK manually. Now I added it using cocoa pods and it is working.

**Comment by dotkebi** [comment]
Same issue here, without awaiting the promise, the app crashes with error:

```
import {AccessToken, GraphRequest, GraphRequestManager, LoginManager} from 'react-native-fbsdk';

class Auth extends React.Component {


  facebook() {
    LoginManager.logInWithReadPermissions(['public_profile', 'email'])
      .then(result => {
        if (result.isCancelled) {
          console.log('Login cancelled');
        } else {
          console.log(
            'Login success with permissions: ' +
            result.grantedPermissions.toString()
          );

          AccessToken.getCurrentAccessToken().then(data => {
            const token = data.accessToken.toString();
            console.log('facebook initialLogin');
            console.log(token);

            const req = new GraphRequest(
              '/me',
              {
                httpMethod: 'GET',
                version: 'v2.5',
                parameters: {
                  fields: {
                    string: 'email,name',
                  },
                },
              },
              (err, res) => {
                if (err) {
                  console.error(err);
                } else {
                  console.log(res);
                }
              }
            );
            new GraphRequestManager().addRequest(req).start();
          });
        }
      })
      .catch(error => {
        console.log('Login fail with error: ' + error);
      });
  }
}
```

`PodFile`
```
platform :ios, '9.0'
use_frameworks!

def shared_pods
  pod 'Bolts'
  pod 'FBSDKShareKit'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FacebookSDK'

  pod 'Firebase/Core','4.13.0'
  pod 'Firebase/Messaging','4.13.0'
end

target 'MyProj' do
  shared_pods

end
```


![image](https://user-images.githubusercontent.com/8197507/56095071-05a20680-5f14-11e9-89a1-af98d2f353c4.png)

**Comment by webmasterdragon** [comment]
I am getting same issue.
Any solutions?

**Comment by RobbieReyes1** [comment]
@webmasterdragon  I got same problem and I want to know where is libRCTFBSDK.a . I can't find that

**Comment by wellington-cunha** [comment]
same issue

**Comment by LiDevil** [comment]
i solve this problem by 'react-native link react-native-fbsdk' , my rn version is 0.60.5,i dont know why

**Comment by wellington-cunha** [comment]
@LiDevil You don't need link. can you post your package.json and Pofile?

**Comment by fabriciosautner** [comment]
same problem, any solution?

**Comment by dev-intellisoft** [comment]
@fabriciosautner what react-native version are you using? post here you package.json and Podfile

**Comment by LiDevil** [comment]
sry, i can't reproduce the error now...

**Comment by fabriciosautner** [comment]
@dev-intellisoft 

Basically I uninstalled everything and redid it.

I think as months went by, the new versions of the SDK, the POD itself updated and now it worked.

Thanks!

**Comment by LiDevil** [comment]
i forget to add  this line in android...
```
            packages.add(new FBSDKPackage());
```
