### ISSUE TITLE
Getting error oppressing login button

### ISSUE THREAD

**Issue by AarshApple** [facebook/react-native-fbsdk#513]
I tried using it in a fresh application but am getting an error **Login failed with error: SERVER_ERROR: 1349195[message]: The key hash does not match any stored key hashes.Go to docs for more information**

## 🐛 Bug Report
If Facebook app is not installed somehow the error does not come. But if i install Facebook app and run the app again i get an error like stated above.

## To Reproduce
react-native init AwesomeApp
cd AwesomeApp
yarn add react-native-fbsdk
react-native link react-native-fbsdk
Followed all the steps in Facebook developer website 
Run the app and try to login through **LoginManager** and this error comes.
Maybe it has something to do with how i create a development key hash in quick start section of my app in Facebook developer console.

## Expected Behavior
I Expected to get success after logging in instead get an error of hash key

## Code Example
```
async loginFacebook() {
    try {
      let result = await LoginManager.logInWithReadPermissions(['public_profile'])
      if (result.isCancelled) {
        alert('Login was cancelled');
      } else {
        alert('Login was successful with permissions: '
          + result.grantedPermissions.toString());
      }
    } catch (error) {
      alert('Login failed with error: ' + error)      
    }
```

## Environment

React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (2) x64 Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz
      Memory: 126.48 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.14.2 - /usr/local/bin/node
      Yarn: 1.13.0 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
      Android SDK:
        API Levels: 19, 22, 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 23.0.3, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
        System Images: android-23 | Google APIs Intel x86 Atom, android-24 | Intel x86 Atom, android-25 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.1 => 16.6.1 
      react-native: 0.57.7 => 0.57.7 
    npmGlobalPackages:
      generator-react-native-ignite: 1.13.0
      react-native-cli: 2.0.1

**Comment by mixa63rus** [comment]
Did you find solution? A have same problem

**Comment by thilinawarnakula** [comment]
Did you find solution? A have same problem
