### ISSUE TITLE
'FBSDKCoreKit/FBSDKCoreKit.h' file not found when run in XCODE

### ISSUE THREAD

**Issue by wellbeck190** [facebook/react-native-fbsdk#519]
'FBSDKCoreKit/FBSDKCoreKit.h' file not found when run in XCODE but work when run from command line "react-native run-ios"

xcode v10.2.1
react-native-fbsdk v0.8.0
react-native-cli v2.0.1
react-native v0.59.0

**Comment by bilsak18** [comment]
Can you please tell us why you closed the issue ? Did you solve the problem ? If yes, can you please tell us how you did that ? Thanks
