### ISSUE TITLE
iOS: AppDelegate application:openURL:sourceApplication:annotation: deprecated (RN 0.59.4)

### ISSUE THREAD

**Issue by sseppola** [facebook/react-native-fbsdk#525]
## 🐛 Bug Report

The signature of AppDelegate.m has changed from: [application:openURL:sourceApplication:annotation:](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623112-application?language=objc)
to 
[application:openURL:options:](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1623112-application?language=objc)

However, your instructions in the readme:

<img width="923" alt="Screen Shot 2019-05-14 at 11 26 14" src="https://user-images.githubusercontent.com/4065840/57687121-25276e80-763b-11e9-83e6-93f82b176049.png">

[vary from the iOS FB SDK instructions](https://developers.facebook.com/docs/ios/getting-started/#app-delegate):
<img width="838" alt="Screen Shot 2019-05-14 at 11 18 43" src="https://user-images.githubusercontent.com/4065840/57687191-4a1be180-763b-11e9-9f2e-57e1a0492982.png">

[and the React Native Linking docs](https://facebook.github.io/react-native/docs/linking)
<img width="905" alt="Screen Shot 2019-05-14 at 11 32 57" src="https://user-images.githubusercontent.com/4065840/57687644-14c3c380-763c-11e9-997a-1e15ee12cfc8.png">

In particular, notice the use of `sourceApplication` and `annotation` instead of `options`.

## To Reproduce

Using the deprecated method in RN 0.59.4 breaks linking back to the application, in our case the source was Auth0, not sure about FB functionality.

## Environment

```
$ react-native info
info
  React Native Environment Info:
    System:
      OS: macOS High Sierra 10.13.6
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 80.34 MB / 8.00 GB
      Shell: 5.5.1 - /usr/local/bin/zsh
    Binaries:
      Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
      Yarn: 1.10.1 - ~/.nvm/versions/node/v8.11.3/bin/yarn
      npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 27.0.3, 28.0.2, 28.0.3
        System Images: android-28 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3
      react-native: 0.59.4 => 0.59.4
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

**Comment by janicduplessis** [comment]
Updated the example 7c045f80a4dac668cb028e3ec84204e5cb610ae3
