### ISSUE TITLE
我可以把 sdk 升级到 5.0 吗？

### ISSUE THREAD

**Issue by JedShiMing** [facebook/react-native-fbsdk#538]
Facebook 后台提醒我 sdk 已过期，需要升级到 5.0！如果原生中改了 5.0 会不会出现问题

**Comment by cavator** [comment]
translate bro, or someone pls close this kk

**Comment by superandrew213** [comment]
Google translation:

The Facebook background reminds me that sdk has expired and needs to be upgraded to 5.0! If you change 5.0 in your native language, there will be no problem.

**Comment by cavator** [comment]
i update and all still Ok, until now kkk
