### ISSUE TITLE
Is there any way to custom FacebookLoginButton or ...

### ISSUE THREAD

**Issue by andyyou** [facebook/react-native-fbsdk#54]
In my project  I need to change the login button style, so is there any way to custom the style.

Or use FBSDKLoginManager but I need a callback on `onLogoutFinished`

[Add a callback for FBSDKLoginManager](https://github.com/facebook/react-native-fbsdk/blob/0d60d76137de8cdb5b1d493271c22f2c7e349520/react-native-fbsdklogin/js/FBSDKLoginManager.ios.js#L96-L98)

Does anyone can provide me a possible solution because I am not familiar with Obj-C or Swift

**Comment by andyyou** [comment]
I am not quite sure in` react-native` if I write code as follow

```
FBSDKLoginManager.logOut();
/**
 * Do anything, it certain logout, no need to check again or other possible problem will case any issues
 */
this.props.onFacebookLogout();
```

**Comment by MossP** [comment]
I'll fire up some code tonight for this if you're still looking for it?

**Comment by andyyou** [comment]
@MossP thank you :)

**Comment by dzhuowen** [comment]
see #48

**Comment by andyyou** [comment]
@dzhuowen  thanks
