### ISSUE TITLE
compileDebugJavaWithJavac error when migrated to AndroidX

### ISSUE THREAD

**Issue by Base29** [facebook/react-native-fbsdk#561]
## 🐛 Bug Report

  I have migrated to AndroidX for my project and when I try to build I get this error 

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-fbsdk:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```

## To Reproduce

1. Install the RN FBSDK 0.8.0
2. Migrate to AndroidX

## Expected Behavior

  Should be working.

## Environment

  
Environment:
  OS: macOS 10.14.5
  Node: 10.11.0
  Yarn: 1.10.1
  npm: 6.9.0
  Watchman: 4.9.0
  Xcode: Xcode 10.2.1 Build version 10E1001
  Android Studio: 3.4 AI-183.6156.11.34.5522156

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0

**Comment by janicduplessis** [comment]
You can try 1.0.0-rc.2 which is updated to Androidx an RN 0.60.0

**Comment by khalidos32** [comment]
@Base29 any updates, i have the same issue here!

**Comment by Base29** [comment]
@khalidos32 ... Actually I was running a very old version of RN (0.51.0) ... I have upgraded to 0.59.10 ... This version does not use AndroidX so everything got working for me.
