### ISSUE TITLE
Error with RCTFBSDKInitializer.m, is no longer included on the repo but it is in RCTFBSDK.xcodeproj 

### ISSUE THREAD

**Issue by amorino** [facebook/react-native-fbsdk#562]
## 🐛 Bug Report
The file RCTFBSDKInitializer.m is included on the RCTFBSDK.xcodeproj project file, when added as a library to a project and running react-native run-ios, the following error ocurrs:

`clang: error: no such file or directory: '.../node_modules/react-native-fbsdk/ios/RCTFBSDK/core/RCTFBSDKInitializer.m'
clang: error: no input files`

## To Reproduce
Add RCTFBSDK.xcodeproj to the project, link libRCTFBSDK.a.

## Expected Behavior
RCTFBSDKInitializer.m shouldn't be included on RCTFBSDK.xcodeproj, as the file doesn't exists anymore since 0.8.0

## Environment
Environment:
  OS: macOS 10.14.5
  Node: 8.11.4
  Yarn: 1.16.0
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 10.2.1 Build version 10E1001
  Android Studio: 3.4 AI-183.6156.11.34.5522156

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native:  => 0.51.4

**Comment by jp928** [comment]
Same issue on 0.59.9

**Comment by pardeepsingal** [comment]
error: Build input file cannot be found: '/
/node_modules/react-native-fbsdk/ios/RCTFBSDK/core/RCTFBSDKInitializer.m'

Unable to integrate the Facebook Login feature, Could you please suggest in which version it works very well, Currently we are using 0.10.0

**Comment by sruthirajank** [comment]
Same issue

**Comment by robert589** [comment]
same issue here, latest version

**Comment by robert589** [comment]
Ok, i found a quick solution,
from your Xcode directories, open your app xcodeproj > RCTFBSDK.xcodeproj >RCTFBSDK > core, then remove RCTFBSKInitializer.m file.

**Comment by ElieMyIdea** [comment]
> Ok, i found a quick solution,
> from your Xcode directories, open your app xcodeproj > RCTFBSDK.xcodeproj >RCTFBSDK > core, then remove RCTFBSKInitializer.m file.

Workaround works efficiently, however waiting for a more appropriate solution.

Thank you

**Comment by redcancode** [comment]
thanks for reporting this issue. i will create a PR later today to fix it unless someone else already fixes it by that time 🙂

**Comment by amorino** [comment]
Did a pull request 👍

**Comment by janicduplessis** [comment]
Sorry about this, it is fixed now

**Comment by jbolter** [comment]
@janicduplessis Should 0.10.1 be the "stable release"? I ran into this issue today when installing the 0.10.0 release that is marked stable.  Thanks!

**Comment by vorasudh** [comment]
No, it does not seem to be solved in v0.10.1. I face this issue with it as well. I'll go for above workaround for now.

**Comment by yaronlevi** [comment]
Is there an official fix for 0.10.0?

**Comment by nasmuris** [comment]
@yaronlevi you can delete the `RCTFBSKInitializer.m` and then create patch using [patch-package](https://www.npmjs.com/package/patch-package)

**Comment by anniewey** [comment]
Seems ok with 0.10.1 tho
