### ISSUE TITLE
Build Failed with Semantic Issue Property 'expiredPermissions' not found on object of type 'FBSDKAccessToken *'

### ISSUE THREAD

**Issue by halaszbalazs** [facebook/react-native-fbsdk#563]
## 🐛 Bug Report

Building is not possible - Build fails with Semantic Issue:
_"Property 'expiredPermissions' not found on object of type 'FBSDKAccessToken *'; did you mean 'declinedPermissions'?"_
in RCTFBSDKAccessToken.m on line 70

## To Reproduce

Link react-native-fbsdk, set up project as described in Getting Started then try to build.

## Expected Behavior

Application should build.

## Code Example

![Screenshot 2019-06-19 at 12 00 04](https://user-images.githubusercontent.com/12443792/59756500-22e3b000-928a-11e9-9099-36b0700a282f.png)

## Environment

React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
      Memory: 3.28 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.14.0 - /usr/local/bin/node
      Yarn: 1.15.2 - /usr/local/bin/yarn
      npm: 6.9.0 - /usr/local/bin/npm
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    IDEs:
      Android Studio: 3.4 AI-183.5429.30.34.5452501
      Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.9 => 0.59.9 
    npmGlobalPackages:
      react-native-cli: 2.0.1

**Comment by marf** [comment]
Same problem here

**Comment by ThiagoLovatine** [comment]
Same problem here.

**Comment by redcancode** [comment]
this means that the version of the native FBSDK is below 5.0.0. can you check what is the version of that?

**Comment by ThiagoLovatine** [comment]
I was using 4.4.0, I followed the tutorial, I'm trying with 5.0.2 for iOS now, but I'm getting:

ld: warning: Could not find auto-linked framework 'FBSDKCoreKit'
ld: warning: Could not find auto-linked framework 'FBSDKShareKit'
ld: warning: Could not find auto-linked framework 'FBSDKLoginKit'

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by redcancode** [comment]
@ThiagoLovatine if that's an error message of the JS side then it means you don't have the correct `react-native-fbsdk` version because `loginWithPermissions` is only available since version 0.10.0. can you check which one you have installed?

**Comment by Kiran0791** [comment]
property 'expiredPermissions' not found on object of type 'FBSDKAccessToken *'; did you mean 'declinedPermissions'

Am also facing the same issue. "react-native-fbsdk": "^0.10.0", and SDK 4.40.0

**Comment by janicduplessis** [comment]
You need to update the fbsdk to v5, see release notes https://github.com/facebook/react-native-fbsdk/releases/tag/0.10.0

**Comment by Kiran0791** [comment]
@janicduplessis can u share link to download the SDK 5

**Comment by halaszbalazs** [comment]
A download link would be appreciated to SDK 5.x just like SDK 4.x.

**Comment by CodeGains** [comment]
Been trying to install this thing for like 6 hours. I've downloaded the latest 5.1.1 version of FBSDKCoreKit.zip, FBSDKLoginKit.zip, FBSDKShareKit.zip from https://github.com/facebook/facebook-objc-sdk/releases.

I've re-copied the `FBSDKCoreKit.framework`, `FBSDKLoginKit.framework`, and `FBSDKShareKit.framework` over into my `Frameworks` in Xcode per these instructions: https://medium.com/@rachieb19/struggles-with-react-native-link-1f1738076472

Then I reimport libRCTFBSDK.a into my `Linked Frameworks and Libraries`, but I still get this same error. Am I missing something?

**Comment by CodeGains** [comment]
Finally fixed it, just disregard all of this and follow these steps instead:

https://github.com/facebook/react-native-fbsdk/pull/551#issuecomment-506548286
