### ISSUE TITLE
LoginManager.logInWithReadPermissions is not a function

### ISSUE THREAD

**Issue by aliasgharkarani** [facebook/react-native-fbsdk#566]
<img width="260" alt="Screenshot 2019-06-19 at 7 40 49 PM" src="https://user-images.githubusercontent.com/33603201/59775656-fc923480-92ca-11e9-9a68-fab2b2e9968a.png">

**Comment by herlarb** [comment]
@aliasgharkarani downgrade your react-native-fbsdk to 0.8.0 from 0.10.0 
`yarn remove react-native-fbsdk`
then
`yarn add react-native-fbsdk@0.8` 

I believe you use yarn or use the npm equivalent.

**Comment by redcancode** [comment]
please try `loginWithPermissions` instead. the other two methods are deprecated (`loginWithReadPermissions`, `loginWithPublishPermissions`)

**Comment by ThiagoLovatine** [comment]
@herlarb I tried downgrading now it doesn't give me any errors but the build continues to fail...

**Comment by redcancode** [comment]
@ThiagoLovatine if you downgrade `react-native-fbsdk` to below 0.10.0 you must downgrade the native FBSDK to 4.42.0 or below. i suggest staying with `react-native-fbsdk` 0.10.0 and solving all the issues there. anything below that version is too old 🙂

**Comment by ThiagoLovatine** [comment]
Ok im on 0.10.10 with FBSDK iOS 5.0.2, still the same, doesn't build, doesn't show any errors.

**Comment by redcancode** [comment]
@ThiagoLovatine if it doesn't build there should be an error. can you reopen your app in xcode, clean the build folder (Build / Clean build folder) and try building in xcode? errors should come up that way for sure

**Comment by ThiagoLovatine** [comment]
Sorry forgot to clean the cache, yes im using xcode.
I can build now, no errors, but when I click on the login button I get this:

![Screen Shot 2019-06-19 at 18 50 33](https://user-images.githubusercontent.com/1659635/59803913-4d9e2a80-92c3-11e9-964c-a8854e45c041.png)

**Comment by redcancode** [comment]
@ThiagoLovatine that still looks like an incorrect native FBSDK version is being used. are you using pods or added this library as a project to your ios project?

**Comment by ThiagoLovatine** [comment]
I added the library as a project, I downloaded it here: https://github.com/facebook/facebook-objc-sdk/releases (5.0.2)

**Comment by redcancode** [comment]
@ThiagoLovatine that should be okay then. can you check this file in your project? `node_modules/react-native-fbsdk/ios/RCTFBSDK/login/RCTFBSDKLoginManager.m`. can you paste line 74 from that file?

**Comment by ThiagoLovatine** [comment]
![Screen Shot 2019-06-19 at 19 12 44](https://user-images.githubusercontent.com/1659635/59804957-40366f80-92c6-11e9-9e28-45a906dbf98f.png)

**Comment by redcancode** [comment]
@ThiagoLovatine that looks perfect. i believe your issue is different than this one. i assume you don't use pods and add every library as a project to your project and you don't have `RCTFBSDK.xcodeproj` added to your project.

if you look at your error message `Cannot read property logInWithPermissions of undefined` below that it says `FBLoginManager.js:68:24` which means the error came from line 68 in that file. if you look at that line here https://github.com/facebook/react-native-fbsdk/blob/0.10.0-stable/js/FBLoginManager.js#L68 then you will see that `LoginManager` is undefined, which if you check on top the file see that it's the actual native module.

can you open a new issue about `RCTFBSDK.xcodeproj` not being added after `react-native link`? i will take a look at that later. so far i always installed it as a pod.

**Comment by ThiagoLovatine** [comment]
With cocoapods I got this:

error: Build input file cannot be found: '/Users/thiagolovatine/apps/FoodParkCarioca/node_modules/react-native-fbsdk/ios/RCTFBSDK/core/RCTFBSDKInitializer.m'

**Comment by 4hZhQiBHl4jRsshhb2Yo** [comment]
for me `logInWithPermissions` is worked. thanks. notice the capital.

**Comment by ThiagoLovatine** [comment]
I found the problem, I didn't see the code to add in AppDelegate.m:
#import <FBSDKCoreKit/FBSDKCoreKit.h> and the rest of the code after that:
https://developers.facebook.com/quickstarts/2069367446694544/?platform=ios

After adding this code it worked, with Pod and without Pods.
react-native-fbsdk version 0.10.0
FBSDK version 5.0.2

Thanks for the help!

**Comment by aliasgharkarani** [comment]
<img width="1297" alt="Screenshot 2019-06-20 at 6 54 22 PM" src="https://user-images.githubusercontent.com/33603201/59854746-ec428e00-938c-11e9-993f-b137d425ec67.png">


Still getting this.

**Comment by ausaquiVS** [comment]
@aliasgharkarani I think you have a typo in `loginWithPermissions` method, it should be `logInWithPermissions`.

**Comment by aliasgharkarani** [comment]
Down Gradding to 0.8.0 Fixed for me.

**Comment by neuberoliveira** [comment]
I was having the same issue, but on android, turns out that was a cache problem (weird). I just delete the dir `~/Library/Caches/typescript/3.5/node_modules/@types/react-native-fbsdk` (path can diff a little) this solved the issue for me.

**Comment by baudev** [comment]
> I was having the same issue, but on android, turns out that was a cache problem (weird). I just delete the dir `~/Library/Caches/typescript/3.5/node_modules/@types/react-native-fbsdk` (path can diff a little) this solved the issue for me.

Indeed, the `types` of `react-native-fbsdk` are not corresponding to the `0.10.0` version but only the `0.8.0`.

**Comment by jonathanmachado** [comment]
I have same problem :(

I use official doc but don't working 

"react-native-fbsdk": "^0.10.1",

Pre-downloading: `FBSDKCoreKit` from `https://github.com/facebook/facebook-objc-sdk.git`
Pre-downloading: `FBSDKLoginKit` from `https://github.com/facebook/facebook-objc-sdk.git`
Pre-downloading: `FBSDKShareKit` from `https://github.com/facebook/facebook-objc-sdk.git`
Downloading dependencies
Installing FBSDKCoreKit (5.1.1)
Installing FBSDKLoginKit (5.1.1)
Installing FBSDKShareKit (5.1.1)

Please help

**Comment by ausaquiVS** [comment]
Are you using pods @jonathanmachado ?

**Comment by jonathanmachado** [comment]
yes but not working, I try to link libray librctFBSDK.a but broken build iOS, only iOS don't working

**Comment by ausaquiVS** [comment]
what it is failing, installing pod dependencies?

**Comment by jonathanmachado** [comment]
Nop I have same error after call LoginManager.logInWithReadPermissions in react native, Primise is rejected.

**Comment by ausaquiVS** [comment]
`logInWithReadPermissions` is a method from `react-native-fbsdk` version 0.8.0, you should use instead `logInWithPermissions`

**Comment by ausaquiVS** [comment]
By the way, You shouldn't link librctFBSDK.a if you are using react-native-fbsdk version 0.10.0 and FBSDK version 5.0.2. Unlink it, if you don't want a broken build.

**Comment by jonathanmachado** [comment]
Sure I remove.

May be I have a problem vinculate sdk in AppDelegate.m?

`/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>
#import <React/RCTLinkingManager.h>
#import <RNGoogleSignin/RNGoogleSignin.h>
#import <FBSDKCoreKit/FBSDKCoreKit.h>

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  
  [[FBSDKApplicationDelegate sharedInstance] application:application
                           didFinishLaunchingWithOptions:launchOptions];
  
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"EscuelaPlus"
                                            initialProperties:nil];

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

- (BOOL)application:(UIApplication *)application openURL:(nonnull NSURL *)url options:(nonnull NSDictionary<NSString *,id> *)options {
  return [RNGoogleSignin application:application
                             openURL:url
                   sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]
                          annotation:options[UIApplicationOpenURLOptionsAnnotationKey]];
}

- (void)applicationDidBecomeActive:(UIApplication *)application {
  [FBSDKAppEvents activateApp];
}

- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
  
  return [[FBSDKApplicationDelegate sharedInstance] application:application
                                                        openURL:url
                                              sourceApplication:sourceApplication
                                                     annotation:annotation]
  
  || [RNGoogleSignin application:application openURL:url sourceApplication:sourceApplication annotation:annotation]
  
  || [RCTLinkingManager application:application openURL:url sourceApplication:sourceApplication annotation:annotation]
  
  || [[FBSDKApplicationDelegate sharedInstance] application:application openURL:url sourceApplication:sourceApplication annotation:annotation];
  
}


@end
`

**Comment by jonathanmachado** [comment]
My pod file

`# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  pod 'GoogleSignIn'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'FacebookSDK'

end
`

**Comment by ausaquiVS** [comment]
mmm, what version did you get installed? because you are not specifying FBSDK version there?

**Comment by jonathanmachado** [comment]
`Installing Bolts (1.9.0)
Installing FBSDKCoreKit (4.40.0)
Installing FBSDKLoginKit (4.40.0)
Installing FBSDKMarketingKit (4.38.0)
Installing FBSDKShareKit (4.40.0)
Installing FacebookSDK (4.38.0)
Installing GTMSessionFetcher (1.2.2)
Installing GoogleSignIn (4.4.0)
Installing GoogleToolboxForMac (2.2.1)`

**Comment by jonathanmachado** [comment]
You recommend one specific?

**Comment by ausaquiVS** [comment]
It doesn't look ok, you are using an outdated version for `react-native-fbsdk` 0.10.0, use the one the library specifies in the `react-native-fbsdk.podspec` file in `node_modules/react-native-fbsdk`.

**Comment by ausaquiVS** [comment]
Adding this line `pod 'react-native-fbsdk', :path=> '{relative_path}/node_modules/react-native-fbsdk'` to the Podfile

**Comment by jonathanmachado** [comment]
Installing FBSDKCoreKit (5.0.0)
Installing FBSDKLoginKit (5.0.2)
Installing FBSDKMarketingKit (5.0.0)
Installing FBSDKShareKit (5.0.2)
Installing FacebookSDK (5.0.2)
Installing GTMSessionFetcher (1.2.2)
Installing GoogleSignIn (4.4.0)
Installing GoogleToolboxForMac (2.2.1)

**Comment by ausaquiVS** [comment]
Ok, are you getting the build? Remember to use `logInWithPermissions`.

**Comment by jonathanmachado** [comment]
Sorry my build failed 

'React/RCTConvert.h' file not found in node_modules/react-native-fbsdk/ios/RCTFBSDK/login/RCTConvert+FBSDKLogin.m

**Comment by ausaquiVS** [comment]
You have in ios/Libraries this file `RCTFBSDK.xcodeproj`?

**Comment by jonathanmachado** [comment]
Nice @ausaquiVS thanks you save my day.

My Pods file.

`pod 'GoogleSignIn'
  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  rn_path = '../node_modules/react-native'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
    end
  end`

**Comment by yazhengwang** [comment]
@redcancode  thanks, I resolve😄

**Comment by Ethan0007** [comment]
hi, im having the same issue, Cannot read property 'logInWithPermissions' of undefined i downloaded the sdk and drag in Frameworks, also tried to install using the POD. got an error .
also, following docs on https://developers.facebook.com/docs/ios/getting-started/.

<img width="523" alt="Scr
![Screen Shot 2019-07-01 at 5 09 13 PM](https://user-images.githubusercontent.com/12542052/60428447-0436cf00-9c23-11e9-93a1-8514b72e8aa8.png)

een Shot 2019-07-01 at 10 09 27 AM" src="https://user-images.githubusercontent.com/12542052/60428320-c89c0500-9c22-11e9-8884-db379db85726.png">

**Comment by yazhengwang** [comment]
@Ethan0007 you should make sure the verison of  FBSDKCoreKit / FBSDKLoginKit 
and FBSDKShareKit

**Comment by Ethan0007** [comment]
@yazhengwang I'm using FacebookSDKs-iOS-4.40.0.

**Comment by Pausania** [comment]
> Cannot read property 'logInWithPermissions' of undefined

I'm having the same issue with pods or manual install...

**Comment by yazhengwang** [comment]
@Ethan0007 i have updated 0.5.10, it's ok

**Comment by Ethan0007** [comment]
Sir, can you please send me the exact guide on how can i do the configuration? Im still getting the same error even if i updated the version, i used manual and pod setup but no luck. 

Thanks..

**Comment by yazhengwang** [comment]
@Ethan0007 
 "react-native-fbsdk": "^0.10.1",
![image](https://user-images.githubusercontent.com/14901532/60693891-9b936f00-9f0e-11e9-9325-a7fa32c7fb4c.png)
you can try it ,good luck

**Comment by Ethan0007** [comment]
i used 5.2.1 and it works, thank you!

**Comment by deepakgd** [comment]
> @aliasgharkarani I think you have a typo in `loginWithPermissions` method, it should be `logInWithPermissions`.

Thanks @ausaquiVS

**Comment by NarendraSingh88** [comment]
> _reactNativeFbsdk.logInWithPermissions is not a function. (In '_reactNativeFbsdk.logInWithPermissions(['public_profile','email'])', '_reactNativeFbsdk.logInWithPermissions' is undefined)

Tried with **LoginManager.logInWithPermissions**

"**react-native**": "**^0.59.5**",

"**react-native-fbsdk**": "**^0.10.1**",

![fbsdk_login_error](https://user-images.githubusercontent.com/39184801/62305299-4ad74d80-b49d-11e9-9692-09686e9eacb7.jpg)

**Comment by losheredos** [comment]
Same issue in RN 0.60.4, what to do? Any suggestions?

**Comment by blueromans** [comment]
> Same issue for android in RN 0.60.4, what to do? Any suggestions?

use logInWithPermissions

**Comment by msqar** [comment]
Guys, im super frustrated.

i'm trying to implement Facebook login in my React-Native app but for some reason, it's throwing `Cannot read property 'logInWithPermissions' of undefined`.
I'm using `React-Native 0.60.4`.
I've downloaded `FacebookSDK 5.3.0` (_Stable framework)

Attempted using Cocoapod but after some research, many people don't suggest using it because it messes up the project.

These are the steps I followed:

 1. Downloaded FacebookSDK 5.3.0 (current latest up to 08/15/19)
 2. Dropped the `FBSDKCoreKit.framework`, `FBSDKLoginKit.framework` and `FBSDKShareKit.framework` inside a folder as `~/Documents/FacebookSDK`. 
 3. Also dropped those 3 framework files inside my project in XCode in the `/Frameworks` folder. 
 4. Just in case, I also added the path `~/Documents/FacebookSDK` in the Framework Search Paths under Build Settings.
 5. Made a Build on XCode, it's successful. 
 6. I download react-native-fbsdk from my react-native project. It downloads version 1.0.1.
 7. I don't add `libRTCFBSDK.a` file in the `Link binary with Libraries` because it throws an error saying the `FBSDKShareKit.h isn't found`.

This is what I do on my AuthView.js, I add this to a simple bound onPress event in a TouchableOpacity.

```
const FBSDK = require('react-native-fbsdk');
const {
  LoginManager,
} = FBSDK;

handleFacebookLogin() {
        LoginManager.logInWithPermissions(['public_profile', 'publish_actions']).then(
            (result) => {
                if (result.isCancelled) {
                    console.log('Login cancelled')
                } else {
                    console.log('Login success with permissions: ' + result.grantedPermissions.toString())
                }
            },
            (error) => {
                console.log('Login fail with error: ' + error)
            }
        )
    }
```


Now, I notice that inside Facebook's `FBLoginManager.js` this is the function being called

```
logInWithPermissions(permissions: Array<string>): Promise<LoginResult> {
    return LoginManager.logInWithPermissions(permissions);
  },
```

Whenever I hover LoginManager, it says it's **undefined**. Why would this be undefined? When it's literally a const on top of the file

`const LoginManager = require('react-native').NativeModules.FBLoginManager;`

Can anyone help me? I've been struggling for 4 days now. I already attempted installing it with cocoapods, no success. Then doing `react-native link react-native-fbsdk` no success... a lot of people suggested NOT using link but doing it manually.

What else could I try? Thanks.

**Comment by msqar** [comment]
Also, if i DO add libRTCFBSDK.a to the Copy link to Libraries. I get the following error while building.

```
Showing Recent Messages
/Users/marian-mac/Documents/dev/MyApp/node_modules/react-native-fbsdk/ios/RCTFBSDK/login/RCTFBSDKLoginButtonManager.m:22:9: 'React/RCTComponentEvent.h' file not found
```

**Comment by msqar** [comment]
Ended up doing this https://github.com/facebook/react-native-fbsdk/issues/580#issuecomment-512356091 and worked!

**Comment by Yurdaaaaa** [comment]
@4hZhQiBHl4jRsshhb2Yo worked for me thanks !

**Comment by jekar6630** [comment]
Try this:
1. Remove node_modules directory
2. Npm install expo-facebook
3. Import * as Facebook from 'expo-facebook';
4. Use Facebook.logInWithReadPermissionsAsync(yourid,permissions)

**Comment by creditcoder** [comment]
> @aliasgharkarani I think you have a typo in `loginWithPermissions` method, it should be `logInWithPermissions`.

Thanks @ausaquiVS!
