### ISSUE TITLE
 Build Error: package android.support.annotation does not exist import android.support.annotation.Nullable

### ISSUE THREAD

**Issue by roshan-p** [facebook/react-native-fbsdk#567]
I get this Erros after Android X migration, Please help
Package.json
 "react-native": "0.57.0",
 "react-native-fbsdk": "^0.10.0",

Erros:
`> Task :react-native-fbsdk:compileReleaseJavaWithJavac FAILED
/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBLikeViewManager.java:24: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBAppEventsLoggerModule.java:23: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBLoginButtonManager.java:23: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBLikeViewManager.java:51: error: cannot find symbol
    public void setObjectIdAndType(RCTLikeView likeView, @Nullable ReadableMap objectIdAndType) {
                                                          ^
  symbol:   class Nullable
  location: class FBLikeViewManager
/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBLikeViewManager.java:60: error: cannot find symbol
    public void setLikeViewStyle(RCTLikeView likeView, @Nullable String likeViewStyle) {
                                                        ^
  symbol:   class Nullable
  location: class FBLikeViewManager
/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBLikeViewManager.java:65: error: cannot find symbol
    public void setAuxiliaryViewPosition(RCTLikeView likeView, @Nullable String auxiliaryViewPosition) {
                                                                ^
  symbol:   class Nullable
  location: class FBLikeViewManager
/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBLikeViewManager.java:70: error: cannot find symbol
    public void setHorizontalAlignment(RCTLikeView likeView, @Nullable String horizontalAlignment) {
                                                              ^
  symbol:   class Nullable
  location: class FBLikeViewManager
/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBAppEventsLoggerModule.java:175: error: cannot find symbol
      @Nullable ReadableMap parameters) {
       ^
  symbol:   class Nullable
  location: class FBAppEventsLoggerModule
/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBAppEventsLoggerModule.java:187: error: cannot find symbol
     public void logPushNotificationOpen(@Nullable ReadableMap payload) {
                                          ^
  symbol:   class Nullable
  location: class FBAppEventsLoggerModule
/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBAppEventsLoggerModule.java:210: error: cannot find symbol
     @Nullable
      ^
  symbol:   class Nullable
  location: class FBAppEventsLoggerModule
/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBLoginButtonManager.java:62: error: cannot find symbol
    public void setLoginBehavior(RCTLoginButton loginButton, @Nullable String loginBehavior) {
                                                              ^
  symbol:   class Nullable
  location: class FBLoginButtonManager
/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBLoginButtonManager.java:67: error: cannot find symbol
    public void setDefaultAudience(RCTLoginButton loginButton, @Nullable String defaultAudience) {
                                                                ^
  symbol:   class Nullable
  location: class FBLoginButtonManager
/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBLoginButtonManager.java:74: error: cannot find symbol
            @Nullable ReadableArray publishPermissions) {
             ^
  symbol:   class Nullable
  location: class FBLoginButtonManager
/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBLoginButtonManager.java:81: error: cannot find symbol
            @Nullable ReadableArray readPermissions){
             ^
  symbol:   class Nullable
  location: class FBLoginButtonManager
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/xxxxx/Documents/GitHub/xxxxxxx/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/Utility.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.`

**Comment by redcancode** [comment]
this is a very interesting issue. i think it shouldn't be happening. your error log mentions this file `/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBLikeViewManager.java` which doesn't exist in 0.10.0, you can check it in the repo. are you sure you've pulled in the correct version of this library?

**Comment by roshan-p** [comment]
@redcancode OK So I have tried delete node_modules and build it again I still get the same errors but not with "FBLikeViewManager.java" anymore.

Errors:
`> Task :react-native-fbsdk:compileReleaseJavaWithJavac FAILED
/Users/xxx.p/Documents/GitHub/xxx/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBAppEventsLoggerModule.java:23: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/xxx.p/Documents/GitHub/xxx/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBLoginButtonManager.java:23: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/xxx.p/Documents/GitHub/xxx/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/Utility.java:52: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;
                                 ^
/Users/xxx.p/Documents/GitHub/xxx/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBAppEventsLoggerModule.java:175: error: cannot find symbol
      @Nullable ReadableMap parameters) {
       ^
  symbol:   class Nullable
  location: class FBAppEventsLoggerModule
/Users/xxx.p/Documents/GitHub/xxx/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBAppEventsLoggerModule.java:187: error: cannot find symbol
     public void logPushNotificationOpen(@Nullable ReadableMap payload) {
                                          ^
  symbol:   class Nullable
  location: class FBAppEventsLoggerModule
/Users/xxx.p/Documents/GitHub/xxx/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBAppEventsLoggerModule.java:210: error: cannot find symbol
     @Nullable
      ^
  symbol:   class Nullable
  location: class FBAppEventsLoggerModule
/Users/xxx.p/Documents/GitHub/xxx/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBAppEventsLoggerModule.java:226: error: cannot find symbol
    private @Nullable String getNullableString(ReadableMap data, String key) {
             ^
  symbol:   class Nullable
  location: class FBAppEventsLoggerModule
/Users/xxx.p/Documents/GitHub/xxx/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBLoginButtonManager.java:57: error: cannot find symbol
    public void setLoginBehavior(RCTLoginButton loginButton, @Nullable String loginBehavior) {
                                                              ^
  symbol:   class Nullable
  location: class FBLoginButtonManager
/Users/xxx.p/Documents/GitHub/xxx/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBLoginButtonManager.java:62: error: cannot find symbol
    public void setDefaultAudience(RCTLoginButton loginButton, @Nullable String defaultAudience) {
                                                                ^
  symbol:   class Nullable
  location: class FBLoginButtonManager
/Users/xxx.p/Documents/GitHub/xxx/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBLoginButtonManager.java:69: error: cannot find symbol
            @Nullable ReadableArray publishPermissions) {
             ^
  symbol:   class Nullable
  location: class FBLoginButtonManager
/Users/xxx.p/Documents/GitHub/xxx/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/Utility.java:306: error: cannot find symbol
    public static @Nullable List<String> reactArrayToStringList(@Nullable ReadableArray array) {
                                                                 ^
  symbol:   class Nullable
  location: class Utility
/Users/xxx.p/Documents/GitHub/xxx/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/Utility.java:306: error: cannot find symbol
    public static @Nullable List<String> reactArrayToStringList(@Nullable ReadableArray array) {
                   ^
  symbol:   class Nullable
  location: class Utility
/Users/xxx.p/Documents/GitHub/xxx/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBLoginManagerModule.java:145: error: cannot find symbol
            loginManager.logIn(activity,
                        ^
  symbol:   method logIn(Activity,List<String>)
  location: variable loginManager of type LoginManager
/Users/xxx.p/Documents/GitHub/xxx/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBAppEventsLoggerModule.java:237: error: cannot find symbol
      AppEventsLogger.setUserData(
                     ^
  symbol:   method setUserData(String,String,String,String,String,String,String,String,String,String)
  location: class AppEventsLogger
/Users/xxx.p/Documents/GitHub/xxx/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBGraphRequestModule.java:155: error: no suitable constructor found for AccessToken(String,String,String,<null>,<null>,<null>,<null>,<null>,<null>,<null>)
            graphRequest.setAccessToken(new AccessToken(
                                        ^
    constructor AccessToken.AccessToken(String,String,String,Collection<String>,Collection<String>,AccessTokenSource,Date,Date) is not applicable
      (actual and formal argument lists differ in length)
    constructor AccessToken.AccessToken(Parcel) is not applicable
      (actual and formal argument lists differ in length)
/Users/xxx.p/Documents/GitHub/xxx/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/FBLoginButtonManager.java:70: error: cannot find symbol
        loginButton.setPermissions(Utility.reactArrayToStringList(publishPermissions));
                   ^
  symbol:   method setPermissions(List<String>)
  location: variable loginButton of type RCTLoginButton
/Users/xxx.p/Documents/GitHub/xxx/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/Utility.java:68: error: no suitable constructor found for AccessToken(String,String,String,List<String>,List<String>,List<String>,AccessTokenSource,Date,Date,Date)
        return new AccessToken(
               ^
    constructor AccessToken.AccessToken(String,String,String,Collection<String>,Collection<String>,AccessTokenSource,Date,Date) is not applicable
      (actual and formal argument lists differ in length)
    constructor AccessToken.AccessToken(Parcel) is not applicable
      (actual and formal argument lists differ in length)
/Users/xxx.p/Documents/GitHub/xxx/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/Utility.java:95: error: cannot find symbol
            Arguments.fromJavaArgs(setToStringArray(accessToken.getExpiredPermissions())));
                                                               ^
  symbol:   method getExpiredPermissions()
  location: variable accessToken of type AccessToken
/Users/xxx.p/Documents/GitHub/xxx/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/Utility.java:99: error: cannot find symbol
        map.putDouble("dataAccessExpirationTime", (double) accessToken.getDataAccessExpirationTime().getTime());
                                                                      ^
  symbol:   method getDataAccessExpirationTime()
  location: variable accessToken of type AccessToken
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/xxx.p/Documents/GitHub/xxx/node_modules/react-native-fbsdk/android/src/main/java/com/facebook/reactnative/androidsdk/Utility.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
19 errors`

**Comment by duarte-evocorp** [comment]
Has anyone been able to solve the problem?

**Comment by janicduplessis** [comment]
Try version 1.0.0-rc.3 it should be compatible with androidx

**Comment by tokinonagare** [comment]
try to use androidx

```
// build.gradle 
implementation "androidx.annotation:annotation:1.1.0"

// where use it
import androidx.annotation.Nullable;
```

**Comment by roshan-p** [comment]
> Try version 1.0.0-rc.3 it should be compatible with androidx

Thanks It's work! :)

**Comment by ronakjain-2** [comment]
> Try version 1.0.0-rc.3 it should be compatible with androidx

can you please tell us. which module of 1.0.0-rc.3 version we need to use.

I am also getting the same issue when doing change
Upgrade com.android.tools.build:gradle to v3.2.1.
Upgrade compileSdkVersion to 28.
Update your app to use Jetpack (AndroidX)

**Comment by rkbansal** [comment]
@ronakjain-2 , it will be react-native-fbsdk
"react-native-fbsdk": "1.0.0-rc.3"

**Comment by praveens96** [comment]
1.0.0-rc.3 solves this issue but receiving issue saying:
error: constructor FBSDKPackage in class FBSDKPackage cannot be applied to given types; new FBSDKPackage()

**Comment by NestedLooper** [comment]
@praveens96 it needs to be 
`new FBSDKPackage(mCallbackManager)`
If you have an additional FBSDKPackage() without the callback manager being passed then remove it.

**Comment by faith-hb** [comment]
> try to use androidx
> 
> ```
> // build.gradle 
> implementation "androidx.annotation:annotation:1.1.0"
> 
> // where use it
> import androidx.annotation.Nullable;
> ```

Still won't do

**Comment by harleylovitos** [comment]
try this one.
https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility#not-recommended-manually-migrate-your-app

**Comment by harleylovitos** [comment]
i think this is the key

> In android/gradle/wrapper/gradle-wrapper.properties change the line starting with distributionUrl like this:

content_copy
distributionUrl=https\://services.gradle.org/distributions/gradle-4.10.2-all.zip

**Comment by harleylovitos** [comment]
npx jetify

**Comment by tgamauf** [comment]
> try to use androidx
> 
> ```
> // build.gradle 
> implementation "androidx.annotation:annotation:1.1.0"
> 
> // where use it
> import androidx.annotation.Nullable;
> ```

This + installing npx seems to have done it for me.

**Comment by fxbayuanggara** [comment]
> npx jetify

Thanks dude it works!

**Comment by Liqiankun** [comment]
Not work for me!

**Comment by dhevendhiran-adt** [comment]
> npx jetify

Thanks. It saved my day. React native is terrible.

**Comment by omprakashnitdgp** [comment]
Thanks,

It worked for me as well

**Comment by Liqiankun** [comment]
[build error: package com.android.annotations does not exist](https://github.com/react-native-community/react-native-image-picker/issues/1235)

**Comment by YangShaoXiong** [comment]
> npx jetify

it works. thanks

**Comment by ThaoTrinh** [comment]
> npx jetify

It worked for me.  Thanks

**Comment by jyoo** [comment]
> npx jetify

Thank you! 👍

**Comment by cloudtenlabs** [comment]
> try this one.
> https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility#not-recommended-manually-migrate-your-app

Are you crazy?

**Comment by surhidamatya** [comment]
> npx jetify

it works

**Comment by hussainarthuna** [comment]
> npx jetify

Thank you so much 😊

**Comment by inblind** [comment]
> npx jetify

wow! save me a ton of pain!

**Comment by SECRET-esc** [comment]
> npx jetify

Thanks! It`s work!

**Comment by priyanka-Sadh** [comment]
> npx jetify

Saviour  !

**Comment by khanhdevvn** [comment]
> npx jetify

Thankiu bro. 
you save mylife

**Comment by AhmadBadah** [comment]
> npx jetify
Thanks ..
it's work :)
