### ISSUE TITLE
No visible @interface for 'FBSDKShareOpenGraphAction' declares the selector 'initWithActionType:'

### ISSUE THREAD

**Issue by Kiran0791** [facebook/react-native-fbsdk#569]
react-native-fbsdk : 0.10.0 is throwing this issue.

**Comment by redcancode** [comment]
have you installed `react-native-fbsdk` as a pod or added it as a project?

**Comment by Kiran0791** [comment]
I have added it as project

**Comment by janicduplessis** [comment]
You need to update the fbsdk to v5, see release notes https://github.com/facebook/react-native-fbsdk/releases/tag/0.10.0

**Comment by dakoto747** [comment]
@janicduplessis I upgraded but still getting the issue. Does it work with a specific version of facebook iOS sdk? because I upgraded that as well.

**Comment by hugoh59** [comment]
The upgrade instructions are out of date, it's a mess.

**Comment by hugoh59** [comment]
@dakoto747 did you figure it out?

**Comment by nikhil-atlogys** [comment]
Hi I am also facing the same issue. I have tried fb framework v5, v4.42, v4.39 and still getting the same error.  Please help in this regard ?

**Comment by muratmerdogan** [comment]
Does anyone solve the problem ?

**Comment by dakoto747** [comment]
> @dakoto747 did you figure it out?
@hugoh59 
No, I had to revert to a previous build.

**Comment by nabilfreeman** [comment]
Hi, this worked for me, I upgraded from `v0.8.0` to `v0.10.1`. I had to replace the `~/Documents/FacebookSDK` directory with the v5 static library:

https://github.com/facebook/facebook-ios-sdk/releases/download/v5.12.0/FacebookSDK_Static.zip

**Comment by Mcebrera** [comment]
@nabilfreeman Thank you so much. I followed your comment and it successfully updated my FBSDK and xcode built successfully.
