### ISSUE TITLE
Does FBSDKAccessToken.getCurrentAccessToken() return null if access token has expired?

### ISSUE THREAD

**Issue by hzyIO** [facebook/react-native-fbsdk#57]
I looked around in the code and couldn't find the answer to this question. I'm trying to figure out some login logic and right now I'm basing my assumption that this is true, does anyone have a definitive answer?

**Comment by swiese** [comment]
It should return the current access token even if it is expired. The iOS sdk will try to do refreshes of the token periodically but if it expires because you app hasn't run in a long enough period you'll have to request a new token by doing a new login.

**Comment by hzyIO** [comment]
@swiese thank you for your response. Ended up implementing a check for expiration and token existence.
