### ISSUE TITLE
Are  'web' lobinBehavior deprecated?

### ISSUE THREAD

**Issue by tkow** [facebook/react-native-fbsdk#573]
As related to latest updated, https://github.com/facebook/react-native-fbsdk/issues/422 was not solution for re-login now.
Is there any alternafive? 
If we passed web to setLoginBehavior, error message show 

Invalid FBSDKLobinBehavior 'web'. should be one of :(browser)

**Comment by bernhardt1** [comment]
@tkow In the latest release they changed the login behavior enum. Here is a copy of the FBLoginManager file.

I do this now:
 `LoginManager.setLoginBehavior(Platform.OS === 'ios' ? 'browser' : 'native_with_fallback');`


```
export type LoginBehavior = LoginBehaviorIOS | LoginBehaviorAndroid;
/**
 * Indicate how Facebook Login should be attempted on Android.
 */
export type LoginBehaviorAndroid =
  // Attempt login in using the Facebook App, and if that does not work fall back to web dialog auth.
  | 'native_with_fallback'
  // Only attempt to login using the Facebook App.
  | 'native_only'
  // Only the web dialog auth should be used.
  | 'web_only';
/**
 * Indicate how Facebook Login should be attempted on iOS.
 */
export type LoginBehaviorIOS =
  // Attempts log in through the Safari browser.
  // This is the only behavior supported by the native sdk.
  'browser';
/**
```

**Comment by tkow** [comment]
@bernhardt1 Thanks for reply. This is an answer, so I close this issue.
