### ISSUE TITLE
react-native-fbsdk/ios/RCTFBSDK/login/RCTFBSDKLoginManager.m:78:3: Unknown type name 'FBSDKLoginManagerLoginResultBlock'; did you mean 'FBSDKLoginManagerLoginResult'?

### ISSUE THREAD

**Issue by erdemildiz** [facebook/react-native-fbsdk#574]
Same issue, anybody find solution? 

<img width="1436" alt="Screen Shot 2019-06-22 at 15 00 34" src="https://user-images.githubusercontent.com/5012592/59963643-ad344a00-94fe-11e9-8646-2b7c52cfe0f2.png">

<img width="348" alt="Screen Shot 2019-06-22 at 15 00 52" src="https://user-images.githubusercontent.com/5012592/59963665-f97f8a00-94fe-11e9-9f48-a1734f39e189.png">

_Originally posted by @erdemildiz in https://github.com/facebook/react-native-fbsdk/issues/570#issuecomment-504660065_

**Comment by GenghisJuan** [comment]
I just encountered this same problem. I fixed it by using the latest version of the SDK which I found here: https://github.com/facebook/facebook-objc-sdk/releases

**Comment by erdemildiz** [comment]
@GenghisJuan Which version and files did you download? I download `5.1.0` version. I am getting `Foundation.framework/Headers/Foundation.h:48:9: 'Foundation/NSKeyedArchiver.h' file not found` error.

**Comment by GenghisJuan** [comment]
FacebookSDK_Static.zip
Then I copied these into the frameworks:
![Screen Shot 2019-06-22 at 1 20 01 PM](https://user-images.githubusercontent.com/869613/59966279-84a55380-94f0-11e9-847c-d9687c9448cf.png)

**Comment by erdemildiz** [comment]
@GenghisJuan  Thanks, It's worked!!

**Comment by bernhardt1** [comment]
@erdemildiz  @GenghisJuan 

Thanks, your solution worked to get the build running. I am running to an error with the FB login  now, as described here: https://github.com/facebook/react-native-fbsdk/issues/583

**did you have to use cocoapods to get this API working properly?**

**Comment by MaxNative95** [comment]
Hey @GenghisJuan how you did to make it run? 
I was making a facebook login today and after trying to run on xcode i am facing the same issue.
Initializing 'FBSDKLoginManagerLoginResult *__strong' with an expression of incompatible type 'void (^)(FBSDKLoginManagerLoginResult *__strong, NSError *__strong)'

What do i have to do? 
Thanks

**Comment by arturcorvino** [comment]
I have the same issue here, but only in debug mode. In release mode, works for me. Any solution?

**Comment by janicduplessis** [comment]
Gonna close this since the initial error is resolved. Version 0.10+ is only compatible with version 5+ of the fbsdk
