### ISSUE TITLE
Can't find variable: GlobalStore

### ISSUE THREAD

**Issue by matthewswallace** [facebook/react-native-fbsdk#58]
I have the following in my view and I get the GlobalStore can't find error. 

```javascript
var FBSDKLogin = require('react-native-fbsdklogin');

//init facebook login
  fbTouchHandler(event) {
    FBSDKLoginManager.setLoginBehavior(GlobalStore.getItem('behavior', 'native'));
    FBSDKLoginManager.logInWithReadPermissions([], (error, result) => {
      if (error) {
        alert('Error logging in.');
      } else {
        if (result.isCancelled) {
          alert('Login cancelled.');
        } else {
          alert('Logged in.');
        }
      }
    });
  }
```

How do I resolve this ?

**Comment by philikon** [comment]
Well, it seems like you didn't define the `GlobalStore` variable that you're using in the `FBSDKLoginManager.setLoginBehavior()` line...

**Comment by matthewswallace** [comment]
Right! ... I'm asking how I import that so that it's available. The code is from an example in your Readme file. I figured I was ask being that I'm new to React Native and I'm not sure where GlobalStore needs to be required from.
