### ISSUE TITLE
ios_setup.js link is broken (404) 

### ISSUE THREAD

**Issue by lawrencehui** [facebook/react-native-fbsdk#588]
Hi, I try to follow the integration guid to configure iOS Project, Under the step 7 of Configure the Native iOS Project, the ios_setup.js file from the command 
`curl -O https://raw.githubusercontent.com/facebook/react-native-fbsdk/master/bin/ios_setup.js
`
returns a 404: Not Found in the file content

Is the file moved to elsewhere? please kindly update the official doc if the link has changed.

env
"react-native-fbsdk": "^0.10.1",

**Comment by ymc-thzi** [comment]
Same issue here. Found this old version
https://raw.githubusercontent.com/facebook/react-native-fbsdk/0.6.1/ios_setup.js

**Comment by jonliX2** [comment]
Same issue, what happened?

**Comment by lawrencehui** [comment]
> Same issue, what happened?

There documentation is out of date as using the older version of react-native-fbsdk and also older facebook-objc-sdk. Please see #586 @danfri86 reply on the proper config

**Comment by kessler9** [comment]
same issue
