### ISSUE TITLE
Was this you? "UIWebView on Apple iPhone 6s" is a confusing...

### ISSUE THREAD

**Issue by aphillipo** [facebook/react-native-fbsdk#59]
Hi there,

I'm seeing this screen (attached) and I find it really confusing for users of my app.  Any ideas how to change the text to say an Application Name instead of UIWebView?

<img width="525" alt="UIWebView Issue" src="https://cloud.githubusercontent.com/assets/52347/10892097/7f03c68c-8199-11e5-8d07-c2630ba77c2b.png">

Thanks!

**Comment by dzhuowen** [comment]
Hi,
Which login mode are you using? Can you provide more detail e.g screenshot for login?

**Comment by aphillipo** [comment]
Sure... So using the Login button and I just click to login, it takes me to a UIWebView on the simulator to authorise Facebook because I'm using the simulator (I understand first it will authorise through the settings if facebook is connected to the iPhone, then via the Facebook app if installed - neither are on the simulator).

I then authorise the app through the UIWebView and am returned to the app.  The screen above is not show then, but facebook on my computer has a notification about access granted to a browser!  The text on the notification reads: "Your account was logged in to from a new browser or device. Please review this login now."

When I click said notification I see the screenshot above.  If I was a user I would not think that UIWebView was something I had authorised!

**Comment by mingflifb** [comment]
What version of the Facebook SDK are you using, and what iOS version are you on (7/8/9)? The default should be to use either the SafariViewController of app switch to Safari instead of using UIWebView.

**Comment by aphillipo** [comment]
Just a crazy idea I thought it would say the application name?

I'm using iOS 9 so far as I know and FacebookSDK is version 4.6.

**Comment by mingflifb** [comment]
I don't think we're disagreeing. We're just trying to get as much information as possible so we can track down what's happening. This code is not related to the react-native SDK, so it involves figuring out what's happening behind the scenes.

**Comment by aphillipo** [comment]
Yes true that!  Um I could probably create a simple project for you guys if need be?

**Comment by dzhuowen** [comment]
Yes please create a simple project to reproduce. It would be great if you can report a bug at https://developers.facebook.com/bugs/ with the sample app.
