### ISSUE TITLE
Cant send advertiser_id with custom events

### ISSUE THREAD

**Issue by 1pocketaces1** [facebook/react-native-fbsdk#599]
## 🐛 Bug Report

 I am trying to send custom events using AppEventsLogger.logEvent() to record actions in my app, but the Analytics is not registering unique users with those custom events logged. I found  [here](https://developers.facebook.com/docs/marketing-api/app-event-api) that we need to include the advertiser_id with custom events. 
However, I cannot find a way to access this in React Native. I have used react-native-device-info but this only gives the IDFV on iOS and I am needing the IDFA. Is there a way to access this through the FBSDK?

On a related note, the AppEventsLogger would be much more powerful if it exposed more Standard Events such as ViewContent.

## To Reproduce

Send a custom event using AppEventsLogger.logEvent()

## Expected Behavior

 Expected to be able to target a lookalike audience with ads based on custom events in app.

## Environment

 react native: 0.58.3
react native fbsdk: 0.10.1

**Comment by nes123** [comment]
+1
