### ISSUE TITLE
FBSDKLoginManagerInterface is undefined

### ISSUE THREAD

**Issue by justinmakaila** [facebook/react-native-fbsdk#6]
I'm attempting to create my own login button using the `FBSDKLoginManager`. Everyt time I try to invoke a method on the login manager, I get some variation of this error:

![screen shot 2015-08-10 at 2 29 09 pm](https://cloud.githubusercontent.com/assets/1638996/9179716/7071c2aa-3f6c-11e5-980b-ac114a70a0fb.png)

Here's my button code:

```
const {
	Image,
	StyleSheet,
	Text,
	View,
} = React

import RectangleButton from '../RectangleButton/index'

import FBSDKLogin from 'react-native-fbsdklogin'
const {
	FBSDKLoginManager
} = FBSDKLogin

// TODO: Replace with a real facebook icon
const FACEBOOK_ICON = require('image!bottomBar__rewards--on')

export default class FacebookLoginButton extends React.Component {
	static defaultProps = {
		readPermissions: [],
		publishPermissions: [],
		onLoginFinished: () => {},
	}

	render() {
		const {
			style,
		} = this.props
		const icon = <Image source={FACEBOOK_ICON} style={styles.icon}/>

		return (
			<RectangleButton
				color='#3B5997'
				textColor='white'
				onPress={() => this.signIn()}
				icon={icon}
				iconStyles={styles.icon}
				textStyle={styles.text}
				style={[style, styles.button]}>
				
				Sign In With <Text style={styles.facebookLabel}>Facebook</Text>
			</RectangleButton>
		)
	}

	signIn() {
		const {
			readPermissions,
			onLoginFinished,
		} = this.props

		FBSDKLoginManager.logInWithReadPermissions(readPermissions, onLoginFinished)
	}
}

const styles = StyleSheet.create({
	button: {
		flexDirection: 'row',
	},

	text: {
		flex: 3,
		fontSize: 14,
	},
	facebookLabel: {
		fontWeight: 'bold',
	},

	icon: {
		flex: 1,
	}
})

```

**Comment by cphackm** [comment]
That error indicates the native login manager module wasn't found. Make sure you've correctly added the package to your Xcode project.

**Comment by justinmakaila** [comment]
@cphackm I've followed the instructions and I'm still dealing with the issue. Does it matter if the modules are added as folder references?

**Comment by cphackm** [comment]
@justinmakaila Adding them as folder references should be fine - that's how the sample app handles it. Which version of react-native-fbsdklogin do you have, and does the login button have any issues in the same project?

**Comment by justinmakaila** [comment]
@cphackm i'm using 0.0.3. I have issues with the login button. It doesn't display on the screen. I was participating in this thread: https://github.com/facebook/react-native-fbsdk/issues/1

**Comment by justinmakaila** [comment]
Turns out that the folder references were the problem. You can't add files from a folder reference as a compile source. Closing the issue.

**Comment by braco** [comment]
If anyone else finds this, running `rnpm link` after installing seemed to fix my problem. Should have been linked already, so not sure what happened.

**Comment by AndrewHenderson** [comment]
I ran into this issue because I started my work following the [React Native SDK](https://developers.facebook.com/docs/react-native/login) without having first followed the instructions for installing the [Facebook SDK](https://developers.facebook.com/docs/facebook-login/ios) in my iOS app.
