### ISSUE TITLE
Detailed Share API?

### ISSUE THREAD

**Issue by vinu123** [facebook/react-native-fbsdk#60]
I have run examples provided in readme.md but I was wondering if there's any place I could take a look at detailed Share API

**Comment by dzhuowen** [comment]
React Native FBSDK is a wrapper for the Facebook iOS SDK. You should check out the iOS SDK for detail.

**Comment by swiese** [comment]
https://developers.facebook.com/docs/sharing/ios
https://developers.facebook.com/docs/reference/ios/current/class/FBSDKShareAPI/

**Comment by vinu123** [comment]
I think I may have almost come close to sharing a linkcontent without the dialog (because that's what I want)

![linkcontent-without-the-dialog](https://cloud.githubusercontent.com/assets/240336/10965396/b0b3e9ce-83d2-11e5-828d-00f28a93c476.png)

This doesn't work though

**Comment by vinu123** [comment]
Thanks for the Documentation reference.
