### ISSUE TITLE
error: cannot find symbo  import androidx.annotation.Nullable;

### ISSUE THREAD

**Issue by DerekFei** [facebook/react-native-fbsdk#600]
After running react-native run-android 
This happens 

node_modules\react-native-fbsdk\android\src\main\java\com\facebook\reactnative\androidsdk\FBLoginButtonManager.java:62: error: cannot find symbol   
    public void setDefaultAudience(RCTLoginButton loginButton, @Nullable String defaultAudience) {
                                                                ^
  symbol:   class Nullable
  location: class FBLoginButtonManager
node_modules\react-native-fbsdk\android\src\main\java\com\facebook\reactnative\androidsdk\FBLoginButtonManager.java:69: error: cannot find symbol
            @Nullable ReadableArray publishPermissions) {
             ^
  symbol:   class Nullable
  location: class FBLoginButtonManager
\node_modules\react-native-fbsdk\android\src\main\java\com\facebook\reactnative\androidsdk\Utility.java:306: error: cannot find symbol
    public static @Nullable List<String> reactArrayToStringList(@Nullable ReadableArray array) {
                                                                 ^
  symbol:   class Nullable
  location: class Utility
\node_modules\react-native-fbsdk\android\src\main\java\com\facebook\reactnative\androidsdk\Utility.java:306: error: cannot find symbol
    public static @Nullable List<String> reactArrayToStringList(@Nullable ReadableArray array) {
                   ^
  symbol:   class Nullable
  location: class Utility
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: node_modules\react-native-fbsdk\android\src\main\java\com\facebook\reactnative\androidsdk\Utility.java uses unchecked or unsafe operations.   
Note: Recompile with -Xlint:unchecked for details.
12 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-fbsdk:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

**Comment by stevieoj** [comment]
This is likely an android x migration issue

**Comment by mohitbhansali** [comment]
Any solution for above? Facing the same issue.

**Comment by aricoz** [comment]
Same issue here :(

**Comment by IamMHC** [comment]
same issue here

**Comment by theyasirahmad** [comment]
**in android/gradle.properties add below two line. in my case solve issue using this.**
```
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by lomocc** [comment]
https://developer.android.com/jetpack/androidx

**Comment by arjdev69** [comment]
> **in android/gradle.properties add below two line. in my case solve issue using this.**
> 
> ```
> android.useAndroidX=true
> android.enableJetifier=true
> ```

Thanks

**Comment by myxit** [comment]
Hi,
It looks like I have a similar problem as topic started.
I have modified graddle.properties as theyasirahmad suggested did not help.

How to reproduce:
1. clone the repo
2. `yarn install && yarn run start` in `example/` folder
3. in another terminal run `npx react-native run-android`
as a result I get a lot of errors as above:
```
ImagePickerModule.java:15: error: package androidx.annotation does not exist
import androidx.annotation.NonNull;
```

Any ideas?

**Comment by dennysjmarquez** [comment]
Genial Funciona 100 Puntos 👍👍 @theyasirahmad

**Comment by fandu139** [comment]
> android.useAndroidX=true
> android.enableJetifier=true

i get error as 
```
Task :react-native-gesture-handler:compileDebugJavaWithJavac
/Users/fandupratamalakuana/test-interview/react-native/<my_folder>/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerModule.java:37: error: cannot find symbol
import androidx.annotation.Nullable;
```
end then this methods its works

**Comment by luisorduz** [comment]
Add the following two flags to true in your gradle.properties file at ProjectFolder/android/gradle.properties

android.useAndroidX=true
android.enableJetifier=true

Execute:
npm install --save-dev jetifier
npx jetify
npx react-native run-android

In your package.json add the following to scripts
"postinstall" : "npx jetify"

https://stackoverflow.com/questions/40380519/error-package-com-android-annotations-does-not-exist

**Comment by mishin** [comment]
implementation("com.google.code.findbugs:jsr305:3.0.2")
