### ISSUE TITLE
No visible @interface for 'FBSDKAccessToken' declares the selector 'initWithTokenString:permissions:declinedPermissions:expiredPermissions:appID:userID:expirationDate:refreshDate:dataAccessExpirationDate:'

### ISSUE THREAD

**Issue by khanhphamqn** [facebook/react-native-fbsdk#605]
## 🐛 Bug Report
Fresh install package and working on iOS build fails with:
> No visible @interface for 'FBSDKAccessToken' declares the selector 'initWithTokenString:permissions:declinedPermissions:expiredPermissions:appID:userID:expirationDate:refreshDate:dataAccessExpirationDate:'

## To Reproduce
-npm install react-native-fbsdk
-react-native link react-native-fbsdk
-download and unzip FacebookSDKs-iOS-4.40.0 
-From the Facebook SDK folder, drag the folder Bolts.framework, FBSDKCoreKit.Framework, FBSDKLoginKit.Framework, FBSDKShareKit.Framework into your Xcode Projects Framework folder.
-Open Xcode's "Build Settings" tab in your project and add the Facebook SDK folder's path to "Framework Search Paths" setting.
 -And follow all steps from this link
https://developers.facebook.com/docs/facebook-login/ios/?sdk=fbsdk
-Use xcode to build and the result will throw this issue
<img width="1259" alt="Screen Shot 2019-07-25 at 2 57 18 PM" src="https://user-images.githubusercontent.com/25603602/61856631-b85b0b00-aeec-11e9-95c7-55514594763f.png">
## Expected Behavior
Successful build

## Environment
react: ^16.8.6
react-native: 0.59.9
react-native-fbsdk: ^0.10.1
Xcode Version 9.4.1 (9F2000)

**Comment by eliasassuncao** [comment]
same problem !

**Comment by Ankushds** [comment]
ssame also here. entire library is mesh.

**Comment by m-tymchyk** [comment]
I have the same problem.

```
react: 16.8.6
react-native: 0.59.5
react-native-fbsdk: 0.10.1

Xcode Version 10.2.1 (10E1001)
```

**Comment by edicarloslds** [comment]
You need to update the Facebook SDK to v5.
release notes: https://github.com/facebook/react-native-fbsdk/releases/tag/0.10.0

**Comment by khanhphamqn** [comment]
@edicarloslds Thanks you. 
I solved this issue thanks to Facebook SDK v5.3.0. it just released 2 days ago
https://github.com/facebook/facebook-objc-sdk/releases/tag/v5.3.0
by downloading the static one and overwrite the files in folder FacebookSDKs-iOS-4.40.0.
and make sure you have to clear cache before build it again.

So I closed this issue.
Thanks for all of you

**Comment by blueneel05** [comment]
I am still getting this issue. I followed the installation instructions using cocoapods. Where do I put files downloaded from https://github.com/facebook/facebook-objc-sdk/releases/tag/v5.3.0 ??

**Comment by khanhphamqn** [comment]
@blueneel05 
Here is example of react native facebook you can download for reference. That I just created
without cocoapods https://github.com/khanhphamqn/loginFacebook
with cocopods https://github.com/khanhphamqn/loginFacebookUseCocoapods

hope you enjoy it

**Comment by witalobenicio** [comment]
@khanhphamqn where did you get the frameworks to work without cocoa pods?

**Comment by khanhphamqn** [comment]
@witalobenicio , you can access this link https://github.com/khanhphamqn/loginFacebook
in IOS folder there is a Frameworks folder that' what you need. Otherwise, Please follow this intruction https://developers.facebook.com/quickstarts/2269210073319606/?platform=ios and
download the latest release at https://github.com/facebook/facebook-ios-sdk/releases and overwrite it

**Comment by witalobenicio** [comment]
@khanhphamqn but in https://github.com/facebook/facebook-ios-sdk/releases we don't have the `.framework` anymore.

**Comment by witalobenicio** [comment]
@khanhphamqn I'm asking because I need to find a way to get those files in my CI/CD process.

**Comment by khanhphamqn** [comment]
@witalobenicio You'd better download the FacebookSDK_Static.zip and unzip it

**Comment by witalobenicio** [comment]
@khanhphamqn thanks :)

**Comment by witalobenicio** [comment]
@khanhphamqn do you have any clue why my project isn't working on release mode?
I've followed your tip to get from FacebookSDK_Static.zip and tried locally, and everything was just fine. But when I try on release, the app crashes and gives me the error of this issue.

**Comment by khanhphamqn** [comment]
@witalobenicio. I am not sure but I guess one reason. Could you please screenshot of IOS folder and **Framework Search Path** in Build Settings  and share it to me?
