### ISSUE TITLE
[Android] ShareDialog callback promise does not start

### ISSUE THREAD

**Issue by ryomura** [facebook/react-native-fbsdk#606]
## 🐛 Bug Report

ShareDialog callback promise does not start.

```
ShareDialog.show({contentType: 'link', contentUrl: 'http://example.com/'}).then(  
  (result) => { console.log(result); },    
  (error) => { console.log(error); }  
);
```

ShareDialog opens, but logs are not output when share or cancel.

In the Stable version, mCallbackManager is a static variable of mainActivity, but it is an instance variable in FBActivityEventListener of v1.0.0-rc.5.

Is the cause of this problem handled by mCallbackManager?

## Environment

react: 16.8.6
react-native: 0.60.3
react-native-fbsdk: v1.0.0-rc.5

**Comment by henriqueidt** [comment]
Same error here

**Comment by eran-pinhas** [comment]
#MeToo

**Comment by HelloCore** [comment]
Could you try this fork, it's from [this branch](https://github.com/HelloCore/react-native-fbsdk/tree/fix/android-callback-manager).
```
yarn add https://github.com/HelloCore/react-native-fbsdk.git\#fix/android-callback-manager
```

**Comment by vibdheeraj** [comment]
call back is not working
