### ISSUE TITLE
null is not an object (evaluating 'LoginManager.logWithPermission')

### ISSUE THREAD

**Issue by wellington-cunha** [facebook/react-native-fbsdk#607]

**Comment by wellington-cunha** [comment]
My AppDelegate.m 

is like that 


/**
 * Copyright (c) Facebook, Inc. and its affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

#import "AppDelegate.h"

#import <React/RCTBridge.h>
#import <React/RCTBundleURLProvider.h>
#import <React/RCTRootView.h>

#import <FBSDKCoreKit/FBSDKCoreKit.h>


@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  
  
  
  RCTBridge *bridge = [[RCTBridge alloc] initWithDelegate:self launchOptions:launchOptions];
  RCTRootView *rootView = [[RCTRootView alloc] initWithBridge:bridge
                                                   moduleName:@"ReactLogin"
                                            initialProperties:nil];
  
  [[FBSDKApplicationDelegate sharedInstance] application:application
                           didFinishLaunchingWithOptions:launchOptions];
 

  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}

- (NSURL *)sourceURLForBridge:(RCTBridge *)bridge
{
#if DEBUG
  return [[RCTBundleURLProvider sharedSettings] jsBundleURLForBundleRoot:@"index" fallbackResource:nil];
#else
  return [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
#endif
}

  - (void)applicationDidBecomeActive:(UIApplication *)application {
    [FBSDKAppEvents activateApp];
  }
  
  
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication
         annotation:(id)annotation {
  return [[FBSDKApplicationDelegate sharedInstance] application:application
                                                        openURL:url
                                              sourceApplication:sourceApplication
                                                     annotation:annotation];
}
  
  
  

  
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
            options:(NSDictionary<UIApplicationOpenURLOptionsKey,id> *)options {
  
  BOOL handled = [[FBSDKApplicationDelegate sharedInstance] application:application
                                                                openURL:url
                                                     sourceApplication:options[UIApplicationOpenURLOptionsSourceApplicationKey]
                                                           annotation:options[UIApplicationOpenURLOptionsAnnotationKey]
                  ];  
  // Add any custom logic here.
  return handled;
}
@end


My package.json is like this 

{
  "name": "ReactLogin",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-fbsdk": "^0.10.1"
  },
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/runtime": "^7.5.5",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.8.0",
    "eslint": "^6.1.0",
    "jest": "^24.8.0",
    "metro-react-native-babel-preset": "^0.55.0",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}

**Comment by rohanrana** [comment]
You have to download the latest [facebook sdk](https://github.com/facebook/facebook-objc-sdk/releases/tag/v5.2.3) because this SDK is not working and will run into errors like above
-  Then paste it into ~/Documents/FacebookSDK 


**this solution solved my problem**

**Comment by allthetime** [comment]
You have a type as well, it's 

`LogInWithPermissions`

Note the capital `I` for `In`

**Comment by smooJitter** [comment]
@rohanrana which file did you download.  I tried the source folder but the contents does reveal framework files

**Comment by wellington-cunha** [comment]
> You have a type as well, it's
> 
> `LogInWithPermissions`
> 
> Note the capital `I` for `In`
Yeah I wrote "logInWithPermission" and the error persists. I just mistype  on I wrote here.

**Comment by rohanrana** [comment]
@smooJitter  just see the image you have to download this zip file
![Screenshot 2019-08-01 at 10 40 47 AM](https://user-images.githubusercontent.com/32788793/62267243-23ef2c00-b449-11e9-80ef-747e7f570674.png)

**Comment by babaiyu** [comment]
> @smooJitter just see the image you have to download this zip file
> ![Screenshot 2019-08-01 at 10 40 47 AM](https://user-images.githubusercontent.com/32788793/62267243-23ef2c00-b449-11e9-80ef-747e7f570674.png)

I Just follow you for this solution, but there is still error
<img width="445" alt="Screen Shot 2019-08-01 at 15 24 34" src="https://user-images.githubusercontent.com/41254174/62277518-80b20d00-b470-11e9-85d5-d6f0f9a594b4.png">

**Comment by wellington-cunha** [comment]
@babaiyu I just make it work it`s pretty simple. dont need do add nothings

1 - after you run the command "react-native init [your project]"

2 -  add
on your package.json 
{
...
"react": "16.8.6",
 "react-native": "0.60.4",
"react-native-fbsdk": "git+https://github.com/facebook/react-native-fbsdk.git",
...
}

3 - on you Podfile
pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

4 - after yarn or npm your project go to ios folder pod install 

and that is it!

**Comment by wellington-cunha** [comment]
Hello everybody I am going to close this issue I think a gave a lot precious tips can solve problems.
