### ISSUE TITLE
Sharing a photo with URL, title and Description

### ISSUE THREAD

**Issue by vinu123** [facebook/react-native-fbsdk#61]
Using https://github.com/facebook/react-native-fbsdk#share-api successfully allows me to share a photo however, I cannot do following things.

1. Link an entire post (URL)
2. Provide title
3. Provide Description

Is there anyway, I could do this? I tried the following but it didn't work.
![sharing-a-photo-with-url-title-and-description](https://cloud.githubusercontent.com/assets/240336/10965934/350f0b42-83d6-11e5-8845-0df90d77187d.png)

This only shares a photo

**Comment by mingflifb** [comment]
What is the error that you're getting?

**Comment by vinu123** [comment]
Gives me an alert "Error sharing"

**Comment by dzhuowen** [comment]
Line 51 defines a linkContent and line 53 is sharing a photoContent. Do I miss something there?

**Comment by mingflifb** [comment]
You should also be able to print out the error, which may give you more details about what went wrong.
