### ISSUE TITLE
new FBSDKPackage() error with react native 0.60.4

### ISSUE THREAD

**Issue by prashantsingh0205** [facebook/react-native-fbsdk#614]
`react-native info` result
`info Fetching system and libraries information...
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Memory: 1.48 GB / 7.90 GB
  Binaries:
    Node: 10.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.12.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
  IDEs:
    Android Studio: Version  3.4.0.0 AI-183.6156.11.34.5692245`

Versions : 
`"react-native": "0.60.4",
"react-native-fbsdk": "^0.10.1",`

Error:
`P:\AppName\android\app\build\generated\rncli\src\main\java\com\facebook\react\PackageList.java:80: error: constructor FBSDKPackage in class FBSDKPackage cannot be applied to given types;
      new FBSDKPackage(),
      ^
  required: CallbackManager
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error

FAILURE: Build failed with an exception.`

Followed the following link for installation
https://github.com/facebook/react-native-fbsdk#installation

**Comment by Zontex** [comment]
Did you figured out how to solve it? I'm getting the same error, tried linking/unlinking and even not giving a callback to the FBSDKPackage. using the latest SDK and RN60.4

**Comment by ivanguimam** [comment]
same problem
