### ISSUE TITLE
Native Module FBAccessToken tried to override FBAccessTokenModule

### ISSUE THREAD

**Issue by yanguyt** [facebook/react-native-fbsdk#618]
## 🐛 Bug Report

  I'm trying to use Facebook login on my app, but when i try to run my application on Android i receive this message. When i go to my mainApplication.java to see if there is something duplicated, everything looks alright. By the way, on IOS it's working.

my config is
    "react": "16.8.6",
    "react-native": "0.60.4",
    "react-native-fbsdk": "^1.0.1",
    "react-native-firebase": "~5.5.6"

![Captura de Tela 2019-08-06 às 17 34 19](https://user-images.githubusercontent.com/46541206/62575143-75941e00-b870-11e9-98be-af2f819712f0.png)
 
```java
@Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());
      packages.add(new RNFirebaseNotificationsPackage());
      packages.add(new RNFirebaseMessagingPackage());
      packages.add(new FBSDKPackage());
      return packages;
    }
```

**Comment by janicduplessis** [comment]
I think you need to remove the packages.add(FBSDKPackage) line. The package should work with autolinking and doesn’t need to be included manuallly.

**Comment by junjun16818** [comment]
@janicduplessis 
Remove the packages.add(FBSDKPackage) line
Error
The sdk has not been initialized make sure to call facebooksdk.sdkinitialize

**Comment by dinhmai74** [comment]
I got the same issue if remove the packages.add(FBSDKPackage) line  @janicduplessis 
>The sdk has not been initialized make sure to call facebooksdk.sdkinitialize

**Comment by Rutheniceye92** [comment]
Had the same issue. had no duplicates in mainapplication file. Solved it by removing the `packages.add(new FBSDKPackage())` line. just like @janicduplessis suggested because that module was already being returned by `getPackages()` method. That's why it was being added again.

**Comment by akhzarna** [comment]
Remove the packages.add(FBSDKPackage) line
Error
The sdk has not been initialized make sure to call facebooksdk.sdkinitialize
