### ISSUE TITLE
Official Compatibility List 

### ISSUE THREAD

**Issue by fm09752** [facebook/react-native-fbsdk#630]
Hey, 

yesterday I started integrating FBSDK into my project and tried it with the following versions.

RN 0.59
FBSDK 5
react-native-fbsdk > 1.0.0

Seems like those versions are not compatible as react-native-fbsdk 1.0.0 requires RN 0.60 and upwards. Using a lower version than 5.0 for FacebookSDK causes Facebook to tell you to use a more recent version in the developer tools.

Can anyone provide a compatibility list of those versions working together? (Or a general one)

Upgrading to RN 0.60 would break a lot of things in the project. 

As far as I can say multiple people are searching for such a list, maybe it is helpful to the community. 

Cheers

**Comment by janicduplessis** [comment]
You can use version 0.10.+ with FBSDK 5 and RN 0.59.

Version 1.0+ support RN 0.60+

If someone wants to add a compatibility table in the readme that would be great.
