### ISSUE TITLE
[RN 0.59.10] Unable to run the app

### ISSUE THREAD

**Issue by yasir-netlinks** [facebook/react-native-fbsdk#641]
Im sorry for posting this here but I have updated the library from . `0.10.0` to `1.0.3` and now im facing all sorts of problems. At first this error:
```
Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:7:5-117 to override
```
I am still using `0.59.10` so it doesn't support androidx yet, how can I make this work ?
I was using `0.10.0` and for some reason FB restricted my app , and they told me that there are problems with your login integration, although I have already tested the login and it was working fine, however, this is why I am trying to update

## Environment
System:
      OS: macOS 10.14.3
      CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
      Memory: 46.25 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
      npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      Android SDK:
        API Levels: 23, 25, 27, 28
        Build Tools: 23.0.1, 23.0.2, 27.0.3, 28.0.0, 28.0.3
        System Images: android-19 | Google APIs Intel x86 Atom, android-21 | Google APIs ARM EABI v7a, android-21 | Google APIs Intel x86 Atom, android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.3 AI-182.5107.16.33.5314842
      Xcode: /undefined - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.10 => 0.59.10

**Comment by tobiastornros** [comment]
Since v1.0.0 the react-native-fbsdk require RN 0.60+

**Comment by jacquesdev** [comment]
@tobiastornros - can you please confirm that?

It's not at all clear from the docs? https://github.com/facebook/react-native-fbsdk#2-link

@janicduplessis - happy to update the docs myself, if you can just confirm this.

**Comment by tobiastornros** [comment]
@jacquesdev 

Have tried myself but found it [here](https://github.com/facebook/react-native-fbsdk/releases/tag/v1.0.0-rc.0)

**Comment by fabriziobertoglio1987** [comment]
I wish it was explained in the readme as I invested around 2-3 hours to configure the Facebook SignIn, but I don't have the time now to upgrade to rn0.60

The readme gives two options for installation, depending on rn 0.60 and 0.59
I would like to have facebook authentication before I launch my app, but seems to be a feature I will add later in the future.

Thansk
