### ISSUE TITLE
logInWithReadPermissions returning isCancelled value always true

### ISSUE THREAD

**Issue by jamesawer3** [facebook/react-native-fbsdk#646]
##  Bug Report
- I'm using react native fbsdk and trying to login but I'm getting isCancelled value as true always

---

## Environment

<details><summary>Click To Expand</summary>
<p>

**`react-native info` output:**

```
React Native Environment Info:
    System:
      OS: macOS 10.14.6
      CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
      Memory: 1.93 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 12.4.0 - /usr/local/bin/node
      npm: 6.9.2 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.0, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    IDEs:
      Android Studio: 3.5 AI-191.8026.42.35.5791312
      Xcode: 11.0/11A420a - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.5 => 0.59.5 
    npmGlobalPackages:
      react-native-cli: 2.0.1
```

- **Platform that you're experiencing the issue on**:
  - [ ] iOS
  - [ ] Android
  - [ ] **iOS** but have not tested behavior on Android
  - [ ] **Android** but have not tested behavior on iOS
  - [x] Both
- **`FBSDK` module(s) you're using that has the issue:**
  - `logInWithReadPermissions`
- **Are you using `TypeScript`?**
  - `N`
  
</p>
</details>

---

## To Reproduce
<details><summary>Click To Expand</summary>
<p>

- My `react-native-fbsdk` version is 0.8.0 and my `FacebookSDK's` version is 4.40.0
</p>
</details>

---

## Expected Behavior
<details><summary>Click To Expand</summary>
<p>

- I want to successfully login with facebook, I'm totally struck with this kindle help me
</p>
</details>

---

## Code
<details><summary>Click To Expand</summary>
<p>

```
LoginManager.logOut();
var result = await LoginManager.logInWithReadPermissions(["public_profile", "email"]);

```
</p>
</details>

---

## Response
<details><summary>Click To Expand</summary>
<p>

```
declinedPermissions: null
grantedPermissions: null
isCancelled: true

```
</p>
</details>

**Comment by stefancrowdbotics** [comment]
Same problem @HERE!

**Comment by ThomasPnt** [comment]
Same problem for me, but I'm on ^0.10.1 version

**Comment by lysontrung1706** [comment]
I got this problem, with ios13
"react-native-fbsdk": "^0.10.1",
LoginManager.logInWithPermissions => always return isCancelled:true

**Comment by Dunky45** [comment]
Same here :(, this needs to be fixed as soon as possible, or people are gonna eat us alive :-D.

**Comment by kostop19** [comment]
Quick workaround: Change the dependency of the react-native-fbsdk.podspec of all FBSDKCoreKit, FBSDKLoginKit, FBSDKShareKit entries to version 5.6.0

**Comment by jamesawer3** [comment]
I'm using sdk

**Comment by IrynaBt** [comment]
I have the same problem for 0.10.1

**Comment by Nidhi-Gandhi** [comment]
I also got the same problem with 13.0 and higher It's working fine in 12.2.
`
    "react-native-fbsdk": "^0.10.1",
`
I got this response on LoginManager.logInWithPermissions

```
declinedPermissions: null
grantedPermissions: null
isCancelled: true
```

**Comment by johnlim5847** [comment]
I'm having the same issue as well. I'm on `0.10.0` and using Pod, the FBSDKCoreKit, FBSDKLoginKit, FBSDKShareKit I installed are `5.0.2`

I can't even launch the popup modal(the open URL) it didn't show any error in chrome debugger nor in Xcode debugger. Can anyone help?

**Comment by johnlim5847** [comment]
it was working fine on iOS 12.2 but on iOS 13 I got `-canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. ` error when I try to call `logInWithPermissions` can anyone from the team help me?

**Comment by lysontrung1706** [comment]
pod 

> it was working fine on iOS 12.2 but on iOS 13 I got `-canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. ` error when I try to call `logInWithPermissions` can anyone from the team help me?
> 
> ```
> Pod
> 
>   pod 'FBSDKCoreKit', '~> 5.0.2'
>   pod 'FBSDKLoginKit', '~> 5.0.2'
>   pod 'FBSDKShareKit', '~> 5.0.2'
> 
> Npm
> 
> react-native-fbsdk 0.10.1
> ```
> 
> UPDATE: OK finally I got it running fine on `13.0` what I did was use `5.6.0` instead of `5.0.2`

Pod 
   pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk' 
   pod 'FBSDKCoreKit'  
   pod 'FBSDKLoginKit'
   pod 'FBSDKShareKit'
Npm
   react-native-fbsdk 0.10.1
I cannot update to 5.6.0
I got this error when pod install
 CocoaPods could not find compatible versions for pod "FBSDKShareKit":
  In Podfile:
    FBSDKShareKit (~> 5.6.0)

how I can resolve it ???

**Comment by lysontrung1706** [comment]
> pod
> 
> > it was working fine on iOS 12.2 but on iOS 13 I got `-canOpenURL: failed for URL: "fbauth2:/" - error: "The operation couldn’t be completed. ` error when I try to call `logInWithPermissions` can anyone from the team help me?
> > ```
> > Pod
> > 
> >   pod 'FBSDKCoreKit', '~> 5.0.2'
> >   pod 'FBSDKLoginKit', '~> 5.0.2'
> >   pod 'FBSDKShareKit', '~> 5.0.2'
> > 
> > Npm
> > 
> > react-native-fbsdk 0.10.1
> > ```
> > 
> > 
> > UPDATE: OK finally I got it running fine on `13.0` what I did was use `5.6.0` instead of `5.0.2`
> 
> Pod
> pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
> pod 'FBSDKCoreKit'
> pod 'FBSDKLoginKit'
> pod 'FBSDKShareKit'
> Npm
> react-native-fbsdk 0.10.1
> I cannot update to 5.6.0
> I got this error when pod install
> CocoaPods could not find compatible versions for pod "FBSDKShareKit":
> In Podfile:
> FBSDKShareKit (~> 5.6.0)
> 
> how I can resolve it ???

UPDATE
in my case 
I unlink react native fbsdk => pod install => link react native fbsdk again and I can update 5.6.0
But I got new problem "null is not an object(Evaluating 'LoginManager.logInWithPermissions')

**Comment by CoderAndroid** [comment]
**remove**
react-native-fbsdk from **pod** file 
and **add** in pod
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'

then
install the pod

when pod install successfully then try to add facebook libraries manually in project
**Steps**
Add file to project
goes to node_module folder>react-native-fbsdk >ios 
select RCTFBSDK.xcodeproj and add
then link libRCTFBSDK.a to libraries
 
search 
then link libraries

**Comment by florianalbrecht** [comment]
If you have problems updating to version 5.6.0 via Cocoapods just to "pod repo update" and "pod update FBSDKCoreKit FBSDKLoginKit FBSDKShareKit" afterwards.

**Comment by fostahgix** [comment]
I was able to get this working combining the two comments above (@florianalbrecht  and @lysontrung1706 )running the following:

`pod repo update
`
In your pod file
```
Pod

  pod 'FBSDKCoreKit', '~> 5.6.0'
  pod 'FBSDKLoginKit', '~> 5.6.0'
  pod 'FBSDKShareKit', '~> 5.6.0'

```
In your package.json
`"react-native-fbsdk": "0.10.1"`

Then run
`rm -rf node_modules && yarn && cd ios && pod install`

**Comment by Nidhi-Gandhi** [comment]
I was using react-native-fbsdk Without Cocoapods. So now I add these code to Podfile:
```
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  # pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
```
Then run `pod install`
When I tried to run this project then got error of duplicate references.
remove FBSDKCoreKit.framework, FBSDKLoginKit.framework, FBSDKShareKit.framework from "Frameworks" folder from the project directory(ProjectName=>Frameworks) and it's works perfect.

**Comment by stefancrowdbotics** [comment]
I fixed this issue when return to old version of xCode.
My current version is 10.3.0.
Version with error is 11.x.x

**Comment by ammichael** [comment]
Worked for me:

Project `package.json`:
```
    "react-native-fbsdk": "https://github.com/facebook/react-native-fbsdk.git#0.10.0-stable",
```
Podfile:
```
  pod 'FBSDKCoreKit', '~> 5.6.0'
  pod 'FBSDKLoginKit', '~> 5.6.0'
  pod 'FBSDKShareKit', '~> 5.6.0'
```

**Comment by vforvasile** [comment]
I'm not using Pods, my solution was to download the FBSDK (5.6.0) that supports iOS 13 (from [here](https://github.com/facebook/facebook-ios-sdk/releases)) and replace the old frameworks.

The above solution would work if you manually react-native-fbsdk

I am using `"react-native-fbsdk": "^0.10.0"`

**Comment by moulie415** [comment]
@ammichael your solution worked for me but I had to run
``` pod install --repo-update``` 
instead

**Comment by karltaylor** [comment]
> I'm not using Pods, my solution was to download FBSDK (5.6.0) that supports iOS 13 (from [here](https://github.com/facebook/facebook-ios-sdk/releases)) and replace the old frameworks.
> 
> The above solution will work if you manually link react-native-fbsdk
> 
> I am using
> `"react-native-fbsdk": "^0.10.0" "react-native": "0.59.9" `
> 
> p.s. using pods: '~> 5.6.0' I managed to build it but encountered an error when clicking log in, same as [here](https://github.com/facebook/react-native-fbsdk/issues/608#issuecomment-515989247)

So it is still not working for you on 0.59.9?

**Comment by chilidoggca** [comment]
react-native 0.59.10
react-native-fbsdk 0.10.1

I finally got this working in iOS 13 by manually linking react-native-fbsdk (follow instructions here): https://facebook.github.io/react-native/docs/linking-libraries-ios#manual-linking

Podfile
`pod 'FBSDKCoreKit', '~> 5.6.0'
  pod 'FBSDKLoginKit', '~> 5.6.0'
  pod 'FBSDKShareKit', '~> 5.6.0'`

**Comment by jamesawer3** [comment]
Updated my React native version updated fbsdk version and it started working like a charm

**Comment by wellmonge** [comment]
same here! rn-0.59.9 and fbsdk-0.10.1 --> trying to update to rn-0.60.9 and fbsdk-1.0.4...

**Comment by motogod** [comment]
> I was using react-native-fbsdk Without Cocoapods, and had the same issue,
> 
> Take others solutions, I think I should upgrade my `react-native-fbsdk` first.
> 
> ```
> "react-native": "0.57.1"
> "react-native-fbsdk": "0.8.0"
> ```
> 
> When I try to upgrade it by type command `yarn upgrade react-native-fbsdk@0.10.1`
> 
> Run the project shows the error:
> `/Users/motogod19/MyWork/SalonYarn/polipoli-mobile-salon/node_modules/react-native-fbsdk/ios/RCTFBSDK/login/RCTFBSDKLoginManager.m:78:3: Unknown type name 'FBSDKLoginManagerLoginResultBlock'; did you mean 'FBSDKLoginManagerLoginResult'?`
> 
> [<img alt="螢幕快照 2019-10-18 下午3 58 01" width="764" src="https://user-images.githubusercontent.com/17781603/67085642-c362c600-f1d1-11e9-8947-fe1e1430f8f0.png">](https://user-images.githubusercontent.com/17781603/67085642-c362c600-f1d1-11e9-8947-fe1e1430f8f0.png)
> 
> Any one has the same problem like me ?
> 
> How to solve it ?

Fix my issue now.

I can't fix my issue by replacing SDK version.  So I try to use cocopods.

Step 1:
`pod init`
Step 2:
Rember uncomment `platform :ios, '9.0'` on pod file before you type `pod install`
Step 3:
Delete your older Facebook SDK that is under project Framework folder and remove these framework under Link Binary With Libraries.

then Build will success.

**Comment by ChrisEelmaa** [comment]
solution by @vforvasile works. I will just say that `LoginManager.logInWithReadPermissions` is deprecated in react-native-fbsdk 0.10.1, so instead now you use` LoginManager.logInWithPermissions `

https://github.com/facebook/react-native-fbsdk/issues/566

**Comment by chungheepark** [comment]
I solved!

- My env:
  xcode: 11.1
  react: 16.8.3
  react-native: 0.59.9
  react-native-fbsdk: 0.10.1
  objectivec: yes
  pods: no
  
My iOS project is a legacy system based on objective-c with no pods. And I tried to use cocoapods, But I couldn't use cocoapods because of legacy search path settings.

1. Target-> BuildSettings
2. `$ {inherited}` syntax has been added to the Framework, Library, Header search path.
3. Sort `$ {inherited}` syntax to the top.

Then, add below line to Podfile:

```ruby
```

**Comment by praveenganesh** [comment]
I solved the issue!!

add following code in 2 files

strings.xml
__________________
 <string name="facebook_app_id">/*your app id*/</string>

AndroidManifest.xml
_______________________
<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>

**Comment by praveenganesh** [comment]
I solved the issue !!!

in your strings.xml file add the following code
 <string name="facebook_app_id">/*your app id*/</string>

then, AndroidManifest.xml file add the following line 
<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>

**Comment by praveenganesh** [comment]
I solved the issue !!!
Add following lines
**strings.xml**
 `<string name="facebook_app_id">/*your app id*/</string>`

**AndroidManifest.xml**
`<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>`

**Comment by Mcebrera** [comment]
_Upgrading my `react-native-fbsdk` from `0.8.0` to `0.10.0` fixed this issue for me._

For those who are having errors on Xcode when upgrading from `0.8.0` to `0.10.0`

I was having our FB button always return a isCancelled = true value when pressed. Essentially, it wasn't letting people in via FB button.

I found this comment and followed the instructions and it built successfully on Xcode
- https://github.com/facebook/react-native-fbsdk/issues/569#issuecomment-563269267

make sure you delete the bolt.framework file. I did every step up to that and it wasn't building but once I deleted it, it built successfully.

**Comment by MelihOzyurt** [comment]
> I solved!
> 
> * My env:
>   xcode: 11.1
>   react: 16.8.3
>   react-native: 0.59.9
>   react-native-fbsdk: 0.10.1
>   objectivec: yes
>   pods: no
> 
> My iOS project is a legacy system based on objective-c with no pods. And I tried to use cocoapods, But I couldn't use cocoapods because of legacy search path settings.
> 
> 1. Target-> BuildSettings
> 2. `${inherited}` syntax has been added to the Framework, Library, Header search path.
> 3. Sort `${inherited}` syntax to the top.
> 
> And add below line to Podfile:
> 
> ```ruby
> pod 'FBSDKCoreKit', '~> 5.6.0'
> pod 'FBSDKLoginKit', '~> 5.6.0'
> pod 'FBSDKShareKit', '~> 5.6.0'
> ```
> 
> Then you will be success to build!
 
I solved with your solution but i got this warning. 
> Duplicate symbols for architecture x86_64 under Xcode_ warning.

The problem was solved when i followed the steps below.

**Build Phases in Link Binary With Libraries,**
> 1. remove login/share/core.framework,
> 2. add login/share/core.a files.

Thank you.

**Comment by ahsanmster** [comment]
> **remove**
> react-native-fbsdk from **pod** file
> and **add** in pod
> pod 'FBSDKCoreKit'
> pod 'FBSDKLoginKit'
> pod 'FBSDKShareKit'
> 
> then
> install the pod
> 
> when pod install successfully then try to add facebook libraries manually in project
> **Steps**
> Add file to project
> goes to node_module folder>react-native-fbsdk >ios
> select RCTFBSDK.xcodeproj and add
> then link libRCTFBSDK.a to libraries
> 
> search
> then link libraries

after above steps i face following issue

![image](https://user-images.githubusercontent.com/32548815/94430833-efdadc80-01ad-11eb-8ac6-8d045a9d22de.png)

**Comment by olgaababic** [comment]
Did anyone have problem with Android? I get always isCancelled with Android devices. And it happens when I ask for email as permission.
