### ISSUE TITLE
Can't find variable: GlobalStore

### ISSUE THREAD

**Issue by bartonhammond** [facebook/react-native-fbsdk#65]
Using the provided example code for Login Manager:

```
// Attempt a login using the native login dialog asking for default permissions.
FBSDKLoginManager.setLoginBehavior(GlobalStore.getItem('behavior', 'native'));
FBSDKLoginManager.logInWithReadPermissions([], (error, result) => {
....
```
Error: Can't find variable: GlobalStore

BTW, when running on my ios device w/ FB installed, it appears that a safari browser window is displayed during FB login.  Is this the correct behavior?

**Comment by bartonhammond** [comment]
I tried the following and it works but still on both simulator and ios device w/ FB, a browser window is displayed.

```
FBSDKLoginManager.setLoginBehavior('native');
FBSDKLoginManager.logInWithReadPermissions(["email","user_friends"], (error, result) => {
```
Maybe the example Login Manager code should be update?

**Comment by mingflifb** [comment]
The use of SafariViewController is the expected behavior now. See our blog post explaining the feature here: https://developers.facebook.com/blog/post/2015/10/29/Facebook-Login-iOS9/

We'll update the docs around GlobalStore in a future update. Thanks for the report.
