### ISSUE TITLE
logInWithReadPermissions result does not given user details. Result contains about granted permission and declined permission only

### ISSUE THREAD

**Issue by Gautham21** [facebook/react-native-fbsdk#653]

**Comment by gmertk** [comment]
Hi @Gautham21
`logInWithReadPermissions` was deprecated a while ago. Can you make sure you are using the latest version of the SDK? 
See the Login Manager example on https://github.com/facebook/react-native-fbsdk#login with `logInWithPermissions` rather than `logInWithReadPermissions`
