### ISSUE TITLE
Property 'previewPhoto' not found on object of type 'FBSDKShareVideoContent *'

### ISSUE THREAD

**Issue by jamesawer3** [facebook/react-native-fbsdk#658]
## 🐛 Bug Report

![Screen Shot 2019-10-15 at 7 41 07 PM](https://user-images.githubusercontent.com/43437378/66839248-c23c5980-ef83-11e9-83f5-25955d814b51.png)

## To Reproduce

Added `pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'` in podfile and then gave `pod install`

## Environment
```
info Fetching system and libraries information...
System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Memory: 983.64 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    npm: 6.9.2 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2 
  npmGlobalPackages:
    react-native-cli: 2.0.1
```

**Comment by jamesawer3** [comment]
After upgrading to latest version of fbsdk this issue fixed for me

**Comment by Faheem0331** [comment]
Property 'isTestAdsEnabled' not found on object of type 'ALSdkSettings *'

I have same issue

**Comment by jamesawer3** [comment]
Try upgrading fbsdk to latest version @Faheem0331
