### ISSUE TITLE
Facebook comments plugin?

### ISSUE THREAD

**Issue by KestasVenslauskas** [facebook/react-native-fbsdk#660]
Is there any plans for facebook comments plugin integration?

**Comment by gmertk** [comment]
Hi @KestasVenslauskas, 
I believe comments plugin is only supported on the web.
Even the native Android  and iOS FB SDKs don't have comments plugin integration. 
As react-native-fbsdk is a wrapper around the native SDKs, I don't see this happening in the near future :)

**Comment by scaralfred** [comment]
Is there any update on this?
