### ISSUE TITLE
App stuck at launch screen after setting up sdk

### ISSUE THREAD

**Issue by shangsunset** [facebook/react-native-fbsdk#67]
Hi, 
for some reason, my app always gets stuck at the launch screen where shows the app name and 'powered by react native' on the bottom. 

no error from packager. just some warnings from xcode: `warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.1.sdk/Developer/Library/Frameworks'`

and in `RCTFBSDKShareAPI.m`: `'shareDidCancel' in protocol 'FBSDKSharingDelegate' not implemented`.

I tried running HNsample, same thing happened.

any help would be appreciated. thanks.

**Comment by alfonsodev** [comment]
Are you running react-native 0.14 ?

**Comment by shangsunset** [comment]
no the version is 0.12

**Comment by dzhuowen** [comment]
These warning shouldn't matter.

**Comment by alfonsodev** [comment]
Yeah, I can confirm it still works well in 0.14

**Comment by shangsunset** [comment]
i updated to 0.14 but the issue still persists.

**Comment by dzhuowen** [comment]
Hi @shangsunset , I haven't seen this issue before, it would be great if you can provide more detail like how you setup the project, stack trace in Xcode console, etc.  And here's something you can do to check.
1. The app runs successfully BEFORE and AFTER you remove all the subprojects under Libraries/ in Xcode and run pod install.
2. Add a login button in index.ios.js file like the sample code in README, build and run your app to see if you have the button on the welcome screen.

**Comment by shangsunset** [comment]
Hi,
I set up the project with the second option: using the provided Xcode projects. app works fine until I add FBSDK Xcode projects from node_modules to my app's Xcode project following [Linking Library Guide](http://facebook.github.io/react-native/docs/linking-libraries-ios.html)
![screen shot 2015-11-20 at 11 56 54 am](https://cloud.githubusercontent.com/assets/3700269/11306065/d978689c-8f7d-11e5-86fa-3aacda79fccf.png)


Before I linked sdk xcode project to my project, i could only see a red box and got a warning in the console: `warning:  Native component for "RCTFBSDKLoginButton" does not exist.` when i add a login button.

**Comment by shangsunset** [comment]
ok turns out the problem comes from RCTFBSDKShare.a. everything is fine until I linked it my xcode project.

and the output from xcode:

*** First throw call stack:
(
	0   CoreFoundation                      0x000000010857ff45 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x0000000107781deb objc_exception_throw + 48
	2   Cairn                               0x0000000106fbd702 __56+[FBSDKInternalUtility checkRegisteredCanOpenURLScheme:]_block_invoke + 0
	3   Cairn                               0x0000000106ff08db +[FBSDKShareDialog initialize] + 71
	4   libobjc.A.dylib                     0x0000000107782bff _class_initialize + 679
	5   libobjc.A.dylib                     0x0000000107788d23 lookUpImpOrForward + 176
	6   libobjc.A.dylib                     0x00000001077978bb objc_msgSend + 187
	7   Cairn                               0x0000000106f8ee06 -[RCTFBSDKShareDialog init] + 134
	8   Cairn                               0x0000000106f21eac -[RCTBatchedBridge initModules] + 2556
	9   Cairn                               0x0000000106f1f0df -[RCTBatchedBridge start] + 399
	10  Cairn                               0x0000000106f1eeef -[RCTBatchedBridge initWithParentBridge:] + 1695
	11  Cairn                               0x0000000106f45458 -[RCTBridge setUp] + 504
	12  Cairn                               0x0000000106f44bd9 -[RCTBridge initWithBundleURL:moduleProvider:launchOptions:] + 649
	13  Cairn                               0x0000000106edf717 -[RCTRootView initWithBundleURL:moduleName:initialProperties:launchOptions:] + 183
	14  Cairn                               0x0000000106eca9d0 -[AppDelegate application:didFinishLaunchingWithOptions:] + 192
	15  UIKit                               0x0000000109e8bf24 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:] + 272
	16  UIKit                               0x0000000109e8d0ca -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:] + 3415
	17  UIKit                               0x0000000109e939c3 -[UIApplication _runWithMainScene:transitionContext:completion:] + 1750
	18  UIKit                               0x0000000109e90ba3 -[UIApplication workspaceDidEndTransaction:] + 188
	19  FrontBoardServices                  0x000000010c1d6784 -[FBSSerialQueue _performNext] + 192
	20  FrontBoardServices                  0x000000010c1d6af2 -[FBSSerialQueue _performNextFromRunLoopSource] + 45
	21  CoreFoundation                      0x00000001084ac011 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	22  CoreFoundation                      0x00000001084a1f3c __CFRunLoopDoSources0 + 556
	23  CoreFoundation                      0x00000001084a13f3 __CFRunLoopRun + 867
	24  CoreFoundation                      0x00000001084a0e08 CFRunLoopRunSpecific + 488
	25  UIKit                               0x0000000109e904f5 -[UIApplication _run] + 402
	26  UIKit                               0x0000000109e9530d UIApplicationMain + 171
	27  Cairn                               0x0000000106ecaf0f main + 111
	28  libdyld.dylib                       0x000000010bb3292d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by dzhuowen** [comment]
@shangsunset it might be the same issue #71
