### ISSUE TITLE
TypeError: Cannot read property 'logInWithPermissions' of undefined.

### ISSUE THREAD

**Issue by motogod** [facebook/react-native-fbsdk#671]
## 🐛 Bug Report

Use login function will show `TypeError: Cannot read property 'logInWithPermissions' of undefined.` on Android.
<img width="309" alt="螢幕快照 2019-11-16 下午6 11 18" src="https://user-images.githubusercontent.com/17781603/68991719-9e2ea980-089c-11ea-8afb-f20a65ddaf8e.png">

## To Reproduce

 step 1:
`yarn add react-native-fbsdk`
step 2:
add the code on Android side:
android/app/src/main/res/values/strings.xml

```
<resources>
    <string name="app_name">MyProjectName</string>
    <string name="facebook_app_id">290084008583199</string>
</resources>
```

step 3-1:
add the code on root:  android/app/src/main/AndroidManifest.xml

```
<application>
...
<meta-data android:name="com.facebook.sdk.ApplicationId" android:value="@string/facebook_app_id"/>
...
<application>
```

step 3-2
add `mavenCentral()`
polipolisalon/android/build.gradle

```
    repositories {
        mavenCentral()
        google()
        jcenter()
    }
```

step 3-3:

I'm not sure should I type the code , but I just type it on android/app/build.gradle

    `implementation 'com.facebook.android:facebook-android-sdk:[4,5)'`

step 4:
run the project by Android Studio.

step 5:
trigger the facebookSignIn function on React Native:

```
import { LoginManager } from 'react-native-fbsdk';

// for Facebook sginIn
  facebookSignIn = () => {
    LoginManager.logInWithPermissions(["public_profile"]).then(
  function(result) {
    if (result.isCancelled) {
      console.log("Login cancelled");
    } else {
      console.log(
        "Login success with permissions: " +
          result.grantedPermissions.toString()
      );
    }
  },
  function(error) {
    console.log("Login fail with error: " + error);
  }
);
  }
```

## Expected Behavior

  It should show the facebook login view just like IOS.

## Environment

    ```
"react": "16.9.0",
    "react-native": "0.61.2",
    "react-native-fbsdk": "^1.1.1",

```

IOS works fine but get failed on Android.  Is any step I miss it ?

**Comment by JarnoNijhof** [comment]
Hi,
Are you sure the package is linked on both andoriod and ios
Mayby it's linked on ios but not on android.

Just try to run another time and make sure you are linking with libRCTFBSDK.a

**Comment by motogod** [comment]
> Hi,
> Are you sure the package is linked on both andoriod and ios
> Mayby it's linked on ios but not on android.
> 
> Just try to run another time and make sure you are linking with libRCTFBSDK.a

Hi,

I am sure I link the package on IOS.   But why I can't link the package on Android in my step. ( include 3-1, 3-2, 3-3).

About the file `libRCTFBSDK.a` is IOS side not Android side right ?

**Comment by motogod** [comment]
I found what my problem, when I try to run my project by `react-native run-android`

Show the message that can't find the device.

It looks like something wrong with my android simulator.

So I change to another simulator and it works now.

Close issue.
