### ISSUE TITLE
Urgent - App Events not being registered for Ads? Ad + Developer support has no idea what is wrong

### ISSUE THREAD

**Issue by dgobaud** [facebook/react-native-fbsdk#681]
@ fernandomtp and I are struggling with Facebook support being sent back and forth between Ads and Developer support for around a month each claiming this is not their problem.

please does anyone know?

There are 2 problems:

1. When we try to create a Conversion ad that uses App events it says "We haven't received any standard app events from your app." see attached 1.png

In the Event Manager you can see it CONFIRMS that Standard Events including Submit Application are received - see 2.png

2. We cannot create a Custom Conversion based on our custom event USER_MADE_DEPOSIT. See attached 3.png that shows when creating a Custom Conversion the app does not show up as a Data Source even though it is added which you can see in 4.png.

In 5.png you can see confirmed USER_MADE_DEPOSIT events are happening.

<img width="938" alt="1" src="https://user-images.githubusercontent.com/240811/70090258-aa21a780-15ce-11ea-8dc0-4c9bdfb20a27.png">
<img width="1329" alt="2" src="https://user-images.githubusercontent.com/240811/70090259-aa21a780-15ce-11ea-838c-be004a24025c.png">
<img width="948" alt="3" src="https://user-images.githubusercontent.com/240811/70090260-aaba3e00-15ce-11ea-968e-36a07e3361c4.png">
<img width="1676" alt="4" src="https://user-images.githubusercontent.com/240811/70090261-aaba3e00-15ce-11ea-8084-5bfedb9b65d2.png">
<img width="1741" alt="5" src="https://user-images.githubusercontent.com/240811/70090262-aaba3e00-15ce-11ea-97b1-0e8027330967.png">
<img width="962" alt="2019-11-27 - FB Ad Support" src="https://user-images.githubusercontent.com/240811/70090263-aaba3e00-15ce-11ea-8591-0e8afae4987a.png">
<img width="698" alt="2019-11-28 - FB Dev Support" src="https://user-images.githubusercontent.com/240811/70090264-aaba3e00-15ce-11ea-9752-8ade1039d18a.png">
<img width="628" alt="2019-11-29 - FB Ad Support" src="https://user-images.githubusercontent.com/240811/70090265-aaba3e00-15ce-11ea-9cda-202bc3ce4423.png">
<img width="688" alt="2019-12-01 - FB Dev Support" src="https://user-images.githubusercontent.com/240811/70090266-ab52d480-15ce-11ea-9ab5-43a77f6479f0.png">

**Comment by OldRustyDijkstra** [comment]
Did you managed to resolve this @dgobaud ?

I'm finding myself in the same predicament as you.

**Comment by dgobaud** [comment]
yes it is an absolute nightmare horrible documentation and no support but below are the events that work.....

type FacebookStandardEvent =
  | 'fb_mobile_tutorial_completion'
  | 'fb_mobile_level_achieved'
  | 'fb_mobile_add_payment_info'
  | 'fb_mobile_achievement_unlocked'
  | 'fb_mobile_purchase'
  | 'fb_mobile_add_to_cart'
  | 'fb_mobile_complete_registration';

**Comment by dgobaud** [comment]
a lot of other stuff like custom events/conversions also seem broken or the docs are wrong I don't know how it all runs at all they don't seem to care

**Comment by AntonyJBlackett** [comment]
I've just run into this as well. I came across this page:
https://stackoverflow.com/questions/23109030/minimum-installations-for-using-cpa-in-mbile-app-install-ads

I think there is fraud protection that means you cannot setup an install or event campaign until your app has logged some threshold of those events. Otherwise you could spam install campaigns for an app that never logs those events and get a small amount of free advertising each time.

**Comment by OldRustyDijkstra** [comment]
> yes it is an absolute nightmare horrible documentation and no support but below are the events that work.....
> 
> type FacebookStandardEvent =
> | 'fb_mobile_tutorial_completion'
> | 'fb_mobile_level_achieved'
> | 'fb_mobile_add_payment_info'
> | 'fb_mobile_achievement_unlocked'
> | 'fb_mobile_purchase'
> | 'fb_mobile_add_to_cart'
> | 'fb_mobile_complete_registration';

Totally agreed, really appalling documentation.  
I will try the `fb_mobile_complete_registration` events out, see if it'll work.
Thanks for your response @dgobaud .

I'm assuming you submitting them just like your `custom events`?

**Comment by chrisedington** [comment]
@OldRustyDijkstra did you have any luck using fb_mobile_complete_registration ?

Mine comes through in the debugger like this, but doesn't show in the "Events" section on FB.

<img width="633" alt="Screenshot 2020-08-15 at 14 02 15" src="https://user-images.githubusercontent.com/2725500/90311867-fc59ed00-deff-11ea-8fec-5957ba1b8652.png">

**Comment by dooleyb1** [comment]
@chrisedington any luck on your side? Also trying to log `fb_mobile_complete_registration` to represent the Standard Event for `Complete Registration`. I've tried this doing both of the following, neither of which seem to be appearing in the Event Manager console for this Standard Event:


```javascript
AppEventsLogger.logEvent("EVENT_NAME_COMPLETED_REGISTRATION", {});
AppEventsLogger.logEvent("fb_mobile_complete_registration", {});
```

**Comment by sneha220991** [comment]
> yes it is an absolute nightmare horrible documentation and no support but below are the events that work.....
> 
> type FacebookStandardEvent =
> | 'fb_mobile_tutorial_completion'
> | 'fb_mobile_level_achieved'
> | 'fb_mobile_add_payment_info'
> | 'fb_mobile_achievement_unlocked'
> | 'fb_mobile_purchase'
> | 'fb_mobile_add_to_cart'
> | 'fb_mobile_complete_registration';

Hi, even I am facing the exact same issue. None of the events are reflecting when I try to set  up the campaign. How did you manage to make the above work?

**Comment by chrisedington** [comment]
@dooleyb1 This is how it managed to work in our code:


```
import { AppEventsLogger } from 'react-native-fbsdk'

-----------

AppEventsLogger.logEvent('fb_mobile_complete_registration', { fb_registration_method: 'web', _valueToSum: price, fb_currency: 'USD' })

-----------

  const params = {
    'fb_content_type': 'product',
    'fb_content_id': 'food',
    'fb_currency': 'USD'
  };
  AppEventsLogger.logEvent('fb_mobile_add_to_cart', price, params);

-----------

  AppEventsLogger.logEvent(`fb_mobile_activate_app`)

-----------
```

**Comment by dooleyb1** [comment]
@chrisedington Thank you man, shall give this a go and report back whether or not it works for me 👍
