### ISSUE TITLE
Facebook login silently instead of dialog prompt

### ISSUE THREAD

**Issue by 1nfinite** [facebook/react-native-fbsdk#683]
I am able to successfully implemented facebook log in to facebook with this plugin.
**Expectation:** 
FB app open and a dialog box prompt where user can choose to continue/cancel
- MyShopName will receive: your public profile

**Reality:**
Login silently once i click the login button without any confirmation dialog box

Is this a normal expected flow or am I missing some parameter to force the dialog box prompt?

**Comment by thangvo9x** [comment]
Hi bro. I'm facing this problem the same.

**Comment by harleenarora** [comment]
@1nfinite can you do this?
