### ISSUE TITLE
File not found with <angled> include ; use "quotes" instead

### ISSUE THREAD

**Issue by lendyme** [facebook/react-native-fbsdk#69]
Hi

I'm currently experiencing a number of these errors:

![](https://s3.amazonaws.com/f.cl.ly/items/2U0W0k2R2W3x1d3g1z2I/Image%202015-11-17%20at%204.37.12%20pm.png)

```
'RCTBridgeModule.' file not found with <angled> include ; use "quotes" instead
```

I am fixing them as they come and replacing with quotes as asked, but there are quite a few. I'm also getting them in react-native-fbsdklogin

My package.json looks like:

```
{
  "name": "Project",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node_modules/react-native/packager/packager.sh"
  },
  "dependencies": {
    "parse": "^1.6.9",
    "parse-react": "^0.5.0",
    "react-native": "^0.14.2",
    "react-native-apple-pay": "naoufal/react-native-apple-pay",
    "react-native-device-display": "^1.0.4",
    "react-native-fbsdkcore": "0.0.5",
    "react-native-fbsdklogin": "0.0.5",
    "react-native-fbsdkshare": "0.0.5",
    "react-native-icons": "^0.4.0",
    "react-native-navbar": "^0.8.2",
    "tcomb-form-native": "git+https://git@github.com/APSL/tcomb-form-native.git#rn0.10.0"
  }
}
```

And my Podfile:
```
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'


pod 'Parse'
pod 'Stripe'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'react-native-fbsdkcore', :path => '../node_modules/react-native-fbsdkcore'
pod 'react-native-fbsdklogin', :path => '../node_modules/react-native-fbsdklogin'
pod 'react-native-fbsdkshare', :path => '../node_modules/react-native-fbsdkshare'

target 'Project' do

end

target 'ProjectTests' do

end

```

I will keep fixing these issues and see if the issue resolves itself, but has anyone come across this?

**Comment by dzhuowen** [comment]
I didn't see this error before, but it looks like Xcode doesn't recognize the framework headers. You might wanna try reinstall react-native-fbsdk with the lattest version.

**Comment by lendyme** [comment]
@dzhuowen Thanks. I did as suggested and made progress, though am left with the following errors. Do this seem familiar to you? 

![](https://s3.amazonaws.com/f.cl.ly/items/182o0A2i0i1X0B2a2d30/Image%202015-11-17%20at%209.32.02%20pm.png)

**Comment by dzhuowen** [comment]
DerivedData directory contains intermediate built results from Xcode. You can try delete the whole DerivedData dir and rebuild when run into odd build problems.

**Comment by lendyme** [comment]
@dzhuowen afraid doing so, deleting DerivedData, just resulted in more...

![](https://s3.amazonaws.com/f.cl.ly/items/13361U1U133N3F0M3U3c/Image%202015-11-17%20at%2010.28.53%20pm.png)

**Comment by keeth** [comment]
+1 I had the same problem when I added `use_frameworks!`

here's a workaround that got my project building again...

```
needs_react_header_path = [
  'react-native-fbsdkcore',
  'react-native-fbsdklogin',
  'react-native-fbsdkshare'
]

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if needs_react_header_path.include? target.name
      puts "Adding React header path to %s" % target.name
      target.build_configurations.each do |config|
        config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) $(PODS_ROOT)/Headers/Private/React'
      end
    end
  end
end
```

**Comment by dzhuowen** [comment]
Hi @lendyme , do you still have the problem?  If so, can you provide more detail, probably Cocoapods version, installation process or probably a small sample?

**Comment by mikecole20** [comment]
@keeth I know this is a bit old, but are you still using a `post_install` script as a workaround? My `Pods/Headers` is empty (which I thought was expected with `use_frameworks!`)
