### ISSUE TITLE
Safari login view does not return to app

### ISSUE THREAD

**Issue by navels** [facebook/react-native-fbsdk#70]
I am running the sample code.  The login button takes me to the Safari View Controller and I am able to log in and authorize the app, but the result then is the SVC showing a blank page.  The only thing I can do that point is click "Done" which does return me to the app but cancels the login.

Running latest versions of everything (node 5.0, npm 3.4.0, fb sdk 4.8, react-native 0.14.2, react-native-fb* 0.0.7).

Anyone seen this?

**Comment by mrspeaker** [comment]
Yes, I see exactly the same thing. Authorizing the login doesn't take me back, and no messages are logged via the callbacks.

**Comment by navels** [comment]
I dropped back to the previous FB SDK (4.7.1) and still have this problem . . .

**Comment by dzhuowen** [comment]
Hi @navels, have you seen this issue before or it's the first time you try running the code?

**Comment by navels** [comment]
This is my first time with react-native, etc.

**Comment by mrspeaker** [comment]
My first time too... perhaps it's a setup issue on my end (I initially thought I was doing something wrong because it didn't load the facebook app, but I see that's "by design" for the latest SDK).

**Comment by mrspeaker** [comment]
Yes, sorry. Pebkac error. I did not realize I needed to modify the AppDelegate.m file (I thought the plugin magically did this step). https://developers.facebook.com/docs/ios/getting-started#delegate

**Comment by dzhuowen** [comment]
@mrspeaker 😉
Does this work for you @navels ?

**Comment by navels** [comment]
Yes, thanks!
