### ISSUE TITLE
There are any method/function to get user mobile phone?

### ISSUE THREAD

**Issue by JohnyLe** [facebook/react-native-fbsdk#706]
Hi,
I found this post "https://developers.facebook.com/blog/post/2011/01/14/platform-updates--new-user-object-fields--edge-remove-event-and-more/"
It said: "Update: The user_address and user_mobile_phone permissions have been removed. Please see this post for more info."

My question is: There are any method/function to get user mobile phone?

Many thanks for your help!

**Comment by gmertk** [comment]
Hi @JohnyLe  

Unfortunately there is no other way. 

Note that this isn't really about the React Native Facebook SDK. It is about the Facebook Platform itself. So this question would be more appropriate for the Developer Community Forum https://developers.facebook.com/community/ or https://www.facebook.com/groups/fbdevelopers/
