### ISSUE TITLE
No check for advertisingTrackingEnabled

### ISSUE THREAD

**Issue by sintylapse** [facebook/react-native-fbsdk#715]
App Store requires not to track users by their unique identifiers, but I haven't found any code that checks for `advertisingTrackingEnabled` inside fbsdk - https://developer.apple.com/documentation/adsupport/asidentifiermanager/1614148-advertisingtrackingenabled?language=objc . Is that check necessary and should developers implement this check on their side?

**Comment by gmertk** [comment]
Hi @sintylapse, this react-native-fbsdk is a wrapper around the facebook-ios-sdk which checks this flag internally. Please see https://github.com/facebook/facebook-ios-sdk/blob/003c46e80ad379bc1fc9748837c04dd57fbbbf50/FBSDKCoreKit/FBSDKCoreKit/AppEvents/Internal/FBSDKAppEventsUtility.m#L60-L70
