### ISSUE TITLE
FBSDKLoginManager browser doesn't close after success auth

### ISSUE THREAD

**Issue by aforty** [facebook/react-native-fbsdk#72]
Having an issue where the browser doesn't close after a successful login. I'm running iOS 9.1, I've tried both on the simulator as well as on a device (same iOS version)

```
FBSDKLoginManager.logInWithReadPermissions(['email'], (error, result) => {
  console.log(error, result);
});
```

In the Xcode console I see the following messages, presumably attempting to access the native app before falling back to the browser method.
```
2015-11-23 20:30:04.413 Dish[6872:2922048] -canOpenURL: failed for URL: "fbauth2:/" - error: "(null)"
2015-11-23 20:30:04.421 Dish[6872:2922048] -canOpenURL: failed for URL: "fbauth2:/" - error: "(null)"
```

After giving the app permissions (or as in these screenshots permissions have already been granted) the next screen is simply blank and the browser window never closes/redirects. It never hits my `console.log(...)` statement until I press 'Done', in which case `result.isCanceled = true`.

<img width="393" alt="screen shot 2015-11-23 at 20 30 12" src="https://cloud.githubusercontent.com/assets/523683/11355214/4035dee8-9221-11e5-93d1-de7a7f44fdde.png">
<img width="393" alt="screen shot 2015-11-23 at 20 30 15" src="https://cloud.githubusercontent.com/assets/523683/11355215/4043830e-9221-11e5-9ad2-3d8d9c327c6b.png">

**Comment by aforty** [comment]
And resolved. My apologies for not trying all possible things before posting. Hopefully this explanation is useful for the next person coming across this.

I had not edited my `AppDelegate.m` as detailed here: https://developers.facebook.com/docs/ios/getting-started#delegate

I was under the impression that using CocoaPods would perform that step for me somehow. Pretty new to iOS as you can probably tell.

**Comment by keeth** [comment]
I ran into this as well.. noob iOS mistake :/ make sure your AppDelegate's openURL calls back into the FB SDK.
