### ISSUE TITLE
are we using UIWebView?

### ISSUE THREAD

**Issue by girish54321** [facebook/react-native-fbsdk#721]
## 🐛 Bug Report
is this package using UIWebView
i got mail form apple
Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs starting from April 2020

## To Reproduce
should have upload to testflight without error or warning 

## Expected Behavior
should have upload to testflight without error or warning 

## Code Example

after running  ---- grep -r UIWebView node_modules/* 

Binary file node_modules/@philly25/react-native-paytm/ios/libPaymentsSDK.a matches
node_modules/@philly25/react-native-paytm/ios/PGTransactionViewController.h:@interface PGTransactionViewController : UIViewController <UIWebViewDelegate, UIActionSheetDelegate>
node_modules/@types/react-native/index.d.ts:     * If `true`, use WKWebView instead of UIWebView.
node_modules/fbjs/lib/UserAgent.js.flow:   * - UIWebView
node_modules/fbjs/lib/UserAgent.js:   * - UIWebView
node_modules/metro/node_modules/fbjs/lib/UserAgent.js.flow:   * - UIWebView
node_modules/metro/node_modules/fbjs/lib/UserAgent.js:   * - UIWebView
node_modules/react-native/node_modules/fbjs/lib/UserAgent.js.flow:   * - UIWebView
node_modules/react-native/node_modules/fbjs/lib/UserAgent.js:   * - UIWebView
node_modules/react-native/Libraries/Components/WebView/WebView.android.js:     * If true, use WKWebView instead of UIWebView.
node_modules/react-native/Libraries/Components/WebView/WebView.ios.js:     * If true, use WKWebView instead of UIWebView.
node_modules/react-native/React/Views/RCTWebView.m:@interface RCTWebView () <UIWebViewDelegate, RCTAutoInsetsProtocol>
node_modules/react-native/React/Views/RCTWebView.m:  UIWebView *_webView;
node_modules/react-native/React/Views/RCTWebView.m:    _webView = [[UIWebView alloc] initWithFrame:self.bounds];
node_modules/react-native/React/Views/RCTWebView.m:#pragma mark - UIWebViewDelegate methods
node_modules/react-native/React/Views/RCTWebView.m:- (BOOL)webView:(__unused UIWebView *)webView shouldStartLoadWithRequest:(NSURLRequest *)request
node_modules/react-native/React/Views/RCTWebView.m: navigationType:(UIWebViewNavigationType)navigationType
node_modules/react-native/React/Views/RCTWebView.m:      @(UIWebViewNavigationTypeLinkClicked): @"click",
node_modules/react-native/React/Views/RCTWebView.m:      @(UIWebViewNavigationTypeFormSubmitted): @"formsubmit",
node_modules/react-native/React/Views/RCTWebView.m:      @(UIWebViewNavigationTypeBackForward): @"backforward",
node_modules/react-native/React/Views/RCTWebView.m:      @(UIWebViewNavigationTypeReload): @"reload",
node_modules/react-native/React/Views/RCTWebView.m:      @(UIWebViewNavigationTypeFormResubmitted): @"formresubmit",
node_modules/react-native/React/Views/RCTWebView.m:      @(UIWebViewNavigationTypeOther): @"other",
node_modules/react-native/React/Views/RCTWebView.m:- (void)webView:(__unused UIWebView *)webView didFailLoadWithError:(NSError *)error
node_modules/react-native/React/Views/RCTWebView.m:      // Error code 102 "Frame load interrupted" is raised by the UIWebView if
node_modules/react-native/React/Views/RCTWebView.m:- (void)webViewDidFinishLoad:(UIWebView *)webView
node_modules/react-native-fbsdk/js/FBShareDialog.js:   * Displays the dialog in a UIWebView within the app.
Binary file node_modules/react-native-maps/.gradle/4.10.3/taskHistory/taskHistory.bin matches
node_modules/react-native-webview/README.md:- [7.0.1](https://github.com/react-native-community/react-native-webview/releases/tag/v7.0.1) - Removed UIWebView
node_modules/ua-parser-js/test/browser-test.json:        "ua"      : "Mozilla/5.0 (iPhone; CPU iPhone OS 10_0_2 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Mobile/14A456 QQ/6.5.3.410 V1_IPH_SQ_6.5.3_1_APP_A Pixel/1080 Core/UIWebView NetType/WIFI Mem/26",
.
## Environment
react-native version:0.59.10
react-native-webview version: 7.5.2
"react-native-fbsdk": "0.10.3",

**Comment by systemride** [comment]
See #640

**Comment by girish54321** [comment]
thanks @systemride

**Comment by hussainarthuna** [comment]
> thanks @systemride

Hey how did you solve this? i am having the same issue and went to the thread by @systemride but i am not able to do that.

**Comment by girish54321** [comment]
@hussainarthuna  not solved yet i but dont think FBSDK using web view..

**Comment by ajithkumark771** [comment]
Solved it? I am having same issue . I think the issue is because paytm library is using UIWebView. 

_node_modules/@philly25/react-native-paytm/ios/PGTransactionViewController.h:@interface PGTransactionViewController : UIViewController <UIWebViewDelegate, UIActionSheetDelegate>_

Using latest paytm library 1.0.9
