### ISSUE TITLE
CocoaPods could not find compatible versions for pod "FBSDKShareKit"

### ISSUE THREAD

**Issue by orzhtml** [facebook/react-native-fbsdk#738]
[!] CocoaPods could not find compatible versions for pod "FBSDKShareKit":
  In Podfile:
    react-native-fbsdk (from `../node_modules/react-native-fbsdk`) was resolved to 1.1.2, which depends on
      react-native-fbsdk/Share (= 1.1.2) was resolved to 1.1.2, which depends on
        FBSDKShareKit (= 5.8)

None of your spec sources contain a spec satisfying the dependency: `FBSDKShareKit (= 5.8)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Comment by ayush-shta** [comment]
@orzhtml Could you please share how you solved this?

**Comment by feia-github** [comment]
> @orzhtml Could you please share how you solved this?

I had the same issue and solved it by updating the pod repo:
`pod install --repo-update`
