### ISSUE TITLE
logInWithPermissions will not redirect back if user choose to login in facebook app

### ISSUE THREAD

**Issue by miracle0930** [facebook/react-native-fbsdk#741]
## 🐛 Bug Report
  When calling `LoginManager.logInWithPermissions(['public_profile'])`, there will be a poped up page with two options, 'Log in with the Facebook app', and 'Log in with phone or email'. 

If using 'Log in with phone or email', the whole process will be working correctly. 

But when using 'Login with the Facebook app', it will bring user to Facebook app and NEVER redirect back, no matter user click continue or cancel in that page, it will just give user a white page and stay there forever

## To Reproduce
  1. `LoginManager.logInWithPermissions(['public_profile'])`;
  2. Click Log in with the Facebook app;
  3. Click 'open' when asking 'Open in Facebook?';
  4. Click 'Continue' or 'Cancel' will give you a white page and stay there forever.

## Environment
  react-native: ~0.61.5,
  react-native-fbsdk: ^1.1.2

**Comment by raj-2020** [comment]
Facing that same issue.  🐛

**Comment by miracle0930** [comment]
I found the solution, select your **project** -> **targets** -> **info** tab -> scroll down to **URL Types**, need to fill your fb scheme like this
![Screen Shot 2020-04-30 at 5 14 17 PM](https://user-images.githubusercontent.com/15270493/80770815-401e1780-8b06-11ea-936d-b57f3616ec24.png)
