### ISSUE TITLE
Unable to resolve module react-native-fbsdkcore

### ISSUE THREAD

**Issue by ranyefet** [facebook/react-native-fbsdk#77]
Hi all,

I'm trying to add Facebook Login button and retrieve the user Access Token in my React Native app.
I'm using:
node 4.0.0
nam 2.14.2
"react-native": "^0.15.0",
"react-native-fbsdkcore": "0.0.7",
"react-native-fbsdklogin": "0.0.7",

at the top of ```Login.js``` i have the following:
```js
import { FBSDKAccessToken } from 'react-native-fbsdkcore';
import { FBSDKLoginButton } from 'react-native-fbsdklogin';
```

The first line throw me an error
```
Unable to resolve module react-native-fbsdkcore from /Users/ranyefet/Code/yesno/ios-app/app/screens/Login.js: Invalid directory /Users/node_modules/react-native-fbsdkcore
```

If I change it to to include the JS file directly, it works.
```js
import { FBSDKAccessToken } from '../../node_modules/react-native-fbsdkcore/FBSDKCore.ios';
import { FBSDKLoginButton } from 'react-native-fbsdklogin';
```

Any suggestion what is happening here?

**Comment by dzhuowen** [comment]
Hi @ranyefet ,

Did you do npm install under your <project name> dir ?  The node_module shouldn't be under /Users somehow.

**Comment by ranyefet** [comment]
Yeah of course I did. As I mentioned when I require the file directly it
does work.
It seems like an issue with npm
Any ideas on how to debug it?

On Friday, December 4, 2015, dzhuowen <notifications@github.com> wrote:

> Hi @ranyefet <https://github.com/ranyefet> ,
>
> Did you do npm install under your dir ? The node_module shouldn't be under
> /Users somehow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/facebook/react-native-fbsdk/issues/77#issuecomment-161801568>
> .
>


-- 
בברכה, רן יפת.
http://Ran.Yefet.net

**Comment by philikon** [comment]
> The node_module shouldn't be under /Users somehow.

This is a symptom of the react-native packager. It walks up the directory structure and bails at the last possible place (which is one level away from the root directory, hence `/Users/`)

**Comment by ranyefet** [comment]
I had an Xcode error regarding App Transport Security Settings once I fixed it, it seems that the issue was gone, not sure how's that related.

Thanks.
