### ISSUE TITLE
Event for Login Button onLoginStart?

### ISSUE THREAD

**Issue by Ledda** [facebook/react-native-fbsdk#78]
Is it possible to include an event handler for an on click event?
e.g. onLoginStart, onLogoutStart

I am trying to get the status bar color to change to default from light-content

**Comment by swiese** [comment]
What did you try so far that didn't work?

**Comment by Ledda** [comment]
I tried listening to events and only onLoginFinished and onLogoutFinished seem to be firing.
I assume it hasn't been registered with the Objective C code..?
I don't know Objective C so I stopped there.

The alternative is that I could try to wrap the button in a TouchableHighlight that changes the status bar color but then there isn't a way to programmatically change the color back when the navigator hides?

**Comment by dzhuowen** [comment]
Hi Ledda，if you look at  FBSDKLoginButton.ios.js, onLoginFinished and onLogoutFinished are the right prop  to use.

**Comment by Ledda** [comment]
@dzhuowen Not exactly what I need. 
I need to change the status bar color when the facebook login navigator slides up. The navigator scene is a white background and my status bar is "light-content" I cant find a way to change the status bar color back to "default". 
So i thought if there was a onLoginStart then I could change it.. any ideas?

**Comment by dzhuowen** [comment]
Yeah you're right in iOS SDK there's no such method to trigger callback at start of login/logout, so in react native SDK we don't provide this as well.

**Comment by swiese** [comment]
You should be able to listen to events on the button itself. @dzhuowen  do you know how to do this in react. In objective c you would just call addTarget

**Comment by dzhuowen** [comment]
If I understand correctly, you want to have the touchable highlight to trigger the status bar color change when click the login button, and after the login flow, change the status bar color back with onLoginFinished?  Am I missing anything?

**Comment by Ledda** [comment]
spot on :)

**Comment by dzhuowen** [comment]
Hi Ledda, we've implemented onWillLogin event and you will have it in the next release.
Thanks for pointing this out!

**Comment by Ledda** [comment]
Awesome! Look forward to it :+1:
