### ISSUE TITLE
Log Standard Event

### ISSUE THREAD

**Issue by priyasamyal** [facebook/react-native-fbsdk#784]
Any event i log shows me in custom event.
 Can you tell, how can i log the Standard event using this plugin like "Complete Registration"

AppEventsLogger.logEvent("Complete Registration", {user_type:"owner"});

 React Native 0.61

**Comment by priyasamyal** [comment]
Issue solved

**Comment by bernhardt1** [comment]
@priyasamyal did you find some documentation ? how did you solve it?
