### ISSUE TITLE
Any interest in an update to FBSDK 8.0?

### ISSUE THREAD

**Issue by mikehardy** [facebook/react-native-fbsdk#798]
Hello!

I have the underlying native SDKs updated to 8.0 in my work project for testing (it's early in my release cycle) and everything seems fine.

Interested in a PR to implement that here? It's just a bump in build.gradle and the podspec it seems, so nothing big but it would be great to see if it works for others or if I'm missing something

**Comment by kathigeiger** [comment]
Hi! I would be interested in the changes you made for updating to 8.0, would you mind sharing them with me? Thanks!

**Comment by mikehardy** [comment]
Sure @kathigeiger - they are trivial really, the patch-package format patch that I cat to console below is needed for the podspec:

```
mike@isabela:~/work/Kullki/ksocialscore/packages/public-app (rebranding) % cat patches/react-native-fbsdk+2.0.0.patch 
diff --git a/node_modules/react-native-fbsdk/react-native-fbsdk.podspec b/node_modules/react-native-fbsdk/react-native-fbsdk.podspec
index d766164..afb902d 100644
--- a/node_modules/react-native-fbsdk/react-native-fbsdk.podspec
+++ b/node_modules/react-native-fbsdk/react-native-fbsdk.podspec
@@ -14,17 +14,17 @@ Pod::Spec.new do |s|
   s.dependency      'React'
 
   s.subspec 'Core' do |ss|
-    ss.dependency     'FBSDKCoreKit', '~> 7.0'
+    ss.dependency     'FBSDKCoreKit', '~> 8.0'
     ss.source_files = 'ios/RCTFBSDK/core/*.{h,m}'
   end
 
   s.subspec 'Login' do |ss|
-    ss.dependency     'FBSDKLoginKit', '~> 7.0'
+    ss.dependency     'FBSDKLoginKit', '~> 8.0'
     ss.source_files = 'ios/RCTFBSDK/login/*.{h,m}'
   end
 
   s.subspec 'Share' do |ss|
-    ss.dependency     'FBSDKShareKit', '~> 7.0'
+    ss.dependency     'FBSDKShareKit', '~> 8.0'
     ss.source_files = 'ios/RCTFBSDK/share/*.{h,m}'
   end
 end
```

and in my app/build.gradle I have this

```
        facebookSdkVersion = "8.0.0"
```

...that's all there is to it in my project to pull in v8

**Comment by kathigeiger** [comment]
Cool thank you very much! :)

**Comment by mikehardy** [comment]
I posted a PR to implement this so I could get it out of my patch-package queue ;-)

**Comment by yum650350** [comment]
We currently need this, thank you.

**Comment by mikehardy** [comment]
Done with #804
