### ISSUE TITLE
Any plans for FBSDK 8.0?

### ISSUE THREAD

**Issue by gnuwilliam** [facebook/react-native-fbsdk#799]
Hello!

I just started using this lib on my project, and followed the official Facebook SDK integration docs to install and compile on both Android and iOS (https://developers.facebook.com/docs/react-native/configure-ios and https://developers.facebook.com/docs/react-native/configure-android), however, the user profile always come with a placeholder image. Doing some research, I discovered that in FBSDK 8.0, it's going to be required to pass the `accessToken` in order to retrieve the user avatar.

According to the official documentation (https://developers.facebook.com/docs/graph-api/reference/user/picture/), as of October 24th 2020, this will be the only way to retrieve the user picture, but it looks like when you install following the Facebook SDK documentation, they provide the 8.0 version already, since I'm having this issue. I'm wondering if this lib will also be updated to 8.0 soon, or if this will come later.

Thanks!

**Comment by Jonovono** [comment]
Curious about this as well

**Comment by Jonovono** [comment]
@michaelknoch would definitely appreciate it. From what I understand FBSDK 8.0 is required to fetch user profiles going forward.

**Comment by michaelknoch** [comment]
@Jonovono seems that there is already a pr https://github.com/facebook/react-native-fbsdk/pull/804

**Comment by gnuwilliam** [comment]
It looks like this was solved with #804, so I'm closing the issue.
