### ISSUE TITLE
"Unable to resolve module"

### ISSUE THREAD

**Issue by tnguyen42** [facebook/react-native-fbsdk#8]
Hi,

Right after compiling my project, when I run it, a few errors are displayed in my terminal:
```
Unable to resolve module invariant from /Project/node_modules/react-native-fbsdkcore/js-modules/FBSDKGraphRequestManager.ios.js
Unable to resolve module NativeModules from /Project/node_modules/react-native-fbsdkcore/js-modules/FBSDKGraphRequestManager.ios.js
```

Is there any reason about it? Is it only me? Does it need to be solved on my side?
The app still works, by the way...

**Comment by cphackm** [comment]
I've never noticed any errors importing the invariant module, so I'm unsure what's causing that.  The second error is due to [this](https://github.com/corymsmith/react-native-icons/issues/59).  There was a recent pull request to fix that, but I don't believe the npm package has been updated yet.

**Comment by tnguyen42** [comment]
Thanks for the answer!

**Comment by yelled3** [comment]
@cphackm 
> but I don't believe the npm package has been updated yet.

when will the npm package going to be updated?

**Comment by cphackm** [comment]
@yelled3 Should be soon. Waiting on some other changes for the next release.

**Comment by philikon** [comment]
> I've never noticed any errors importing the invariant module, so I'm unsure what's causing that. The second error is due to [this](https://github.com/corymsmith/react-native-icons/issues/59).

They are both due to the same issue. They're both fixed in 0.4.0.

**Comment by yelled3** [comment]
@philikon thank you.

**Comment by tnguyen42** [comment]
Thanks!
