### ISSUE TITLE
FBSDKGraphRequest in React Native returning incomplete object

### ISSUE THREAD

**Issue by johnnyjanzen** [facebook/react-native-fbsdk#80]
I'm implementing FBSDKGraphRequest and although my login and graph request works, the graph request is only returning a small portion of the data the /me node of the graph is supposed to return.  Not sure if it is programmer error on my part, or an issue with the fbsdk?

I've included the full source code here:
http://stackoverflow.com/questions/34030082/fbsdkgraphrequest-in-react-native-returning-incomplete-object

**Comment by swiese** [comment]
You have to explicitly request fields. Try using this to debug
https://developers.facebook.com/tools/explorer/145634995501895/

**Comment by johnnyjanzen** [comment]
Brilliant!  It might be useful to include some kind of reference to this in the documentation.

**Comment by philikon** [comment]
The FB API docs at https://developers.facebook.com *is* the documentation.

**Comment by johnnyjanzen** [comment]
Thanks guys! :)  What I mean is, it could be convenient to document the actual implementation of how to explicitly request fields in react-native.  The FB API docs include implementation for iOS and Javascript, but it can be unclear which model to follow in react-native.  I was trying for a while to pass the request parameters as an additional object (as per iOS), rather than using "/me?fields=id"
