### ISSUE TITLE
FBSDKCoreKit/FBSDKCoreKit.modulemap' not found  Xcode 12 

### ISSUE THREAD

**Issue by ahtisham09** [facebook/react-native-fbsdk#801]
I am running my app on IOS and getting error 
module map file '/Users/macbook/Library/Developer/Xcode/DerivedData/Connect360-fkvotrokqjgczacuwgznybcvqqnp/Build/Products/Debug-iphonesimulator/FBSDKCoreKit/FBSDKCoreKit.modulemap' not found
my app is running fine on Xcode 11 today i just update Xcode 12 from Xcode 11 and then i am getting this error i tried many things but its not working please help me i am stuck very badly

**Comment by thanhcuong1990** [comment]
@ahtisham09 you can try this:
On Build Settings search `VALID_ARCH` then press delete. This should work for me with Xcode 12.0.1

https://stackoverflow.com/questions/63607158/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios/64267780#64267780

**Comment by ahtisham09** [comment]
@thanhcuong1990 i tried this but its not working

**Comment by lander854** [comment]
tried that, not working

**Comment by arjunkomath** [comment]
Adding `arm64` to excluded architectures (for **both project and Pods build settings**) fixed the issue for me.

<img width="436" alt="Screen Shot 2020-11-21 at 10 03 07 pm" src="https://user-images.githubusercontent.com/2555067/99875650-57a92300-2c45-11eb-8625-58603df07295.png">

**Comment by lander854** [comment]
didnt work :(

**Comment by ahtisham09** [comment]
Community needs to look this issue still not reply any collaborate on this issue

**Comment by shawwal** [comment]
> Community needs to look this issue still not reply any collaborate on this issue

Yeah I also having this issue and have been seeing a lot people reporting the same issue, I'm using Mac OS Big Sur version 11.0.1 and Xcode version 12.2 (12B45b).

**Comment by shawwal** [comment]
> > Community needs to look this issue still not reply any collaborate on this issue
> 
> Yeah I also having this issue and have been seeing a lot people reporting the same issue, I'm using Mac OS Big Sur version 11.0.1 and Xcode version 12.2 (12B45b).

Finally I managed to solve this issue by getting the latest update of MacOS big Sur 11.1 and Xcode 12.3

**Comment by ahtisham09** [comment]
@shawwal so your issue is solved?

**Comment by shawwal** [comment]
> @shawwal so your issue is solved?

Yes it's solved after I update XCode to version 12.3

**Comment by ahtisham09** [comment]
@shawwal ok i will try

**Comment by ahtisham09** [comment]
Fix Xcode 12 compatibility
[](https://github.com/facebook/react-native-fbsdk/pull/819#issue-535576153)

**Comment by karthikkncs14** [comment]
> Adding `arm64` to excluded architectures (for **both project and Pods build settings**) fixed the issue for me.
> 
> <img alt="Screen Shot 2020-11-21 at 10 03 07 pm" width="436" src="https://user-images.githubusercontent.com/2555067/99875650-57a92300-2c45-11eb-8625-58603df07295.png">

Yes i did same thing in xcode 12.3 & mac os 11.1 and ios 14.

It works very well with physical device above setting is required only in simulator.

**Comment by matt-dalton** [comment]
I have upgraded to Xcode 12.3 and tried the suggestion above, but I now get:
```
Check dependencies
No architectures to compile for (ARCHS=arm64, VALID_ARCHS=arm64 arm64e armv7 armv7s, EXCLUDED_ARCHS=(
    arm64
)).

** ARCHIVE FAILED **
```

Any ideas?

**Comment by alapanerao** [comment]
> Adding `arm64` to excluded architectures (for **both project and Pods build settings**) fixed the issue for me.
> 
> <img alt="Screen Shot 2020-11-21 at 10 03 07 pm" width="436" src="https://user-images.githubusercontent.com/2555067/99875650-57a92300-2c45-11eb-8625-58603df07295.png">

This solution worked for me.

**Comment by ahtisham09** [comment]
I solve this Issue by adding $(ARCHS_STANDARD) in VALID_ARCHS
