### ISSUE TITLE
Problems with react-native@0.18.0-rc

### ISSUE THREAD

**Issue by CoericK** [facebook/react-native-fbsdk#82]
Was trying to install npm install --save react-native-fbsdkcore and i got this error:

npm ERR! node v5.3.0
npm ERR! npm  v2.14.15
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package react-native@0.18.0-rc does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native-fbsdkcore@0.0.8 wants react-native@>=v0.13.0
npm ERR! peerinvalid Peer react-native-fbsdkshare@0.0.8 wants react-native@>=v0.13.0

How to fix it?

**Comment by mcz** [comment]
Same for me, but you can safely ignore it. Regardless of the warning, it works for me.

**Comment by dzhuowen** [comment]
The system versioning doesn't support `rc` by design. https://github.com/facebook/react-native-fbsdk/issues/62#issuecomment-170998401
