### ISSUE TITLE
SERVER_ERROR: [code] 1349195 [message]: The key hash does not match any stored key hashes. in Real Device (Android)

### ISSUE THREAD

**Issue by nammiharika** [facebook/react-native-fbsdk#827]
## 🐛 Bug Report
I am using this module. It's working fine in iOS but in android device i am getting this error 
 **SERVER_ERROR: [code] 1349195 [message]: The key hash does not match any stored key hashes. Go to https://developers.facebook.com/docs/facebook-login/android for more information. [extra]:** 
 I tested in android emulator it's working fine and getting success response.

## To Reproduce
Error is getting only in real device android. Android emulator is getting success response.
Testing Devices:- Samsung S9 & Samsung M31s
I followed this doc https://developers.facebook.com/docs/android/getting-started/ for generating hash key.

## Expected Behaviour
Success Response for real devices android

## Code Example
```
<LoginButton
                permissions={["email"]}
                onLoginFinished={
                    (error, result) => {
                        if (error) {
                            console.log("login has error: ", error);
                        } else if (result.isCancelled) {
                            console.log("login is cancelled.");
                        } else {
                            AccessToken.getCurrentAccessToken().then(
                                (data) => {
                                    console.log( data)
                                }
                            )
                        }
                    }
                }
                onLogoutFinished={() => console.log("logout.")} />
```

## Environment
![Screenshot 2021-01-06 at 2 47 11 PM](https://user-images.githubusercontent.com/57613587/103751597-95fc7500-502e-11eb-934c-c892adde261e.png)

**Comment by tomarlokesh** [comment]
Get The Debug And Release Key Hash from Project/android/app Directory and put into the Facebook Developer Account

**Comment by nammiharika** [comment]
I fixed this issue by follow this https://stackoverflow.com/a/12577997/8626023

I did a mistake by giving wrong password for generating hash key

I will give **android** as a password to generate hash key and it's working fine for me. Thank you.

**Comment by amalmadawa90** [comment]
> I fixed this issue by follow this https://stackoverflow.com/a/12577997/8626023
> 
> I did a mistake by giving wrong password for generating hash key
> 
> I will give **android** as a password to generate hash key and it's working fine for me. Thank you.

this worked for me too. Why it's need to give password as **Android** ?

**Comment by muhammadashfaq** [comment]
> I fixed this issue by follow this https://stackoverflow.com/a/12577997/8626023
> 
> I did a mistake by giving wrong password for generating hash key
> 
> I will give **android** as a password to generate hash key and it's working fine for me. Thank you.

not workign for me
