### ISSUE TITLE
Not able to login with facebook app only in iOS 

### ISSUE THREAD

**Issue by saurabh874** [facebook/react-native-fbsdk#829]
Social: Authentication- Unable to authenticate connection to Facebook through Facebook app, whereas able to authenticate connection when Facebook app not installed on iOS Device.

anybody have any idea how to resolve it?

**Comment by yash-sage** [comment]
@saurabh874 before triggering LoginManager.logInWithPermissions, set the login behaviour to web_only
  LoginManager.setLoginBehavior('web_only');
  It worked in my case

**Comment by aguscha333** [comment]
@saurabh874 this answer in this other issue helped me solve this very same issue in my app https://github.com/facebook/react-native-fbsdk/issues/785#issuecomment-731925742

**Comment by saurabh874** [comment]
@aguscha333 thanks. you saved my lot of time.
