### ISSUE TITLE
always get empty array when make requests with graph api

### ISSUE THREAD

**Issue by shangsunset** [facebook/react-native-fbsdk#88]
Greetings, 
I changed the `graphpath` in the example code trying to get logged in user's data but i always end up getting a empty array. it only works when the `graphpath` is `/me`. it never worked when it was `/me/friends` or `/me/photos`. am i doing anything wrong?
```javascript
    var feedRequest = new FBSDKGraphRequest(
      this._handleRequest.bind(this),
      '/495164637280739/photos',
      {
        type: { string: 'uploaded' },
        fields: { string: 'images, link' }
      }
    );
    feedRequest.start();
  ....

  _handleRequest(error, result) {
    if (!error) {
    console.log(result);         
    }
  }

```

**Comment by mingflifb** [comment]
What permissions did you ask for when you implemented login?

**Comment by shangsunset** [comment]
Oh i didnt think about permissions. i was just using the sample code in the repo.
are you talking about this?
```javascript
          onLogoutFinished={() => alert('Logged out.')}
          readPermissions={[]}
          publishPermissions={[]}/>
```

now i noticed that after filling password, a screen says 'you have authorized New Horizons'.  but where did i give authorization to 'New Horizons'?

thanks.

**Comment by mingflifb** [comment]
You need to ask for permissions in order to get friends and photos information. Please read more about Facebook Login on the developer site here: https://developers.facebook.com/docs/facebook-login

**Comment by shangsunset** [comment]
Thanks. i have better understanding now. however, when i set 'user_photos` permission and tried to get my photos, the result was still an empty array.

```javascript
     onLogoutFinished={() => alert('Logged out.')}
     readPermissions={['user_photos']}
     publishPermissions={[]}/>

...

    var feedRequest = new FBSDKGraphRequest(
      this._handleRequest.bind(this),
      '/me/photos?type=uploaded' );
```

**Comment by mingflifb** [comment]
You should use the Graph API Explorer to test your requests and debug any issues: https://developers.facebook.com/tools/explorer/
