### ISSUE TITLE
AppInviteDialog Doesn't Work

### ISSUE THREAD

**Issue by RussMax783** [facebook/react-native-fbsdk#89]
When i upgrade to the latest version 0.8, the App invite no longer worked. As i've dug around trying to figure out the problem, i noticed that the API changed. Instead of going `AppInviteDialog.show(content, cb)` it now has .setContent, .canShow, .show, and .validateWithError. But it seems as though something is not right. When i try and implement it like the sample project. i get the following with this code:

```
...
const content = new AppInviteContent('http://www.startchillin.com', 'http://www.chillin.io/share/fb-invite-share.png');
debugger;
AppInviteDialog.setContent(content);
...
``` 

![simulator screen shot feb 11 2016 1 40 19 pm](https://cloud.githubusercontent.com/assets/5333786/12990196/3c37d86c-d0c6-11e5-8530-fca9cd7b8c82.png)

When i step through I find that the actuall FBSDKAppInviteDialogInterface does not have the methods like setContent, but only has .show... 

![screen shot 2016-02-11 at 1 39 15 pm](https://cloud.githubusercontent.com/assets/5333786/12990162/078aa41e-d0c6-11e5-8d0f-f4a94857e9c6.png)

Here is the original error i got right after upgrading 

![error](https://cloud.githubusercontent.com/assets/5333786/12990103/b482687e-d0c5-11e5-99cf-7386526899af.png)

**Comment by dzhuowen** [comment]
Just try out the AppInviteDialog and it works as expected.
Please make sure you actually upgrade the sdk.

**Comment by RussMax783** [comment]
I had downloaded the version prior to 20160210 on the Facebook SDK, So version 0.8 react-native-fbsdk is not compatible with the Facebook SDK Prior to the one mentioned.

**Comment by ivanbrens** [comment]
So I ran into this same issue and I upgraded the FBSDK to 20160316 and it does not work.  I have also restarted the packager just in case and still no dice.  Any other suggestions?

**Comment by RussMax783** [comment]
Try removing (un-linking) the SDK by removing it from your project and linking it again. If you happened to copy the files when linking there is a chance it's still using the old SDK.

**Comment by ivanbrens** [comment]
@RussMax783 Thanks, that definitely that did the trick.
