### ISSUE TITLE
FBSDKLoginManager logInWithReadPermissions returning result.isCancelled

### ISSUE THREAD

**Issue by antigirl** [facebook/react-native-fbsdk#90]
since 0.8 release FBSDKLoginManager.logInWithReadPermissions keeps returning isCancelled even when you follow the dialogue properly to login.

**Comment by dzhuowen** [comment]
Tested LoginManager and everything works as expected for me. 
The native SDK doesn't provide API for feature like 'onWillLogin' so we can't provide it in rnsdk. Also I believe you can just do the stuff right before calling the login method. 
Thanks for the advice! Will do.

**Comment by antigirl** [comment]
Sorry i edited my issue as i explored it further and the error made more sense to me, 
For me, if you login then attempt at logging in again [even after restarting the app] it will return isCancelled. I think its because the access token exists. 
Correct protocol is to probably check with FBSDKAccessToken.getCurrentAccessToken, 
however it wasnt an issue with the previous release.

in any case if my findings are correct then it needs to return something different, not isCancelled

**Comment by dzhuowen** [comment]
👍
