### ISSUE TITLE
Update docs to troubleshoot iOS9 NSAppTransportSecurity

### ISSUE THREAD

**Issue by paulohenriquesg** [facebook/react-native-fbsdk#94]
Following the steps in Quick Starts (https://developers.facebook.com/quickstarts/), if I add the **NSAppTransportSecurity** iOS SDK 9 directive in my .plist, the app becomes unable to connect to the development server.

The docs should have the resolution for this, as stated in https://github.com/facebook/react-native/issues/304

The resolution id to add localhost as shown bellow
```xml
  <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSExceptionDomains</key>
        <dict>
            <key>localhost</key>
            <dict>
                <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
                <true/>
            </dict>
        </dict>
    </dict>
```

**Comment by mingflifb** [comment]
You no longer need to add the NSAppTransportSecurity key for the Facebook SDK, we will remove it from the quickstart. Thanks.
