### ISSUE TITLE
Best practice for keeping user logged in?

### ISSUE THREAD

**Issue by gpazo** [facebook/react-native-fbsdk#97]
I have the SDK setup and working inside of my app, it will navigate into my 'main' code after login but I'm looking to keep the user logged in on subsequent launches of the app.  The login button itself seems to be smart enough to set the text to "log out" when a user is logged in on launch, and I see examples of how to setup the login but not keeping a user logged in on new launches of an app. What is the best practice for this?

**Comment by chrisp-fb** [comment]
Did you following the [Getting Started Guide for iOS](https://developers.facebook.com/docs/ios/getting-started), specifically step 6 about connecting the application delegate:

```
  - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [[FBSDKApplicationDelegate sharedInstance] application:application
      didFinishLaunchingWithOptions:launchOptions];
    return YES;
  }
  
  - (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication annotation:(id)annotation {
    return [[FBSDKApplicationDelegate sharedInstance] application:application
      openURL:url
      sourceApplication:sourceApplication
      annotation:annotation
    ];
  }
```

**Comment by gpazo** [comment]
Yes, I think it is setup correctly. This is my AppDelegate.m file right now: 

`- (void)applicationDidBecomeActive:(UIApplication *)application {
  [FBSDKAppEvents activateApp];
}

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  jsCodeLocation = [NSURL URLWithString:@"http://192.168.1.78:8081/index.ios.bundle?platform=ios&dev=true"];

  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"Comparity_react"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  
  return [[FBSDKApplicationDelegate sharedInstance] application:application
                                  didFinishLaunchingWithOptions:launchOptions];
}

- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication
         annotation:(id)annotation {
  return [[FBSDKApplicationDelegate sharedInstance] application:application
                                                        openURL:url
                                              sourceApplication:sourceApplication
                                                     annotation:annotation];
}`

**Comment by chrisp-fb** [comment]
Can you try moving up the `[[FBSDKApplicationDelegate sharedInstance] application:application
      didFinishLaunchingWithOptions:launchOptions];` to the top? That's where the SDK will restore a token from cache so it needs to be done before your view is loaded (and as an aside, you probably want to return YES like the snippet rather than the return value of the FBSDKApplicationDelegate). Let me know if that fixes it and we can update our snippet like `// Add your custom logic here`.

**Comment by gpazo** [comment]
Sorry, I was following the sample in this repository: https://github.com/facebook/react-native-fbsdk/blob/master/Sample/iOS/AppDelegate.m#L66

If the token is restored from the cache before the javascript is loaded, how would you know when to show the login screen inside your root component?

**Comment by chrisp-fb** [comment]
Ah, thanks for that link, we'll fix that.

You should be able to use `FBSDKAccessToken.getCurrentAccessToken` to see if there is a token - if so that means the user is logged in.

**Comment by gpazo** [comment]
@chrisp-fb thank you for the help, for anyone looking at this same problem. I used the componentDidMount function to call the function for the token above, when I got a response I updated the state to show the correct screen. 

```
FBSDKAccessToken.getCurrentAccessToken((result) => {
      if (result == null) {
        this.setState({
          isLoading: false,
          showScreen: {name: 'login'}
        });
      } else {
        this.setState({
          isLoading: false,
          showScreen: {name: 'main'}
        });
      }
    });
```

**Comment by chrisp-fb** [comment]
Awesome, glad we got it sorted out and thanks for submitting the pull request!
