### ISSUE TITLE
login button - always show ' you have already authorized '

### ISSUE THREAD

**Issue by jaynsw** [facebook/react-native-fbsdk#99]
#1) after clicking login button, it always show 'you have already authroized xxx'
![screen shot 2016-03-25 at 1 14 33 am](https://cloud.githubusercontent.com/assets/5652798/14019546/75514cc8-f227-11e5-9aa3-44dc73154d47.png)

**Comment by dzhuowen** [comment]
This should help ParsePlatform/ParseFacebookUtils-iOS/issues/5
And you can try turning on the SSO in your dev setting.
